import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_api.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_net from"node:net";import*as esm_import$node_process from"node:process";import*as esm_import$node_readline from"node:readline";import*as esm_import$node_vm from"node:vm";
var IT=function(a){var b=function(){var e=$APP.Fr.h(a,"(");return $APP.k(e)?new $APP.G(null,2,5,$APP.H,[$APP.Vi.j(a,0,e+1),$APP.Vi.h(a,e+1)],null):new $APP.G(null,2,5,$APP.H,[null,a],null)}(),c=$APP.y.j(b,0,null),d=$APP.y.j(b,1,null);b=$APP.B.h(function(){try{return $APP.wMa(new $APP.h(null,2,[$APP.P,$APP.l.g($APP.n(HT)),$APP.YG,d],null))}catch(f){var e=f;console.warn($APP.l.g($APP.JBa),$APP.gk(e));return null}}(),"completions");return $APP.ej.h(function(e){return[$APP.l.g(c),$APP.l.g(e)].join("")},
$APP.Tg(function(e){return $APP.Ea(e,d)},$APP.ej.h(function(e){return $APP.B.h(e,"candidate")},b)))},UXa=function(a){return[$APP.ys.g(IT(a)),a]},VXa=function(a,b){$APP.ug(JT,!1);a.setPrompt([$APP.l.g($APP.n(HT)),"\x3d\x3e "].join(""));a.prompt();return $APP.hl($APP.n(KT))?null:LT.h?LT.h(b,a):LT.call(null,b,a)},WXa=function(a){var b=$APP.ul(a);a=$APP.vl(a);var c=$APP.gl($APP.n(KT));b=$APP.Dg.h(b-1,c);c=$APP.r(b);b=$APP.v(c);c=$APP.w(c);a=$APP.k(b)?$APP.Vi.h(b,a):null;$APP.ug(KT,$APP.nn.h("\n",$APP.yf(a,
c)))},XXa=function(a,b){b={f:b};esm_import$node_vm.createContext(b);try{return $APP.k($APP.k(MT)?$APP.Bb(a):MT)&&esm_import$node_process.stdin.setRawMode(!1),esm_import$node_vm.runInContext("f()",b,{displayErrors:!0,breakOnSigint:!0,microtaskMode:"afterEvaluate"}).then(function(c){var d={f:$APP.k(a)?function(){return c}:function(){var e=$APP.v(c);$APP.yu.l($APP.z([e]));return c}};esm_import$node_vm.createContext(d);return esm_import$node_vm.runInContext("f()",d,{displayErrors:!0,breakOnSigint:!0,
microtaskMode:"afterEvaluate"})}).finally(function(){return $APP.k($APP.k(MT)?$APP.Bb(a):MT)?esm_import$node_process.stdin.setRawMode(!0):null})}catch(c){return b=c,$APP.k($APP.k(MT)?$APP.Bb(a):MT)&&esm_import$node_process.stdin.setRawMode(!0),Promise.reject(b)}},LT=function(a,b){if($APP.k(function(){var e=$APP.n(JT);return $APP.k(e)?e:$APP.hl($APP.n(KT))}()))return null;$APP.ug(JT,!0);var c=$APP.xp($APP.n(KT)),d=function(){try{var e=$APP.Tf([$APP.Nq,$APP.n(HT)]);$APP.Yp(e);try{return $APP.Yia(c)}finally{$APP.$p()}}catch(f){e=
f;if($APP.Ha($APP.gk(e),"EOF while reading"))return YXa;WXa(c);$APP.yu.l($APP.z([$APP.l.g(e)]));return ZXa}}();if($APP.x.h(ZXa,d))return VXa(b,a);if($APP.x.h(YXa,d))return $APP.ug(JT,!1);WXa(c);if($APP.x.h($APP.tG,d))return $APP.ug(JT,!1);$APP.Yp($APP.Tf([$APP.Nq,$APP.n(HT)]));return XXa(a,function(){return $APP.lMa(d,new $APP.h(null,3,[$APP.P,$APP.n(HT),$APP.Vl,$APP.n($APP.vq),$APP.AI,$APP.Iw],null))}).then(function(e){var f=$APP.y.j(e,0,null);e=$APP.y.j(e,1,null);e=$APP.Vf(e);e=$APP.B.h(e,$APP.P);
$APP.ug(HT,e);$APP.gN.h($APP.QM,$APP.sg($APP.n($APP.PM)));$APP.gN.h($APP.PM,$APP.sg($APP.n($APP.OM)));$APP.gN.h($APP.OM,$APP.sg(f));$APP.k(a)&&a.write($APP.Ry.l($APP.z([f])));return VXa(b,a)}).catch(function(e){$APP.yu.l($APP.z([$APP.l.g(e)]));$APP.gN.h($APP.RM,$APP.sg(e));return VXa(b,a)}).finally(function(){return $APP.$p()})},$Xa=function(a,b){a.on("line",function(c){$APP.Bj.F(KT,$APP.l,c,"\n");return LT(b,a)})},aYa=function(a){return esm_import$node_readline.createInterface({input:a,output:a,
completer:UXa})},bYa=function(a){var b=aYa(a);$Xa(b,a);a.setNoDelay(!0);return a.on("close",function(){return $APP.Uy.l($APP.z(["Client closed connection."]))})},cYa=new $APP.q(null,"nbb.impl.repl","nbb.impl.repl",-339140484,null),YXa=new $APP.F("nbb.impl.repl","eof-while-reading","nbb.impl.repl/eof-while-reading",1743626215),dYa=new $APP.q("nbb.impl.repl","completer*","nbb.impl.repl/completer*",455172317,null),eYa=new $APP.q("nbb.impl.repl","repl","nbb.impl.repl/repl",-1645296655,null),fYa=new $APP.q(null,
"completer*","completer*",-648150376,null),gYa=new $APP.q("nbb.impl.repl","socket-repl","nbb.impl.repl/socket-repl",1509490200,null),hYa=new $APP.F(null,"init","init",-1875481434),iYa=new $APP.q(null,"get-completions","get-completions",1933789168,null),ZXa=new $APP.F("nbb.impl.repl","continue","nbb.impl.repl/continue",-1326808644);var HT=$APP.yj.g($APP.n($APP.Nq)),KT=$APP.yj.g(""),JT=$APP.yj.g(!1),MT,jYa=esm_import$node_process.stdout.isTTY;MT=$APP.k(jYa)?esm_import$node_process.stdin.setRawMode:jYa;var kYa=$APP.kN.h($APP.oz,null),NT=function NT(a){switch(arguments.length){case 0:return NT.D();case 1:return NT.g(arguments[0]);default:throw Error(["Invalid arity: ",$APP.l.g(arguments.length)].join(""));}};NT.D=function(){return NT.g(null)};
NT.g=function(a){var b=function(){var d=$APP.XF.g(a);return $APP.k(d)?d:0}(),c=esm_import$node_net.createServer(bYa);return c.listen(b,"127.0.0.1",function(){var d=c.address(),e=d.address;return $APP.Uy.l($APP.z([["Socket REPL listening on port ",$APP.l.g(d.port)," on host ",$APP.l.g(e)].join("")]))})};NT.B=1;var OT=function OT(a){switch(arguments.length){case 0:return OT.D();case 1:return OT.g(arguments[0]);default:throw Error(["Invalid arity: ",$APP.l.g(arguments.length)].join(""));}};OT.D=function(){return OT.g(null)};
OT.g=function(a){function b(e){return $APP.iMa(new $APP.D(null,$APP.Ak,new $APP.D(null,new $APP.D(null,$APP.Ak,new $APP.D(null,e,null,1,null),2,null),null,1,null),2,null))}$APP.k(MT)&&esm_import$node_process.stdin.setRawMode(!0);var c=$APP.y.j($APP.rN,0,null),d=$APP.y.j($APP.rN,1,null);$APP.Uy.l($APP.z([["Welcome to nbb-logseq v",$APP.jv(),"!"].join("")]));return b(c).then(function(){return b(d)}).then(hYa.h(a,$APP.ef)).then(function(){return new Promise(function(e){var f=$APP.k(null)?aYa(null):esm_import$node_readline.createInterface({input:esm_import$node_process.stdin,
output:esm_import$node_process.stdout,completer:UXa});$Xa(f,null);f.setPrompt([$APP.l.g($APP.n(HT)),"\x3d\x3e "].join(""));f.on("close",e);return f.prompt()})})};OT.B=1;
var lYa=new $APP.h(null,3,[$APP.yMa,function(){var a=new $APP.Cd(function(){return OT},eYa,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.oI,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[cYa,$APP.yMa,"nbb/impl/repl.cljs",11,new $APP.h(null,6,[$APP.DA,!1,$APP.Qs,1,$APP.DJ,1,$APP.lJ,new $APP.G(null,2,5,$APP.H,[$APP.Sg,new $APP.G(null,1,5,$APP.H,[$APP.bG],null)],null),$APP.U,$APP.J($APP.Sg,new $APP.G(null,1,5,$APP.H,[$APP.bG],null)),$APP.fF,$APP.J(null,null)],null),1,187,187,$APP.J($APP.Sg,new $APP.G(null,
1,5,$APP.H,[$APP.bG],null)),null,$APP.k(OT)?OT.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,kYa,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),iYa,function(){var a=new $APP.Cd(function(){return IT},dYa,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],
[cYa,fYa,"nbb/impl/repl.cljs",17,1,16,16,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.Ona],null)),"Given a line, returns a flat vector of completions",$APP.k(IT)?IT.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,kYa,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),$APP.xMa,function(){var a=new $APP.Cd(function(){return NT},
gYa,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.oI,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[cYa,$APP.xMa,"nbb/impl/repl.cljs",18,new $APP.h(null,6,[$APP.DA,!1,$APP.Qs,1,$APP.DJ,1,$APP.lJ,new $APP.G(null,2,5,$APP.H,[$APP.Sg,new $APP.G(null,1,5,$APP.H,[$APP.bG],null)],null),$APP.U,$APP.J($APP.Sg,new $APP.G(null,1,5,$APP.H,[$APP.bG],null)),$APP.fF,$APP.J(null,null)],null),1,172,172,$APP.J($APP.Sg,new $APP.G(null,1,5,$APP.H,[$APP.bG],null)),null,$APP.k(NT)?NT.H:null])),b=$APP.n(a),c=$APP.se(a);
a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,kYa,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}()],null);$APP.Yu(new $APP.h(null,1,[$APP.Kq,new $APP.h(null,1,[$APP.oz,lYa],null)],null));