import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var EKa,FKa,IN,JN,GKa,HKa,IKa,KN,MN,JKa,KKa,LKa,ON,PN,QN,RKa,RN,SN,TN,UN,VN,WN,SKa,TKa,UKa,VKa,YN,WKa,XN,ZN,$N,XKa,YKa,aO,ZKa,$Ka,aLa,bO,dLa,cO,dO,eO,fO,gO,hO,iO,jO,kO,lO,mO,nO,oO,pO,qO,rO,sO,tO,uO,vO,eLa,fLa,wO,gLa,hLa,iLa,jLa,kLa,xO,yO,lLa,mLa,nLa,zO,AO,CO,DO,GO,IO,oLa,JO,pLa,qLa,rLa,sLa,tLa,uLa,vLa,LO,wLa,xLa,yLa,zLa,ALa,BLa,NO,OO,CLa,DLa,ELa,FLa,GLa,HLa,ILa,JLa,KLa,LLa,MLa,NLa,OLa,PLa,QLa,RLa,SLa,TLa,ULa,VLa,WLa;
EKa=function(a,b){b&=63;if(0==b)return a;var c=a.eb;return 32>b?$APP.ra(a.Nb>>>b|c<<32-b,c>>>b):32==b?$APP.ra(c,0):$APP.ra(c>>>b-32,0)};FKa=function(a){if(null!=a&&null!=a.ca)a=a.ca(a);else{var b=FKa[$APP.ea(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=FKa._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.Kb("ICloneable.-clone",a);}return a};
IN=function(a,b){if("-"==a.charAt(0))return $APP.va(IN(a.substring(1),b));var c=parseInt(a,b||10);if(9007199254740991>=c)return new $APP.pa(c%4294967296|0,c/4294967296|0);if(0==a.length)throw Error("number format error: empty string");if(0<=a.indexOf("-"))throw Error('number format error: interior "-" character: '+a);b=b||10;if(2>b||36<b)throw Error("radix out of range: "+b);c=$APP.Aa(Math.pow(b,8));for(var d=$APP.wa,e=0;e<a.length;e+=8){var f=Math.min(8,a.length-e),m=parseInt(a.substring(e,e+f),
b);8>f?(f=$APP.Aa(Math.pow(b,f)),d=d.multiply(f).add($APP.Aa(m))):(d=d.multiply(c),d=d.add($APP.Aa(m)))}return d};JN=function(){return Math.round(15*Math.random()).toString(16)};GKa=function(a,b){if(3<a.length){if(b)return!0;b=a.charAt(1);return"~"===a.charAt(0)?":"===b||"$"===b||"#"===b:!1}return!1};HKa=function(a){var b=Math.floor(a/44);a=String.fromCharCode(a%44+48);return 0===b?"^"+a:"^"+String.fromCharCode(b+48)+a};IKa=function(){this.Ul=this.Xf=this.idx=0;this.cache={}};
KN=function(){this.idx=0;this.cache=[]};MN=function(a,b){if(null==a)return null==b;if(a===b)return!0;if("object"===typeof a){if(LN(a)){if(LN(b)&&a.length===b.length){for(var c=0;c<a.length;c++)if(!MN(a[c],b[c]))return!1;return!0}return!1}if(a.ue)return a.ue(b);if(null!=b&&"object"===typeof b){if(b.ue)return b.ue(a);c=0;var d=NN(b).length,e;for(e in a)if(a.hasOwnProperty(e)&&(c++,!b.hasOwnProperty(e)||!MN(a[e],b[e])))return!1;return c===d}}return!1};
JKa=function(a,b){return a^b+2654435769+(a<<6)+(a>>2)};KKa=function(a){var b=0;if(null!=a.forEach)a.forEach(function(m,p){b=(b+(ON(p)^ON(m)))%4503599627370496});else for(var c=NN(a),d=0;d<c.length;d++){var e=c[d],f=a[e];b=(b+(ON(e)^ON(f)))%4503599627370496}return b};LKa=function(a){var b=0;if(LN(a))for(var c=0;c<a.length;c++)b=JKa(b,ON(a[c]));else a.forEach&&a.forEach(function(d){b=JKa(b,ON(d))});return b};
ON=function(a){if(null==a)return 0;switch(typeof a){case "number":return a;case "boolean":return!0===a?1:0;case "string":var b=MKa[a];if(null!=b)a=b;else{for(var c=b=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;NKa++;256<=NKa&&(MKa={},NKa=1);a=MKa[a]=b}return a;case "function":return b=a.transit$hashCode$,b||(b=OKa,"undefined"!=typeof Object.defineProperty?Object.defineProperty(a,"transit$hashCode$",{value:b,enumerable:!1}):a.transit$hashCode$=b,OKa++),b;default:return a instanceof Date?
a.valueOf():LN(a)?LKa(a):a.Qe?a.Qe():KKa(a)}};PN=function(a,b){this.tag=a;this.rep=b;this.Db=-1};QN=function(a,b){return new PN(a,b)};RKa=function(a){if("number"===typeof a||a instanceof $APP.pa)return a;a=IN(a,10);return 0<a.compare(PKa)||0>a.compare(QKa)?a:$APP.Ba(a)};RN=function(a){this.pc=a;this.Db=-1};SN=function(a){this.pc=a;this.Db=-1};
TN=function(a,b,c){var d="";c=c||b+1;for(var e=8*(7-b),f=(new $APP.pa(255,0)).shiftLeft(e);b<c;b++,e-=8,f=EKa(f,8)){var m=EKa(a.and(f),e).toString(16);1==m.length&&(m="0"+m);d+=m}return d};UN=function(a,b){this.high=a;this.low=b;this.Db=-1};VN=function(a,b){this.entries=a;this.type=b||0;this.idx=0};WN=function(a,b){this.map=a;this.type=b||0;this.keys=this.map.rg();this.idx=0;this.dg=null;this.Rf=0};
SKa=function(a,b){if(a instanceof XN&&(b instanceof YN||b instanceof XN)){if(a.size!==b.size)return!1;for(var c in a.map)for(var d=a.map[c],e=0;e<d.length;e+=2)if(!MN(d[e+1],b.get(d[e])))return!1;return!0}if(a instanceof YN&&(b instanceof YN||b instanceof XN)){if(a.size!==b.size)return!1;a=a.Lb;for(e=0;e<a.length;e+=2)if(!MN(a[e+1],b.get(a[e])))return!1;return!0}if(null!=b&&"object"===typeof b&&(e=NN(b),c=e.length,a.size===c)){for(d=0;d<c;d++){var f=e[d];if(!a.has(f)||!MN(b[f],a.get(f)))return!1}return!0}return!1};
TKa=function(a){return null==a?"null":"array"===$APP.ea(a)?"["+a.toString()+"]":"string"===$APP.ea(a)?'"'+a+'"':a.toString()};UKa=function(a){var b=0,c="TransitMap {";a.forEach(function(d,e){c+=TKa(e)+" \x3d\x3e "+TKa(d);b<a.size-1&&(c+=", ");b++});return c+"}"};VKa=function(a){var b=0,c="TransitSet {";a.forEach(function(d){c+=TKa(d);b<a.size-1&&(c+=", ");b++});return c+"}"};YN=function(a){this.Lb=a;this.Fb=null;this.Db=-1;this.size=a.length/2;this.Xj=0};
WKa=function(a){if(a.Fb)throw Error("Invalid operation, already converted");if(8>a.size)return!1;a.Xj++;return 32<a.Xj?(a.Fb=ZN(a.Lb,!1,!0),a.Lb=[],!0):!1};XN=function(a,b,c){this.map=b||{};this.Ig=a||[];this.size=c||0;this.Db=-1};
ZN=function(a,b,c){a=a||[];b=!1===b?b:!0;if((!0!==c||!c)&&64>=a.length){if(b){var d=a;a=[];for(b=0;b<d.length;b+=2){var e=!1;for(c=0;c<a.length;c+=2)if(MN(a[c],d[b])){a[c+1]=d[b+1];e=!0;break}e||(a.push(d[b]),a.push(d[b+1]))}}return new YN(a)}d={};e=[];var f=0;for(b=0;b<a.length;b+=2){c=ON(a[b]);var m=d[c];if(null==m)e.push(c),d[c]=[a[b],a[b+1]],f++;else{var p=!0;for(c=0;c<m.length;c+=2)if(MN(m[c],a[b])){m[c+1]=a[b+1];p=!1;break}p&&(m.push(a[b]),m.push(a[b+1]),f++)}}return new XN(e,d,f)};
$N=function(a){this.map=a;this.size=a.size};XKa=function(a){a=a||[];for(var b={},c=[],d=0,e=0;e<a.length;e++){var f=ON(a[e]),m=b[f];if(null==m)c.push(f),b[f]=[a[e],a[e]],d++;else{f=!0;for(var p=0;p<m.length;p+=2)if(MN(m[p],a[e])){f=!1;break}f&&(m.push(a[e]),m.push(a[e]),d++)}}return new $N(new XN(c,b,d))};YKa=function(a){this.pd=a};
aO=function(a){this.options=a||{};this.Gc={};for(var b in this.Ah.Gc)this.Gc[b]=this.Ah.Gc[b];for(b in this.options.handlers){a:{switch(b){case "_":case "s":case "?":case "i":case "d":case "b":case "'":case "array":case "map":a=!0;break a}a=!1}if(a)throw Error('Cannot override handler for ground type "'+b+'"');this.Gc[b]=this.options.handlers[b]}this.Ci=null!=this.options.preferStrings?this.options.preferStrings:this.Ah.Ci;this.Ij=null!=this.options.preferBuffers?this.options.preferBuffers:this.Ah.Ij;
this.uj=this.options.defaultHandler||this.Ah.uj;this.Ce=this.options.mapBuilder;this.Jg=this.options.arrayBuilder};
ZKa=function(a,b,c,d,e){if(e){var f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return f}f=c&&c.idx;if(2===b.length&&"string"===typeof b[0]&&(e=a.decode(b[0],c,!1,!1))&&e instanceof YKa)return b=b[1],f=a.Gc[e.pd],null!=f?f=f(a.decode(b,c,d,!0),a):QN(e.pd,a.decode(b,c,d,!1));c&&f!=c.idx&&(c.idx=f);if(a.Jg){if(32>=b.length&&a.Jg.fromArray){f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return a.Jg.fromArray(f,b)}f=a.Jg.init(b);for(e=0;e<b.length;e++)f=a.Jg.add(f,a.decode(b[e],
c,d,!1),b);return a.Jg.finalize(f,b)}f=[];for(e=0;e<b.length;e++)f.push(a.decode(b[e],c,d,!1));return f};$Ka=function(a,b){if("~"===b.charAt(0)){var c=b.charAt(1);if("~"===c||"^"===c||"`"===c)return b.substring(1);if("#"===c)return new YKa(b.substring(2));var d=a.Gc[c];return null==d?a.uj(c,b.substring(2)):d(b.substring(2),a)}return b};aLa=function(a){this.rm=new aO(a)};bO=function(a,b){this.Pn=a;this.options=b||{};this.cache=this.options.cache?this.options.cache:new KN};
dLa=function(a){if(null==a)return"null";if(a===String)return"string";if(a===Boolean)return"boolean";if(a===Number)return"number";if(a===Array)return"array";if(a===Object)return"map";var b=a[bLa];null==b&&("undefined"!=typeof Object.defineProperty?(b=++cLa,Object.defineProperty(a,bLa,{value:b,enumerable:!1})):a[bLa]=b=++cLa);return b};cO=function(a,b){a=a.toString();for(var c=a.length;c<b;c++)a="0"+a;return a};dO=function(){};eO=function(){};fO=function(){};gO=function(){};hO=function(){};iO=function(){};
jO=function(){};kO=function(){};lO=function(){};mO=function(){};nO=function(){};oO=function(){};pO=function(){};qO=function(){};rO=function(){};sO=function(){};tO=function(){};uO=function(){};
vO=function(){this.Gc={};this.set(null,new dO);this.set(String,new eO);this.set(Number,new fO);this.set($APP.pa,new gO);this.set(Boolean,new hO);this.set(Array,new iO);this.set(Object,new jO);this.set(Date,new lO);this.set(UN,new mO);this.set(RN,new nO);this.set(SN,new oO);this.set(PN,new pO);this.set($N,new qO);this.set(YN,new rO);this.set(XN,new sO);"undefined"!=typeof $APP.Ku.Oi&&this.set($APP.Ku.Oi,new tO);"undefined"!=typeof Uint8Array&&this.set(Uint8Array,new uO)};
eLa=function(a){this.Id=a||{};this.Ci=null!=this.Id.preferStrings?this.Id.preferStrings:!0;this.Ok=this.Id.objectBuilder||null;this.transform=this.Id.transform||null;this.Gc=new vO;if(a=this.Id.handlers){if(LN(a)||!a.forEach)throw Error('transit writer "handlers" option must be a map');var b=this;a.forEach(function(c,d){if(void 0!==d)b.Gc.set(d,c);else throw Error("Cannot create handler for JavaScript undefined");})}this.Dh=this.Id.handlerForForeign;this.Mi=this.Id.unpack||function(c){return c instanceof
YN&&null===c.Fb?c.Lb:!1};this.Th=this.Id&&this.Id.verbose||!1};fLa=function(a,b){var c=a.Gc.get(null==b?null:b.constructor);return null!=c?c:(b=b&&b.transitTag)?a.Gc.get(b):null};wO=function(a,b,c,d,e){a=a+b+c;return e?e.write(a,d):a};gLa=function(a,b,c){var d=[];if(LN(b))for(var e=0;e<b.length;e++)d.push(xO(a,b[e],!1,c));else b.forEach(function(f){d.push(xO(a,f,!1,c))});return d};hLa=function(a,b){return"string"!==typeof b?(a=fLa(a,b))&&1===a.tag(b).length:!0};
iLa=function(a,b){var c=a.Mi(b),d=!0;if(c){for(b=0;b<c.length&&(d=hLa(a,c[b]),d);b+=2);return d}if(b.keys){c=b.keys();var e=null;if(c.next){for(e=c.next();!e.done;){d=hLa(a,e.value);if(!d)break;e=c.next()}return d}}if(b.forEach)return b.forEach(function(f,m){d=d&&hLa(a,m)}),d;throw Error("Cannot walk keys of object type "+(null==b?null:b.constructor).name);};
jLa=function(a){if(a.constructor.transit$isObject)return!0;var b=a.constructor.toString();b=b.substr(9);b=b.substr(0,b.indexOf("("));b="Object"==b;"undefined"!=typeof Object.defineProperty?Object.defineProperty(a.constructor,"transit$isObject",{value:b,enumerable:!1}):a.constructor.transit$isObject=b;return b};
kLa=function(a,b,c){var d=null,e=null,f=null;d=null;var m=0;if(b.constructor===Object||null!=b.forEach||a.Dh&&jLa(b)){if(a.Th){if(null!=b.forEach)if(iLa(a,b)){var p={};b.forEach(function(u,t){p[xO(a,t,!0,!1)]=xO(a,u,!1,c)})}else{d=a.Mi(b);e=[];f=wO("~#","cmap","",!0,c);if(d)for(;m<d.length;m+=2)e.push(xO(a,d[m],!1,!1)),e.push(xO(a,d[m+1],!1,c));else b.forEach(function(u,t){e.push(xO(a,t,!1,!1));e.push(xO(a,u,!1,c))});p={};p[f]=e}else for(d=NN(b),p={};m<d.length;m++)p[xO(a,d[m],!0,!1)]=xO(a,b[d[m]],
!1,c);return p}if(null!=b.forEach){if(iLa(a,b)){d=a.Mi(b);p=["^ "];if(d)for(;m<d.length;m+=2)p.push(xO(a,d[m],!0,c)),p.push(xO(a,d[m+1],!1,c));else b.forEach(function(u,t){p.push(xO(a,t,!0,c));p.push(xO(a,u,!1,c))});return p}d=a.Mi(b);e=[];f=wO("~#","cmap","",!0,c);if(d)for(;m<d.length;m+=2)e.push(xO(a,d[m],!1,c)),e.push(xO(a,d[m+1],!1,c));else b.forEach(function(u,t){e.push(xO(a,t,!1,c));e.push(xO(a,u,!1,c))});return[f,e]}p=["^ "];for(d=NN(b);m<d.length;m++)p.push(xO(a,d[m],!0,c)),p.push(xO(a,b[d[m]],
!1,c));return p}if(null!=a.Ok)return a.Ok(b,function(u){return xO(a,u,!0,c)},function(u){return xO(a,u,!1,c)});m=(null==b?null:b.constructor).name;d=Error("Cannot write "+m);d.data={Ja:b,type:m};throw d;};
xO=function(a,b,c,d){null!==a.transform&&(b=a.transform(b));var e=fLa(a,b)||(a.Dh?a.Dh(b,a.Gc):null),f=e?e.tag(b):null,m=e?e.rep(b):null;if(null!=e&&null!=f)switch(f){case "_":return c?wO("~","_","",c,d):null;case "s":return 0<m.length?(a=m.charAt(0),a="~"===a||"^"===a||"`"===a?"~"+m:m):a=m,wO("","",a,c,d);case "?":return c?wO("~","?",m.toString()[0],c,d):m;case "i":return Infinity===m?wO("~","z","INF",c,d):-Infinity===m?wO("~","z","-INF",c,d):isNaN(m)?wO("~","z","NaN",c,d):c||"string"===typeof m||
m instanceof $APP.pa?wO("~","i",m.toString(),c,d):m;case "d":return c?wO(m.$n,"d",m,c,d):m;case "b":return wO("~","b",m,c,d);case "'":return a.Th?(c={},b=wO("~#","'","",!0,d),c[b]=xO(a,m,!1,d),d=c):d=[wO("~#","'","",!0,d),xO(a,m,!1,d)],d;case "array":return gLa(a,m,d);case "map":return kLa(a,m,d);default:a:{if(1===f.length){if("string"===typeof m){d=wO("~",f,m,c,d);break a}if(c||a.Ci){(a=a.Th&&e.getVerboseHandler())?(f=a.tag(b),m=a.stringRep(b,a)):m=e.stringRep(b,e);if(null!==m){d=wO("~",f,m,c,d);
break a}d=Error('Tag "'+f+'" cannot be encoded as string');d.data={tag:f,rep:m,Ja:b};throw d;}}c=f;b=m;a.Th?(e={},e[wO("~#",c,"",!0,d)]=xO(a,b,!1,d),d=e):d=[wO("~#",c,"",!0,d),xO(a,b,!1,d)]}return d}else throw d=(null==b?null:b.constructor).name,a=Error("Cannot write "+d),a.data={Ja:b,type:d},a;};yO=function(a,b){this.ah=a;this.options=b||{};this.cache=!1===this.options.cache?null:this.options.cache?this.options.cache:new IKa};
lLa=function(a,b){if("json"===a||"json-verbose"===a||null==a)return a=new aLa(b),new bO(a,b);throw Error("Cannot create reader of type "+a);};mLa=function(a,b){if("json"===a||"json-verbose"===a||null==a)return"json-verbose"===a&&(null==b&&(b={}),b.verbose=!0),a=new eLa(b),new yO(a,b);b=Error('Type must be "json"');b.data={type:a};throw b;};
nLa=function(a,b){for(var c=$APP.r($APP.Ja(b)),d=null,e=0,f=0;;)if(f<e){var m=d.ha(null,f);a[m]=$APP.La(b,m);f+=1}else if(c=$APP.r(c))d=c,$APP.Ee(d)?(c=$APP.cd(d),f=$APP.dd(d),d=c,e=$APP.be(c),c=f):(c=$APP.v(d),a[c]=$APP.La(b,c),c=$APP.w(d),d=null,e=0),f=0;else break;return a};zO=function(){};AO=function(){};$APP.BO=function(a,b){return a.read(b)};CO=function(){};DO=function(){};$APP.EO=function(){};$APP.FO=function(){};GO=function(){};$APP.HO=function(){};IO=function(){};
oLa=function(a,b){this.value=a;this.P=b};JO=function(){};$APP.KO=function(a,b){return a.write(b)};pLa=function(a){return a};qLa=function(a,b,c,d,e){this.Li=a;this.Ei=b;this.Rh=c;this.Uh=d;this.Mm=e;this.J=393216;this.M=0};rLa=function(a,b){return QN(a,b)};sLa=function(a){return RKa(a)};tLa=function(a){if(null!=a&&(a.J&131072||$APP.vd===a.jg)){var b=a.U(null);return null!=b?new oLa(a.V(null,null),b):a}return a};$APP.Ed.prototype.ca=$APP.ca(21,function(){return new $APP.Ed(this.I,this.X,this.P)});
$APP.fe.prototype.ca=$APP.ca(20,function(){return new $APP.fe(this.gh,this.X,this.P)});$APP.D.prototype.ca=$APP.ca(19,function(){return new $APP.D(this.P,this.first,this.rc,this.count,this.C)});$APP.uf.prototype.ca=$APP.ca(18,function(){return new $APP.uf(this.P)});$APP.xf.prototype.ca=$APP.ca(17,function(){return new $APP.xf(this.P,this.first,this.rc,this.C)});$APP.G.prototype.ca=$APP.ca(16,function(){return new $APP.G(this.P,this.T,this.shift,this.root,this.Kc,this.C)});
$APP.lh.prototype.ca=$APP.ca(15,function(){return new $APP.lh(this.P,this.v,this.start,this.end,this.C)});$APP.sh.prototype.ca=$APP.ca(14,function(){return new $APP.sh(this.P,this.count,this.nd,this.Od,this.C)});$APP.h.prototype.ca=$APP.ca(13,function(){return new $APP.h(this.P,this.T,this.I,this.C)});$APP.fi.prototype.ca=$APP.ca(12,function(){return new $APP.fi(this.P,this.T,this.root,this.wc,this.Hc,this.C)});
$APP.ni.prototype.ca=$APP.ca(11,function(){return new $APP.ni(this.md,this.Je,this.T,this.P,this.C)});$APP.xi.prototype.ca=$APP.ca(10,function(){return new $APP.xi(this.P,this.Ae,this.C)});$APP.Ai.prototype.ca=$APP.ca(9,function(){return new $APP.Ai(this.P,this.Zd,this.C)});$APP.Ki.prototype.ca=$APP.ca(8,function(){return new $APP.Ki(this.P,this.start,this.end,this.step,this.T,this.C)});
$APP.Li.prototype.ca=$APP.ca(7,function(){return new $APP.Li(this.P,this.start,this.end,this.step,this.hd,this.fh,this.C)});$APP.kl.prototype.ca=$APP.ca(6,function(){return new $APP.kl(this.gf,this.form,this.A,this.o,this.C)});$APP.wo.prototype.ca=$APP.ca(5,function(){return new $APP.wo(this.yf,this.sf,this.A,this.o,this.C)});
$APP.rp.prototype.ca=$APP.ca(4,function(){return new $APP.rp(this.Qb,this.deref,this.ac,this.bc,this.cc,this.quote,this.na,this.ob,this.Xb,this.Yb,this.Zb,this.Pb,this.Tb,this.Rb,this.source,this.$b,this.Wb,this.Ub,this.Sb,this.Vb,this.A,this.o,this.C)});$APP.Ip.prototype.ca=$APP.ca(3,function(){return new $APP.Ip(this.f,this.stack,this.A,this.o,this.C)});$APP.Er.prototype.ca=$APP.ca(2,function(){return new $APP.Er(this.ag,this.type,this.ob,this.Zc,this.yi)});
$APP.Js.prototype.ca=$APP.ca(1,function(){return new $APP.Js(this.ec,this.body,this.Rd,this.$d,this.Xd,this.Td,this.A,this.o,this.C)});$APP.pa.prototype.Db=$APP.ca(0,function(){return this.Nb^this.eb});uLa=new $APP.q(null,"write-meta","write-meta",-1711397117,null);vLa=new $APP.q(null,"from-rep","from-rep",911750077,null);LO=new $APP.q(null,"str-rep-fn","str-rep-fn",-1179615016,null);wLa=new $APP.q(null,"ListHandler","ListHandler",-856350412,null);$APP.MO=new $APP.F(null,"handlers","handlers",79528781);
xLa=new $APP.q("cognitect.transit","integer","cognitect.transit/integer",-1862495722,null);yLa=new $APP.q("cognitect.transit","write-meta","cognitect.transit/write-meta",-859929338,null);zLa=new $APP.F(null,"arrayBuilder","arrayBuilder",1446317421);ALa=new $APP.F(null,"mapBuilder","mapBuilder",-278083754);BLa=new $APP.F(null,"preferStrings","preferStrings",-1532249482);NO=new $APP.q(null,"tag-fn","tag-fn",242055482,null);OO=new $APP.q(null,"rep-fn","rep-fn",-1724891035,null);
CLa=new $APP.q(null,"rep","rep",413710963,null);DLa=new $APP.q("cognitect.transit","ListHandler","cognitect.transit/ListHandler",397689651,null);ELa=new $APP.q(null,"tagged-value","tagged-value",-110559503,null);FLa=new $APP.q(null,"write-handler","write-handler",-692059351,null);GLa=new $APP.F(null,"map-builder","map-builder",-1843343288);HLa=new $APP.q("cognitect.transit","reader","cognitect.transit/reader",1051062779,null);ILa=new $APP.F(null,"prefer-strings","prefer-strings",1254507185);
JLa=new $APP.q("cognitect.transit","read-handler","cognitect.transit/read-handler",-523561611,null);KLa=new $APP.F(null,"array-builder","array-builder",1275998041);LLa=new $APP.q(null,"read-handler","read-handler",1426618230,null);MLa=new $APP.F(null,"prefer-buffers","prefer-buffers",377042081);NLa=new $APP.q("cognitect.transit","write-handler","cognitect.transit/write-handler",-2147442390,null);OLa=new $APP.q("cognitect.transit","write","cognitect.transit/write",432992816,null);
PLa=new $APP.q("cognitect.transit","writer","cognitect.transit/writer",-92501676,null);QLa=new $APP.q("cognitect.transit","read","cognitect.transit/read",-553970069,null);RLa=new $APP.q("cognitect.transit","tagged-value","cognitect.transit/tagged-value",1403542766,null);SLa=new $APP.q(null,"w","w",1994700528,null);TLa=new $APP.F(null,"preferBuffers","preferBuffers",1843176451);ULa=new $APP.q(null,"verbose-handler-fn","verbose-handler-fn",547340594,null);
VLa=new $APP.q(null,"integer","integer",1035809817,null);WLa=new $APP.q(null,"write","write",-217117641,null);var NN="undefined"!=typeof Object.keys?function(a){return Object.keys(a)}:function(a){return $APP.Ja(a)},LN="undefined"!=typeof Array.isArray?function(a){return Array.isArray(a)}:function(a){return"array"===$APP.ea(a)};IKa.prototype.write=function(a,b){return GKa(a,b)?(4096===this.Ul?(this.clear(),this.Xf=0,this.cache={}):1936===this.idx&&this.clear(),b=this.cache[a],null==b?(this.cache[a]=[HKa(this.idx),this.Xf],this.idx++,a):b[1]!=this.Xf?(b[1]=this.Xf,b[0]=HKa(this.idx),this.idx++,a):b[0]):a};IKa.prototype.clear=function(){this.idx=0;this.Xf++};KN.prototype.write=function(a){1936==this.idx&&(this.idx=0);this.cache[this.idx]=a;this.idx++;return a};
KN.prototype.read=function(a){return this.cache[2===a.length?a.charCodeAt(1)-48:44*(a.charCodeAt(1)-48)+(a.charCodeAt(2)-48)]};KN.prototype.clear=function(){this.idx=0};var OKa=1,MKa={},NKa=0;var PO="undefined"!=typeof Symbol?Symbol.iterator:"@@iterator";PN.prototype.toString=function(){return"[TaggedValue: "+this.tag+", "+this.rep+"]"};PN.prototype.equiv=function(a){return MN(this,a)};PN.prototype.equiv=PN.prototype.equiv;PN.prototype.ue=function(a){return a instanceof PN?this.tag===a.tag&&MN(this.rep,a.rep):!1};PN.prototype.Qe=function(){-1===this.Db&&(this.Db=JKa(ON(this.tag),ON(this.rep)));return this.Db};var PKa=IN("9007199254740991"),QKa=IN("-9007199254740991");
$APP.pa.prototype.equiv=function(a){return MN(this,a)};$APP.pa.prototype.equiv=$APP.pa.prototype.equiv;$APP.pa.prototype.ue=function(a){return a instanceof $APP.pa&&this.equals(a)};$APP.pa.prototype.Qe=function(){return this.Nb};RN.prototype.toString=function(){return":"+this.pc};RN.prototype.namespace=function(){var a=this.pc.indexOf("/");return-1!=a?this.pc.substring(0,a):null};RN.prototype.name=function(){var a=this.pc.indexOf("/");return-1!=a?this.pc.substring(a+1,this.pc.length):this.pc};
RN.prototype.equiv=function(a){return MN(this,a)};RN.prototype.equiv=RN.prototype.equiv;RN.prototype.ue=function(a){return a instanceof RN&&this.pc==a.pc};RN.prototype.Qe=function(){-1===this.Db&&(this.Db=ON(this.pc));return this.Db};SN.prototype.namespace=function(){var a=this.pc.indexOf("/");return-1!=a?this.pc.substring(0,a):null};SN.prototype.name=function(){var a=this.pc.indexOf("/");return-1!=a?this.pc.substring(a+1,this.pc.length):this.pc};SN.prototype.toString=function(){return this.pc};
SN.prototype.equiv=function(a){return MN(this,a)};SN.prototype.equiv=SN.prototype.equiv;SN.prototype.ue=function(a){return a instanceof SN&&this.pc==a.pc};SN.prototype.Qe=function(){-1===this.Db&&(this.Db=ON(this.pc));return this.Db};UN.prototype.toString=function(){var a=this.high,b=this.low;var c=TN(a,0,4)+"-";c+=TN(a,4,6)+"-";c+=TN(a,6,8)+"-";c+=TN(b,0,2)+"-";return c+=TN(b,2,8)};UN.prototype.equiv=function(a){return MN(this,a)};UN.prototype.equiv=UN.prototype.equiv;
UN.prototype.ue=function(a){return a instanceof UN&&this.high.equals(a.high)&&this.low.equals(a.low)};UN.prototype.Qe=function(){-1===this.Db&&(this.Db=ON(this.toString()));return this.Db};Date.prototype.ue=function(a){return a instanceof Date?this.valueOf()===a.valueOf():!1};Date.prototype.Qe=function(){return this.valueOf()};
VN.prototype.next=function(){if(this.idx<this.entries.length){var a={value:0===this.type?this.entries[this.idx]:1===this.type?this.entries[this.idx+1]:[this.entries[this.idx],this.entries[this.idx+1]],done:!1};this.idx+=2;return a}return{value:null,done:!0}};VN.prototype.next=VN.prototype.next;VN.prototype[PO]=function(){return this};
WN.prototype.next=function(){if(this.idx<this.map.size){null!=this.dg&&this.Rf<this.dg.length||(this.dg=this.map.map[this.keys[this.idx]],this.Rf=0);var a={value:0===this.type?this.dg[this.Rf]:1===this.type?this.dg[this.Rf+1]:[this.dg[this.Rf],this.dg[this.Rf+1]],done:!1};this.idx++;this.Rf+=2;return a}return{value:null,done:!0}};WN.prototype.next=WN.prototype.next;WN.prototype[PO]=function(){return this};YN.prototype.toString=function(){return UKa(this)};YN.prototype.inspect=function(){return this.toString()};
YN.prototype.clear=function(){this.Db=-1;this.Fb?this.Fb.clear():this.Lb=[];this.size=0};YN.prototype.clear=YN.prototype.clear;YN.prototype.keys=function(){return this.Fb?this.Fb.keys():new VN(this.Lb,0)};YN.prototype.keys=YN.prototype.keys;YN.prototype.vg=function(){if(this.Fb)return this.Fb.vg();for(var a=[],b=0,c=0;c<this.Lb.length;b++,c+=2)a[b]=this.Lb[c];return a};YN.prototype.keySet=YN.prototype.vg;YN.prototype.entries=function(){return this.Fb?this.Fb.entries():new VN(this.Lb,2)};
YN.prototype.entries=YN.prototype.entries;YN.prototype.values=function(){return this.Fb?this.Fb.values():new VN(this.Lb,1)};YN.prototype.values=YN.prototype.values;YN.prototype.forEach=function(a){if(this.Fb)this.Fb.forEach(a);else for(var b=0;b<this.Lb.length;b+=2)a(this.Lb[b+1],this.Lb[b])};YN.prototype.forEach=YN.prototype.forEach;
YN.prototype.get=function(a,b){if(this.Fb)return this.Fb.get(a);if(WKa(this))return this.get(a);for(var c=0;c<this.Lb.length;c+=2)if(MN(this.Lb[c],a))return this.Lb[c+1];return b};YN.prototype.get=YN.prototype.get;YN.prototype.has=function(a){if(this.Fb)return this.Fb.has(a);if(WKa(this))return this.has(a);for(var b=0;b<this.Lb.length;b+=2)if(MN(this.Lb[b],a))return!0;return!1};YN.prototype.has=YN.prototype.has;
YN.prototype.set=function(a,b){this.Db=-1;if(this.Fb)this.Fb.set(a,b),this.size=this.Fb.size;else{for(var c=0;c<this.Lb.length;c+=2)if(MN(this.Lb[c],a)){this.Lb[c+1]=b;return}this.Lb.push(a);this.Lb.push(b);this.size++;32<this.size&&(this.Fb=ZN(this.Lb,!1,!0),this.Lb=null)}};YN.prototype.set=YN.prototype.set;
YN.prototype["delete"]=function(a){this.Db=-1;if(this.Fb)return a=this.Fb.delete(a),this.size=this.Fb.size,a;for(var b=0;b<this.Lb.length;b+=2)if(MN(this.Lb[b],a))return a=this.Lb[b+1],this.Lb.splice(b,2),this.size--,a};YN.prototype.clone=function(){var a=ZN();this.forEach(function(b,c){a.set(c,b)});return a};YN.prototype.clone=YN.prototype.clone;YN.prototype[PO]=function(){return this.entries()};YN.prototype.Qe=function(){if(this.Fb)return this.Fb.Qe();-1===this.Db&&(this.Db=KKa(this));return this.Db};
YN.prototype.ue=function(a){return this.Fb?SKa(this.Fb,a):SKa(this,a)};XN.prototype.toString=function(){return UKa(this)};XN.prototype.inspect=function(){return this.toString()};XN.prototype.clear=function(){this.Db=-1;this.map={};this.Ig=[];this.size=0};XN.prototype.clear=XN.prototype.clear;XN.prototype.rg=function(){return null!=this.Ig?this.Ig:NN(this.map)};
XN.prototype["delete"]=function(a){this.Db=-1;this.Ig=null;for(var b=ON(a),c=this.map[b],d=0;d<c.length;d+=2)if(MN(a,c[d]))return a=c[d+1],c.splice(d,2),0===c.length&&delete this.map[b],this.size--,a};XN.prototype.entries=function(){return new WN(this,2)};XN.prototype.entries=XN.prototype.entries;XN.prototype.forEach=function(a){for(var b=this.rg(),c=0;c<b.length;c++)for(var d=this.map[b[c]],e=0;e<d.length;e+=2)a(d[e+1],d[e],this)};XN.prototype.forEach=XN.prototype.forEach;
XN.prototype.get=function(a,b){var c=ON(a);c=this.map[c];if(null!=c)for(b=0;b<c.length;b+=2){if(MN(a,c[b]))return c[b+1]}else return b};XN.prototype.get=XN.prototype.get;XN.prototype.has=function(a){var b=ON(a);b=this.map[b];if(null!=b)for(var c=0;c<b.length;c+=2)if(MN(a,b[c]))return!0;return!1};XN.prototype.has=XN.prototype.has;XN.prototype.keys=function(){return new WN(this,0)};XN.prototype.keys=XN.prototype.keys;
XN.prototype.vg=function(){for(var a=this.rg(),b=[],c=0;c<a.length;c++)for(var d=this.map[a[c]],e=0;e<d.length;e+=2)b.push(d[e]);return b};XN.prototype.keySet=XN.prototype.vg;XN.prototype.set=function(a,b){this.Db=-1;var c=ON(a),d=this.map[c];if(null==d)this.Ig&&this.Ig.push(c),this.map[c]=[a,b],this.size++;else{c=!0;for(var e=0;e<d.length;e+=2)if(MN(b,d[e])){c=!1;d[e]=b;break}c&&(d.push(a),d.push(b),this.size++)}};XN.prototype.set=XN.prototype.set;
XN.prototype.values=function(){return new WN(this,1)};XN.prototype.values=XN.prototype.values;XN.prototype.clone=function(){var a=ZN();this.forEach(function(b,c){a.set(c,b)});return a};XN.prototype.clone=XN.prototype.clone;XN.prototype[PO]=function(){return this.entries()};XN.prototype.Qe=function(){-1===this.Db&&(this.Db=KKa(this));return this.Db};XN.prototype.ue=function(a){return SKa(this,a)};$N.prototype.toString=function(){return VKa(this)};$N.prototype.inspect=function(){return this.toString()};
$N.prototype.add=function(a){this.map.set(a,a);this.size=this.map.size};$N.prototype.add=$N.prototype.add;$N.prototype.clear=function(){this.map=new XN;this.size=0};$N.prototype.clear=$N.prototype.clear;$N.prototype["delete"]=function(a){a=this.map.delete(a);this.size=this.map.size;return a};$N.prototype.entries=function(){return this.map.entries()};$N.prototype.entries=$N.prototype.entries;$N.prototype.forEach=function(a){var b=this;this.map.forEach(function(c,d){a(d,b)})};$N.prototype.forEach=$N.prototype.forEach;
$N.prototype.has=function(a){return this.map.has(a)};$N.prototype.has=$N.prototype.has;$N.prototype.keys=function(){return this.map.keys()};$N.prototype.keys=$N.prototype.keys;$N.prototype.vg=function(){return this.map.vg()};$N.prototype.keySet=$N.prototype.vg;$N.prototype.values=function(){return this.map.values()};$N.prototype.values=$N.prototype.values;$N.prototype.clone=function(){var a=XKa();this.forEach(function(b){a.add(b)});return a};$N.prototype.clone=$N.prototype.clone;
$N.prototype[PO]=function(){return this.values()};$N.prototype.ue=function(a){if(a instanceof $N){if(this.size===a.size)return MN(this.map,a.map)}else return!1};$N.prototype.Qe=function(){return ON(this.map)};aO.prototype.Ah={Gc:{_:function(){return null},"?":function(a){return"t"===a},b:function(a,b){if(b&&!1===b.Ij||"undefined"==typeof $APP.Ku.Oi)if("undefined"!=typeof Uint8Array){if("undefined"!=typeof atob)var c=atob(a);else{a=String(a).replace(/=+$/,"");if(1==a.length%4)throw Error("'atob' failed: The string to be decoded is not correctly encoded.");b=0;for(var d,e=0,f="";d=a.charAt(e++);~d&&(c=b%4?64*c+d:d,b++%4)?f+=String.fromCharCode(255&c>>(-2*b&6)):0)d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d".indexOf(d);
c=f}a=c.length;b=new Uint8Array(a);for(d=0;d<a;d++)b[d]=c.charCodeAt(d);c=b}else c=QN("b",a);else c=new $APP.Ku.Oi(a,"base64");return c},i:function(a){return RKa(a)},n:function(a){return QN("n",a)},d:function(a){return parseFloat(a)},f:function(a){return QN("f",a)},c:function(a){return a},":":function(a){return new RN(a)},$:function(a){return new SN(a)},r:function(a){return QN("r",a)},z:function(a){a:switch(a){case "-INF":a=-Infinity;break a;case "INF":a=Infinity;break a;case "NaN":a=NaN;break a;
default:throw Error("Invalid special double value "+a);}return a},"'":function(a){return a},m:function(a){a="number"===typeof a?a:parseInt(a,10);return new Date(a)},t:function(a){return new Date(a)},u:function(a){a=a.replace(/-/g,"");var b,c;var d=b=0;for(c=24;8>d;d+=2,c-=8)b|=parseInt(a.substring(d,d+2),16)<<c;var e=0;d=8;for(c=24;16>d;d+=2,c-=8)e|=parseInt(a.substring(d,d+2),16)<<c;var f=$APP.ra(e,b);b=0;d=16;for(c=24;24>d;d+=2,c-=8)b|=parseInt(a.substring(d,d+2),16)<<c;e=0;for(c=d=24;32>d;d+=2,
c-=8)e|=parseInt(a.substring(d,d+2),16)<<c;return new UN(f,$APP.ra(e,b))},set:function(a){return XKa(a)},list:function(a){return QN("list",a)},link:function(a){return QN("link",a)},cmap:function(a){return ZN(a,!1)}},uj:function(a,b){return QN(a,b)},Ci:!0,Ij:!0};
aO.prototype.decode=function(a,b,c,d){if(null==a)return null;switch(typeof a){case "string":return GKa(a,c)?(a=$Ka(this,a),b&&b.write(a,c),b=a):b="^"===a.charAt(0)&&" "!==a.charAt(1)?b.read(a,c):$Ka(this,a),b;case "object":if(LN(a))if("^ "===a[0])if(this.Ce)if(17>a.length&&this.Ce.fromArray){d=[];for(c=1;c<a.length;c+=2)d.push(this.decode(a[c],b,!0,!1)),d.push(this.decode(a[c+1],b,!1,!1));b=this.Ce.fromArray(d,a)}else{d=this.Ce.init(a);for(c=1;c<a.length;c+=2)d=this.Ce.add(d,this.decode(a[c],b,!0,
!1),this.decode(a[c+1],b,!1,!1),a);b=this.Ce.finalize(d,a)}else{d=[];for(c=1;c<a.length;c+=2)d.push(this.decode(a[c],b,!0,!1)),d.push(this.decode(a[c+1],b,!1,!1));b=ZN(d,!1)}else b=ZKa(this,a,b,c,d);else{c=NN(a);var e=c[0];if((d=1==c.length?this.decode(e,b,!1,!1):null)&&d instanceof YKa)a=a[e],c=this.Gc[d.pd],b=null!=c?c(this.decode(a,b,!1,!0),this):QN(d.pd,this.decode(a,b,!1,!1));else if(this.Ce)if(16>c.length&&this.Ce.fromArray){var f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.decode(e,b,!0,!1)),
f.push(this.decode(a[e],b,!1,!1));b=this.Ce.fromArray(f,a)}else{f=this.Ce.init(a);for(d=0;d<c.length;d++)e=c[d],f=this.Ce.add(f,this.decode(e,b,!0,!1),this.decode(a[e],b,!1,!1),a);b=this.Ce.finalize(f,a)}else{f=[];for(d=0;d<c.length;d++)e=c[d],f.push(this.decode(e,b,!0,!1)),f.push(this.decode(a[e],b,!1,!1));b=ZN(f,!1)}}return b}return a};aO.prototype.decode=aO.prototype.decode;bO.prototype.read=function(a){var b=this.cache;a=this.Pn.rm.decode(JSON.parse(a),b);this.cache.clear();return a};bO.prototype.read=bO.prototype.read;var cLa=0,XLa=(8|3&Math.round(14*Math.random())).toString(16),bLa="transit$guid$"+(JN()+JN()+JN()+JN()+JN()+JN()+JN()+JN()+"-"+JN()+JN()+JN()+JN()+"-4"+JN()+JN()+JN()+"-"+XLa+JN()+JN()+JN()+"-"+JN()+JN()+JN()+JN()+JN()+JN()+JN()+JN()+JN()+JN()+JN()+JN());dO.prototype.tag=function(){return"_"};dO.prototype.rep=function(){return null};dO.prototype.stringRep=function(){return"null"};eO.prototype.tag=function(){return"s"};eO.prototype.rep=function(a){return a};eO.prototype.stringRep=function(a){return a};
fO.prototype.tag=function(){return"i"};fO.prototype.rep=function(a){return a};fO.prototype.stringRep=function(a){return a.toString()};gO.prototype.tag=function(){return"i"};gO.prototype.rep=function(a){return a.toString()};gO.prototype.stringRep=function(a){return a.toString()};hO.prototype.tag=function(){return"?"};hO.prototype.rep=function(a){return a};hO.prototype.stringRep=function(a){return a.toString()};iO.prototype.tag=function(){return"array"};iO.prototype.rep=function(a){return a};
iO.prototype.stringRep=function(){return null};jO.prototype.tag=function(){return"map"};jO.prototype.rep=function(a){return a};jO.prototype.stringRep=function(){return null};kO.prototype.tag=function(){return"t"};kO.prototype.rep=function(a){return a.getUTCFullYear()+"-"+cO(a.getUTCMonth()+1,2)+"-"+cO(a.getUTCDate(),2)+"T"+cO(a.getUTCHours(),2)+":"+cO(a.getUTCMinutes(),2)+":"+cO(a.getUTCSeconds(),2)+"."+cO(a.getUTCMilliseconds(),3)+"Z"};kO.prototype.stringRep=function(a,b){return b.rep(a)};
lO.prototype.tag=function(){return"m"};lO.prototype.rep=function(a){return a.valueOf()};lO.prototype.stringRep=function(a){return a.valueOf().toString()};lO.prototype.getVerboseHandler=function(){return new kO};mO.prototype.tag=function(){return"u"};mO.prototype.rep=function(a){return a.toString()};mO.prototype.stringRep=function(a){return a.toString()};nO.prototype.tag=function(){return":"};nO.prototype.rep=function(a){return a.pc};nO.prototype.stringRep=function(a,b){return b.rep(a)};
oO.prototype.tag=function(){return"$"};oO.prototype.rep=function(a){return a.pc};oO.prototype.stringRep=function(a,b){return b.rep(a)};pO.prototype.tag=function(a){return a.tag};pO.prototype.rep=function(a){return a.rep};pO.prototype.stringRep=function(){return null};qO.prototype.tag=function(){return"set"};qO.prototype.rep=function(a){var b=[];a.forEach(function(c){b.push(c)});return QN("array",b)};qO.prototype.stringRep=function(){return null};rO.prototype.tag=function(){return"map"};
rO.prototype.rep=function(a){return a};rO.prototype.stringRep=function(){return null};sO.prototype.tag=function(){return"map"};sO.prototype.rep=function(a){return a};sO.prototype.stringRep=function(){return null};tO.prototype.tag=function(){return"b"};tO.prototype.rep=function(a){return a.toString("base64")};tO.prototype.stringRep=function(){return null};uO.prototype.tag=function(){return"b"};
uO.prototype.rep=function(a){for(var b,c=0,d=a.length,e="",f;c<d;)f=a.subarray(c,Math.min(c+32768,d)),e+=String.fromCharCode.apply(null,f),c+=32768;if("undefined"!=typeof btoa)b=btoa(e);else{a=String(e);d=0;e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/\x3d";for(f="";a.charAt(d|0)||(e="\x3d",d%1);f+=e.charAt(63&b>>8-d%1*8)){c=a.charCodeAt(d+=.75);if(255<c)throw Error("'btoa' failed: The string to be encoded contains characters outside of the Latin1 range.");b=b<<8|c}b=f}return b};
uO.prototype.stringRep=function(){return null};vO.prototype.get=function(a){a="string"===typeof a?this.Gc[a]:this.Gc[dLa(a)];return null!=a?a:this.Gc["default"]};vO.prototype.get=vO.prototype.get;vO.prototype.set=function(a,b){var c;if(c="string"===typeof a)a:{switch(a){case "null":case "string":case "boolean":case "number":case "array":case "map":c=!1;break a}c=!0}c?this.Gc[a]=b:this.Gc[dLa(a)]=b};yO.prototype.Hm=function(){return this.ah};yO.prototype.marshaller=yO.prototype.Hm;
yO.prototype.write=function(a,b){var c=b||{};b=c.asMapKey||!1;var d=this.ah.Th?!1:this.cache;if(!1===c.marshalTop)a=xO(this.ah,a,b,d);else{c=this.ah;var e=JSON,f=e.stringify,m=xO;var p=fLa(c,a)||(c.Dh?c.Dh(a,c.Gc):null);if(null!=p)a=1===p.tag(a).length?QN("'",a):a;else throw b=(null==a?null:a.constructor).name,d=Error("Cannot write "+b),d.data={Ja:a,type:b},d;a=f.call(e,m(c,a,b,d))}null!=this.cache&&this.cache.clear();return a};yO.prototype.write=yO.prototype.write;
yO.prototype.register=function(a,b){this.ah.Gc.set(a,b)};yO.prototype.register=yO.prototype.register;$APP.bk.prototype.S=function(a,b){return b instanceof $APP.bk?this.me===b.me:b instanceof UN?this.me===b.toString():!1};$APP.bk.prototype.Le=$APP.vd;$APP.bk.prototype.be=function(a,b){if(b instanceof $APP.bk||b instanceof UN)return $APP.Ve(this.toString(),b.toString());throw Error(["Cannot compare ",$APP.l.g(this)," to ",$APP.l.g(b)].join(""));};UN.prototype.Le=$APP.vd;
UN.prototype.be=function(a,b){if(b instanceof $APP.bk||b instanceof UN)return $APP.Ve(this.toString(),b.toString());throw Error(["Cannot compare ",$APP.l.g(this)," to ",$APP.l.g(b)].join(""));};$APP.pa.prototype.S=function(a,b){return this.equiv(b)};UN.prototype.S=function(a,b){return b instanceof $APP.bk?b.S(null,this):this.equiv(b)};PN.prototype.S=function(a,b){return this.equiv(b)};$APP.pa.prototype.ih=$APP.vd;$APP.pa.prototype.Y=function(){return ON(this)};UN.prototype.ih=$APP.vd;
UN.prototype.Y=function(){return $APP.yd(this.toString())};PN.prototype.ih=$APP.vd;PN.prototype.Y=function(){return ON(this)};UN.prototype.gj=$APP.vd;UN.prototype.La=$APP.vd;UN.prototype.W=function(a,b){return $APP.Kc(b,['#uuid "',$APP.l.g(this.toString()),'"'].join(""))};zO.prototype.init=function(){return $APP.Tc($APP.Uf)};zO.prototype.add=function(a,b,c){return $APP.Gh.j(a,b,c)};zO.prototype.finalize=function(a){return $APP.Vc(a)};
zO.prototype.fromArray=function(a){return $APP.Ch.j?$APP.Ch.j(a,!0,!0):$APP.Ch.call(null,a,!0,!0)};AO.prototype.init=function(){return $APP.Tc($APP.Sg)};AO.prototype.add=function(a,b){return $APP.Rg.h(a,b)};AO.prototype.finalize=function(a){return $APP.Vc(a)};AO.prototype.fromArray=function(a){return $APP.dh.h?$APP.dh.h(a,!0):$APP.dh.call(null,a,!0)};
$APP.QO=function QO(a){switch(arguments.length){case 1:return QO.g(arguments[0]);case 2:return QO.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.l.g(arguments.length)].join(""));}};$APP.QO.g=function(a){return $APP.QO.h(a,null)};
$APP.QO.h=function(a,b){return lLa($APP.Ei(a),nLa({handlers:$APP.cz($APP.Kl.l($APP.z([new $APP.h(null,6,["$",function(c){return $APP.kj.g(c)},":",function(c){return $APP.fj.g(c)},"set",function(c){return $APP.Eh.h($APP.yi,c)},"list",function(c){return $APP.Eh.h($APP.Hd,c.reverse())},"cmap",function(c){for(var d=0,e=$APP.Tc($APP.Uf);;)if(d<c.length){var f=d+2;e=$APP.Gh.j(e,c[d],c[d+1]);d=f}else return $APP.Vc(e)},"with-meta",function(c){return $APP.re(c[0],c[1])}],null),$APP.Ll.h($APP.MO.g(b),$APP.Km)]))),
defaultHandler:$APP.Km.g($APP.MO.g(b)),mapBuilder:new zO,arrayBuilder:new AO,preferStrings:!1,preferBuffers:!1},$APP.cz($APP.zt($APP.Ll.h(b,$APP.MO),new $APP.h(null,4,[KLa,zLa,GLa,ALa,ILa,BLa,MLa,TLa],null)))))};$APP.QO.B=2;CO.prototype.tag=function(){return":"};CO.prototype.rep=function(a){return a.N};CO.prototype.stringRep=function(a){return a.N};DO.prototype.tag=function(){return"$"};DO.prototype.rep=function(a){return a.pd};DO.prototype.stringRep=function(a){return a.pd};
$APP.EO.prototype.tag=function(){return"list"};$APP.EO.prototype.rep=function(a){var b=[];a=$APP.r(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.ha(null,e);b.push(f);e+=1}else if(a=$APP.r(a))c=a,$APP.Ee(c)?(a=$APP.cd(c),e=$APP.dd(c),c=a,d=$APP.be(a),a=e):(a=$APP.v(c),b.push(a),a=$APP.w(c),c=null,d=0),e=0;else break;return QN("array",b)};$APP.EO.prototype.stringRep=function(){return null};$APP.FO.prototype.tag=function(){return"map"};$APP.FO.prototype.rep=function(a){return a};
$APP.FO.prototype.stringRep=function(){return null};GO.prototype.tag=function(){return"set"};GO.prototype.rep=function(a){var b=[];a=$APP.r(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.ha(null,e);b.push(f);e+=1}else if(a=$APP.r(a))c=a,$APP.Ee(c)?(a=$APP.cd(c),e=$APP.dd(c),c=a,d=$APP.be(a),a=e):(a=$APP.v(c),b.push(a),a=$APP.w(c),c=null,d=0),e=0;else break;return QN("array",b)};GO.prototype.stringRep=function(){return null};$APP.HO.prototype.tag=function(){return"array"};
$APP.HO.prototype.rep=function(a){var b=[];a=$APP.r(a);for(var c=null,d=0,e=0;;)if(e<d){var f=c.ha(null,e);b.push(f);e+=1}else if(a=$APP.r(a))c=a,$APP.Ee(c)?(a=$APP.cd(c),e=$APP.dd(c),c=a,d=$APP.be(a),a=e):(a=$APP.v(c),b.push(a),a=$APP.w(c),c=null,d=0),e=0;else break;return b};$APP.HO.prototype.stringRep=function(){return null};IO.prototype.tag=function(){return"u"};IO.prototype.rep=function(a){return a.me};IO.prototype.stringRep=function(a){return this.rep(a)};JO.prototype.tag=function(){return"with-meta"};
JO.prototype.rep=function(a){return QN("array",[a.value,a.P])};JO.prototype.stringRep=function(){return null};$APP.RO=function RO(a){switch(arguments.length){case 1:return RO.g(arguments[0]);case 2:return RO.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.l.g(arguments.length)].join(""));}};$APP.RO.g=function(a){return $APP.RO.h(a,null)};
$APP.RO.h=function(a,b){var c=new $APP.EO,d=new $APP.FO,e=new GO,f=new $APP.HO,m=$APP.Kl.l($APP.z([$APP.gi([$APP.fi,$APP.xf,$APP.h,$APP.Xh,$APP.sh,$APP.Ed,$APP.F,$APP.mi,$APP.uf,$APP.Ff,$APP.lh,$APP.rh,$APP.ai,$APP.ri,oLa,$APP.Ah,$APP.G,$APP.D,$APP.fe,$APP.xi,$APP.ni,$APP.pi,$APP.hh,$APP.Ai,$APP.Kf,$APP.q,$APP.bk,$APP.Li,$APP.ji,$APP.li],[d,c,d,c,c,c,new CO,f,c,c,f,c,c,c,new JO,c,f,c,c,e,d,c,c,e,c,new DO,new IO,c,c,f]),"undefined"!==typeof $APP.Bx&&"undefined"!==typeof $APP.Cx&&"undefined"!==typeof $APP.qj?
$APP.Tf([$APP.qj,c]):null,"undefined"!==typeof $APP.Bx&&"undefined"!==typeof $APP.Cx&&"undefined"!==typeof $APP.Gg?$APP.Tf([$APP.Gg,c]):null,"undefined"!==typeof $APP.Bx&&"undefined"!==typeof $APP.Cx&&"undefined"!==typeof $APP.Se?$APP.Tf([$APP.Se,f]):null,$APP.MO.g(b)]));return mLa($APP.Ei(a),nLa({objectBuilder:function(p,u,t){return $APP.df(function(A,C,E){A.push(u.g?u.g(C):u.call(null,C),t.g?t.g(E):t.call(null,E));return A},["^ "],p)},handlers:function(){var p=FKa(m);p.forEach=function(u){for(var t=
$APP.r(this),A=null,C=0,E=0;;)if(E<C){var I=A.ha(null,E),Q=$APP.y.j(I,0,null);I=$APP.y.j(I,1,null);$APP.x.h($APP.Km,Q)?u.h?u.h(I,"default"):u.call(null,I,"default"):u.h?u.h(I,Q):u.call(null,I,Q);E+=1}else if(t=$APP.r(t))$APP.Ee(t)?(A=$APP.cd(t),t=$APP.dd(t),Q=A,C=$APP.be(A),A=Q):(A=$APP.v(t),Q=$APP.y.j(A,0,null),I=$APP.y.j(A,1,null),$APP.x.h($APP.Km,Q)?u.h?u.h(I,"default"):u.call(null,I,"default"):u.h?u.h(I,Q):u.call(null,I,Q),t=$APP.w(t),A=null,C=0),E=0;else return null};return p}(),unpack:function(p){return p instanceof
$APP.h?p.I:!1}},$APP.cz($APP.Ll.h(b,$APP.MO))))};$APP.RO.B=2;$APP.g=qLa.prototype;$APP.g.V=function(a,b){return new qLa(this.Li,this.Ei,this.Rh,this.Uh,b)};$APP.g.U=function(){return this.Mm};$APP.g.tag=function(a){return this.Li.g?this.Li.g(a):this.Li.call(null,a)};$APP.g.rep=function(a){return this.Ei.g?this.Ei.g(a):this.Ei.call(null,a)};$APP.g.stringRep=function(a){return $APP.k(this.Rh)?this.Rh.g?this.Rh.g(a):this.Rh.call(null,a):null};
$APP.g.getVerboseHandler=function(){return $APP.k(this.Uh)?this.Uh.D?this.Uh.D():this.Uh.call(null):null};$APP.SO=function SO(a){switch(arguments.length){case 2:return SO.h(arguments[0],arguments[1]);case 3:return SO.j(arguments[0],arguments[1],arguments[2]);case 4:return SO.F(arguments[0],arguments[1],arguments[2],arguments[3]);default:throw Error(["Invalid arity: ",$APP.l.g(arguments.length)].join(""));}};$APP.SO.h=function(a,b){return $APP.SO.F(a,b,null,null)};
$APP.SO.j=function(a,b,c){return $APP.SO.F(a,b,c,null)};$APP.SO.F=function(a,b,c,d){return new qLa($APP.pe(a)?a:$APP.sg(a),$APP.pe(b)?b:$APP.sg(b),$APP.pe(c)?c:$APP.sg(c),$APP.pe(d)?d:$APP.sg(d),$APP.Uf)};$APP.SO.B=4;var TO=$APP.kN.h($APP.ZG,null),YLa=$APP.gi([FLa,ELa,WLa,$APP.dC,wLa,uLa,VLa,LLa,$APP.yA,$APP.Yz],[function(){var a=new $APP.Cd(function(){return $APP.SO},NLa,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.oI,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.ZG,FLa,"cognitect/transit.cljs",20,new $APP.h(null,6,[$APP.DA,!1,$APP.Qs,4,$APP.DJ,4,$APP.lJ,new $APP.G(null,3,5,$APP.H,[new $APP.G(null,2,5,$APP.H,[NO,OO],null),new $APP.G(null,3,5,$APP.H,[NO,OO,LO],null),new $APP.G(null,4,5,$APP.H,[NO,OO,LO,
ULa],null)],null),$APP.U,$APP.J(new $APP.G(null,2,5,$APP.H,[NO,OO],null),new $APP.G(null,3,5,$APP.H,[NO,OO,LO],null),new $APP.G(null,4,5,$APP.H,[NO,OO,LO,ULa],null)),$APP.fF,$APP.J(null,null,null)],null),1,309,309,$APP.J(new $APP.G(null,2,5,$APP.H,[NO,OO],null),new $APP.G(null,3,5,$APP.H,[NO,OO,LO],null),new $APP.G(null,4,5,$APP.H,[NO,OO,LO,ULa],null)),"Creates a transit write handler whose tag, rep,\n   stringRep, and verboseWriteHandler methods\n   invoke the provided fns.",$APP.k($APP.SO)?$APP.SO.H:
null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,TO,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return rLa},RLa,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.ZG,ELa,"cognitect/transit.cljs",19,1,332,332,
$APP.J(new $APP.G(null,2,5,$APP.H,[$APP.RG,CLa],null)),"Construct a tagged value. tag must be a string and rep can\n   be any transit encodeable value.",$APP.k(rLa)?rLa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,TO,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return $APP.KO},
OLa,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.ZG,WLa,"cognitect/transit.cljs",12,1,294,294,$APP.J(new $APP.G(null,2,5,$APP.H,[SLa,$APP.PH],null)),"Encode an object into a transit string given a transit writer.",$APP.k($APP.KO)?$APP.KO.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,TO,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=
$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return $APP.BO},QLa,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.ZG,$APP.dC,"cognitect/transit.cljs",11,1,146,146,$APP.J(new $APP.G(null,2,5,$APP.H,[$APP.QH,$APP.IG],null)),"Read a transit encoded string into ClojureScript values given a\n   transit reader.",$APP.k($APP.BO)?$APP.BO.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?
null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,TO,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return $APP.EO},DLa,new $APP.h(null,8,[$APP.P,$APP.ZG,$APP.M,null,$APP.Vl,"cognitect/transit.cljs",$APP.Wl,164,$APP.Om,19,$APP.N,wLa,$APP.lF,$APP.k($APP.EO)?$APP.EO.H:null,$APP.U,$APP.Hd],null)),b=$APP.n(a),
c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,TO,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return tLa},yLa,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.ZG,uLa,"cognitect/transit.cljs",17,1,432,432,$APP.J(new $APP.G(null,
1,5,$APP.H,[$APP.WH],null)),"For :transform. Will write any metadata present on the value.",$APP.k(tLa)?tLa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,TO,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return sLa},xLa,$APP.gi([$APP.P,$APP.N,$APP.Vl,
$APP.Zz,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.ZG,VLa,"cognitect/transit.cljs",14,1,343,343,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.TH],null)),"Construct a transit integer value. Returns JavaScript number if\n  in the 53bit integer range, a goog.math.Long instance if above. s\n  may be a string or a JavaScript number.",$APP.k(sLa)?sLa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,TO,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],
null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return pLa},JLa,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.ZG,LLa,"cognitect/transit.cljs",19,1,299,299,$APP.J(new $APP.G(null,1,5,$APP.H,[vLa],null)),"Construct a read handler. Implemented as identity, exists primarily\n   for API compatiblity with transit-clj",
$APP.k(pLa)?pLa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,TO,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return $APP.QO},HLa,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.oI,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.ZG,$APP.yA,"cognitect/transit.cljs",
13,new $APP.h(null,6,[$APP.DA,!1,$APP.Qs,2,$APP.DJ,2,$APP.lJ,new $APP.G(null,2,5,$APP.H,[new $APP.G(null,1,5,$APP.H,[$APP.FE],null),new $APP.G(null,2,5,$APP.H,[$APP.FE,$APP.bG],null)],null),$APP.U,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.FE],null),new $APP.G(null,2,5,$APP.H,[$APP.FE,$APP.bG],null)),$APP.fF,$APP.J(null,null)],null),1,106,106,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.FE],null),new $APP.G(null,2,5,$APP.H,[$APP.FE,$APP.bG],null)),"Return a transit reader. type may be either :json or :json-verbose.\n   opts may be a map optionally containing a :handlers entry. The value\n   of :handlers should be map from string tag to a decoder function of one\n   argument which returns the in-memory representation of the semantic transit\n   value. If a :default handler is provided, it will be used when no matching\n   read handler can be found.",
$APP.k($APP.QO)?$APP.QO.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,TO,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return $APP.RO},PLa,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.oI,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.ZG,$APP.Yz,
"cognitect/transit.cljs",13,new $APP.h(null,6,[$APP.DA,!1,$APP.Qs,2,$APP.DJ,2,$APP.lJ,new $APP.G(null,2,5,$APP.H,[new $APP.G(null,1,5,$APP.H,[$APP.FE],null),new $APP.G(null,2,5,$APP.H,[$APP.FE,$APP.bG],null)],null),$APP.U,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.FE],null),new $APP.G(null,2,5,$APP.H,[$APP.FE,$APP.bG],null)),$APP.fF,$APP.J(null,null)],null),1,212,212,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.FE],null),new $APP.G(null,2,5,$APP.H,[$APP.FE,$APP.bG],null)),"Return a transit writer. type maybe either :json or :json-verbose.\n  opts is a map with the following optional keys:\n\n    :handlers  - a map of type constructors to handler instances. Can optionally\n                 provide a :default write handler which will be used if no\n                 matching handler can be found.\n    :transform - a function of one argument returning a transformed value. Will\n                 be invoked on a value before it is written.",
$APP.k($APP.RO)?$APP.RO.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,TO,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}()]);$APP.Yu(new $APP.h(null,1,[$APP.Kq,new $APP.h(null,1,[$APP.ZG,YLa],null)],null));