import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var eS=function(a,b,c){if(null!=a&&null!=a.pf)a=a.pf(a,b,c);else{var d=eS[$APP.ca(null==a?null:a)];if(null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else if(d=eS._,null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else throw $APP.Ab("ITransientVector.-assoc-n!",a);}return a},fS=function(a,b,c){var d=$APP.ie(a);if(c>=d)return-1;!(0<c)&&0>c&&(c+=d,c=0>c?0:c);for(;;)if(c<d){if($APP.B.h($APP.C.h(a,c),b))return c;c+=1}else return-1},gS=function(a,b,c){var d=$APP.ie(a);if(0===d)return-1;0<c?(--d,c=d<c?d:c):c=0>
c?d+c:c;for(;;)if(0<=c){if($APP.B.h($APP.C.h(a,c),b))return c;--c}else return-1},hS=function(a,b){if($APP.Je(b))if($APP.ge(a)&&$APP.ge(b)&&$APP.ie(a)!==$APP.ie(b))a=!1;else a:for(a=$APP.u(a),b=$APP.u(b);;){if(null==a){a=null==b;break a}if(null!=b&&$APP.B.h($APP.x(a),$APP.x(b)))a=$APP.z(a),b=$APP.z(b);else{a=!1;break a}}else a=null;return $APP.Ta(a)},iS=function(a,b){var c=a.Z(null);if(0===c)return b.F?b.F():b.call(null);for(var d=a.fa(null,0),e=1;;)if(e<c){var h=a.fa(null,e);d=b.h?b.h(d,h):b.call(null,
d,h);if($APP.Xd(d))return $APP.q(d);e+=1}else return d},jS=function(a,b,c){var d=a.Z(null),e=c;for(c=0;;)if(c<d){var h=a.fa(null,c);e=b.h?b.h(e,h):b.call(null,e,h);if($APP.Xd(e))return $APP.q(e);c+=1}else return e},kS=function(a){return"number"===typeof a||"string"===typeof a||$APP.Ue(a)||null==a},nS=function(a,b,c,d){var e=null!=d?d.g?d.g(a):d.call(null,a):null;return null==e?kS(a)?a:$APP.sb(a)?new lS(null,a,b,c,d,!0,null,null,null):$APP.nb(a)?new mS(null,b,c,d,a,null):a:e},oS=function(a){return kS(a)?
a:a instanceof lS?a.Da:a instanceof mS?a.H:a},pS=function(a,b,c,d,e){var h=$APP.Wh($APP.Tc(Oia));$APP.cS(a,function(l,p){return h.Mc(null,$APP.kj.j(h.Oa(null),b.g?b.g(p):b.call(null,p),$APP.m(e)?nS(l,b,c,d):l))});return $APP.Vc($APP.q(h))},rS=function(a){a:for(var b=a.length,c=$APP.Db(a),d=0;;)if(d<b){var e=d;var h=a[d];h=qS.g?qS.g(h):qS.call(null,h);c[e]=h;d+=1}else break a;return $APP.uf(c)},sS=function(a,b,c,d,e,h,l){l=h[l];h=b.g?b.g(l):b.call(null,l);a=a[l];b=e?nS(a,b,c,d):a;return new $APP.kf(h,
b,null)},tS=function(a,b){return a instanceof $APP.k&&b===$APP.Xk||"string"===typeof a&&b===$APP.zf},uS=function(a,b){return kS(a)||!($APP.Le(a)&&!(a instanceof lS)||$APP.Ne(a)&&!(a instanceof mS))&&$APP.qb($APP.m(b)?$APP.sb(a)||$APP.nb(a):b)},vS=function(a,b,c,d,e,h){this.Mb=!0;this.Da=a;this.ta=b;this.ca=c;this.transform=d;this.za=e;this.gd=h;this.J=259;this.N=56},wS=function(a,b,c,d,e,h,l){this.Da=a;this.ta=b;this.ca=c;this.transform=d;this.za=e;this.H=h;this.S=0;this.O=l},xS=function(a,b,c,d,
e,h,l,p){this.Da=a;this.ta=b;this.ca=c;this.transform=d;this.za=e;this.H=h;this.S=l;this.K=p;this.J=2179858686;this.N=8192},lS=function(a,b,c,d,e,h,l,p,t){this.K=a;this.Da=b;this.ta=c;this.ca=d;this.transform=e;this.za=h;this.qd=l;this.gd=p;this.D=t;this.J=2164131599;this.N=139268},yS=function(a,b,c,d){this.Mb=!0;this.H=a;this.ta=b;this.ca=c;this.transform=d;this.N=88;this.J=275},zS=function(a,b,c,d,e){this.ta=a;this.ca=b;this.transform=c;this.H=d;this.S=0;this.O=e},AS=function(a,b,c,d,e,h){this.ta=
a;this.ca=b;this.transform=c;this.H=d;this.S=e;this.K=h;this.J=2179858686;this.N=8192},mS=function(a,b,c,d,e,h){this.K=a;this.ta=b;this.ca=c;this.transform=d;this.H=e;this.D=h;this.J=2315150111;this.N=141316},BS=function(a){return a instanceof $APP.k?a.T:null},CS=function(a){return a instanceof lS},DS=function(a){return a.Da},dNa=new $APP.r("cljs-bean.core","-\x3ejs","cljs-bean.core/-\x3ejs",272545438,null),eNa=new $APP.k(null,"key-\x3eprop","key-\x3eprop",-1028452531),fNa=new $APP.r(null,"bean?",
"bean?",2057456095,null),gNa=new $APP.k(null,"recursive","recursive",718885872),hNa=new $APP.k(null,"prop-\x3ekey","prop-\x3ekey",-1297715246),iNa=new $APP.r("cljs-bean.core","bean?","cljs-bean.core/bean?",-413971875,null),jNa=new $APP.r("cljs-bean.core","bean","cljs-bean.core/bean",444589162,null),kNa=new $APP.r(null,"bean","bean",-1620239896,null),lNa=new $APP.k(null,"transform","transform",1381301764),mNa=new $APP.r(null,"-\x3eclj","-\x3eclj",-1549422014,null),nNa=new $APP.r("cljs-bean.core","object",
"cljs-bean.core/object",1153194626,null),oNa=new $APP.r("cljs-bean.core","-\x3eclj","cljs-bean.core/-\x3eclj",649375936,null),pNa=new $APP.r(null,"-\x3ejs","-\x3ejs",-1825590244,null);var KU={},Oia=$APP.uh;$APP.f=vS.prototype;$APP.f.ea=function(a,b){if(this.Mb)return a=this.Da[this.ca.g?this.ca.g(b):this.ca.call(null,b)],this.za?nS(a,this.ta,this.ca,this.transform):a;throw Error("lookup after persistent!");};$APP.f.M=function(a,b,c){if(this.Mb)return a=$APP.Ja(this.Da,this.ca.g?this.ca.g(b):this.ca.call(null,b),c),this.za&&a!==c?nS(a,this.ta,this.ca,this.transform):a;throw Error("lookup after persistent!");};
$APP.f.Z=function(){return null==this.gd?this.gd=$APP.ie($APP.Ga(this.Da)):this.gd};$APP.f.Gd=function(a,b){a:if($APP.m(this.Mb))if($APP.Fi(b))a=this.be(null,$APP.gc(b),$APP.hc(b));else if($APP.Ne(b))a=this.be(null,b.g?b.g(0):b.call(null,0),b.g?b.g(1):b.call(null,1));else for(a=$APP.u(b),b=this;;){var c=$APP.x(a);if($APP.m(c))a=$APP.z(a),b=$APP.Wc(b,$APP.gc(c),$APP.hc(c));else{a=b;break a}}else throw Error("conj! after persistent!");return a};
$APP.f.ne=function(){if(this.Mb)return this.Mb=!1,new lS(null,this.Da,this.ta,this.ca,this.transform,this.za,null,this.gd,null);throw Error("persistent! called twice");};$APP.f.be=function(a,b,c){if(this.Mb){if(!tS(b,this.ta)||!uS(c,this.za))return $APP.Wc($APP.Tc(pS(this.Da,this.ta,this.ca,this.transform,this.za)),b,c);this.Da[this.ca.g?this.ca.g(b):this.ca.call(null,b)]=this.za?oS(c):c;this.gd=null;return this}throw Error("assoc! after persistent!");};
$APP.f.bg=function(a,b){if(this.Mb)return delete this.Da[this.ca.g?this.ca.g(b):this.ca.call(null,b)],this.gd=null,this;throw Error("dissoc! after persistent!");};$APP.f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.n.g(arguments.length-1)].join(""));}};$APP.f.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Db(b)))};
$APP.f.g=function(a){if(this.Mb)return a=this.Da[this.ca.g?this.ca.g(a):this.ca.call(null,a)],this.za?nS(a,this.ta,this.ca,this.transform):a;throw Error("lookup after persistent!");};$APP.f.h=function(a,b){if(this.Mb)return a=$APP.Ja(this.Da,this.ca.g?this.ca.g(a):this.ca.call(null,a),b),this.za&&a!==b?nS(a,this.ta,this.ca,this.transform):a;throw Error("lookup after persistent!");};wS.prototype.hasNext=function(){return this.S<this.O};
wS.prototype.next=function(){var a=sS(this.Da,this.ta,this.ca,this.transform,this.za,this.H,this.S);this.S+=1;return a};$APP.f=xS.prototype;$APP.f.toString=function(){return $APP.qd(this)};$APP.f.equiv=function(a){return this.R(null,a)};$APP.f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return fS(this,b,0);case 2:return fS(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return fS(this,b,0)};a.h=function(b,c){return fS(this,b,c)};return a}();
$APP.f.lastIndexOf=function(){function a(c){return gS(this,c,$APP.ie(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return gS(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return gS(this,c,d)};return b}();$APP.f.fa=function(a,b){a=b+this.S;if(0<=a&&a<this.H.length)return sS(this.Da,this.ta,this.ca,this.transform,this.za,this.H,a);throw Error("Index out of bounds");};
$APP.f.Ua=function(a,b,c){a=b+this.S;return 0<=a&&a<this.H.length?sS(this.Da,this.ta,this.ca,this.transform,this.za,this.H,a):c};$APP.f.V=function(a,b,c){return $APP.Lk(b,$APP.Vk,"("," ",")",c,this)};$APP.f.W=function(){return this.K};$APP.f.ba=function(){return new xS(this.Da,this.ta,this.ca,this.transform,this.za,this.H,this.S,this.K)};$APP.f.Na=function(){return this.S+1<this.H.length?new xS(this.Da,this.ta,this.ca,this.transform,this.za,this.H,this.S+1,null):null};
$APP.f.Z=function(){var a=this.H.length-this.S;return 0>a?0:a};$APP.f.Y=function(){return $APP.Nd(this)};$APP.f.R=function(a,b){return hS(this,b)};$APP.f.Ha=function(){return $APP.Id};$APP.f.Qa=function(a,b){return iS(this,b)};$APP.f.Ra=function(a,b,c){return jS(this,b,c)};$APP.f.Sa=function(){return sS(this.Da,this.ta,this.ca,this.transform,this.za,this.H,this.S)};$APP.f.hb=function(){return this.S+1<this.H.length?new xS(this.Da,this.ta,this.ca,this.transform,this.za,this.H,this.S+1,null):$APP.Id};
$APP.f.aa=function(){return this};$APP.f.X=function(a,b){return b===this.K?this:new xS(this.Da,this.ta,this.ca,this.transform,this.za,this.H,this.S,b)};$APP.f.da=function(a,b){return $APP.Fg(b,this)};$APP.f=lS.prototype;$APP.f.Zd=$APP.yd;$APP.f.Fd=function(a,b){a=$APP.Ja(this.Da,this.ca.g?this.ca.g(b):this.ca.call(null,b),KU);return a===KU?null:new $APP.kf(b,this.za?nS(a,this.ta,this.ca,this.transform):a,null)};$APP.f.toString=function(){return $APP.qd(this)};
$APP.f.equiv=function(a){return this.R(null,a)};$APP.f.keys=function(){return $APP.Ld($APP.fk(this))};$APP.f.entries=function(){return $APP.$i($APP.u(this))};$APP.f.values=function(){return $APP.Ld($APP.hk(this))};$APP.f.has=function(a){return $APP.jf(this,a)};$APP.f.get=function(a,b){return this.M(null,a,b)};
$APP.f.forEach=function(a){for(var b=$APP.u(this),c=null,d=0,e=0;;)if(e<d){var h=c.fa(null,e),l=$APP.C.j(h,0,null);h=$APP.C.j(h,1,null);a.h?a.h(h,l):a.call(null,h,l);e+=1}else if(b=$APP.u(b))$APP.Oe(b)?(c=$APP.dd(b),b=$APP.fd(b),l=c,d=$APP.ie(c),c=l):(c=$APP.x(b),l=$APP.C.j(c,0,null),h=$APP.C.j(c,1,null),a.h?a.h(h,l):a.call(null,h,l),b=$APP.z(b),c=null,d=0),e=0;else return null};
$APP.f.ea=function(a,b){a=this.Da[this.ca.g?this.ca.g(b):this.ca.call(null,b)];return this.za?nS(a,this.ta,this.ca,this.transform):a};$APP.f.M=function(a,b,c){a=$APP.Ja(this.Da,this.ca.g?this.ca.g(b):this.ca.call(null,b),c);return this.za&&a!==c?nS(a,this.ta,this.ca,this.transform):a};
$APP.f.ra=function(a,b,c){var d=this;try{var e=$APP.Wh(c);$APP.cS(d.Da,function(h,l){var p=e.Mc;var t=e.Oa(null);l=d.ta.g?d.ta.g(l):d.ta.call(null,l);h=d.za?nS(h,d.ta,d.ca,d.transform):h;t=b.j?b.j(t,l,h):b.call(null,t,l,h);p=p.call(e,null,t);if($APP.Xd(p))throw p;return null});return $APP.q(e)}catch(h){a=h;if($APP.Xd(a))return $APP.q(a);throw a;}};$APP.f.V=function(a,b,c){return $APP.Yk(this,$APP.Vk,b,c)};
$APP.f.ia=function(){null==this.qd&&(this.qd=$APP.Ga(this.Da));return new wS(this.Da,this.ta,this.ca,this.transform,this.za,this.qd,this.Z(null))};$APP.f.W=function(){return this.K};$APP.f.ba=function(){return new lS(this.K,this.Da,this.ta,this.ca,this.transform,this.za,this.qd,this.gd,this.D)};$APP.f.Z=function(){return null==this.gd?(null==this.qd&&(this.qd=$APP.Ga(this.Da)),this.gd=this.qd.length):this.gd};$APP.f.Y=function(){var a=this.D;return null!=a?a:this.D=a=$APP.Od(this)};
$APP.f.R=function(a,b){return $APP.Xi(this,b)};$APP.f.Yd=function(){return new vS($APP.dS(this.Da),this.ta,this.ca,this.transform,this.za,this.gd)};$APP.f.Ha=function(){return new lS(this.K,{},this.ta,this.ca,this.transform,this.za,[],0,null)};$APP.f.Qa=function(a,b){return $APP.Cz(this.aa(null),b)};$APP.f.Ra=function(a,b,c){return this.ra(null,function(d,e,h){e=new $APP.kf(e,h,null);return b.h?b.h(d,e):b.call(null,d,e)},c)};
$APP.f.wa=function(a,b){a=this.K;var c=$APP.dS(this.Da);delete c[this.ca.g?this.ca.g(b):this.ca.call(null,b)];return new lS(a,c,this.ta,this.ca,this.transform,this.za,null,null,null)};$APP.f.U=function(a,b,c){if(tS(b,this.ta)&&uS(c,this.za)){a=this.K;var d=$APP.dS(this.Da);d[this.ca.g?this.ca.g(b):this.ca.call(null,b)]=this.za?oS(c):c;b=new lS(a,d,this.ta,this.ca,this.transform,this.za,null,null,null)}else b=$APP.$b($APP.Ae(pS(this.Da,this.ta,this.ca,this.transform,this.za),this.K),b,c);return b};
$APP.f.ja=function(a,b){return this.M(null,b,KU)!==KU};$APP.f.aa=function(){null==this.qd&&(this.qd=$APP.Ga(this.Da));return 0<this.qd.length?new xS(this.Da,this.ta,this.ca,this.transform,this.za,this.qd,0,null):null};$APP.f.X=function(a,b){return b===this.K?this:new lS(b,this.Da,this.ta,this.ca,this.transform,this.za,this.qd,this.gd,this.D)};
$APP.f.da=function(a,b){a:if($APP.Ne(b))a=this.U(null,$APP.ve(b,0),$APP.ve(b,1));else for(a=this,b=$APP.u(b);;){if(null==b)break a;var c=$APP.x(b);if($APP.Ne(c))a=$APP.$b(a,$APP.ve(c,0),$APP.ve(c,1)),b=$APP.z(b);else throw Error("conj on a map takes map entries or seqables of map entries");}return a};
$APP.f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.n.g(arguments.length-1)].join(""));}};$APP.f.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Db(b)))};$APP.f.g=function(a){a=this.Da[this.ca.g?this.ca.g(a):this.ca.call(null,a)];return this.za?nS(a,this.ta,this.ca,this.transform):a};
$APP.f.h=function(a,b){a=$APP.Ja(this.Da,this.ca.g?this.ca.g(a):this.ca.call(null,a),b);return this.za&&a!==b?nS(a,this.ta,this.ca,this.transform):a};$APP.f=yS.prototype;$APP.f.Gd=function(a,b){if(this.Mb)return uS(b,!0)?(this.H.push(oS(b)),this):$APP.Uc($APP.Tc(rS(this.H)),b);throw Error("conj! after persistent!");};$APP.f.ne=function(){if(this.Mb)return this.Mb=!1,new mS(null,this.ta,this.ca,this.transform,this.H,null);throw Error("persistent! called twice");};
$APP.f.be=function(a,b,c){if("number"===typeof b)a=this.pf(null,b,c);else throw Error([$APP.n.g("TransientArrayVector"),"'s key for assoc! must be a number."].join(""));return a};
$APP.f.pf=function(a,b,c){if(this.Mb){if(uS(c,!0)){if(0<=b&&b<this.H.length)return this.H[b]=oS(c),this;if(b===this.H.length)return this.Gd(null,c);throw Error(["Index ",$APP.n.g(b)," out of bounds for TransientArrayVector of length",$APP.n.g(this.H.length)].join(""));}return eS($APP.Tc(rS(this.H)),b,c)}throw Error("assoc! after persistent!");};
$APP.f.Pg=function(){if(this.Mb){if(0===this.H.length)throw Error("Can't pop empty vector");this.H=this.H.slice(0,this.H.length-1);return this}throw Error("pop! after persistent!");};$APP.f.Z=function(){if(this.Mb)return this.H.length;throw Error("count after persistent!");};$APP.f.fa=function(a,b){if(this.Mb)return nS(this.H[b],this.ta,this.ca,this.transform);throw Error("nth after persistent!");};$APP.f.Ua=function(a,b,c){return 0<=b&&b<this.H.length?this.fa(null,b):c};
$APP.f.ea=function(a,b){return this.M(null,b,null)};$APP.f.M=function(a,b,c){return"number"===typeof b?this.Ua(null,b,c):c};$APP.f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.n.g(arguments.length-1)].join(""));}};$APP.f.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Db(b)))};$APP.f.g=function(a){return this.ea(null,a)};
$APP.f.h=function(a,b){return this.M(null,a,b)};zS.prototype.hasNext=function(){return this.S<this.O};zS.prototype.next=function(){var a=nS(this.H[this.S],this.ta,this.ca,this.transform);this.S+=1;return a};$APP.f=AS.prototype;$APP.f.toString=function(){return $APP.qd(this)};$APP.f.equiv=function(a){return this.R(null,a)};
$APP.f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return fS(this,b,0);case 2:return fS(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return fS(this,b,0)};a.h=function(b,c){return fS(this,b,c)};return a}();
$APP.f.lastIndexOf=function(){function a(c){return gS(this,c,$APP.ie(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return gS(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return gS(this,c,d)};return b}();$APP.f.fa=function(a,b){a=b+this.S;if(0<=a&&a<this.H.length)return nS(this.H[a],this.ta,this.ca,this.transform);throw Error("Index out of bounds");};
$APP.f.Ua=function(a,b,c){a=b+this.S;return 0<=a&&a<this.H.length?nS(this.H[a],this.ta,this.ca,this.transform):c};$APP.f.V=function(a,b,c){return $APP.Lk(b,$APP.Vk,"("," ",")",c,this)};$APP.f.W=function(){return this.K};$APP.f.ba=function(){return new AS(this.ta,this.ca,this.transform,this.H,this.S,this.K)};$APP.f.Na=function(){return this.S+1<this.H.length?new AS(this.ta,this.ca,this.transform,this.H,this.S+1,null):null};$APP.f.Z=function(){var a=this.H.length-this.S;return 0>a?0:a};$APP.f.Y=function(){return $APP.Nd(this)};
$APP.f.R=function(a,b){return hS(this,b)};$APP.f.Ha=function(){return $APP.Id};$APP.f.Qa=function(a,b){return iS(this,b)};$APP.f.Ra=function(a,b,c){return jS(this,b,c)};$APP.f.Sa=function(){return nS(this.H[this.S],this.ta,this.ca,this.transform)};$APP.f.hb=function(){return this.S+1<this.H.length?new AS(this.ta,this.ca,this.transform,this.H,this.S+1,null):$APP.Id};$APP.f.aa=function(){return this};$APP.f.X=function(a,b){return b===this.K?this:new AS(this.ta,this.ca,this.transform,this.H,this.S,b)};
$APP.f.da=function(a,b){return $APP.Fg(b,this)};$APP.f=mS.prototype;$APP.f.Zd=$APP.yd;$APP.f.Fd=function(a,b){return 0<=b&&b<this.H.length?new $APP.kf(b,nS(this.H[b],this.ta,this.ca,this.transform),null):null};$APP.f.toString=function(){return $APP.qd(this)};$APP.f.equiv=function(a){return this.R(null,a)};
$APP.f.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return fS(this,b,0);case 2:return fS(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return fS(this,b,0)};a.h=function(b,c){return fS(this,b,c)};return a}();
$APP.f.lastIndexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return gS(this,b,$APP.ie(this));case 2:return gS(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return gS(this,b,$APP.ie(this))};a.h=function(b,c){return gS(this,b,c)};return a}();$APP.f.ea=function(a,b){return this.M(null,b,null)};$APP.f.M=function(a,b,c){return"number"===typeof b?this.Ua(null,b,c):c};
$APP.f.ra=function(a,b,c){a=0;for(var d=c;;)if(a<this.H.length){c=this.H.length;var e;a:for(e=0;;)if(e<c){var h=e+a,l=nS(this.H[e],this.ta,this.ca,this.transform);d=b.j?b.j(d,h,l):b.call(null,d,h,l);if($APP.Xd(d)){e=d;break a}e+=1}else{e=d;break a}if($APP.Xd(e))return $APP.q(e);a+=c;d=e}else return d};$APP.f.fa=function(a,b){if(0<=b&&b<this.H.length)return nS(this.H[b],this.ta,this.ca,this.transform);throw Error(["No item ",$APP.n.g(b)," in vector of length ",$APP.n.g(this.H.length)].join(""));};
$APP.f.Ua=function(a,b,c){return 0<=b&&b<this.H.length?nS(this.H[b],this.ta,this.ca,this.transform):c};$APP.f.V=function(a,b,c){return $APP.Lk(b,$APP.Vk,"["," ","]",c,this)};$APP.f.jd=function(a,b,c){if(0<=b&&b<this.H.length)return uS(c,!0)?(a=$APP.Db(this.H),a[b]=oS(c),new mS(this.K,this.ta,this.ca,this.transform,a,null)):$APP.nc(rS(this.H),b,c);if(b===this.H.length)return this.da(null,c);throw Error(["Index ",$APP.n.g(b)," out of bounds  [0,",$APP.n.g(this.H.length),"]"].join(""));};
$APP.f.ia=function(){return new zS(this.ta,this.ca,this.transform,this.H,this.H.length)};$APP.f.W=function(){return this.K};$APP.f.ba=function(){return new mS(this.K,this.ta,this.ca,this.transform,this.H,this.D)};$APP.f.Z=function(){return this.H.length};$APP.f.$d=function(){return 0<this.H.length?this.fa(null,this.H.length-1):null};
$APP.f.ae=function(){if(0===this.H.length)throw Error("Can't pop empty vector");if(1===this.H.length)return this.Ha(null);var a=$APP.Db(this.H);return new mS(this.K,this.ta,this.ca,this.transform,a.slice(0,a.length-1),null)};$APP.f.Wc=function(){return 0<this.H.length?new $APP.me(this,this.H.length-1,null):null};$APP.f.Y=function(){var a=this.D;return null!=a?a:this.D=a=$APP.Nd(this)};
$APP.f.R=function(a,b){a:if(b instanceof mS)if(this.H.length===$APP.ie(b))for(a=this.ia(null),b=$APP.od(b);;)if(a.hasNext()){var c=a.next(),d=b.next();if(!$APP.B.h(c,d)){a=!1;break a}}else{a=!0;break a}else a=!1;else a=hS(this,b);return a};$APP.f.Yd=function(){return new yS($APP.Db(this.H),this.ta,this.ca,this.transform)};$APP.f.Ha=function(){return new mS(this.K,this.ta,this.ca,this.transform,[],null)};$APP.f.Qa=function(a,b){return iS(this,b)};$APP.f.Ra=function(a,b,c){return jS(this,b,c)};
$APP.f.U=function(a,b,c){if("number"===typeof b)a=this.jd(null,b,c);else throw Error("Vector's key for assoc must be a number.");return a};$APP.f.ja=function(a,b){return $APP.Ze(b)?0<=b&&b<this.H.length:!1};$APP.f.aa=function(){return 0<this.H.length?new AS(this.ta,this.ca,this.transform,this.H,0,null):null};$APP.f.X=function(a,b){return b===this.K?this:new mS(b,this.ta,this.ca,this.transform,this.H,this.D)};
$APP.f.da=function(a,b){return uS(b,!0)?(a=$APP.Db(this.H),a[a.length]=oS(b),new mS(this.K,this.ta,this.ca,this.transform,a,null)):$APP.Pb(rS(this.H),b)};$APP.f.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.n.g(arguments.length-1)].join(""));}};$APP.f.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Db(b)))};$APP.f.g=function(a){return this.fa(null,a)};
$APP.f.h=function(a,b){return this.Ua(null,a,b)};$APP.f.hd=function(a,b){if($APP.Ne(b)){a=$APP.ie(this);var c=$APP.ie(b);if(a<c)b=-1;else if(a>c)b=1;else if(0===a)b=0;else a:for(c=0;;){var d=$APP.mf($APP.C.h(this,c),$APP.C.h(b,c));if(0===d&&c+1<a)c+=1;else{b=d;break a}}return b}throw Error(["Cannot compare ",$APP.n.g(this)," to ",$APP.n.g(b)].join(""));};
var LU=function LU(a){switch(arguments.length){case 0:return LU.F();case 1:return LU.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return LU.l(arguments[0],new $APP.Fd(c.slice(1),0,null))}};LU.F=function(){return new lS(null,{},$APP.Xk,BS,null,!1,[],0,null)};LU.g=function(a){return new lS(null,a,$APP.Xk,BS,null,!1,null,null,null)};
LU.l=function(a,b){var c=$APP.ph(b);b=$APP.gf.h(c,$APP.ly);var d=$APP.gf.h(c,hNa),e=$APP.gf.h(c,eNa),h=$APP.gf.h(c,lNa);c=$APP.gf.h(c,gNa);return!1===b?new lS(null,a,$APP.zf,$APP.zf,h,$APP.Ta(c),null,null,null):null!=d&&null!=e?new lS(null,a,d,e,h,$APP.Ta(c),null,null,null):new lS(null,a,$APP.Xk,BS,h,$APP.Ta(c),null,null,null)};LU.G=function(a){var b=$APP.x(a);a=$APP.z(a);return this.l(b,a)};LU.C=1;
var qS=function qS(a){switch(arguments.length){case 1:return qS.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return qS.l(arguments[0],new $APP.Fd(c.slice(1),0,null))}};qS.g=function(a){return nS(a,$APP.Xk,BS,null)};qS.l=function(a,b){var c=$APP.ph(b);b=$APP.gf.h(c,$APP.ly);var d=$APP.gf.h(c,hNa),e=$APP.gf.h(c,eNa);c=$APP.gf.h(c,lNa);return!1===b?nS(a,$APP.zf,$APP.zf,c):null!=d&&null!=e?nS(a,d,e,c):nS(a,$APP.Xk,BS,c)};
qS.G=function(a){var b=$APP.x(a);a=$APP.z(a);return this.l(b,a)};qS.C=1;var ES=function ES(a){switch(arguments.length){case 1:return ES.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return ES.l(arguments[0],new $APP.Fd(c.slice(1),0,null))}};ES.g=function(a){return a instanceof lS?a.Da:a instanceof mS?a.H:$APP.eB.l(a,$APP.F([$APP.fy,BS]))};
ES.l=function(a,b){if(a instanceof lS)return a.Da;if(a instanceof mS)return a.H;b=$APP.ph(b);b=$APP.gf.j(b,eNa,BS);return $APP.eB.l(a,$APP.F([$APP.fy,b]))};ES.G=function(a){var b=$APP.x(a);a=$APP.z(a);return this.l(b,a)};ES.C=1;var MU=$APP.zJ.h($APP.WE,null),Via=new $APP.g(null,5,[kNa,function(){var a=new $APP.Dd(function(){return LU},jNa,$APP.Oj([$APP.O,$APP.U,$APP.Km,$APP.vB,$APP.FH,$APP.io,$APP.Lm,$APP.BP,$APP.V,$APP.N,$APP.oF],[$APP.WE,kNa,"cljs_bean/core.cljs",11,new $APP.g(null,6,[$APP.nC,!0,$APP.sw,1,$APP.GI,1,$APP.qI,new $APP.H(null,2,5,$APP.I,[$APP.qi,new $APP.H(null,1,5,$APP.I,[$APP.mH],null)],null),$APP.V,$APP.R($APP.qi,new $APP.H(null,1,5,$APP.I,[$APP.mH],null),new $APP.H(null,3,5,$APP.I,[$APP.mH,$APP.ah,$APP.TF],
null)),$APP.lF,$APP.R(null,null,null)],null),1,702,702,$APP.R($APP.qi,new $APP.H(null,1,5,$APP.I,[$APP.mH],null),new $APP.H(null,3,5,$APP.I,[$APP.mH,$APP.ah,$APP.TF],null)),"Takes a JavaScript object and returns a read-only implementation of the map\n  abstraction backed by the object.\n\n  By default, bean produces beans that keywordize the keys. Supply\n  :keywordize-keys false to suppress this behavior. You can alternatively\n  supply :prop-\x3ekey and :key-\x3eprop with functions that control the mapping\n  between properties and keys.\n\n  Supply :recursive true to create a bean which recursively converts\n  JavaScript object values to beans and JavaScript arrays into vectors.\n\n  Supply :transform and a function of one argument to transform values being\n  converted from JavaScript to ClojureScript. This function should return nil\n  if no conversion is to be performed, thus allowing default logic to be applied.\n\n  Calling (bean) produces an empty bean.",
$APP.m(LU)?LU.A:null])),b=$APP.q(a),c=$APP.Be(a);a=$APP.m(null)?null:$APP.U.g(c);var d=new $APP.g(null,4,[$APP.O,MU,$APP.U,a,$APP.V,$APP.V.g(c),$APP.N,$APP.N.g(c)],null);return $APP.m($APP.Qt.g(c))?$APP.uJ.j(a,b,d):$APP.m(function(){var e=$APP.Qs.g(c);return $APP.m(e)?e:$APP.Ys.g(c)}())?$APP.vJ.j(a,b,d):$APP.xy.j(a,b,d)}(),fNa,function(){var a=new $APP.Dd(function(){return CS},iNa,$APP.Oj([$APP.O,$APP.U,$APP.Km,$APP.vB,$APP.io,$APP.Lm,$APP.BP,$APP.V,$APP.N,$APP.oF],[$APP.WE,fNa,"cljs_bean/core.cljs",
12,1,735,735,$APP.R(new $APP.H(null,1,5,$APP.I,[$APP.mH],null)),"Returns true if x is a bean.",$APP.m(CS)?CS.A:null])),b=$APP.q(a),c=$APP.Be(a);a=$APP.m(null)?null:$APP.U.g(c);var d=new $APP.g(null,4,[$APP.O,MU,$APP.U,a,$APP.V,$APP.V.g(c),$APP.N,$APP.N.g(c)],null);return $APP.m($APP.Qt.g(c))?$APP.uJ.j(a,b,d):$APP.m(function(){var e=$APP.Qs.g(c);return $APP.m(e)?e:$APP.Ys.g(c)}())?$APP.vJ.j(a,b,d):$APP.xy.j(a,b,d)}(),$APP.Bya,function(){var a=new $APP.Dd(function(){return DS},nNa,$APP.Oj([$APP.O,$APP.U,
$APP.Km,$APP.vB,$APP.io,$APP.Lm,$APP.BP,$APP.An,$APP.V,$APP.N,$APP.oF],[$APP.WE,$APP.Bya,"cljs_bean/core.cljs",17,1,740,740,$APP.oE,$APP.R(new $APP.H(null,1,5,$APP.I,[$APP.PG],null)),"Takes a bean and returns a JavaScript object.",$APP.m(DS)?DS.A:null])),b=$APP.q(a),c=$APP.Be(a);a=$APP.m(null)?null:$APP.U.g(c);var d=new $APP.g(null,4,[$APP.O,MU,$APP.U,a,$APP.V,$APP.V.g(c),$APP.N,$APP.N.g(c)],null);return $APP.m($APP.Qt.g(c))?$APP.uJ.j(a,b,d):$APP.m(function(){var e=$APP.Qs.g(c);return $APP.m(e)?e:
$APP.Ys.g(c)}())?$APP.vJ.j(a,b,d):$APP.xy.j(a,b,d)}(),pNa,function(){var a=new $APP.Dd(function(){return ES},dNa,$APP.Oj([$APP.O,$APP.U,$APP.Km,$APP.vB,$APP.FH,$APP.io,$APP.Lm,$APP.BP,$APP.V,$APP.N,$APP.oF],[$APP.WE,pNa,"cljs_bean/core.cljs",11,new $APP.g(null,6,[$APP.nC,!0,$APP.sw,1,$APP.GI,1,$APP.qI,new $APP.H(null,1,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.mH],null)],null),$APP.V,$APP.R(new $APP.H(null,1,5,$APP.I,[$APP.mH],null),new $APP.H(null,3,5,$APP.I,[$APP.mH,$APP.ah,$APP.TF],null)),$APP.lF,
$APP.R(null,null)],null),1,775,775,$APP.R(new $APP.H(null,1,5,$APP.I,[$APP.mH],null),new $APP.H(null,3,5,$APP.I,[$APP.mH,$APP.ah,$APP.TF],null)),"Recursively converts ClojureScript values to JavaScript.\n\n  Where possible, directly returns the backing objects and arrays for values\n  produced using -\x3eclj and bean.\n\n  Otherwise delegates to clj-\x3ejs to perform the conversion, converting keyword\n  keys using their qualified names. You can alternatively supply :key-\x3eprop with\n  a function that controls the mapping from keys to properties.",
$APP.m(ES)?ES.A:null])),b=$APP.q(a),c=$APP.Be(a);a=$APP.m(null)?null:$APP.U.g(c);var d=new $APP.g(null,4,[$APP.O,MU,$APP.U,a,$APP.V,$APP.V.g(c),$APP.N,$APP.N.g(c)],null);return $APP.m($APP.Qt.g(c))?$APP.uJ.j(a,b,d):$APP.m(function(){var e=$APP.Qs.g(c);return $APP.m(e)?e:$APP.Ys.g(c)}())?$APP.vJ.j(a,b,d):$APP.xy.j(a,b,d)}(),mNa,function(){var a=new $APP.Dd(function(){return qS},oNa,$APP.Oj([$APP.O,$APP.U,$APP.Km,$APP.vB,$APP.FH,$APP.io,$APP.Lm,$APP.BP,$APP.V,$APP.N,$APP.oF],[$APP.WE,mNa,"cljs_bean/core.cljs",
12,new $APP.g(null,6,[$APP.nC,!0,$APP.sw,1,$APP.GI,1,$APP.qI,new $APP.H(null,1,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.mH],null)],null),$APP.V,$APP.R(new $APP.H(null,1,5,$APP.I,[$APP.mH],null),new $APP.H(null,3,5,$APP.I,[$APP.mH,$APP.ah,$APP.TF],null)),$APP.lF,$APP.R(null,null)],null),1,745,745,$APP.R(new $APP.H(null,1,5,$APP.I,[$APP.mH],null),new $APP.H(null,3,5,$APP.I,[$APP.mH,$APP.ah,$APP.TF],null)),"Recursively converts JavaScript values to ClojureScript.\n\n  JavaScript objects are converted to beans with keywords for keys.\n\n  JavaScript arrays are converted to read-only implementations of the vector\n  abstraction, backed by the supplied array.\n\n  By default, -\x3eclj produces values that keywordize the keys. Supply\n  :keywordize-keys false to suppress this behavior. You can alternatively\n  supply :prop-\x3ekey and :key-\x3eprop with functions that control the mapping\n  between properties and keys.\n\n  Supply :transform and a function of one argument to transform values being\n  converted from JavaScript to ClojureScript. This function should return nil\n  if no conversion is to be performed, thus allowing default logic to be applied.",
$APP.m(qS)?qS.A:null])),b=$APP.q(a),c=$APP.Be(a);a=$APP.m(null)?null:$APP.U.g(c);var d=new $APP.g(null,4,[$APP.O,MU,$APP.U,a,$APP.V,$APP.V.g(c),$APP.N,$APP.N.g(c)],null);return $APP.m($APP.Qt.g(c))?$APP.uJ.j(a,b,d):$APP.m(function(){var e=$APP.Qs.g(c);return $APP.m(e)?e:$APP.Ys.g(c)}())?$APP.vJ.j(a,b,d):$APP.xy.j(a,b,d)}()],null);$APP.Wy(new $APP.g(null,1,[$APP.Ft,new $APP.g(null,1,[$APP.WE,Via],null)],null));