import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_module from"node:module";import*as esm_import$node_fs from"node:fs";import*as esm_import$import_meta_resolve from"import-meta-resolve";import*as esm_import$node_path from"node:path";import*as esm_import$node_url from"node:url";var fGa,hGa,ZFa,YFa,cGa,iGa,dGa,jGa,gGa;
$APP.XFa=function(a){a=$APP.Ld(a);a=$APP.as.h($APP.Af,a);a=$APP.mn.h(function(d){return $APP.bu($APP.wu(),d)},a);var b=$APP.p($APP.Fq),c=$APP.p($APP.rq);return $APP.Au(a,new $APP.k(null,2,[$APP.Q,b,$APP.Wl,c],null))};$APP.$Fa=function(a,b){return YFa(ZFa,a,b)};
$APP.dU=function(a,b){return Promise.resolve($APP.l($APP.p(aGa))?null:function(){var c=esm_import$node_path.resolve($APP.l(a)?a:"script.cljs"),d=$APP.l($APP.bB.g(b))?$APP.vi.j(b,$APP.bB,$APP.SP.g(esm_import$node_fs.readFileSync($APP.bB.g(b),"utf8"))):function(){var h;a:for(h=c;;){var n=esm_import$node_fs.existsSync(h);n=$APP.l(n)?esm_import$node_fs.lstatSync(h).isDirectory():n;if($APP.l(n)){n=esm_import$node_path.resolve(h,"nbb.edn");if($APP.l(esm_import$node_fs.existsSync(n))){h=n;break a}n=esm_import$node_path.dirname(h)}else n=
esm_import$node_path.dirname(h);if($APP.y.h(n,h)){h=null;break a}h=n}return $APP.l(h)?(n=$APP.SP.g(esm_import$node_fs.readFileSync(h,"utf8")),$APP.vi.l(b,$APP.bB,n,$APP.B([$APP.CN,esm_import$node_path.dirname(h)]))):b}(),e=bGa.g?bGa.g(c):bGa.call(null,c),f=$APP.m.g(esm_import$node_url.pathToFileURL(c));$APP.Cu.require=e;$APP.Cj.D($APP.Eu,$APP.vi,$APP.un,e);$APP.Cj.D($APP.Eu,$APP.vi,$APP.Fu,function(h){return esm_import$import_meta_resolve.resolve(h,f)});$APP.Bg($APP.AS,d);return Promise.resolve(function(){var h=
function(){var E=$APP.Cb(cGa.g(d));return E?$APP.bB.g(d):E}();if($APP.l(h)){h=dGa.g(h);if($APP.l(h)){h=$APP.u(h);for(var n=null,t=0,q=0;;)if(q<t){var x=n.ca(null,q);$APP.Cb(esm_import$node_path.isAbsolute(x))?$APP.xp(function(){var E=$APP.CN.g(d);return $APP.l(E)?esm_import$node_path.resolve(E,x):x}()):$APP.xp(x);q+=1}else if(h=$APP.u(h)){n=h;if($APP.Ge(n))h=$APP.cd(n),q=$APP.dd(n),n=h,t=$APP.ce(h),h=q;else{var z=$APP.v(n);$APP.Cb(esm_import$node_path.isAbsolute(z))?$APP.xp(function(){var E=$APP.CN.g(d);
return $APP.l(E)?esm_import$node_path.resolve(E,z):z}()):$APP.xp(z);h=$APP.w(n);n=null;t=0}q=0}else break}else $APP.xp(esm_import$node_process.cwd());return shadow_esm_import("./nbb_deps.js")}return $APP.xp(esm_import$node_process.cwd())}()).then(function(){return $APP.Bg(aGa,!0)})}())};$APP.eGa=function(a,b){return $APP.Gt(a,b)};
fGa=function(a,b){b=$APP.$t(a,$APP.bl("(keys (ns-map '%s))","%s",b));b=$APP.fj.h(function(c){return["`",$APP.m.g(c)].join("")},b);b=["[",$APP.kn.h(" ",b),"]"].join("");a=$APP.$t(a,b);return $APP.as.h(function(c){return $APP.kl($APP.m.g(c),"nbb.internal")},a)};
hGa=function(a,b){var c=$APP.wu();b=$APP.hl.h(b,/\//);$APP.A.j(b,0,null);var d=$APP.A.j(b,1,null),e=$APP.$t(c,$APP.zj.l($APP.B([$APP.T.g($APP.u($APP.K.l(new $APP.D(null,$APP.Jq,null,1,null),new $APP.D(null,$APP.df($APP.T.g($APP.u($APP.K.h(new $APP.D(null,gGa,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.h(new $APP.D(null,$APP.hE,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.h(new $APP.D(null,$APP.zk,null,1,null),new $APP.D(null,a,null,1,null)))),null,1,null)))),null,1,null))))),null,1,
null),$APP.B([new $APP.D(null,$APP.T.g($APP.u($APP.K.l(new $APP.D(null,$APP.mN,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.h(new $APP.D(null,$APP.MG,null,1,null),new $APP.D(null,gGa,null,1,null)))),null,1,null),$APP.B([new $APP.D(null,gGa,null,1,null)])))),null,1,null)]))))])));if($APP.l(e)&&(c=$APP.l(d)?function(){var n=$APP.Fa(d,"."),t=$APP.hl.h(d,/\./);n=n?t:$APP.Gi(t);return new $APP.H(null,2,5,$APP.I,[[$APP.m.g(a),"/",$APP.u(n)?[$APP.kn.h(".",n),"."].join(""):null].join(""),$APP.sg.j($APP.La,
e,n)],null)}():new $APP.H(null,2,5,$APP.I,[[$APP.m.g(a),"/"].join(""),e],null),$APP.l(c))){var f=$APP.A.j(c,0,null),h=$APP.A.j(c,1,null);c=function(){for(var n=h,t=$APP.Sg;;)if($APP.l(n)){var q=Object.getPrototypeOf(n);t=$APP.Fh.h(t,Object.getOwnPropertyNames(n));n=q}else return t}();return $APP.fj.h(function(n){return new $APP.H(null,2,5,$APP.I,[null,[$APP.m.g(f),$APP.m.g(n)].join("")],null)},c)}return null};
$APP.kGa=function(a){var b=$APP.Yf(a);a=$APP.C.h(b,$APP.Q);try{var c=$APP.wu(),d=$APP.l(a)?$APP.eGa(c,$APP.lj.g(a)):null,e=$APP.Wf([$APP.Fq,$APP.l(d)?d:$APP.p($APP.Fq)]);$APP.Vp(e);try{var f=function(){var la=$APP.Am.g(b);return $APP.l(la)?la:$APP.fJ.g(b)}();if($APP.l(f)){var h=$APP.Ha(f,"/"),n=h?function(){var la=$APP.hl.h(f,/\//);la=null==la?null:$APP.v(la);return null==la?null:$APP.lj.g(la)}():null,t=fGa(c,$APP.$t(c,"(ns-name *ns*)")),q=$APP.fj.h(function(la){return new $APP.H(null,3,5,$APP.I,
[$APP.Cf(la),$APP.Hi(la),iGa],null)},t),x=$APP.$t(c,"(let [m (ns-aliases *ns*)] (zipmap (keys m) (map ns-name (vals m))))"),z=$APP.Ii($APP.ti(x),$APP.ri(x)),E=$APP.Nn.g($APP.Og.l(function(la){var ua=$APP.C.h(x,la);la=$APP.$t(c,$APP.bl("(keys (ns-publics '%s))","%s",ua));return $APP.fj.h(function(pa){return new $APP.H(null,3,5,$APP.I,[$APP.m.g(ua),$APP.m.g(pa),jGa],null)},la)},$APP.B([$APP.ri(x)]))),F=$APP.fj.h(function(la){return new $APP.H(null,3,5,$APP.I,[$APP.m.g(la),null,jGa],null)},$APP.$t(c,
"(all-ns)")),N=h?hGa(n,f):null,S=$APP.l(N)?null:h?function(){var la=$APP.C.j(x,n,n),ua=$APP.$t(c,$APP.bl("(and (find-ns '%s)\n                                                                                         (keys (ns-publics '%s)))","%s",la));return $APP.fj.h(function(pa){return new $APP.H(null,3,5,$APP.I,[$APP.m.g(la),$APP.m.g(pa),jGa],null)},ua)}():null,Y=$APP.K.l(q,E,$APP.B([F,S])),aa=$APP.qn.h(function(la){var ua=$APP.A.j(la,0,null);var pa=$APP.A.j(la,1,null);la=$APP.A.j(la,2,null);la=
$APP.y.h(iGa,la)&&$APP.Ha(pa,f)?new $APP.H(null,2,5,$APP.I,[ua,pa],null):null;$APP.l(la)?ua=la:$APP.l(ua)?(la=[$APP.m.g($APP.C.h(z,$APP.lj.g(ua))),"/",$APP.m.g(pa)].join(""),la=$APP.Ha(la,f)?new $APP.H(null,2,5,$APP.I,[ua,la],null):null,$APP.l(la)?ua=la:(pa=[$APP.m.g(ua),"/",$APP.m.g(pa)].join(""),ua=$APP.Ha(pa,f)?new $APP.H(null,2,5,$APP.I,[ua,pa],null):null)):ua=null;return ua},Y),ca=$APP.K.h(aa,N),ha=$APP.df($APP.iy.g($APP.fj.h(function(la){var ua=$APP.A.j(la,0,null);la=$APP.A.j(la,1,null);la=
new $APP.k(null,1,["candidate",$APP.m.g(la)],null);return $APP.l(ua)?$APP.vi.j(la,"ns",$APP.m.g(ua)):la},ca)));return new $APP.k(null,2,["completions",ha,"status",new $APP.H(null,1,5,$APP.I,["done"],null)],null)}return new $APP.k(null,1,["status",new $APP.H(null,1,5,$APP.I,["done"],null)],null)}finally{$APP.Xp()}}catch(la){return console.warn(la),new $APP.k(null,2,["completions",$APP.Sg,"status",new $APP.H(null,1,5,$APP.I,["done"],null)],null)}};ZFa={};
YFa=function YFa(a,b,c){for(;;){if(b instanceof Promise)return b;if(ZFa===a){if($APP.Le(b))return $APP.ES(b,b,c,YFa);a=$APP.Ku(b,c)}else{b=Promise;var e=b.resolve;var f=$APP.YL.g(c);f=$APP.l(f)?f:$APP.ff;c=new $APP.k(null,1,[$APP.Q,$APP.Q.g(c)],null);c=f.h?f.h(a,c):f.call(null,a,c);return e.call(b,c)}}};$APP.lGa=new $APP.r(null,"socket-repl","socket-repl",-1615225633,null);$APP.mGa=new $APP.r(null,"repl","repl",1605132860,null);cGa=new $APP.G(null,"disableConfig","disableConfig",844586790);
iGa=new $APP.G(null,"unqualified","unqualified",-98904653);dGa=new $APP.G(null,"paths","paths",-1807389588);jGa=new $APP.G(null,"qualified","qualified",-2065109343);$APP.nGa=new $APP.r(null,"start-server!","start-server!",203437330,null);gGa=new $APP.r(null,"resolved__34551__auto__","resolved__34551__auto__",1651274921,null);$APP.eU=new $APP.G(null,"classpath","classpath",299521985);var bGa,aGa;bGa=function(){var a=esm_import$node_module.createRequire;return $APP.l(a)?a:function(){return function(){throw Error("createRequire is not defined, this is a no-op");}}}();aGa=$APP.Bj.g(!1);$APP.fU=function fU(a){switch(arguments.length){case 1:return fU.g(arguments[0]);case 2:return fU.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};$APP.fU.g=function(a){return $APP.fU.h(a,null)};
$APP.fU.h=function(a,b){b=$APP.Hy.l(b,$APP.B([$APP.Iy,!0]));var c=esm_import$node_path.resolve(a);$APP.Bg($APP.rDa,c);return $APP.dU(c,b).then(function(){return $APP.Pu(c)})};$APP.fU.A=2;$APP.gU=function gU(a){switch(arguments.length){case 1:return gU.g(arguments[0]);case 2:return gU.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};$APP.gU.g=function(a){return $APP.gU.h(a,null)};
$APP.gU.h=function(a,b){b=$APP.Hy.l(b,$APP.B([$APP.Iy,!0]));return $APP.dU(null,b).then(function(){return $APP.Nu(a)})};$APP.gU.A=2;export const loadFile=$APP.fU;export const loadString=$APP.gU;export const getClassPath=function(){return $APP.wp()};export const addClassPath=function(a){return $APP.xp(a)};export const version=function(){return $APP.av()};export const registerModule=function(a,b){b=$APP.cja($APP.Ik(b));return $APP.Cj.D($APP.Du,$APP.vi,b,a)};export const printErrorReport=$APP.FS;