import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var mTa,oTa,pTa,yS,zS,qTa,rTa,sTa,tTa,uTa,vTa,wTa,xTa,BS,yTa,DS,zTa,ATa,BTa,CTa,FS,GS,HS,DTa,KS,ETa,FTa,GTa,HTa,MS,ITa,JTa,MTa,PS,NTa,OTa,PTa,QTa,RTa,TTa,VTa,WTa,YTa,WS,bUa,dUa,eUa,fUa,gUa,hUa,iUa,lUa,XS,mUa,nUa,oUa,pUa,rUa,YS,tUa,uUa,vUa,wUa,xUa,yUa,zUa,CUa,FUa,GUa,HUa,IUa,LUa,MUa,NUa,TS,OUa,PUa,QUa,RUa,SUa,DUa,TUa,$S,UUa,VUa,WUa,XUa,YUa,ZUa,$Ua,aVa,LS,bVa,cUa,cVa,dVa,eVa,aT,fVa,jUa,gVa,JS,hVa,iVa,jVa,SS,kVa,lVa,mVa,nVa,oVa,pVa,US,qVa,rVa,sVa,tVa,KUa,uVa,vVa,wVa,cT,xVa,yVa,zVa,AVa,BVa,CVa,DVa,EVa,
dT,FVa,GVa,JUa,HVa,IVa,JVa,KVa,LVa,MVa,NVa,OVa,UTa,PVa,QVa,$Ta,RVa,SVa;mTa=function(a){return $APP.Yd(a)<2?$APP.Uk(a):""+$APP.G.h($APP.Uk($APP.Ui.j(a,0,1)))+$APP.G.h($APP.Ui.g(a,1))};oTa=function(a){if(typeof a==="string")return a;a=$APP.Di(a);var b=$APP.Zk.g(a,/-/),c=$APP.m(b);b=$APP.p(c);c=$APP.q(c);return $APP.h(nTa.h?nTa.h(b):nTa.call(null,b))?a:$APP.sg.j($APP.G,b,$APP.Pj.g(mTa,c))};
pTa=function(a){var b=function(){var c=function(){var d=$APP.le(a);if(d){d=a.displayName;if($APP.h(d))return d;d=a.name;return typeof d==="string"&&$APP.m(d)?d:null}return d}();if($APP.h(c))return c;c=function(){var d=a!=null?a.K&4096||$APP.rd===a.mh?!0:!1:!1;return d?$APP.Di(a):d}();if($APP.h(c))return c;c=$APP.pe(a);return $APP.xe(c)?$APP.R.h(c):null}();return $APP.h(b)?$APP.Sk(""+$APP.G.h(b),"$","."):null};yS=function(a){return a instanceof $APP.C||a instanceof $APP.l};
zS=function(a){if($APP.xe(a))try{var b=$APP.z.g(a,$APP.dE)}catch(c){b=null}else b=null;return b};qTa=function(a){var b=$APP.dE.h($APP.pe(a));if($APP.h(b))return b;b=zS($APP.v.j(a,1,null));if($APP.h(b))return b;b=$APP.v.j(a,0,null);switch(b instanceof $APP.C?b.M:null){case "\x3e":case "f\x3e":return zS($APP.v.j(a,2,null));case "r\x3e":return a=$APP.v.j(a,2,null),a==null?null:a.key;default:return null}};rTa=function(a){return setTimeout(a,16)};sTa=function(a,b){return a.tj-b.tj};tTa=function(){return null};
uTa=function(a){for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.D?d.D():d.call(null);c+=1}else return null};vTa=function(a,b,c){b.push(c);return a.schedule()};wTa=function(){this.Qi=!1};xTa=function(a){if($APP.h(a.cljsIsDirty))return null;a.cljsIsDirty=!0;return AS.queue_render(a)};BS=function(a){if(a!=null&&a.zn!=null)a=a.id;else{var b=BS[$APP.ea(a==null?null:a)];if(b!=null)a=b.h?b.h(a):b.call(null,a);else if(b=BS._,b!=null)a=b.h?b.h(a):b.call(null,a);else throw $APP.Ib("Compiler.get-id",a);}return a};
yTa=function(a,b,c){if(a!=null&&a.xl!=null)a=a.xl(a,b,c);else{var d=yTa[$APP.ea(a==null?null:a)];if(d!=null)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else if(d=yTa._,d!=null)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else throw $APP.Ib("Compiler.parse-tag",a);}return a};
$APP.CS=function(a,b){if(a!=null&&a.vl!=null)a=a.vl(a,b);else{var c=$APP.CS[$APP.ea(a==null?null:a)];if(c!=null)a=c.g?c.g(a,b):c.call(null,a,b);else if(c=$APP.CS._,c!=null)a=c.g?c.g(a,b):c.call(null,a,b);else throw $APP.Ib("Compiler.as-element",a);}return a};
DS=function(a,b,c,d,e){if(a!=null&&a.wl!=null)a=a.wl(a,b,c,d,e);else{var f=DS[$APP.ea(a==null?null:a)];if(f!=null)a=f.P?f.P(a,b,c,d,e):f.call(null,a,b,c,d,e);else if(f=DS._,f!=null)a=f.P?f.P(a,b,c,d,e):f.call(null,a,b,c,d,e);else throw $APP.Ib("Compiler.make-element",a);}return a};
zTa=function(a,b){b.Zi=null;var c=ES;ES=b;try{var d=a.D?a.D():a.call(null)}finally{ES=c}a=b.Zi;b.Yf=!1;a:{c=b.Ig;var e=a==null?0:a.length,f=e===(c==null?0:c.length);if(f){for(f=0;;){var k=f===e;if(k){c=k;break a}if(a[f]===c[f])f+=1;else{c=!1;break a}}c=void 0}else c=f}c||b._update_watching(a);return d};ATa=function(a){var b=ES;if(b!=null){var c=b.Zi;c==null?b.Zi=[a]:c.push(a)}};BTa=function(a,b,c){b=$APP.ui.j(a.pb,b,c);a.pb=b;return a.bk=null};
CTa=function(a,b){b=$APP.Il.g(a.pb,b);a.pb=b;return a.bk=null};FS=function(a,b,c){var d=a.bk;d=d==null?a.bk=$APP.af(function(t,w,y){t.push(w);t.push(y);return t},[],a.pb):d;for(var e=d.length,f=0;;)if(f<e){var k=d[f],n=d[f+1];n.F?n.F(k,a,b,c):n.call(null,k,a,b,c);f=2+f}else return null};GS=function(a,b,c,d){$APP.Ic(a,"#object[reagent.ratom."+$APP.G.h(c)+" ");c=ES;ES=null;ES=c;$APP.ej(d,a,b);return $APP.Ic(a,"]")};
HS=function(a,b,c,d){this.state=a;this.O=b;this.Gg=c;this.pb=d;this.I=2154201088;this.K=114690};DTa=function(a,b,c,d,e){var f=b.Tj;f=f==null?$APP.Xf:f;var k=f.g?f.g(c,null):f.call(null,c,null);if(k!=null)return $APP.oc(k);if(ES==null)return a.D?a.D():a.call(null);k=function(){function t(w){var y=$APP.Il.g(b.Tj,c);b.Tj=y;d!=null&&(d.Th=null);return e!=null?e.h?e.h(w):e.call(null,w):null}return IS.j?IS.j(a,JS,t):IS.call(null,a,JS,t)}();var n=$APP.oc(k);b.Tj=$APP.ui.j(f,c,k);d!=null&&(d.Th=k);return n};
KS=function(a,b){this.f=a;this.Ca=b;this.Th=null;this.I=2153807872;this.K=0};ETa=function(a,b){return new KS(a,b)};FTa=function(a,b){var c=ETa(a,b);a=function(){function d(){return c.La(null)}return IS.j?IS.j(d,LS,!0):IS.call(null,d,LS,!0)}();$APP.oc(a);return a};GTa=function(a,b){this.oc=a;this.path=b;this.pb=this.state=this.Th=null;this.I=2153807872;this.K=114690};HTa=function(a){a=a.destroy;return a==null?null:a.D?a.D():a.call(null)};
MS=function(a){if(a!=null&&a.Uj!=null)a=a.Uj(a);else{var b=MS[$APP.ea(a==null?null:a)];if(b!=null)a=b.h?b.h(a):b.call(null,a);else if(b=MS._,b!=null)a=b.h?b.h(a):b.call(null,a);else throw $APP.Ib("IDisposable.dispose!",a);}return a};ITa=function(a,b,c,d){return a._handle_change(b,c,d)};JTa=function(a){this.f=a;this.state=null;this.Yf=!0;this.Rk=!1;this.$i=this.pf=this.pb=this.Ig=null;this.I=2153807872;this.K=114690};
$APP.OS=function(){for(;;){var a=NS;if(a==null)return null;NS=null;for(var b=a.length,c=0;;)if(c<b)a[c]._queued_run(),c+=1;else break}};MTa=function(a,b){var c=KTa,d=LTa,e=zTa(a,d);d.Ig!=null&&(LTa=IS(null),d._set_opts(c),d.f=a,d.pf=function(){return xTa.h?xTa.h(b):xTa.call(null,b)},b.cljsRatom=d);return e};
PS=function(a,b){var c=b.argv;if(c==null){c=$APP.E;a=a.constructor;a:{for(var d=$APP.Oa(b),e=d.length,f=$APP.Xf,k=0;;)if(k<e){var n=d[k];f=$APP.ui.j(f,$APP.fj.h(n),$APP.Qa(b,n));k+=1}else{b=f;break a}b=void 0}b=new $APP.D(null,2,5,c,[a,b],null)}else b=c;return b};NTa=function(a){var b;if(b=$APP.le(a))a=a==null?null:a.prototype,b=(a==null?null:a.bg)!=null;return b};OTa=function(a){var b;if(b=$APP.le(a))a=a==null?null:a.prototype,b=(a==null?null:a.render)!=null;return b};
PTa=function(a,b){for(;;){var c=a.bg,d=a.om===!0?c.call(a,a):function(){var e=PS(a,a.props);switch($APP.Yd(e)){case 1:return c.call(a);case 2:return c.call(a,$APP.v.g(e,1));case 3:return c.call(a,$APP.v.g(e,1),$APP.v.g(e,2));case 4:return c.call(a,$APP.v.g(e,1),$APP.v.g(e,2),$APP.v.g(e,3));case 5:return c.call(a,$APP.v.g(e,1),$APP.v.g(e,2),$APP.v.g(e,3),$APP.v.g(e,4));default:return c.apply(a,$APP.Ir.h(e).slice(1))}}();if($APP.ze(d))return $APP.CS(b,d);if($APP.He(d))a.bg=NTa(d)?function(e,f,k,n,t){return function(){function w(u){var B=
null;if(arguments.length>0){B=0;for(var H=Array(arguments.length-0);B<H.length;)H[B]=arguments[B+0],++B;B=new $APP.Ad(H,0,null)}return y.call(this,B)}function y(u){return $APP.CS(f,$APP.sg.j($APP.yx,t,u))}w.B=0;w.G=function(u){u=$APP.m(u);return y(u)};w.l=y;return w}()}(a,b,c,null,d):d;else return d}};QTa=function(a,b){var c=QS;QS=a;try{return PTa(a,b)}finally{QS=c}};
RTa=function(a,b){switch(a instanceof $APP.C?a.M:null){case "getDefaultProps":throw Error("getDefaultProps not supported");case "getDerivedStateFromProps":return function(c,d){var e=b.call,f=c.argv;f!=null&&(c=$APP.v.j(f,1,null),c=$APP.xe(c)?c:null);return e.call(b,null,c,d)};case "getInitialState":return function(c){var d=c.qm;d=d!=null?d:c.qm=RS.h(null);return $APP.yg(d,b.call(c,c))};case "getSnapshotBeforeUpdate":return function(c,d){return b.call(this,this,PS(this,c),d)};case "componentWillReceiveProps":return function(c){return b.call(this,
this,PS(this,c))};case "UNSAFE_componentWillReceiveProps":return function(c){return b.call(this,this,PS(this,c))};case "shouldComponentUpdate":return function(c){if($APP.h(!1))return!1;var d=this.props.argv,e=c.argv,f=d==null||e==null;if(b==null){if(f)return f;try{return $APP.ti.g(d,e)}catch(k){return!1}}else return f?b.call(this,this,PS(this,this.props),PS(this,c)):b.call(this,this,d,e)};case "componentWillUpdate":return function(c,d){return b.call(this,this,PS(this,c),d)};case "UNSAFE_componentWillUpdate":return function(c,
d){return b.call(this,this,PS(this,c),d)};case "componentDidUpdate":return function(c,d,e){return b.call(this,this,PS(this,c),d,e)};case "componentWillMount":return function(){return b.call(this,this)};case "UNSAFE_componentWillMount":return function(){return b.call(this,this)};case "componentDidMount":return function(){return b.call(this,this)};case "componentWillUnmount":return function(){var c=$APP.Qa(this,"cljsRatom");c!=null&&MS(c);this.cljsIsDirty=!1;return b==null?null:b.call(this,this)};case "componentDidCatch":return function(c,
d){return b.call(this,this,c,d)};default:return null}};TTa=function(a){return $APP.af(function(b,c,d){return $APP.ui.j(b,$APP.fj.h(STa(c)),d)},$APP.Xf,a)};
VTa=function(a,b){var c=function(){var k=SS.h(a);return $APP.h(k)?k:TS.h(a)}(),d=SS.h(a)==null,e=function(){var k=US.h(a);if($APP.h(k))return k;k=pTa(c);return $APP.h(k)?k:""+$APP.G.h($APP.ho.h("reagent"))}(),f=$APP.af(function(k,n,t){var w=$APP.ui.j,y=RTa(n,t);return w.call($APP.ui,k,n,$APP.h(y)?y:t)},$APP.Xf,a);return $APP.ui.l(f,US,e,$APP.x([UTa,d,SS,c,TS,function(){var k=this;if($APP.VS)return QTa(k,b);var n=$APP.Qa(k,"cljsRatom");k.cljsIsDirty=!1;return n==null?MTa(function(){return QTa(k,b)},
k):n._run(!1)}],0))};WTa=function(a){return $APP.af(function(b,c,d){c=$APP.Di(c);b[c]=d;return b},{},a)};YTa=function(a,b){a=TTa(a);a=$APP.Hl.l($APP.x([XTa,a],0));return VTa(a,b)};
WS=function(a,b){function c(n,t,w){$APP.Gv.nbb$internal$react.ck.call(this,n,t,w);$APP.h(k)&&(k.g?k.g(this,n):k.call(null,this,n));$APP.h(f)&&(this.state=f.h?f.h(this):f.call(null,this));this.tj=ZTa+=1;return this}a=YTa(a,b);b=WTa($APP.sg.l($APP.Il,a,US,$Ta,$APP.lt,$APP.x([TS,SS,aUa],0)));var d=WTa($APP.vi(a,aUa)),e=US.h(a),f=$Ta.h(a),k=$APP.lt.h(a);$APP.Ua(c.prototype,$APP.Gv.nbb$internal$react.ck.prototype,b);$APP.h(TS.h(a))&&(c.prototype.render=TS.h(a));$APP.h(SS.h(a))&&(c.prototype.bg=SS.h(a));
$APP.h(UTa.h(a))&&(c.prototype.om=UTa.h(a));$APP.Ua(c,$APP.Gv.nbb$internal$react.ck,d);$APP.h(e)&&(c.displayName=e,c.li=e,c.nm=function(n){return $APP.Ic(n,e)},Object.defineProperty(c,"name",{value:e,writable:!1}));c.Ak=!0;return c.prototype.constructor=c};bUa=function(a,b,c){a=BS(a);return b[a]=c};dUa=function(a,b){var c=$APP.Qa(a,BS(b));c==null?NTa(a)?a=bUa(b,a,a):(c=$APP.pe(a),c=$APP.ui.j(c,cUa,a),c=WS(c,b),a=bUa(b,a,c)):a=c;return a};
eUa=function(a,b){for(;;){var c=b.bg,d=b.argv,e=$APP.sg.g(c,d);if($APP.ze(e))return $APP.CS(a,e);if($APP.He(e))b.bg=NTa(e)?function(f,k,n,t,w,y){return function(){function u(H){var P=null;if(arguments.length>0){P=0;for(var T=Array(arguments.length-0);P<T.length;)T[P]=arguments[P+0],++P;P=new $APP.Ad(T,0,null)}return B.call(this,P)}function B(H){return $APP.CS(f,$APP.sg.j($APP.yx,y,H))}u.B=0;u.G=function(H){H=$APP.m(H);return B(H)};u.l=B;return u}()}(a,b,c,null,d,e):e;else return e}};
fUa=function(a,b){var c=QS;QS=b;try{return eUa(a,b)}finally{QS=c}};
gUa=function(a,b){if($APP.VS)return fUa(a,b);var c=b.argv,d=b.bg;b=$APP.Gv.nbb$internal$react.Ro(0);$APP.v.j(b,0,null);var e=$APP.v.j(b,1,null),f=$APP.Gv.nbb$internal$react.Qo();$APP.h(f.current)||function(){var n={forceUpdate:function(){return e.h?e.h($APP.Md):e.call(null,$APP.Md)}};n.tj=ZTa+=1;n.constructor=d;n.bg=d;return f.current=n}();var k=f.current;b=$APP.Qa(k,"cljsRatom");$APP.Gv.nbb$internal$react.Po(function(){return function(){var n=$APP.Qa(k,"cljsRatom");return n==null?null:MS(n)}},[]);
k.argv=c;k.cljsIsDirty=!1;return b==null?MTa(function(){return fUa(a,k)},k):b._run(!1)};hUa=function(a,b){a=a.argv;b=b.argv;try{return $APP.r.g(a,b)}catch(c){return!1}};iUa=function(a,b){function c(e){return gUa(a,e)}var d=$APP.Qa(b,BS(a));if($APP.h(d))return d;d=pTa(b);c.displayName=d;Object.defineProperty(c,"name",{value:d,writable:!1});d=$APP.Gv.nbb$internal$react.Ko(c,hUa);bUa(a,b,d);return d};
lUa=function(a,b,c,d){var e=$APP.Yf($APP.Xf);e=$APP.z.g(e,jUa);if(a===document.activeElement&&$APP.Ne(kUa,a.type)&&typeof b==="string"&&typeof c==="string"){var f=a.value;if($APP.ti.g(f,c))return AS.add_after_render(function(){return XS.h?XS.h(d):XS.call(null,d)});c=$APP.Yd(f)-a.selectionStart;c=$APP.Yd(b)-c;d.mi=b;a.value=b;$APP.le(e)&&(e.h?e.h(b):e.call(null,b));a.selectionStart=c;return a.selectionEnd=c}d.mi=b;a.value=b;return $APP.le(e)?e.h?e.h(b):e.call(null,b):null};
XS=function(a){if($APP.h(a.sj)){a.Ck=!1;var b=a.pm,c=a.mi,d=a.Fj;return $APP.ti.g(b,c)?lUa(d,b,c,a):null}return null};mUa=function(a,b,c){a.mi=c.target.value;$APP.h(a.Ck)||(a.Ck=!0,AS.add_after_render(function(){return XS(a)}));return b.h?b.h(c):b.call(null,c)};
nUa=function(a){var b=QS;if($APP.h(function(){var f=a!=null;return f?(f=a.hasOwnProperty("onChange"),$APP.h(f)?a.hasOwnProperty("value"):f):f}())){var c=a.value;c=c==null?"":c;var d=a.onChange,e=a.ref;$APP.h(b.sj)||(b.sj=!0,b.mi=c);$APP.h(b.yl)||(b.yl=$APP.le(e)?function(f){b.Fj=f;return e.h?e.h(f):e.call(null,f)}:$APP.h($APP.h(e)?e.hasOwnProperty("current"):e)?function(f){b.Fj=f;return e.current=f}:function(f){return b.Fj=f});b.pm=c;delete a.value;a.defaultValue=c;a.onChange=function(f){return mUa(b,
d,f)};a.ref=b.yl}};oUa=function(a){this.tag=a;this.className=this.id=null};pUa=function(a,b){return a.hasOwnProperty(b)?$APP.Qa(a,b):null};rUa=function(a,b,c){if(yS(b)){var d=pUa(qUa,$APP.Di(b));d==null?(d=oTa(b),b=$APP.Di(b),b=qUa[b]=d):b=d}c=YS.h?YS.h(c):YS.call(null,c);a[b]=c;return a};
YS=function(a){return"object"!==$APP.ea(a)?a:yS(a)?$APP.Di(a):$APP.xe(a)?$APP.af(rUa,{},a):$APP.te(a)?$APP.Iz(a):$APP.He(a)?function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Ad(f,0,null)}return c.call(this,e)}function c(d){return $APP.sg.g(a,d)}b.B=0;b.G=function(d){d=$APP.m(d);return c(d)};b.l=c;return b}():$APP.Iz(a)};
tUa=function(a,b,c){if(yS(b)){var d=pUa(sUa,$APP.Di(b));d==null?(d=oTa(b),b=$APP.Di(b),b=sUa[b]=d):b=d}c=YS(c);a[b]=c;return a};
uUa=function(a){return"object"!==$APP.ea(a)?a:yS(a)?$APP.Di(a):$APP.xe(a)?$APP.af(tUa,{},a):$APP.te(a)?$APP.Iz(a):$APP.He(a)?function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Ad(f,0,null)}return c.call(this,e)}function c(d){return $APP.sg.g(a,d)}b.B=0;b.G=function(d){d=$APP.m(d);return c(d)};b.l=c;return b}():$APP.Iz(a)};
vUa=function(a,b,c,d,e){switch($APP.Yd(b)-e){case 0:return $APP.Gv.nbb$internal$react.createElement(c,d);case 1:return $APP.Gv.nbb$internal$react.createElement(c,d,$APP.CS(a,$APP.v.j(b,e,null)));default:return $APP.Gv.nbb$internal$react.createElement.apply(null,$APP.af(function(f,k,n){k>=e&&f.push($APP.CS(a,n));return f},[c,d],b))}};wUa=function(a,b,c,d){this.tag=a;this.id=b;this.className=c;this.tm=d};
xUa=function(a,b,c){a=dUa(a,c);c={};c.argv=b;b=qTa(b);b!=null&&(c.key=b);return $APP.Gv.nbb$internal$react.createElement(a,c)};yUa=function(a,b,c,d){var e={};e.bg=a;e.argv=$APP.Yk.g(b,c);b=qTa(b);b!=null&&(e.key=b);return $APP.Gv.nbb$internal$react.createElement(iUa(d,a),e)};zUa=function(a,b,c){return OTa(a)?xUa(a,b,c):yUa(a,b,1,c)};
CUa=function(a,b){a=pUa(AUa,b);if(a==null){var c=$APP.q($APP.Qi(BUa,$APP.Di(b)));a=$APP.v.j(c,0,null);var d=$APP.v.j(c,1,null);c=$APP.v.j(c,2,null);c=c==null?null:$APP.Sk(c,/\./," ");var e=$APP.ti.g(-1,a.indexOf("-"));a=new wUa(a,d,c,e);return AUa[b]=a}return a};
FUa=function(a,b,c,d){var e=a.tag,f=$APP.v.j(b,c,null),k=f==null||$APP.xe(f),n=function(){var y=k?f:null;var u=$APP.tr.h(y);u=$APP.h(u)?$APP.ui.j(y,$APP.tr,ZS.h(u)):y;var B=a.id;y=a.className;B=B!=null&&$APP.Kq.h(u)==null?$APP.ui.j(u,$APP.Kq,B):u;if($APP.h(y)){var H=$APP.ui.j,P=ZS.g,T=$APP.tr.h(u);u=$APP.h(T)?T:DUa.h(u);y=H.call($APP.ui,B,$APP.tr,P.call(ZS,y,u))}else y=B;y=$APP.h(a.tm)?uUa(y):YS(y);return $APP.h(y)?y:{}}();c+=k?1:0;a:switch(e){case "input":case "textarea":var t=!0;break a;default:t=
!1}if(t){t=zS(f);var w=function(){var y=d.An;if($APP.h(y))return y;y=WS(EUa,d);return d.An=y}();return $APP.CS(d,$APP.ne(new $APP.D(null,6,5,$APP.E,[w,b,e,n,c,d],null),$APP.Hl.l($APP.x([$APP.h(t)?new $APP.F(null,1,[$APP.dE,t],null):null,$APP.pe(b)],0))))}t=zS($APP.pe(b));t!=null&&(n.key=t);return DS(d,b,e,n,c)};GUa=function(a,b){return $APP.Ir.h($APP.Pj.g(function(c){return $APP.CS(b,c)},a))};
HUa=function(a,b,c){b==null&&console.error("vec-to-elem",$APP.xj.l($APP.x([a],0)));var d=$APP.v.j(a,0,null);switch(d instanceof $APP.C?d.M:null){case "\x3e":return c=$APP.v.j(a,1,null),FUa(new wUa(c,null,null,null),a,2,b);case "r\x3e":c=$APP.v.j(a,1,null);d=$APP.v.j(a,2,null);d=$APP.h(d)?d:{};var e=zS($APP.pe(a));e!=null&&(d.key=e);return DS(b,a,c,d,3);case "f\x3e":return yUa($APP.v.j(a,1,null),a,2,b);case "\x3c\x3e":return d=$APP.v.j(a,1,null),c=d==null||$APP.xe(d),d=YS(c?d:null),d=$APP.h(d)?d:{},
c=1+(c?1:0),e=qTa(a),e!=null&&(d.key=e),DS(b,a,$APP.Gv.nbb$internal$react.co,d,c);default:if(yS(d)||typeof d==="string")a:{for(;;){c=$APP.v.j(a,0,null);d=$APP.Di(c);e=d.indexOf("\x3e");switch(e){case -1:b=FUa(yTa(b,d,c),a,1,b);break a;case 0:b=null;break a;default:a=$APP.ne(new $APP.D(null,2,5,$APP.E,[$APP.Ui.j(d,0,e),$APP.ui.j($APP.ne(a,null),0,$APP.Ui.g(d,e+1))],null),$APP.pe(a));continue}break}b=void 0}else b=d instanceof oUa?FUa(d,a,1,b):c.j?c.j(d,a,b):c.call(null,d,a,b);return b}};
IUa=function(a,b,c,d,e){this.Md=a;this.id=b;this.Jk=c;this.Ji=d;this.hn=e;this.I=393216;this.K=0};LUa=function(a){var b=$APP.ho.h("reagent-compiler"),c=$APP.h(JUa.h(a))?zUa:xUa,d=$APP.z.j(a,KUa,CUa);return new IUa(a,b,c,d,$APP.Xf)};MUa=function(a){return new oUa(a)};NUa=new $APP.l(null,"-generation","-generation",627658965,null);TS=new $APP.C(null,"render","render",-1408033454);OUa=new $APP.l(null,"on-set","on-set",1499578057,null);
PUa=new $APP.l("reagent.ratom","make-reaction","reagent.ratom/make-reaction",272608527,null);QUa=new $APP.l(null,"dispose!","dispose!",-395693497,null);RUa=new $APP.l("reagent.ratom","-destroy","reagent.ratom/-destroy",-1284026419,null);SUa=new $APP.C(null,"componentWillUnmount","componentWillUnmount",1573788814);DUa=new $APP.C(null,"className","className",-1983287057);TUa=new $APP.l(null,"-tracking?","-tracking?",-1106885352,null);$S=new $APP.l(null,"with-let","with-let",-1310113408,null);
UUa=new $APP.l(null,"with-let-values","with-let-values",1929572375,null);VUa=new $APP.l(null,"create-class","create-class",-665911586,null);WUa=new $APP.C(null,"childContextTypes","childContextTypes",578717991);XUa=new $APP.l(null,"class2","class2",-1266396392,null);YUa=new $APP.l(null,"class1","class1",-1905977651,null);ZUa=new $APP.l(null,"auto-run","auto-run",-696035332,null);$Ua=new $APP.l(null,"-set-ratom-generation!","-set-ratom-generation!",-1545989828,null);
aVa=new $APP.l(null,"-destroy","-destroy",-557272508,null);LS=new $APP.C(null,"auto-run","auto-run",1958400437);bVa=new $APP.l(null,"track-console","track-console",17070495,null);cUa=new $APP.C(null,"reagent-render","reagent-render",-985383853);cVa=new $APP.C(null,"contextTypes","contextTypes",-2023853910);dVa=new $APP.l(null,"create-compiler","create-compiler",1059333141,null);eVa=new $APP.l(null,"props","props",2093813254,null);aT=new $APP.l(null,"reaction","reaction",2131401315,null);
fVa=new $APP.C(null,"on-set","on-set",-140953470);jUa=new $APP.C(null,"on-write","on-write",31519475);gVa=new $APP.l(null,"reactive?","reactive?",1213887990,null);JS=new $APP.C(null,"on-dispose","on-dispose",2105306360);$APP.bT=new $APP.l(null,"compiler","compiler",1372604796,null);hVa=new $APP.l("reagent.ratom","-destroy!","reagent.ratom/-destroy!",-337873850,null);iVa=new $APP.l(null,"-destroy!","-destroy!",143253949,null);
jVa=new $APP.l("sci.configs.reagent.reagent","error","sci.configs.reagent.reagent/error",1433174531,null);SS=new $APP.C(null,"reagentRender","reagentRender",-358306383);kVa=new $APP.l(null,"cursor","cursor",-1642498285,null);lVa=new $APP.l(null,"make-reaction","make-reaction",1935680112,null);mVa=new $APP.C(null,"contextType","contextType",1033066077);nVa=new $APP.l(null,"destroy__37905__auto__","destroy__37905__auto__",-870718036,null);
oVa=new $APP.C(null,"component-did-update","component-did-update",-1468549173);pVa=new $APP.l(null,"src","src",-10544524,null);US=new $APP.C(null,"displayName","displayName",-809144601);qVa=new $APP.C(null,"display-name","display-name",694513143);rVa=new $APP.l("sci.configs.reagent.reagent","reaction","sci.configs.reagent.reagent/reaction",-1324858361,null);sVa=new $APP.l(null,"others","others",-569561186,null);tVa=new $APP.C(null,"getDerivedStateFromProps","getDerivedStateFromProps",-991834739);
KUa=new $APP.C(null,"parse-tag","parse-tag",1427313738);uVa=new $APP.l(null,"destroy","destroy",796871122,null);vVa=new $APP.C(null,"shouldComponentUpdate","shouldComponentUpdate",1795750960);wVa=new $APP.l(null,"-ratom-generation","-ratom-generation",-176468250,null);cT=new $APP.l(null,"adapt-react-class","adapt-react-class",1221068673,null);xVa=new $APP.l(null,"track","track",1836319014,null);yVa=new $APP.l(null,".hasOwnProperty",".hasOwnProperty",-1264659034,null);
zVa=new $APP.l(null,"reagent.debug","reagent.debug",1010511129,null);AVa=new $APP.l(null,"reactify-component","reactify-component",-882526483,null);BVa=new $APP.l("js","console","js/console",-1426368245,null);CVa=new $APP.l(null,"sci.configs.reagent.reagent","sci.configs.reagent.reagent",94604865,null);DVa=new $APP.C(null,"no-cache","no-cache",1588056370);EVa=new $APP.l("cljs.core","zero?","cljs.core/zero?",-341242858,null);dT=new $APP.l(null,"track!","track!",-516308489,null);
FVa=new $APP.l(null,".error",".error",1756007195,null);GVa=new $APP.l("reagent.debug","-tracking?","reagent.debug/-tracking?",409956583,null);JUa=new $APP.C(null,"function-components","function-components",1492814963);HVa=new $APP.l("reagent.ratom","reactive?","reagent.ratom/reactive?",-358553475,null);IVa=new $APP.l(null,"as-element","as-element",-2139409597,null);JVa=new $APP.l(null,"make-track","make-track",-1388299455,null);
KVa=new $APP.l("reagent.debug","track-console","reagent.debug/track-console",-1553126476,null);LVa=new $APP.l(null,"on-dispose","on-dispose",-549129409,null);MVa=new $APP.C(null,"component-will-unmount","component-will-unmount",-2058314698);NVa=new $APP.l("reagent.ratom","with-let-values","reagent.ratom/with-let-values",-575838306,null);OVa=new $APP.l(null,"-ratom-context","-ratom-context",1646839514,null);UTa=new $APP.C(null,"cljsLegacyRender","cljsLegacyRender",-1527295613);
PVa=new $APP.l("sci.configs.reagent.reagent","with-let","sci.configs.reagent.reagent/with-let",65759084,null);QVa=new $APP.l(null,"class-names","class-names",-1397320704,null);$Ta=new $APP.C(null,"getInitialState","getInitialState",1541760916);RVa=new $APP.C(null,"getDerivedStateFromError","getDerivedStateFromError",166658477);SVa=new $APP.l(null,"create-element","create-element",1833774591,null);var TVa=$APP.zj.h(null),UVa=function(){var a={};a.warn=function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Ad(f,0,null)}return c.call(this,e)}function c(d){return $APP.Aj.l(TVa,$APP.Fl,new $APP.D(null,1,5,$APP.E,[$APP.mDa],null),$APP.vf,$APP.x([$APP.sg.g($APP.G,d)],0))}b.B=0;b.G=function(d){d=$APP.m(d);return c(d)};b.l=c;return b}();a.error=function(){function b(d){var e=null;if(arguments.length>0){e=0;for(var f=
Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Ad(f,0,null)}return c.call(this,e)}function c(d){return $APP.Aj.l(TVa,$APP.Fl,new $APP.D(null,1,5,$APP.E,[$APP.Hn],null),$APP.vf,$APP.x([$APP.sg.g($APP.G,d)],0))}b.B=0;b.G=function(d){d=$APP.m(d);return c(d)};b.l=c;return b}();return a}();var VVa,nTa,ZS;VVa=typeof window!=="undefined"&&window.document!=null;$APP.VS=!1;nTa=new $APP.xi(null,new $APP.F(null,2,["aria",null,"data",null],null),null);ZS=function ZS(a){switch(arguments.length){case 0:return ZS.D();case 1:return ZS.h(arguments[0]);case 2:return ZS.g(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return ZS.l(arguments[0],arguments[1],2<c.length?new $APP.Ad(c.slice(2),0,null):null)}};ZS.D=function(){return null};
ZS.h=function(a){return $APP.te(a)?(a=$APP.qn.g(function(b){return $APP.h(b)?yS(b)?$APP.Di(b):b:null},a),$APP.m(a)?$APP.kn.g(" ",a):null):yS(a)?$APP.Di(a):a};ZS.g=function(a,b){return $APP.h(a)?$APP.h(b)?""+$APP.G.h(ZS.h(a))+" "+$APP.G.h(ZS.h(b)):ZS.h(a):ZS.h(b)};ZS.l=function(a,b,c){return $APP.Ye.j(ZS,ZS.g(a,b),c)};ZS.G=function(a){var b=$APP.p(a),c=$APP.q(a);a=$APP.p(c);c=$APP.q(c);return this.l(b,a,c)};ZS.B=2;var ZTa=0,WVa=VVa?function(){var a=window;return function(){var b=a.requestAnimationFrame;if($APP.h(b))return b;b=a.webkitRequestAnimationFrame;if($APP.h(b))return b;b=a.mozRequestAnimationFrame;if($APP.h(b))return b;b=a.msRequestAnimationFrame;return $APP.h(b)?b:rTa}().bind(a)}():rTa;$APP.g=wTa.prototype;$APP.g.flush_after_render=function(){var a=this.ei;if(a==null)return null;this.ei=null;return uTa(a)};$APP.g.queue_render=function(a){this.ui==null&&(this.ui=[]);return vTa(this,this.ui,a)};
$APP.g.schedule=function(){function a(){return b.run_queues()}var b=this;if(this.Qi)return null;this.Qi=!0;return WVa.h?WVa.h(a):WVa.call(null,a)};$APP.g.flush_before_flush=function(){var a=this.gi;if(a==null)return null;this.gi=null;return uTa(a)};$APP.g.flush_queues=function(){this.flush_before_flush();tTa();this.flush_render();return this.flush_after_render()};$APP.g.run_queues=function(){this.Qi=!1;return this.flush_queues()};
$APP.g.add_before_flush=function(a){this.gi==null&&(this.gi=[]);return vTa(this,this.gi,a)};$APP.g.add_after_render=function(a){this.ei==null&&(this.ei=[]);return vTa(this,this.ei,a)};$APP.g.flush_render=function(){var a=this.ui;if(a==null)return null;this.ui=null;a:{a.sort(sTa);for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.cljsIsDirty===!0&&d.forceUpdate();c+=1}else{a=null;break a}a=void 0}return a};var AS=new wTa;var ES;$APP.zj.h(0);var NS=null;$APP.g=HS.prototype;$APP.g.V=function(a,b,c){return GS(b,c,"RAtom",new $APP.F(null,1,[$APP.fv,this.La(null)],null))};$APP.g.T=function(){return this.O};$APP.g.X=function(){return $APP.na(this)};$APP.g.R=function(a,b){return this===b};$APP.g.nd=function(a,b){a=this.state;this.state=b;this.pb!=null&&FS(this,a,b);return b};$APP.g.qh=function(a,b){return this.nd(null,b.h?b.h(this.state):b.call(null,this.state))};
$APP.g.rh=function(a,b,c){return this.nd(null,b.g?b.g(this.state,c):b.call(null,this.state,c))};$APP.g.sh=function(a,b,c,d){return this.nd(null,b.j?b.j(this.state,c,d):b.call(null,this.state,c,d))};$APP.g.th=function(a,b,c,d,e){return this.nd(null,$APP.sg.P(b,this.state,c,d,e))};$APP.g.Pg=function(a,b){FS(this,a,b)};$APP.g.ng=function(a,b,c){return BTa(this,b,c)};$APP.g.og=function(a,b){return CTa(this,b)};$APP.g.U=function(a,b){return new HS(this.state,b,this.Gg,this.pb)};
$APP.g.La=function(){ATa(this);return this.state};var RS=function RS(a){switch(arguments.length){case 1:return RS.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return RS.l(arguments[0],1<c.length?new $APP.Ad(c.slice(1),0,null):null)}};RS.h=function(a){return new HS(a,null,null,null)};RS.l=function(a,b){var c=$APP.Yf(b);b=$APP.z.g(c,$APP.cj);c=$APP.z.g(c,$APP.Sy);return new HS(a,b,c,null)};
RS.G=function(a){var b=$APP.p(a);a=$APP.q(a);return this.l(b,a)};RS.B=1;KS.prototype.La=function(){var a=this,b=a.Th;return b==null?DTa(function(){return $APP.sg.g(a.f,a.Ca)},a.f,a.Ca,this,null):$APP.oc(b)};KS.prototype.R=function(a,b){return b instanceof KS&&$APP.r.g(this.f,b.f)&&$APP.r.g(this.Ca,b.Ca)};KS.prototype.X=function(){return $APP.sd(new $APP.D(null,2,5,$APP.E,[this.f,this.Ca],null))};
KS.prototype.V=function(a,b,c){return GS(b,c,"Track",new $APP.F(null,2,[$APP.fv,this.La(null),$APP.kJ,this.f],null))};var eT=function eT(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return eT.l(arguments[0],1<c.length?new $APP.Ad(c.slice(1),0,null):null)};eT.l=function(a,b){return FTa(a,b)};eT.B=1;eT.G=function(a){var b=$APP.p(a);a=$APP.q(a);return this.l(b,a)};$APP.g=GTa.prototype;
$APP.g._peek=function(){var a=ES;ES=null;try{return this.La(null)}finally{ES=a}};$APP.g._set_state=function(a,b){if(a===b)return null;this.state=b;return this.pb!=null?FS(this,a,b):null};$APP.g.V=function(a,b,c){return GS(b,c,"RCursor",new $APP.F(null,2,[$APP.fv,this.La(null),$APP.vs,this.path],null))};$APP.g.X=function(){return $APP.sd(new $APP.D(null,2,5,$APP.E,[this.oc,this.path],null))};$APP.g.R=function(a,b){return b instanceof GTa&&$APP.r.g(this.path,b.path)&&$APP.r.g(this.oc,b.oc)};
$APP.g.nd=function(a,b){this._set_state(this.state,b);(this.oc!=null?this.oc.I&32768||$APP.rd===this.oc.kg||(this.oc.I?0:$APP.Fb($APP.nc,this.oc)):$APP.Fb($APP.nc,this.oc))?$APP.r.g(this.path,$APP.Rg)?$APP.yg(this.oc,b):$APP.Aj.F(this.oc,$APP.Pq,this.path,b):this.oc.g?this.oc.g(this.path,b):this.oc.call(null,this.path,b);return b};$APP.g.qh=function(a,b){a=this.nd;var c=this._peek();b=b.h?b.h(c):b.call(null,c);return a.call(this,null,b)};
$APP.g.rh=function(a,b,c){a=this.nd;var d=this._peek();b=b.g?b.g(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.g.sh=function(a,b,c,d){a=this.nd;var e=this._peek();b=b.j?b.j(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};$APP.g.th=function(a,b,c,d,e){return this.nd(null,$APP.sg.P(b,this._peek(),c,d,e))};$APP.g.Pg=function(a,b){FS(this,a,b)};$APP.g.ng=function(a,b,c){return BTa(this,b,c)};$APP.g.og=function(a,b){return CTa(this,b)};
$APP.g.La=function(){var a=this,b=this,c=a.state,d=function(){var e=a.Th;return e==null?DTa((a.oc!=null?a.oc.I&32768||$APP.rd===a.oc.kg||(a.oc.I?0:$APP.Fb($APP.nc,a.oc)):$APP.Fb($APP.nc,a.oc))?function(){return $APP.wp.g($APP.oc(a.oc),a.path)}:function(){return a.oc.h?a.oc.h(a.path):a.oc.call(null,a.path)},a.oc,a.path,b,null):$APP.oc(e)}();b._set_state(c,d);return d};$APP.g=JTa.prototype;$APP.g._peek_at=function(){var a=ES;ES=null;try{return this.La(null)}finally{ES=a}};
$APP.g._handle_change=function(a,b,c){return b===c||this.Yf?null:this.pf==null?(this.Yf=!0,NS==null&&(NS=[],AS.Qi===!1&&AS.schedule()),NS.push(this)):this.pf===!0?this._run(!1):this.pf.h?this.pf.h(this):this.pf.call(null,this)};
$APP.g._update_watching=function(a){var b=$APP.Bi(a),c=$APP.Bi(this.Ig);this.Ig=a;a=$APP.m($APP.Rx.g(b,c));for(var d=null,e=0,f=0;;)if(f<e){var k=d.ga(null,f);$APP.Nc(k,this,ITa);f+=1}else if(a=$APP.m(a))d=a,$APP.Ae(d)?(a=$APP.Zc(d),f=$APP.$c(d),d=a,e=$APP.Yd(a),a=f):(a=$APP.p(d),$APP.Nc(a,this,ITa),a=$APP.q(d),d=null,e=0),f=0;else break;b=$APP.m($APP.Rx.g(c,b));c=null;for(e=d=0;;)if(e<d)a=c.ga(null,e),$APP.Oc(a,this),e+=1;else if(b=$APP.m(b))c=b,$APP.Ae(c)?(b=$APP.Zc(c),d=$APP.$c(c),c=b,a=$APP.Yd(b),
b=d,d=a):(a=$APP.p(c),$APP.Oc(a,this),b=$APP.q(c),c=null,d=0),e=0;else return null};$APP.g._queued_run=function(){return this.Yf&&this.Ig!=null?this._run(!0):null};$APP.g._try_capture=function(a){try{return this.$i=null,zTa(a,this)}catch(b){return this.$i=this.state=a=b,this.Yf=!1}};$APP.g._run=function(a){var b=this.state;a=$APP.h(a)?this._try_capture(this.f):zTa(this.f,this);this.Rk||(this.state=a,this.pb==null||$APP.r.g(b,a)||FS(this,b,a));return a};
$APP.g._set_opts=function(a){var b=$APP.Yf(a);a=$APP.z.g(b,LS);var c=$APP.z.g(b,fVa),d=$APP.z.g(b,JS);b=$APP.z.g(b,DVa);a!=null&&(this.pf=a);c!=null&&(this.rn=c);d!=null&&(this.Tk=d);return b!=null?this.Rk=b:null};$APP.g.V=function(a,b,c){return GS(b,c,"Reaction",new $APP.F(null,1,[$APP.fv,this.La(null)],null))};$APP.g.X=function(){return $APP.na(this)};$APP.g.R=function(a,b){return this===b};
$APP.g.Uj=function(){var a=this.state,b=this.Ig;this.pf=this.state=this.Ig=null;this.Yf=!0;b=$APP.m($APP.Bi(b));for(var c=null,d=0,e=0;;)if(e<d){var f=c.ga(null,e);$APP.Oc(f,this);e+=1}else if(b=$APP.m(b))c=b,$APP.Ae(c)?(b=$APP.Zc(c),e=$APP.$c(c),c=b,d=$APP.Yd(b),b=e):(b=$APP.p(c),$APP.Oc(b,this),b=$APP.q(c),c=null,d=0),e=0;else break;this.Tk!=null&&this.Tk(a);a=this.Lo;if(a==null)return null;b=a.length;for(c=0;;)if(c<b)d=a[c],d.h?d.h(this):d.call(null,this),c+=1;else return null};
$APP.g.nd=function(a,b){a=this.state;this.state=b;this.rn(a,b);FS(this,a,b);return b};$APP.g.qh=function(a,b){a=this.nd;var c=this._peek_at();b=b.h?b.h(c):b.call(null,c);return a.call(this,null,b)};$APP.g.rh=function(a,b,c){a=this.nd;var d=this._peek_at();b=b.g?b.g(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.g.sh=function(a,b,c,d){a=this.nd;var e=this._peek_at();b=b.j?b.j(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};
$APP.g.th=function(a,b,c,d,e){return this.nd(null,$APP.sg.P(b,this._peek_at(),c,d,e))};$APP.g.Pg=function(a,b){FS(this,a,b)};$APP.g.ng=function(a,b,c){return BTa(this,b,c)};$APP.g.og=function(a,b){a=$APP.se(this.pb);CTa(this,b);return!a&&$APP.se(this.pb)&&this.pf==null?this.Uj(null):null};
$APP.g.La=function(){var a=this.$i;if(a!=null)throw a;(a=ES==null)&&($APP.OS.D?$APP.OS.D():$APP.OS.call(null));a&&this.pf==null?this.Yf&&(a=this.state,this.state=this.f.D?this.f.D():this.f.call(null),this.pb==null||$APP.r.g(a,this.state)||FS(this,a,this.state)):(ATa(this),this.Yf&&this._run(!1));return this.state};tTa=$APP.OS;var IS=function IS(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return IS.l(arguments[0],1<c.length?new $APP.Ad(c.slice(1),0,null):null)};
IS.l=function(a,b){var c=$APP.Yf(b);b=$APP.z.g(c,LS);var d=$APP.z.g(c,fVa);c=$APP.z.g(c,JS);a=new JTa(a);a._set_opts(new $APP.F(null,3,[LS,b,fVa,d,JS,c],null));return a};IS.B=1;IS.G=function(a){var b=$APP.p(a);a=$APP.q(a);return this.l(b,a)};var LTa=IS(null);var QS,KTa=new $APP.F(null,1,[DVa,!0],null),XTa=new $APP.F(null,2,[vVa,null,SUa,null],null),STa=function(a){var b=$APP.zj.h($APP.Xf);return function(c){var d=$APP.z.g($APP.oc(b),c);if(d!=null)return d;d=a.h?a.h(c):a.call(null,c);$APP.Aj.F(b,$APP.ui,c,d);return d}}(function(a){if(typeof a==="string")return a;a=$APP.Di(a);a=$APP.Sk(a,/(unsafe|UNSAFE)[-_]/,"UNSAFE_");a=$APP.Zk.g(a,/-/);var b=$APP.m(a);a=$APP.p(b);b=$APP.q(b);return $APP.sg.j($APP.G,a,$APP.Pj.g(mTa,b))}),aUa=new $APP.D(null,5,5,$APP.E,
[WUa,cVa,mVa,tVa,RVa],null);var kUa=new $APP.xi(null,new $APP.F(null,6,["url",null,"tel",null,"text",null,"textarea",null,"password",null,"search",null],null),null),EUa=new $APP.F(null,4,[qVa,"ReagentInput",oVa,XS,MVa,function(a){return a.sj=null},cUa,function(a,b,c,d,e){nUa(c);return DS(e,a,b,c,d)}],null);var BUa=/([^\s\.#]+)(?:#([^\s\.#]+))?(?:\.([^\s#]+))?/,qUa={"class":"className","for":"htmlFor",charset:"charSet"},sUa={},AUa={};$APP.g=IUa.prototype;$APP.g.U=function(a,b){return new IUa(this.Md,this.id,this.Jk,this.Ji,b)};$APP.g.T=function(){return this.hn};$APP.g.zn=function(){return this.id};$APP.g.xl=function(a,b,c){return this.Ji.j?this.Ji.j(this,b,c):this.Ji.call(null,this,b,c)};
$APP.g.vl=function(a,b){return"object"!==$APP.ea(b)?b:$APP.ze(b)?HUa(b,this,this.Jk):$APP.Fe(b)?GUa(b,this):yS(b)?$APP.Di(b):(b!=null?b.I&2147483648||$APP.rd===b.Xa||(b.I?0:$APP.Fb($APP.Kc,b)):$APP.Fb($APP.Kc,b))?$APP.xj.l($APP.x([b],0)):b};$APP.g.wl=function(a,b,c,d,e){return vUa(this,b,c,d,e)};$APP.fT=LUa($APP.Xf);var gT=function gT(a){switch(arguments.length){case 1:return gT.h(arguments[0]);case 2:return gT.g(arguments[0],arguments[1]);case 3:return gT.j(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return gT.l(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.Ad(c.slice(3),0,null):null)}};gT.h=function(a){return gT.g(a,null)};gT.g=function(a,b){return $APP.Gv.nbb$internal$react.createElement(a,b)};
gT.j=function(a,b,c){return $APP.Gv.nbb$internal$react.createElement(a,b,c)};gT.l=function(a,b,c,d){return $APP.sg.P($APP.Gv.nbb$internal$react.createElement,a,b,c,d)};gT.G=function(a){var b=$APP.p(a),c=$APP.q(a);a=$APP.p(c);var d=$APP.q(c);c=$APP.p(d);d=$APP.q(d);return this.l(b,a,c,d)};gT.B=3;var hT=function hT(a){switch(arguments.length){case 1:return hT.h(arguments[0]);case 2:return hT.g(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};
hT.h=function(a){return $APP.CS($APP.fT,a)};hT.g=function(a,b){return $APP.CS(b,a)};hT.B=2;var iT=function iT(a){switch(arguments.length){case 1:return iT.h(arguments[0]);case 2:return iT.g(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};iT.h=function(a){return iT.g(a,$APP.fT)};iT.g=function(a,b){return OTa(a)?a:dUa(a,b)};iT.B=2;
var jT=function jT(a){switch(arguments.length){case 1:return jT.h(arguments[0]);case 2:return jT.g(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};jT.h=function(a){return WS(a,$APP.fT)};jT.g=function(a,b){return WS(a,b)};jT.B=2;
var kT=function kT(a){switch(arguments.length){case 0:return kT.D();case 1:return kT.h(arguments[0]);case 2:return kT.g(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return kT.l(arguments[0],arguments[1],2<c.length?new $APP.Ad(c.slice(2),0,null):null)}};kT.D=function(){return null};kT.h=function(a){return ZS.h(a)};kT.g=function(a,b){return ZS.g(a,b)};kT.l=function(a,b,c){return $APP.sg.F(ZS,a,b,c)};
kT.G=function(a){var b=$APP.p(a),c=$APP.q(a);a=$APP.p(c);c=$APP.q(c);return this.l(b,a,c)};kT.B=2;var lT=function lT(a){switch(arguments.length){case 1:return lT.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return lT.l(arguments[0],1<c.length?new $APP.Ad(c.slice(1),0,null):null)}};lT.h=function(a){return RS.h(a)};lT.l=function(a,b){return $APP.sg.j(RS,a,b)};lT.G=function(a){var b=$APP.p(a);a=$APP.q(a);return this.l(b,a)};lT.B=1;
var mT=function mT(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return mT.l(arguments[0],1<c.length?new $APP.Ad(c.slice(1),0,null):null)};mT.l=function(a,b){return ETa(a,b)};mT.B=1;mT.G=function(a){var b=$APP.p(a);a=$APP.q(a);return this.l(b,a)};var nT=function nT(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return nT.l(arguments[0],1<c.length?new $APP.Ad(c.slice(1),0,null):null)};nT.l=function(a,b){return FTa(a,b)};
nT.B=1;nT.G=function(a){var b=$APP.p(a);a=$APP.q(a);return this.l(b,a)};var oT=function oT(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return oT.l(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.Ad(c.slice(3),0,null):null)};
oT.l=function(a,b,c,d){var e=$APP.ho.h("with-let");a=$APP.fj.h(e);var f=$APP.ho.h("init");c=$APP.Ch.g(new $APP.D(null,2,5,$APP.E,[f,$APP.U.h($APP.m($APP.N.g(new $APP.A(null,EVa,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.g(new $APP.A(null,$APP.yAa,null,1,null),new $APP.A(null,e,null,1,null)))),null,1,null))))],null),$APP.yv.g(function(t,w){if($APP.qg(t))return w;t=$APP.kf(t,2);return $APP.U.h($APP.m($APP.N.l(new $APP.A(null,$APP.tk,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.l(new $APP.A(null,
$APP.KG,null,1,null),new $APP.A(null,f,null,1,null),$APP.x([new $APP.A(null,$APP.U.h($APP.m($APP.N.g(new $APP.A(null,$APP.Nu,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.l(new $APP.A(null,yVa,null,1,null),new $APP.A(null,e,null,1,null),$APP.x([new $APP.A(null,t,null,1,null)],0)))),null,1,null)))),null,1,null)],0)))),null,1,null),$APP.x([new $APP.A(null,$APP.U.h($APP.m($APP.N.l(new $APP.A(null,$APP.Yza,null,1,null),new $APP.A(null,e,null,1,null),$APP.x([new $APP.A(null,t,null,1,null),new $APP.A(null,
w,null,1,null)],0)))),null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.l(new $APP.A(null,$APP.koa,null,1,null),new $APP.A(null,e,null,1,null),$APP.x([new $APP.A(null,t,null,1,null)],0)))),null,1,null)],0))))},c));var k=function(){var t=$APP.ie(d);return $APP.Fe(t)&&$APP.r.g($APP.qk,$APP.p(t))?new $APP.D(null,2,5,$APP.E,[$APP.Ci(d),$APP.U.h($APP.m($APP.N.l(new $APP.A(null,$APP.Wv,null,1,null),new $APP.A(null,$APP.$e($APP.U.h($APP.m($APP.N.D()))),null,1,null),$APP.x([$APP.Ed(t)],0))))],null):new $APP.D(null,
2,5,$APP.E,[d,null],null)}();b=$APP.v.j(k,0,null);k=$APP.v.j(k,1,null);k=$APP.h(k)?new $APP.A(null,$APP.U.h($APP.m($APP.N.l(new $APP.A(null,$APP.Vq,null,1,null),new $APP.A(null,$APP.$e($APP.U.h($APP.m($APP.N.g(new $APP.A(null,nVa,null,1,null),new $APP.A(null,k,null,1,null))))),null,1,null),$APP.x([new $APP.A(null,$APP.U.h($APP.m($APP.N.l(new $APP.A(null,$APP.tk,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.h(new $APP.A(null,HVa,null,1,null)))),null,1,null),$APP.x([new $APP.A(null,$APP.U.h($APP.m($APP.N.l(new $APP.A(null,
$APP.JA,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.g(new $APP.A(null,$APP.DF,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.g(new $APP.A(null,RUa,null,1,null),new $APP.A(null,e,null,1,null)))),null,1,null)))),null,1,null),$APP.x([new $APP.A(null,$APP.U.h($APP.m($APP.N.l(new $APP.A(null,hVa,null,1,null),new $APP.A(null,e,null,1,null),$APP.x([new $APP.A(null,nVa,null,1,null)],0)))),null,1,null)],0)))),null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.h(new $APP.A(null,nVa,null,1,null)))),
null,1,null)],0)))),null,1,null)],0)))),null,1,null):null;var n=$APP.ho.h("res");return $APP.U.h($APP.m($APP.N.l(new $APP.A(null,$APP.Vq,null,1,null),new $APP.A(null,$APP.$e($APP.U.h($APP.m($APP.N.g(new $APP.A(null,e,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.g(new $APP.A(null,NVa,null,1,null),new $APP.A(null,a,null,1,null)))),null,1,null))))),null,1,null),$APP.x([new $APP.A(null,null,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.l(new $APP.A(null,$APP.Vq,null,1,null),new $APP.A(null,
$APP.Ch.g(c,new $APP.D(null,2,5,$APP.E,[n,$APP.U.h($APP.m($APP.N.g(new $APP.A(null,$APP.sk,null,1,null),b)))],null)),null,1,null),$APP.x([k,new $APP.A(null,n,null,1,null)],0)))),null,1,null)],0))))};oT.B=3;oT.G=function(a){var b=$APP.p(a),c=$APP.q(a);a=$APP.p(c);var d=$APP.q(c);c=$APP.p(d);d=$APP.q(d);return this.l(b,a,c,d)};var pT=function pT(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return pT.l(0<c.length?new $APP.Ad(c.slice(0),0,null):null)};
pT.l=function(a){return $APP.U.h($APP.m($APP.N.g(new $APP.A(null,PUa,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.l(new $APP.A(null,$APP.Wv,null,1,null),new $APP.A(null,$APP.$e($APP.U.h($APP.m($APP.N.D()))),null,1,null),$APP.x([a],0)))),null,1,null))))};pT.B=0;pT.G=function(a){return this.l($APP.m(a))};
var qT=$APP.FM.g($APP.iG,null),XVa=$APP.gi([VUa,xVa,$S,$APP.BA,QVa,aT,IVa,AVa,SVa,QUa,kVa,dT,dVa,cT],[new $APP.pq(jT,VUa,new $APP.F(null,7,[$APP.R,VUa,$APP.O,"Creates JS class based on provided Clojure map, for example:\n\n  ```cljs\n  {;; Constructor\n   :constructor (fn [this props])\n   :get-initial-state (fn [this])\n   ;; Static methods\n   :get-derived-state-from-props (fn [props state] partial-state)\n   :get-derived-state-from-error (fn [error] partial-state)\n   ;; Methods\n   :get-snapshot-before-update (fn [this old-argv new-argv] snapshot)\n   :should-component-update (fn [this old-argv new-argv])\n   :component-did-mount (fn [this])\n   :component-did-update (fn [this old-argv old-state snapshot])\n   :component-will-unmount (fn [this])\n   :component-did-catch (fn [this error info])\n   :reagent-render (fn [args....])\n   ;; Or alternatively:\n   :render (fn [this])\n   ;; Deprecated methods:\n   :UNSAFE_component-will-receive-props (fn [this new-argv])\n   :UNSAFE_component-will-update (fn [this new-argv new-state])\n   :UNSAFE_component-will-mount (fn [this])}\n  ```\n\n  Everything is optional, except either :reagent-render or :render.\n\n  Map keys should use `React.Component` method names (https://reactjs.org/docs/react-component.html),\n  and can be provided in snake-case or camelCase.\n\n  State can be initialized using constructor, which matches React.Component class,\n  or using getInitialState which matches old React createClass function and is\n  now implemented by Reagent for compatibility.\n\n  State can usually be anything, e.g. Cljs object. But if using getDerivedState\n  methods, the state has to be plain JS object as React implementation uses\n  Object.assign to merge partial state into the current state.\n\n  React built-in static methods or properties are automatically defined as statics.",$APP.V,
$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.Uz],null),new $APP.D(null,2,5,$APP.E,[$APP.Uz,$APP.bT],null)),$APP.J,"reagent/core.cljs",$APP.K,68,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq(mT,xVa,new $APP.F(null,7,[$APP.R,xVa,$APP.O,"Takes a function and optional arguments, and returns a derefable\n  containing the output of that function. If the function derefs\n  Reagent atoms (or track, etc), the value will be updated whenever\n  the atom changes.\n\n  In other words, `@(track foo bar)` will produce the same result\n  as `(foo bar)`, but foo will only be called again when the atoms it\n  depends on changes, and will only trigger updates of components when\n  its result changes.\n\n  track is lazy, i.e the function is only evaluated on deref.",
$APP.V,$APP.I($APP.ne(new $APP.D(null,3,5,$APP.E,[$APP.aH,$APP.kk,$APP.rD],null),new $APP.F(null,1,[$APP.JJ,new $APP.D(null,1,5,$APP.E,[$APP.I($APP.pF,$APP.aH)],null)],null))),$APP.J,"reagent/core.cljs",$APP.K,218,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq($APP.Qd(new $APP.yd(function(){return oT},PVa,$APP.gi([$APP.S,$APP.R,$APP.J,$APP.HA,$APP.GH,$APP.M,$APP.K,$APP.uq,$APP.PJ,$APP.V,$APP.O,$APP.DE],[CVa,$S,"sci/configs/reagent/reagent.cljs",23,new $APP.F(null,6,[$APP.mB,!0,$APP.bt,1,$APP.NI,1,$APP.xI,
$APP.I($APP.I($APP.pA,$APP.uC)),$APP.V,$APP.I(new $APP.D(null,3,5,$APP.E,[$APP.pA,$APP.kk,$APP.uC],null)),$APP.yE,$APP.I(null)],null),1,10,!0,10,$APP.I(new $APP.D(null,3,5,$APP.E,[$APP.pA,$APP.kk,$APP.uC],null)),null,$APP.h(oT)?oT.ka:null]))),$S,new $APP.F(null,8,[$APP.R,$S,$APP.O,null,$APP.uq,!0,$APP.V,$APP.I(new $APP.D(null,5,5,$APP.E,[$APP.Xr,$APP.Xr,$APP.pA,$APP.kk,$APP.uC],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,10,$APP.M,15,$APP.S,qT],null),qT),new $APP.pq(lT,$APP.BA,new $APP.F(null,
7,[$APP.R,$APP.BA,$APP.O,"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.V,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.oH],null),new $APP.D(null,3,5,$APP.E,[$APP.oH,$APP.kk,$APP.PB],null)),$APP.J,"reagent/core.cljs",$APP.K,211,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq(kT,QVa,new $APP.F(null,7,[$APP.R,QVa,$APP.O,"Function which normalizes and combines class values to a string\n\n  Reagent allows classes to be defined as:\n  - Strings\n  - Named objects (Symbols or Keywords)\n  - Collections of previous types",
$APP.V,$APP.I($APP.Rg,new $APP.D(null,1,5,$APP.E,[$APP.Jqa],null),new $APP.D(null,2,5,$APP.E,[YUa,XUa],null),new $APP.D(null,4,5,$APP.E,[YUa,XUa,$APP.kk,sVa],null)),$APP.J,"reagent/core.cljs",$APP.K,179,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq($APP.Qd(new $APP.yd(function(){return pT},rVa,$APP.gi([$APP.S,$APP.R,$APP.J,$APP.HA,$APP.GH,$APP.M,$APP.K,$APP.uq,$APP.PJ,$APP.V,$APP.O,$APP.DE],[CVa,aT,"sci/configs/reagent/reagent.cljs",23,new $APP.F(null,6,[$APP.mB,!0,$APP.bt,-2,$APP.NI,-2,$APP.xI,$APP.I($APP.Dd),
$APP.V,$APP.I($APP.Rg),$APP.yE,$APP.I(null)],null),1,62,!0,62,$APP.I($APP.Rg),null,$APP.h(pT)?pT.ka:null]))),aT,new $APP.F(null,8,[$APP.R,aT,$APP.O,null,$APP.uq,!0,$APP.V,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.kk,$APP.uC],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,62,$APP.M,15,$APP.S,qT],null),qT),new $APP.pq(hT,IVa,new $APP.F(null,7,[$APP.R,IVa,$APP.O,"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.V,$APP.I(new $APP.D(null,
1,5,$APP.E,[$APP.GG],null),new $APP.D(null,2,5,$APP.E,[$APP.GG,$APP.bT],null)),$APP.J,"reagent/core.cljs",$APP.K,46,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq(iT,AVa,new $APP.F(null,7,[$APP.R,AVa,$APP.O,"Returns an adapter for a Reagent component, that may be used from\n  React, for example in JSX. A single argument, props, is passed to\n  the component, converted to a map.",$APP.V,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.$G],null),new $APP.D(null,2,5,$APP.E,[$APP.$G,$APP.bT],null)),$APP.J,"reagent/core.cljs",
$APP.K,59,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq(gT,SVa,new $APP.F(null,7,[$APP.R,SVa,$APP.O,'Create a native React element, by calling React.createElement directly.\n\n  That means the second argument must be a javascript object (or nil), and\n  that any Reagent hiccup forms must be processed with as-element. For example\n  like this:\n\n  ```cljs\n  (r/create-element "div" #js{:className "foo"}\n    "Hi " (r/as-element [:strong "world!"])\n  ```\n\n  which is equivalent to\n\n  ```cljs\n  [:div.foo "Hi" [:strong "world!"]]\n  ```',
$APP.V,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.ZD],null),new $APP.D(null,2,5,$APP.E,[$APP.ZD,eVa],null),new $APP.D(null,3,5,$APP.E,[$APP.ZD,eVa,$APP.RG],null),new $APP.D(null,5,5,$APP.E,[$APP.ZD,eVa,$APP.RG,$APP.kk,$APP.wF],null)),$APP.J,"reagent/core.cljs",$APP.K,17,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq(function(a){return MS(a)},QUa,new $APP.F(null,7,[$APP.R,QUa,$APP.O,"Stop the result of track! from updating.",$APP.V,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.oH],null)),$APP.J,"reagent/core.cljs",
$APP.K,242,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq(function(a,b){return new GTa(a,b)},kVa,new $APP.F(null,7,[$APP.R,kVa,$APP.O,"Provide a cursor into a Reagent atom.\n\n  Behaves like a Reagent atom but focuses updates and derefs to\n  the specified path within the wrapped Reagent atom. e.g.,\n\n  ```cljs\n  (let [c (cursor ra [:nested :content])]\n    ... @c ;; equivalent to (get-in @ra [:nested :content])\n    ... (reset! c 42) ;; equivalent to (swap! ra assoc-in [:nested :content] 42)\n    ... (swap! c inc) ;; equivalence to (swap! ra update-in [:nested :content] inc)\n    )\n  ```\n\n  The first parameter can also be a function, that should look\n  something like this:\n\n  ```cljs\n  (defn set-get\n    ([k] (get-in @state k))\n    ([k v] (swap! state assoc-in k v)))\n  ```\n\n  The function will be called with one argument – the path passed to\n  cursor – when the cursor is deref'ed, and two arguments (path and\n  new value) when the cursor is modified.\n\n  Given that set-get function, (and that state is a Reagent atom, or\n  another cursor) these cursors are equivalent:\n  `(cursor state [:foo])` and `(cursor set-get [:foo])`.\n\n  Note that a cursor is lazy: its value will not change until it is\n  used. This may be noticed with add-watch.",
$APP.V,$APP.I(new $APP.D(null,2,5,$APP.E,[pVa,$APP.PEa],null)),$APP.J,"reagent/core.cljs",$APP.K,272,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq(nT,dT,new $APP.F(null,7,[$APP.R,dT,$APP.O,"An eager version of track. The function passed is called\n  immediately, and continues to be called when needed, until stopped\n  with dispose!.",$APP.V,$APP.I($APP.ne(new $APP.D(null,3,5,$APP.E,[$APP.aH,$APP.kk,$APP.rD],null),new $APP.F(null,1,[$APP.JJ,new $APP.D(null,1,5,$APP.E,[$APP.I($APP.pF,$APP.aH)],null)],null))),
$APP.J,"reagent/core.cljs",$APP.K,234,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq(function(a){return LUa(a)},dVa,new $APP.F(null,7,[$APP.R,dVa,$APP.O,"Creates Compiler object with given `opts`,\n  this can be passed to `render`, `as-element` and other functions to control\n  how they turn the Reagent-style Hiccup into React components and elements.",$APP.V,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.zF],null)),$APP.J,"reagent/core.cljs",$APP.K,353,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq(MUa,cT,new $APP.F(null,
7,[$APP.R,cT,$APP.O,"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.V,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.$G],null)),$APP.J,"reagent/core.cljs",$APP.K,52,$APP.M,7,$APP.S,qT],null),qT)]),rT=$APP.FM.g($APP.HI,null),YVa=$APP.gi([UUa,$APP.BA,JVa,aVa,$Ua,gVa,iVa,lVa,OVa,NUa,dT,wVa],[new $APP.pq(function(a){var b=ES;return b==null?[]:DTa($APP.Mb,b,a,null,HTa)},UUa,new $APP.F(null,7,[$APP.R,UUa,$APP.O,null,$APP.V,
$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.VF],null)),$APP.J,"reagent/ratom.cljs",$APP.K,329,$APP.M,7,$APP.S,rT],null),rT),new $APP.pq(RS,$APP.BA,new $APP.F(null,7,[$APP.R,$APP.BA,$APP.O,"Like clojure.core/atom, except that it keeps track of derefs.",$APP.V,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.oH],null),new $APP.D(null,3,5,$APP.E,[$APP.oH,$APP.kk,new $APP.F(null,1,[$APP.tC,new $APP.D(null,2,5,$APP.E,[$APP.gB,$APP.hBa],null)],null)],null)),$APP.J,"reagent/ratom.cljs",$APP.K,172,$APP.M,7,$APP.S,qT],
null),qT),new $APP.pq(ETa,JVa,new $APP.F(null,7,[$APP.R,JVa,$APP.O,null,$APP.V,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.aH,$APP.rD],null)),$APP.J,"reagent/ratom.cljs",$APP.K,228,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq(function(a){return a.destroy},aVa,new $APP.F(null,7,[$APP.R,aVa,$APP.O,null,$APP.V,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.ne($APP.mH,new $APP.F(null,1,[$APP.Am,$APP.UC],null))],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,106,$APP.M,7,$APP.S,rT],null),rT),new $APP.pq(function(a,
b){return a.generation=b.ratomGeneration},$Ua,new $APP.F(null,7,[$APP.R,$Ua,$APP.O,null,$APP.V,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.ne($APP.mH,new $APP.F(null,1,[$APP.Am,$APP.UC],null)),$APP.ne($APP.$G,new $APP.F(null,1,[$APP.Am,$APP.UC],null))],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,98,$APP.M,7,$APP.S,rT],null),rT),new $APP.pq(function(){return ES!=null},gVa,new $APP.F(null,8,[$APP.R,gVa,$APP.O,null,$APP.V,$APP.I($APP.Rg),$APP.Am,$APP.jG,$APP.J,"reagent/ratom.cljs",$APP.K,17,
$APP.M,16,$APP.S,rT],null),rT),new $APP.pq(function(a,b){return a.destroy=b},iVa,new $APP.F(null,7,[$APP.R,iVa,$APP.O,null,$APP.V,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.ne($APP.mH,new $APP.F(null,1,[$APP.Am,$APP.UC],null)),uVa],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,102,$APP.M,7,$APP.S,rT],null),rT),new $APP.pq(IS,lVa,new $APP.F(null,7,[$APP.R,lVa,$APP.O,null,$APP.V,$APP.I(new $APP.D(null,3,5,$APP.E,[$APP.aH,$APP.kk,new $APP.F(null,1,[$APP.tC,new $APP.D(null,3,5,$APP.E,[ZUa,OUa,
LVa],null)],null)],null)),$APP.J,"reagent/ratom.cljs",$APP.K,517,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq(function(){return ES},OVa,new $APP.F(null,7,[$APP.R,OVa,$APP.O,"Read-only access to the ratom context.",$APP.V,$APP.I($APP.Rg),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,85,$APP.M,7,$APP.S,rT],null),rT),new $APP.pq(function(a){return a.generation},NUa,new $APP.F(null,7,[$APP.R,NUa,$APP.O,null,$APP.V,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.ne($APP.oH,new $APP.F(null,1,[$APP.Am,$APP.UC],
null))],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,90,$APP.M,7,$APP.S,rT],null),rT),new $APP.pq(eT,dT,new $APP.F(null,7,[$APP.R,dT,$APP.O,null,$APP.V,$APP.I($APP.ne(new $APP.D(null,3,5,$APP.E,[$APP.aH,$APP.kk,$APP.rD],null),new $APP.F(null,1,[$APP.JJ,new $APP.D(null,1,5,$APP.E,[$APP.I($APP.pF,$APP.aH)],null)],null))),$APP.J,"reagent/ratom.cljs",$APP.K,242,$APP.M,7,$APP.S,qT],null),qT),new $APP.pq(function(a){return a.ratomGeneration},wVa,new $APP.F(null,7,[$APP.R,wVa,$APP.O,null,$APP.V,
$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.ne($APP.oH,new $APP.F(null,1,[$APP.Am,$APP.UC],null))],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,94,$APP.M,7,$APP.S,rT],null),rT)]),sT=$APP.FM.g(zVa,null),tT=function tT(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return tT.l(arguments[0],arguments[1],2<c.length?new $APP.Ad(c.slice(2),0,null):null)};
tT.l=function(a,b,c){return $APP.h(!0)?$APP.U.h($APP.m($APP.N.l(new $APP.A(null,$APP.JA,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.g(new $APP.A(null,$APP.Ou,null,1,null),new $APP.A(null,BVa,null,1,null)))),null,1,null),$APP.x([new $APP.A(null,$APP.U.h($APP.m($APP.N.l(new $APP.A(null,FVa,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.l(new $APP.A(null,$APP.tk,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.h(new $APP.A(null,GVa,null,1,null)))),null,1,null),$APP.x([new $APP.A(null,
KVa,null,1,null),new $APP.A(null,BVa,null,1,null)],0)))),null,1,null),$APP.x([new $APP.A(null,$APP.U.h($APP.m($APP.N.g(new $APP.A(null,$APP.Iu,null,1,null),c))),null,1,null)],0)))),null,1,null)],0)))):null};tT.B=2;tT.G=function(a){var b=$APP.p(a),c=$APP.q(a);a=$APP.p(c);c=$APP.q(c);return this.l(b,a,c)};
var ZVa=new $APP.F(null,3,[$APP.IF,new $APP.pq($APP.Qd(new $APP.yd(function(){return tT},jVa,$APP.gi([$APP.S,$APP.R,$APP.J,$APP.HA,$APP.GH,$APP.M,$APP.K,$APP.uq,$APP.PJ,$APP.V,$APP.O,$APP.DE],[CVa,$APP.IF,"sci/configs/reagent/reagent.cljs",20,new $APP.F(null,6,[$APP.mB,!0,$APP.bt,0,$APP.NI,0,$APP.xI,$APP.I($APP.I($APP.bF)),$APP.V,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.kk,$APP.bF],null)),$APP.yE,$APP.I(null)],null),1,132,!0,132,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.kk,$APP.bF],null)),"Print with console.error.",
$APP.h(tT)?tT.ka:null]))),$APP.IF,new $APP.F(null,8,[$APP.R,$APP.IF,$APP.O,"Print with console.error.",$APP.uq,!0,$APP.V,$APP.I(new $APP.D(null,4,5,$APP.E,[$APP.Xr,$APP.Xr,$APP.kk,$APP.bF],null)),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,132,$APP.M,15,$APP.S,sT],null),sT),TUa,new $APP.pq(function(){return!1},TUa,new $APP.F(null,7,[$APP.R,TUa,$APP.O,null,$APP.V,$APP.I($APP.Rg),$APP.J,"sci/configs/reagent/reagent.cljs",$APP.K,129,$APP.M,7,$APP.S,sT],null),sT),bVa,new $APP.pq(UVa,bVa,new $APP.F(null,
7,[$APP.R,bVa,$APP.O,null,$APP.Am,$APP.HG,$APP.J,"reagent/debug.cljs",$APP.K,10,$APP.M,10,$APP.S,sT],null),sT)],null);$APP.Tv(new $APP.F(null,1,[$APP.Oq,new $APP.F(null,3,[$APP.iG,$APP.ui.j(XVa,cT,new $APP.pq(MUa,cT,new $APP.F(null,7,[$APP.R,cT,$APP.O,"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.V,$APP.I(new $APP.D(null,1,5,$APP.E,[$APP.$G],null)),$APP.J,"reagent/core.cljs",$APP.K,52,$APP.M,7,$APP.S,$APP.FM.h($APP.iG)],null),$APP.FM.h($APP.iG))),$APP.HI,YVa,zVa,ZVa],null)],null));