import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_transit.js";
import "./nbb_datascript.js";
const shadow_esm_import = function(x) { return import(x) };
var epb=function(a){return $APP.BO($APP.QO.h(dpb,new $APP.h(null,1,[$APP.MO,f7],null)),a)},fpb=function(a){return $APP.KO($APP.RO.h(dpb,new $APP.h(null,1,[$APP.MO,g7],null)),a)},dpb=new $APP.F(null,"json","json",1279968570),gpb=new $APP.q("datascript.transit","read-transit-str","datascript.transit/read-transit-str",526272408,null),hpb=new $APP.q(null,"write-handlers","write-handlers",-456757384,null),ipb=new $APP.q("datascript.transit","write-handlers","datascript.transit/write-handlers",-1659157370,
null),jpb=new $APP.q(null,"read-transit-str","read-transit-str",-953853518,null),kpb=new $APP.q("datascript.transit","read-handlers","datascript.transit/read-handlers",400129984,null),lpb=new $APP.q("datascript.transit","write-transit-str","datascript.transit/write-transit-str",-396975951,null),mpb=new $APP.q(null,"read-handlers","read-handlers",-544976454,null),npb=new $APP.q(null,"write-transit-str","write-transit-str",546948831,null);var f7=new $APP.h(null,3,["u",$APP.ck,"datascript/DB",$APP.c2,"datascript/Datom",$APP.h1],null),g7=$APP.Vf([$APP.z1,$APP.SO.h($APP.tg("datascript/DB"),function(a){return new $APP.h(null,2,[$APP.A1,$APP.A1.g(a),$APP.b2,$APP.B1.g(a)],null)}),$APP.f1,$APP.SO.h($APP.tg("datascript/Datom"),function(a){return $APP.k($APP.e1(a))?new $APP.H(null,4,5,$APP.J,[a.e,a.a,a.v,$APP.d1(a)],null):new $APP.H(null,5,5,$APP.J,[a.e,a.a,a.v,$APP.d1(a),!1],null)}),$APP.G0,new $APP.EO]);var h7=$APP.kN.h($APP.RI,null),opb=new $APP.h(null,4,[mpb,function(){var a=new $APP.Ed(function(){return f7},kpb,$APP.gi([$APP.R,$APP.Q,$APP.Sl,$APP.$z,$APP.Pm,$APP.Tl,$APP.CK,$APP.W,$APP.N,$APP.iF],[$APP.RI,mpb,"datascript/transit.cljs",19,1,9,9,$APP.Kd,null,$APP.k(f7)?f7.H:null])),b=$APP.n(a),c=$APP.ue(a);a=$APP.k(null)?null:$APP.Q.g(c);var d=new $APP.h(null,4,[$APP.R,h7,$APP.Q,a,$APP.W,$APP.W.g(c),$APP.N,$APP.N.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.oq.g(c);
return $APP.k(e)?e:$APP.yq.g(c)}())?$APP.fN.j(a,b,d):$APP.nu.j(a,b,d)}(),hpb,function(){var a=new $APP.Ed(function(){return g7},ipb,$APP.gi([$APP.R,$APP.Q,$APP.Sl,$APP.$z,$APP.Pm,$APP.Tl,$APP.CK,$APP.W,$APP.N,$APP.iF],[$APP.RI,hpb,"datascript/transit.cljs",20,1,16,16,$APP.Kd,null,$APP.k(g7)?g7.H:null])),b=$APP.n(a),c=$APP.ue(a);a=$APP.k(null)?null:$APP.Q.g(c);var d=new $APP.h(null,4,[$APP.R,h7,$APP.Q,a,$APP.W,$APP.W.g(c),$APP.N,$APP.N.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=
$APP.oq.g(c);return $APP.k(e)?e:$APP.yq.g(c)}())?$APP.fN.j(a,b,d):$APP.nu.j(a,b,d)}(),jpb,function(){var a=new $APP.Ed(function(){return epb},gpb,$APP.gi([$APP.R,$APP.Q,$APP.Sl,$APP.$z,$APP.Pm,$APP.Tl,$APP.CK,$APP.W,$APP.N,$APP.iF],[$APP.RI,jpb,"datascript/transit.cljs",23,1,29,29,$APP.K(new $APP.H(null,1,5,$APP.J,[$APP.RH],null)),null,$APP.k(epb)?epb.H:null])),b=$APP.n(a),c=$APP.ue(a);a=$APP.k(null)?null:$APP.Q.g(c);var d=new $APP.h(null,4,[$APP.R,h7,$APP.Q,a,$APP.W,$APP.W.g(c),$APP.N,$APP.N.g(c)],
null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.oq.g(c);return $APP.k(e)?e:$APP.yq.g(c)}())?$APP.fN.j(a,b,d):$APP.nu.j(a,b,d)}(),npb,function(){var a=new $APP.Ed(function(){return fpb},lpb,$APP.gi([$APP.R,$APP.Q,$APP.Sl,$APP.$z,$APP.Pm,$APP.Tl,$APP.CK,$APP.W,$APP.N,$APP.iF],[$APP.RI,npb,"datascript/transit.cljs",24,1,33,33,$APP.K(new $APP.H(null,1,5,$APP.J,[$APP.NH],null)),null,$APP.k(fpb)?fpb.H:null])),b=$APP.n(a),c=$APP.ue(a);a=$APP.k(null)?null:$APP.Q.g(c);var d=
new $APP.h(null,4,[$APP.R,h7,$APP.Q,a,$APP.W,$APP.W.g(c),$APP.N,$APP.N.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.oq.g(c);return $APP.k(e)?e:$APP.yq.g(c)}())?$APP.fN.j(a,b,d):$APP.nu.j(a,b,d)}()],null);$APP.$u(new $APP.h(null,1,[$APP.Kq,new $APP.h(null,1,[$APP.RI,opb],null)],null));