import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var RSa,TSa,USa,bU,cU,VSa,WSa,XSa,YSa,ZSa,$Sa,aTa,bTa,eU,cTa,gU,dTa,eTa,fTa,gTa,hTa,iU,jU,kU,iTa,nU,oU,jTa,kTa,lTa,mTa,qU,nTa,oTa,rTa,tU,sTa,tTa,uTa,vTa,wTa,yTa,ATa,BTa,DTa,AU,HTa,JTa,KTa,LTa,MTa,NTa,OTa,RTa,BU,STa,TTa,UTa,VTa,XTa,CU,ZTa,$Ta,aUa,bUa,cUa,dUa,eUa,hUa,kUa,lUa,mUa,nUa,qUa,EU,rUa,sUa,tUa,uUa,vUa,wUa,xUa,yUa,zUa,AUa,BUa,CUa,xU,DUa,EUa,FUa,GUa,HUa,IUa,JUa,iUa,KUa,LUa,MUa,NUa,OUa,PUa,FU,GU,QUa,RUa,SUa,TUa,UUa,VUa,pU,WUa,ITa,XUa,YUa,ZUa,HU,$Ua,aVa,PTa,bVa,mU,cVa,dVa,eVa,wU,fVa,gVa,hVa,iVa,
jVa,kVa,lVa,yU,mVa,nVa,oVa,pVa,qVa,pUa,rVa,sVa,tVa,uVa,vVa,wVa,xVa,JU,yVa,zVa,AVa,BVa,CVa,DVa,EVa,KU,FVa,GVa,HVa,LU,IVa,JVa,oUa,KVa,LVa,MVa,NVa,OVa,PVa,QVa,RVa,SVa,TVa,zTa,UVa,VVa,WVa,XVa,FTa,YVa,ZVa,$Va;RSa=function(a){return 2>$APP.be(a)?$APP.bl(a):[$APP.bl($APP.Yi.j(a,0,1)),$APP.Yi.h(a,1)].join("")};
TSa=function(a){if("string"===typeof a)return a;a=$APP.Fi(a);var b=$APP.fl.h(a,/-/),c=$APP.r(b);b=$APP.v(c);c=$APP.w(c);return $APP.k(SSa.g?SSa.g(b):SSa.call(null,b))?a:$APP.qg.j($APP.m,b,$APP.ej.h(RSa,c))};
USa=function(a){var b=function(){var c=function(){var d=$APP.pe(a);if(d){d=a.displayName;if($APP.k(d))return d;d=a.name;return"string"===typeof d&&$APP.r(d)?d:null}return d}();if($APP.k(c))return c;c=function(){var d=null!=a?a.M&4096||$APP.xd===a.Xg?!0:!1:!1;return d?$APP.Fi(a):d}();if($APP.k(c))return c;c=$APP.se(a);return $APP.Be(c)?$APP.N.g(c):null}();return $APP.k(b)?$APP.$k($APP.m.g(b),"$","."):null};bU=function(a){return a instanceof $APP.F||a instanceof $APP.q};
cU=function(a){if($APP.Be(a))try{var b=$APP.C.h(a,$APP.wF)}catch(c){b=null}else b=null;return b};VSa=function(a){var b=$APP.wF.g($APP.se(a));if($APP.k(b))return b;b=cU($APP.y.j(a,1,null));if($APP.k(b))return b;b=$APP.y.j(a,0,null);switch(b instanceof $APP.F?b.N:null){case "\x3e":case "f\x3e":return cU($APP.y.j(a,2,null));case "r\x3e":return a=$APP.y.j(a,2,null),null==a?null:a.key;default:return null}};WSa=function(a){return setTimeout(a,16)};XSa=function(a,b){return a.Ui-b.Ui};YSa=function(){return null};
ZSa=function(a){for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.D?d.D():d.call(null);c+=1}else return null};$Sa=function(a,b,c){b.push(c);return a.schedule()};aTa=function(){this.ri=!1};bTa=function(a){if($APP.k(a.cljsIsDirty))return null;a.cljsIsDirty=!0;return dU.queue_render(a)};eU=function(a){if(null!=a&&null!=a.Ym)a=a.id;else{var b=eU[$APP.fa(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=eU._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.Lb("Compiler.get-id",a);}return a};
cTa=function(a,b,c){if(null!=a&&null!=a.Zk)a=a.Zk(a,b,c);else{var d=cTa[$APP.fa(null==a?null:a)];if(null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else if(d=cTa._,null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else throw $APP.Lb("Compiler.parse-tag",a);}return a};
$APP.fU=function(a,b){if(null!=a&&null!=a.Xk)a=a.Xk(a,b);else{var c=$APP.fU[$APP.fa(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=$APP.fU._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.Lb("Compiler.as-element",a);}return a};
gU=function(a,b,c,d,e){if(null!=a&&null!=a.Yk)a=a.Yk(a,b,c,d,e);else{var f=gU[$APP.fa(null==a?null:a)];if(null!=f)a=f.P?f.P(a,b,c,d,e):f.call(null,a,b,c,d,e);else if(f=gU._,null!=f)a=f.P?f.P(a,b,c,d,e):f.call(null,a,b,c,d,e);else throw $APP.Lb("Compiler.make-element",a);}return a};dTa=function(){return null!=hU};
eTa=function(a,b){b.Bi=null;a:{var c=hU;hU=b;try{var d=a.D?a.D():a.call(null);break a}finally{hU=c}d=void 0}a=b.Bi;b.Mf=!1;a:{c=b.vg;var e=null==a?0:a.length,f=e===(null==c?0:c.length);if(f)for(f=0;;){var l=f===e;if(l){c=l;break a}if(a[f]===c[f])f+=1;else{c=!1;break a}}else c=f}c||b._update_watching(a);return d};fTa=function(a){var b=hU;if(null!=b){var c=b.Bi;null==c?b.Bi=[a]:c.push(a)}};gTa=function(a,b,c){a.lb=$APP.ui.j(a.lb,b,c);return a.Dj=null};
hTa=function(a,b){a.lb=$APP.Ol.h(a.lb,b);return a.Dj=null};iU=function(a,b,c){var d=a.Dj;d=null==d?a.Dj=$APP.df(function(u,t,A){u.push(t);u.push(A);return u},[],a.lb):d;for(var e=d.length,f=0;;)if(f<e){var l=d[f],p=d[f+1];p.F?p.F(l,a,b,c):p.call(null,l,a,b,c);f=2+f}else return null};jU=function(a,b,c,d){$APP.Lc(a,["#object[reagent.ratom.",$APP.m.g(c)," "].join(""));a:{c=hU;hU=null;try{var e=d;break a}finally{hU=c}e=void 0}$APP.dj(e,a,b);return $APP.Lc(a,"]")};
kU=function(a,b,c,d){this.state=a;this.O=b;this.tg=c;this.lb=d;this.J=2154201088;this.M=114690};iTa=function(a,b,c,d,e){var f=b.uj;f=null==f?$APP.Xf:f;var l=f.h?f.h(c,null):f.call(null,c,null);if(null!=l)return $APP.n(l);if(null==hU)return a.D?a.D():a.call(null);l=function(){function u(t){var A=$APP.Ol.h(b.uj,c);b.uj=A;null!=d&&(d.zh=null);return null!=e?e.g?e.g(t):e.call(null,t):null}return lU.j?lU.j(a,mU,u):lU.call(null,a,mU,u)}();var p=$APP.n(l);b.uj=$APP.ui.j(f,c,l);null!=d&&(d.zh=l);return p};
nU=function(a,b){this.f=a;this.Aa=b;this.zh=null;this.J=2153807872;this.M=0};oU=function(a,b){return new nU(a,b)};jTa=function(a,b){var c=oU(a,b);a=function(){function d(){return c.Ja(null)}return lU.j?lU.j(d,pU,!0):lU.call(null,d,pU,!0)}();$APP.n(a);return a};kTa=function(a,b){this.jc=a;this.path=b;this.lb=this.state=this.zh=null;this.J=2153807872;this.M=114690};lTa=function(a){a=a.destroy;return null==a?null:a.D?a.D():a.call(null)};
mTa=function(a){var b=hU;return null==b?[]:iTa($APP.Pb,b,a,null,lTa)};qU=function(a){if(null!=a&&null!=a.vj)a=a.vj(a);else{var b=qU[$APP.fa(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=qU._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.Lb("IDisposable.dispose!",a);}return a};nTa=function(a,b,c,d){return a._handle_change(b,c,d)};oTa=function(a){this.f=a;this.state=null;this.Mf=!0;this.sk=!1;this.Ci=this.ef=this.lb=this.vg=null;this.J=2153807872;this.M=114690};
$APP.sU=function(){for(;;){var a=rU;if(null==a)return null;rU=null;for(var b=a.length,c=0;;)if(c<b)a[c]._queued_run(),c+=1;else break}};rTa=function(a,b){var c=pTa,d=qTa,e=eTa(a,d);null!=d.vg&&(qTa=lU(null),d._set_opts(c),d.f=a,d.ef=function(){return bTa.g?bTa.g(b):bTa.call(null,b)},b.cljsRatom=d);return e};
tU=function(a,b){var c=b.argv;if(null==c){c=$APP.I;a=a.constructor;a:for(var d=$APP.Ja(b),e=d.length,f=$APP.Xf,l=0;;)if(l<e){var p=d[l];f=$APP.ui.j(f,$APP.fj.g(p),$APP.La(b,p));l+=1}else break a;b=new $APP.H(null,2,5,c,[a,f],null)}else b=c;return b};sTa=function(a){var b;if(b=$APP.pe(a))a=null==a?null:a.prototype,b=null!=(null==a?null:a.Qf);return b};tTa=function(a){var b;if(b=$APP.pe(a))a=null==a?null:a.prototype,b=null!=(null==a?null:a.render);return b};
uTa=function(a,b){for(;;){var c=a.Qf,d=!0===a.Pl?c.call(a,a):function(){var e=tU(a,a.props);switch($APP.be(e)){case 1:return c.call(a);case 2:return c.call(a,$APP.y.h(e,1));case 3:return c.call(a,$APP.y.h(e,1),$APP.y.h(e,2));case 4:return c.call(a,$APP.y.h(e,1),$APP.y.h(e,2),$APP.y.h(e,3));case 5:return c.call(a,$APP.y.h(e,1),$APP.y.h(e,2),$APP.y.h(e,3),$APP.y.h(e,4));default:return c.apply(a,$APP.ws.g(e).slice(1))}}();if($APP.De(d))return $APP.fU(b,d);if($APP.Le(d))a.Qf=sTa(d)?function(e,f,l,p,u){return function(){function t(B){var E=
null;if(0<arguments.length){E=0;for(var G=Array(arguments.length-0);E<G.length;)G[E]=arguments[E+0],++E;E=new $APP.Ed(G,0,null)}return A.call(this,E)}function A(B){return $APP.fU(f,$APP.qg.j($APP.Fw,u,B))}t.B=0;t.G=function(B){B=$APP.r(B);return A(B)};t.l=A;return t}()}(a,b,c,null,d):d;else return d}};vTa=function(a,b){var c=uU;uU=a;try{return uTa(a,b)}finally{uU=c}};
wTa=function(a,b){switch(a instanceof $APP.F?a.N:null){case "getDefaultProps":throw Error("getDefaultProps not supported");case "getDerivedStateFromProps":return function(c,d){var e=b.call,f=c.argv;null!=f&&(c=$APP.y.j(f,1,null),c=$APP.Be(c)?c:null);return e.call(b,null,c,d)};case "getInitialState":return function(c){var d=c.Rl;d=null!=d?d:c.Rl=vU.g(null);return $APP.vg(d,b.call(c,c))};case "getSnapshotBeforeUpdate":return function(c,d){return b.call(this,this,tU(this,c),d)};case "componentWillReceiveProps":return function(c){return b.call(this,
this,tU(this,c))};case "UNSAFE_componentWillReceiveProps":return function(c){return b.call(this,this,tU(this,c))};case "shouldComponentUpdate":return function(c){if($APP.k(!1))return!1;var d=this.props.argv,e=c.argv,f=null==d||null==e;if(null==b){if(f)return f;try{return $APP.ti.h(d,e)}catch(l){return!1}}else return f?b.call(this,this,tU(this,this.props),tU(this,c)):b.call(this,this,d,e)};case "componentWillUpdate":return function(c,d){return b.call(this,this,tU(this,c),d)};case "UNSAFE_componentWillUpdate":return function(c,
d){return b.call(this,this,tU(this,c),d)};case "componentDidUpdate":return function(c,d,e){return b.call(this,this,tU(this,c),d,e)};case "componentWillMount":return function(){return b.call(this,this)};case "UNSAFE_componentWillMount":return function(){return b.call(this,this)};case "componentDidMount":return function(){return b.call(this,this)};case "componentWillUnmount":return function(){var c=$APP.La(this,"cljsRatom");null!=c&&qU(c);this.cljsIsDirty=!1;return null==b?null:b.call(this,this)};case "componentDidCatch":return function(c,
d){return b.call(this,this,c,d)};default:return null}};yTa=function(a){return $APP.df(function(b,c,d){return $APP.ui.j(b,$APP.fj.g(xTa(c)),d)},$APP.Xf,a)};
ATa=function(a,b){var c=function(){var l=wU.g(a);return $APP.k(l)?l:xU.g(a)}(),d=null==wU.g(a),e=function(){var l=yU.g(a);if($APP.k(l))return l;l=USa(c);return $APP.k(l)?l:$APP.m.g($APP.$n.g("reagent"))}(),f=$APP.df(function(l,p,u){var t=$APP.ui.j,A=wTa(p,u);return t.call($APP.ui,l,p,$APP.k(A)?A:u)},$APP.Xf,a);return $APP.ui.l(f,yU,e,$APP.z([zTa,d,wU,c,xU,function(){var l=this;if($APP.zU)return vTa(l,b);var p=$APP.La(l,"cljsRatom");l.cljsIsDirty=!1;return null==p?rTa(function(){return vTa(l,b)},l):
p._run(!1)}]))};BTa=function(a){return $APP.df(function(b,c,d){c=$APP.Fi(c);b[c]=d;return b},{},a)};DTa=function(a,b){return ATa($APP.Nl.l($APP.z([CTa,yTa(a)])),b)};
AU=function(a,b){function c(p,u,t){$APP.Iu.nbb$internal$react.Ej.call(this,p,u,t);$APP.k(l)&&(l.h?l.h(this,p):l.call(null,this,p));$APP.k(f)&&(this.state=f.g?f.g(this):f.call(null,this));this.Ui=ETa+=1;return this}a=DTa(a,b);b=BTa($APP.qg.l($APP.Ol,a,yU,FTa,$APP.Ys,$APP.z([xU,wU,GTa])));var d=BTa($APP.wi(a,GTa)),e=yU.g(a),f=FTa.g(a),l=$APP.Ys.g(a);$APP.Oa(c.prototype,$APP.Iu.nbb$internal$react.Ej.prototype,b);$APP.k(xU.g(a))&&(c.prototype.render=xU.g(a));$APP.k(wU.g(a))&&(c.prototype.Qf=wU.g(a));
$APP.k(zTa.g(a))&&(c.prototype.Pl=zTa.g(a));$APP.Oa(c,$APP.Iu.nbb$internal$react.Ej,d);$APP.k(e)&&(c.displayName=e,c.Ph=e,c.Ol=function(p){return $APP.Lc(p,e)},Object.defineProperty(c,"name",{value:e,writable:!1}));c.Yj=!0;return c.prototype.constructor=c};HTa=function(a,b,c){a=eU(a);return b[a]=c};JTa=function(a,b){var c=$APP.La(a,eU(b));null==c?sTa(a)?a=HTa(b,a,a):(c=$APP.se(a),c=$APP.ui.j(c,ITa,a),c=AU(c,b),a=HTa(b,a,c)):a=c;return a};
KTa=function(a,b){for(;;){var c=b.Qf,d=b.argv,e=$APP.qg.h(c,d);if($APP.De(e))return $APP.fU(a,e);if($APP.Le(e))b.Qf=sTa(e)?function(f,l,p,u,t,A){return function(){function B(G){var O=null;if(0<arguments.length){O=0;for(var T=Array(arguments.length-0);O<T.length;)T[O]=arguments[O+0],++O;O=new $APP.Ed(T,0,null)}return E.call(this,O)}function E(G){return $APP.fU(f,$APP.qg.j($APP.Fw,A,G))}B.B=0;B.G=function(G){G=$APP.r(G);return E(G)};B.l=E;return B}()}(a,b,c,null,d,e):e;else return e}};
LTa=function(a,b){var c=uU;uU=b;try{return KTa(a,b)}finally{uU=c}};
MTa=function(a,b){if($APP.zU)return LTa(a,b);var c=b.argv,d=b.Qf;b=$APP.Iu.nbb$internal$react.to(0);$APP.y.j(b,0,null);var e=$APP.y.j(b,1,null),f=$APP.Iu.nbb$internal$react.so();$APP.k(f.current)||function(){var p={forceUpdate:function(){return e.g?e.g($APP.Pd):e.call(null,$APP.Pd)}};p.Ui=ETa+=1;p.constructor=d;p.Qf=d;return f.current=p}();var l=f.current;b=$APP.La(l,"cljsRatom");$APP.Iu.nbb$internal$react.ro(function(){return function(){var p=$APP.La(l,"cljsRatom");return null==p?null:qU(p)}},[]);
l.argv=c;l.cljsIsDirty=!1;return null==b?rTa(function(){return LTa(a,l)},l):b._run(!1)};NTa=function(a,b){a=a.argv;b=b.argv;try{return $APP.x.h(a,b)}catch(c){return!1}};OTa=function(a,b){function c(e){return MTa(a,e)}var d=$APP.La(b,eU(a));if($APP.k(d))return d;d=USa(b);c.displayName=d;Object.defineProperty(c,"name",{value:d,writable:!1});d=$APP.Iu.nbb$internal$react.mo(c,NTa);HTa(a,b,d);return d};
RTa=function(a,b,c,d){var e=$APP.Yf($APP.Xf);e=$APP.C.h(e,PTa);if(a===document.activeElement&&$APP.Se(QTa,a.type)&&"string"===typeof b&&"string"===typeof c){var f=a.value;if($APP.ti.h(f,c))return dU.add_after_render(function(){return BU.g?BU.g(d):BU.call(null,d)});c=$APP.be(f)-a.selectionStart;c=$APP.be(b)-c;d.Qh=b;a.value=b;$APP.pe(e)&&(e.g?e.g(b):e.call(null,b));a.selectionStart=c;return a.selectionEnd=c}d.Qh=b;a.value=b;return $APP.pe(e)?e.g?e.g(b):e.call(null,b):null};
BU=function(a){if($APP.k(a.Ti)){a.ak=!1;var b=a.Ql,c=a.Qh,d=a.gj;return $APP.ti.h(b,c)?RTa(d,b,c,a):null}return null};STa=function(a,b,c){a.Qh=c.target.value;$APP.k(a.ak)||(a.ak=!0,dU.add_after_render(function(){return BU(a)}));return b.g?b.g(c):b.call(null,c)};
TTa=function(a){var b=uU;if($APP.k(function(){var f=null!=a;return f?(f=a.hasOwnProperty("onChange"),$APP.k(f)?a.hasOwnProperty("value"):f):f}())){var c=a.value;c=null==c?"":c;var d=a.onChange,e=a.ref;$APP.k(b.Ti)||(b.Ti=!0,b.Qh=c);$APP.k(b.$k)||(b.$k=$APP.pe(e)?function(f){b.gj=f;return e.g?e.g(f):e.call(null,f)}:$APP.k($APP.k(e)?e.hasOwnProperty("current"):e)?function(f){b.gj=f;return e.current=f}:function(f){return b.gj=f});b.Ql=c;delete a.value;a.defaultValue=c;a.onChange=function(f){return STa(b,
d,f)};a.ref=b.$k}};UTa=function(a){this.tag=a;this.className=this.id=null};VTa=function(a,b){return a.hasOwnProperty(b)?$APP.La(a,b):null};XTa=function(a,b,c){if(bU(b)){var d=VTa(WTa,$APP.Fi(b));null==d?(d=TSa(b),b=$APP.Fi(b),b=WTa[b]=d):b=d}c=CU.g?CU.g(c):CU.call(null,c);a[b]=c;return a};
CU=function(a){return"object"!==$APP.fa(a)?a:bU(a)?$APP.Fi(a):$APP.Be(a)?$APP.df(XTa,{},a):$APP.we(a)?$APP.$y(a):$APP.Le(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Ed(f,0,null)}return c.call(this,e)}function c(d){return $APP.qg.h(a,d)}b.B=0;b.G=function(d){d=$APP.r(d);return c(d)};b.l=c;return b}():$APP.$y(a)};
ZTa=function(a,b,c){if(bU(b)){var d=VTa(YTa,$APP.Fi(b));null==d?(d=TSa(b),b=$APP.Fi(b),b=YTa[b]=d):b=d}c=CU(c);a[b]=c;return a};
$Ta=function(a){return"object"!==$APP.fa(a)?a:bU(a)?$APP.Fi(a):$APP.Be(a)?$APP.df(ZTa,{},a):$APP.we(a)?$APP.$y(a):$APP.Le(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Ed(f,0,null)}return c.call(this,e)}function c(d){return $APP.qg.h(a,d)}b.B=0;b.G=function(d){d=$APP.r(d);return c(d)};b.l=c;return b}():$APP.$y(a)};
aUa=function(a,b,c,d,e){switch($APP.be(b)-e){case 0:return $APP.Iu.nbb$internal$react.createElement(c,d);case 1:return $APP.Iu.nbb$internal$react.createElement(c,d,$APP.fU(a,$APP.y.j(b,e,null)));default:return $APP.Iu.nbb$internal$react.createElement.apply(null,$APP.df(function(f,l,p){l>=e&&f.push($APP.fU(a,p));return f},[c,d],b))}};bUa=function(a,b,c,d){this.tag=a;this.id=b;this.className=c;this.Ul=d};
cUa=function(a,b,c){a=JTa(a,c);c={};c.argv=b;b=VSa(b);null!=b&&(c.key=b);return $APP.Iu.nbb$internal$react.createElement(a,c)};dUa=function(a,b,c,d){var e={};e.Qf=a;e.argv=$APP.el.h(b,c);b=VSa(b);null!=b&&(e.key=b);return $APP.Iu.nbb$internal$react.createElement(OTa(d,a),e)};eUa=function(a,b,c){return tTa(a)?cUa(a,b,c):dUa(a,b,1,c)};
hUa=function(a,b){a=VTa(fUa,b);if(null==a){var c=$APP.w($APP.Ui(gUa,$APP.Fi(b)));a=$APP.y.j(c,0,null);var d=$APP.y.j(c,1,null);c=$APP.y.j(c,2,null);c=null==c?null:$APP.$k(c,/\./," ");var e=$APP.ti.h(-1,a.indexOf("-"));a=new bUa(a,d,c,e);return fUa[b]=a}return a};
kUa=function(a,b,c,d){var e=a.tag,f=$APP.y.j(b,c,null),l=null==f||$APP.Be(f),p=function(){var A=l?f:null;var B=$APP.Gr.g(A);B=$APP.k(B)?$APP.ui.j(A,$APP.Gr,DU.g(B)):A;var E=a.id;A=a.className;E=null!=E&&null==$APP.Eq.g(B)?$APP.ui.j(B,$APP.Eq,E):B;if($APP.k(A)){var G=$APP.ui.j,O=DU.h,T=$APP.Gr.g(B);B=$APP.k(T)?T:iUa.g(B);A=G.call($APP.ui,E,$APP.Gr,O.call(DU,A,B))}else A=E;A=$APP.k(a.Ul)?$Ta(A):CU(A);return $APP.k(A)?A:{}}();c+=l?1:0;a:switch(e){case "input":case "textarea":var u=!0;break a;default:u=
!1}if(u){u=cU(f);var t=function(){var A=d.Zm;if($APP.k(A))return A;A=AU(jUa,d);return d.Zm=A}();return $APP.fU(d,$APP.re(new $APP.H(null,6,5,$APP.I,[t,b,e,p,c,d],null),$APP.Nl.l($APP.z([$APP.k(u)?new $APP.h(null,1,[$APP.wF,u],null):null,$APP.se(b)]))))}u=cU($APP.se(b));null!=u&&(p.key=u);return gU(d,b,e,p,c)};lUa=function(a,b){return $APP.ws.g($APP.ej.h(function(c){return $APP.fU(b,c)},a))};
mUa=function(a,b,c){null==b&&console.error("vec-to-elem",$APP.yj.l($APP.z([a])));var d=$APP.y.j(a,0,null);switch(d instanceof $APP.F?d.N:null){case "\x3e":return c=$APP.y.j(a,1,null),kUa(new bUa(c,null,null,null),a,2,b);case "r\x3e":c=$APP.y.j(a,1,null);d=$APP.y.j(a,2,null);d=$APP.k(d)?d:{};var e=cU($APP.se(a));null!=e&&(d.key=e);return gU(b,a,c,d,3);case "f\x3e":return dUa($APP.y.j(a,1,null),a,2,b);case "\x3c\x3e":return d=$APP.y.j(a,1,null),c=null==d||$APP.Be(d),d=CU(c?d:null),d=$APP.k(d)?d:{},
c=1+(c?1:0),e=VSa(a),null!=e&&(d.key=e),gU(b,a,$APP.Iu.nbb$internal$react.Gn,d,c);default:if(bU(d)||"string"===typeof d)a:for(;;)switch(c=$APP.y.j(a,0,null),d=$APP.Fi(c),e=d.indexOf("\x3e"),e){case -1:b=kUa(cTa(b,d,c),a,1,b);break a;case 0:b=null;break a;default:a=$APP.re(new $APP.H(null,2,5,$APP.I,[$APP.Yi.j(d,0,e),$APP.ui.j($APP.re(a,null),0,$APP.Yi.h(d,e+1))],null),$APP.se(a))}else b=d instanceof UTa?kUa(d,a,1,b):c.j?c.j(d,a,b):c.call(null,d,a,b);return b}};
nUa=function(a,b,c,d,e){this.Ed=a;this.id=b;this.hk=c;this.ki=d;this.Im=e;this.J=393216;this.M=0};qUa=function(a){var b=$APP.$n.g("reagent-compiler"),c=$APP.k(oUa.g(a))?eUa:cUa,d=$APP.C.j(a,pUa,hUa);return new nUa(a,b,c,d,$APP.Xf)};EU=function(a){return new UTa(a)};rUa=function(a){return qU(a)};sUa=function(a,b){return new kTa(a,b)};tUa=function(a){return qUa(a)};uUa=function(){return hU};vUa=function(a){return a.generation};wUa=function(a){return a.ratomGeneration};
xUa=function(a,b){return a.generation=b.ratomGeneration};yUa=function(a,b){return a.destroy=b};zUa=function(a){return a.destroy};AUa=function(){return!1};BUa=new $APP.q(null,"-generation","-generation",627658965,null);CUa=new $APP.q("reagent.ratom","track!","reagent.ratom/track!",1183599982,null);xU=new $APP.F(null,"render","render",-1408033454);DUa=new $APP.q(null,"on-set","on-set",1499578057,null);EUa=new $APP.q("reagent.core","adapt-react-class","reagent.core/adapt-react-class",1789410154,null);
FUa=new $APP.q("reagent.ratom","make-reaction","reagent.ratom/make-reaction",272608527,null);GUa=new $APP.q(null,"dispose!","dispose!",-395693497,null);HUa=new $APP.q("reagent.ratom","-destroy","reagent.ratom/-destroy",-1284026419,null);IUa=new $APP.q("reagent.core","create-compiler","reagent.core/create-compiler",491047088,null);JUa=new $APP.F(null,"componentWillUnmount","componentWillUnmount",1573788814);iUa=new $APP.F(null,"className","className",-1983287057);
KUa=new $APP.q(null,"-tracking?","-tracking?",-1106885352,null);LUa=new $APP.q(null,"with-let","with-let",-1310113408,null);MUa=new $APP.q(null,"with-let-values","with-let-values",1929572375,null);NUa=new $APP.q(null,"create-class","create-class",-665911586,null);OUa=new $APP.F(null,"childContextTypes","childContextTypes",578717991);PUa=new $APP.q("reagent.core","atom","reagent.core/atom",1748890217,null);FU=new $APP.q(null,"class2","class2",-1266396392,null);
GU=new $APP.q(null,"class1","class1",-1905977651,null);QUa=new $APP.q("reagent.core","cursor","reagent.core/cursor",-1137097804,null);RUa=new $APP.q(null,"auto-run","auto-run",-696035332,null);SUa=new $APP.q(null,"-set-ratom-generation!","-set-ratom-generation!",-1545989828,null);TUa=new $APP.q("sci.configs.reagent.reagent","-ratom-context","sci.configs.reagent.reagent/-ratom-context",270989566,null);
UUa=new $APP.q("sci.configs.reagent.reagent","-destroy","sci.configs.reagent.reagent/-destroy",-1999711192,null);VUa=new $APP.q(null,"-destroy","-destroy",-557272508,null);pU=new $APP.F(null,"auto-run","auto-run",1958400437);WUa=new $APP.q(null,"track-console","track-console",17070495,null);ITa=new $APP.F(null,"reagent-render","reagent-render",-985383853);XUa=new $APP.F(null,"contextTypes","contextTypes",-2023853910);YUa=new $APP.q(null,"create-compiler","create-compiler",1059333141,null);
ZUa=new $APP.q(null,"destroy__37500__auto__","destroy__37500__auto__",67271297,null);HU=new $APP.q(null,"props","props",2093813254,null);$Ua=new $APP.q(null,"reaction","reaction",2131401315,null);aVa=new $APP.F(null,"on-set","on-set",-140953470);PTa=new $APP.F(null,"on-write","on-write",31519475);bVa=new $APP.q(null,"reactive?","reactive?",1213887990,null);mU=new $APP.F(null,"on-dispose","on-dispose",2105306360);$APP.IU=new $APP.q(null,"compiler","compiler",1372604796,null);
cVa=new $APP.q("reagent.ratom","-destroy!","reagent.ratom/-destroy!",-337873850,null);dVa=new $APP.q(null,"-destroy!","-destroy!",143253949,null);eVa=new $APP.q("sci.configs.reagent.reagent","error","sci.configs.reagent.reagent/error",1433174531,null);wU=new $APP.F(null,"reagentRender","reagentRender",-358306383);fVa=new $APP.q("reagent.core","reactify-component","reagent.core/reactify-component",-385504376,null);gVa=new $APP.q(null,"cursor","cursor",-1642498285,null);
hVa=new $APP.q(null,"make-reaction","make-reaction",1935680112,null);iVa=new $APP.F(null,"contextType","contextType",1033066077);jVa=new $APP.q("reagent.core","dispose!","reagent.core/dispose!",239740642,null);kVa=new $APP.F(null,"component-did-update","component-did-update",-1468549173);lVa=new $APP.q(null,"src","src",-10544524,null);yU=new $APP.F(null,"displayName","displayName",-809144601);
mVa=new $APP.q("sci.configs.reagent.reagent","-generation","sci.configs.reagent.reagent/-generation",-1754580423,null);nVa=new $APP.F(null,"display-name","display-name",694513143);oVa=new $APP.q("sci.configs.reagent.reagent","reaction","sci.configs.reagent.reagent/reaction",-1324858361,null);pVa=new $APP.q(null,"others","others",-569561186,null);qVa=new $APP.F(null,"getDerivedStateFromProps","getDerivedStateFromProps",-991834739);pUa=new $APP.F(null,"parse-tag","parse-tag",1427313738);
rVa=new $APP.q("sci.configs.reagent.reagent","-ratom-generation","sci.configs.reagent.reagent/-ratom-generation",662254794,null);sVa=new $APP.q(null,"destroy","destroy",796871122,null);tVa=new $APP.F(null,"shouldComponentUpdate","shouldComponentUpdate",1795750960);uVa=new $APP.q("reagent.core","track!","reagent.core/track!",-954652078,null);vVa=new $APP.q("reagent.core","as-element","reagent.core/as-element",-1369748434,null);
wVa=new $APP.q(null,"-ratom-generation","-ratom-generation",-176468250,null);xVa=new $APP.q("reagent.core","create-class","reagent.core/create-class",-1100017147,null);JU=new $APP.q(null,"adapt-react-class","adapt-react-class",1221068673,null);yVa=new $APP.q("reagent.ratom","make-track","reagent.ratom/make-track",267038680,null);zVa=new $APP.q(null,"track","track",1836319014,null);AVa=new $APP.q(null,".hasOwnProperty",".hasOwnProperty",-1264659034,null);
BVa=new $APP.q("sci.configs.reagent.reagent","-tracking?","sci.configs.reagent.reagent/-tracking?",201600244,null);CVa=new $APP.q(null,"reagent.debug","reagent.debug",1010511129,null);DVa=new $APP.q(null,"reactify-component","reactify-component",-882526483,null);EVa=new $APP.q("js","console","js/console",-1426368245,null);KU=new $APP.q(null,"sci.configs.reagent.reagent","sci.configs.reagent.reagent",94604865,null);
FVa=new $APP.q("sci.configs.reagent.reagent","-destroy!","sci.configs.reagent.reagent/-destroy!",-561262631,null);GVa=new $APP.F(null,"no-cache","no-cache",1588056370);HVa=new $APP.q("cljs.core","zero?","cljs.core/zero?",-341242858,null);LU=new $APP.q(null,"track!","track!",-516308489,null);IVa=new $APP.q(null,".error",".error",1756007195,null);JVa=new $APP.q("reagent.debug","-tracking?","reagent.debug/-tracking?",409956583,null);oUa=new $APP.F(null,"function-components","function-components",1492814963);
KVa=new $APP.q("reagent.ratom","reactive?","reagent.ratom/reactive?",-358553475,null);LVa=new $APP.q(null,"as-element","as-element",-2139409597,null);MVa=new $APP.q(null,"make-track","make-track",-1388299455,null);NVa=new $APP.q("reagent.ratom","atom","reagent.ratom/atom",-391081187,null);OVa=new $APP.q("reagent.debug","track-console","reagent.debug/track-console",-1553126476,null);PVa=new $APP.q("reagent.core","create-element","reagent.core/create-element",-1888667366,null);
QVa=new $APP.q(null,"on-dispose","on-dispose",-549129409,null);RVa=new $APP.F(null,"component-will-unmount","component-will-unmount",-2058314698);SVa=new $APP.q("reagent.ratom","with-let-values","reagent.ratom/with-let-values",-575838306,null);TVa=new $APP.q(null,"-ratom-context","-ratom-context",1646839514,null);zTa=new $APP.F(null,"cljsLegacyRender","cljsLegacyRender",-1527295613);
UVa=new $APP.q("sci.configs.reagent.reagent","-set-ratom-generation!","sci.configs.reagent.reagent/-set-ratom-generation!",-35374248,null);VVa=new $APP.q("sci.configs.reagent.reagent","with-let","sci.configs.reagent.reagent/with-let",65759084,null);WVa=new $APP.q("reagent.core","class-names","reagent.core/class-names",-1902681251,null);XVa=new $APP.q(null,"class-names","class-names",-1397320704,null);FTa=new $APP.F(null,"getInitialState","getInitialState",1541760916);
YVa=new $APP.q("reagent.core","track","reagent.core/track",1263921785,null);ZVa=new $APP.F(null,"getDerivedStateFromError","getDerivedStateFromError",166658477);$Va=new $APP.q(null,"create-element","create-element",1833774591,null);var aWa=$APP.Aj.g(null),bWa=function(){var a={};a.warn=function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Ed(f,0,null)}return c.call(this,e)}function c(d){return $APP.Bj.l(aWa,$APP.Ll,new $APP.H(null,1,5,$APP.I,[$APP.dAa],null),$APP.vf,$APP.z([$APP.qg.h($APP.m,d)]))}b.B=0;b.G=function(d){d=$APP.r(d);return c(d)};b.l=c;return b}();a.error=function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=
Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Ed(f,0,null)}return c.call(this,e)}function c(d){return $APP.Bj.l(aWa,$APP.Ll,new $APP.H(null,1,5,$APP.I,[$APP.Kn],null),$APP.vf,$APP.z([$APP.qg.h($APP.m,d)]))}b.B=0;b.G=function(d){d=$APP.r(d);return c(d)};b.l=c;return b}();return a}();var cWa,SSa,DU;cWa="undefined"!==typeof window&&null!=window.document;$APP.zU=!1;SSa=new $APP.zi(null,new $APP.h(null,2,["aria",null,"data",null],null),null);DU=function DU(a){switch(arguments.length){case 0:return DU.D();case 1:return DU.g(arguments[0]);case 2:return DU.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return DU.l(arguments[0],arguments[1],2<c.length?new $APP.Ed(c.slice(2),0,null):null)}};DU.D=function(){return null};
DU.g=function(a){return $APP.we(a)?(a=$APP.sn.h(function(b){return $APP.k(b)?bU(b)?$APP.Fi(b):b:null},a),$APP.r(a)?$APP.mn.h(" ",a):null):bU(a)?$APP.Fi(a):a};DU.h=function(a,b){return $APP.k(a)?$APP.k(b)?[$APP.m.g(DU.g(a))," ",$APP.m.g(DU.g(b))].join(""):DU.g(a):DU.g(b)};DU.l=function(a,b,c){return $APP.af.j(DU,DU.h(a,b),c)};DU.G=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.l(b,a,c)};DU.B=2;var ETa=0,dWa=cWa?function(){var a=window;return function(){var b=a.requestAnimationFrame;if($APP.k(b))return b;b=a.webkitRequestAnimationFrame;if($APP.k(b))return b;b=a.mozRequestAnimationFrame;if($APP.k(b))return b;b=a.msRequestAnimationFrame;return $APP.k(b)?b:WSa}().bind(a)}():WSa;$APP.g=aTa.prototype;$APP.g.flush_after_render=function(){var a=this.Ih;if(null==a)return null;this.Ih=null;return ZSa(a)};$APP.g.queue_render=function(a){null==this.Xh&&(this.Xh=[]);return $Sa(this,this.Xh,a)};
$APP.g.schedule=function(){function a(){return b.run_queues()}var b=this;if(this.ri)return null;this.ri=!0;return dWa.g?dWa.g(a):dWa.call(null,a)};$APP.g.flush_before_flush=function(){var a=this.Kh;if(null==a)return null;this.Kh=null;return ZSa(a)};$APP.g.flush_queues=function(){this.flush_before_flush();YSa();this.flush_render();return this.flush_after_render()};$APP.g.run_queues=function(){this.ri=!1;return this.flush_queues()};
$APP.g.add_before_flush=function(a){null==this.Kh&&(this.Kh=[]);return $Sa(this,this.Kh,a)};$APP.g.add_after_render=function(a){null==this.Ih&&(this.Ih=[]);return $Sa(this,this.Ih,a)};$APP.g.flush_render=function(){var a=this.Xh;if(null==a)return null;this.Xh=null;a:{a.sort(XSa);for(var b=a.length,c=0;;)if(c<b){var d=a[c];!0===d.cljsIsDirty&&d.forceUpdate();c+=1}else break a}return null};var dU=new aTa;var hU;$APP.Aj.g(0);var rU=null;$APP.g=kU.prototype;$APP.g.V=function(a,b,c){return jU(b,c,"RAtom",new $APP.h(null,1,[$APP.hu,this.Ja(null)],null))};$APP.g.U=function(){return this.O};$APP.g.Y=function(){return $APP.la(this)};$APP.g.T=function(a,b){return this===b};$APP.g.fd=function(a,b){a=this.state;this.state=b;null!=this.lb&&iU(this,a,b);return b};$APP.g.Zg=function(a,b){return this.fd(null,b.g?b.g(this.state):b.call(null,this.state))};
$APP.g.$g=function(a,b,c){return this.fd(null,b.h?b.h(this.state,c):b.call(null,this.state,c))};$APP.g.ah=function(a,b,c,d){return this.fd(null,b.j?b.j(this.state,c,d):b.call(null,this.state,c,d))};$APP.g.bh=function(a,b,c,d,e){return this.fd(null,$APP.qg.P(b,this.state,c,d,e))};$APP.g.Dg=function(a,b){iU(this,a,b)};$APP.g.bg=function(a,b,c){return gTa(this,b,c)};$APP.g.cg=function(a,b){return hTa(this,b)};$APP.g.W=function(a,b){return new kU(this.state,b,this.tg,this.lb)};
$APP.g.Ja=function(){fTa(this);return this.state};var vU=function vU(a){switch(arguments.length){case 1:return vU.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return vU.l(arguments[0],1<c.length?new $APP.Ed(c.slice(1),0,null):null)}};vU.g=function(a){return new kU(a,null,null,null)};vU.l=function(a,b){var c=$APP.Yf(b);b=$APP.C.h(c,$APP.nb);c=$APP.C.h(c,$APP.ly);return new kU(a,b,c,null)};
vU.G=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};vU.B=1;nU.prototype.Ja=function(){var a=this,b=a.zh;return null==b?iTa(function(){return $APP.qg.h(a.f,a.Aa)},a.f,a.Aa,this,null):$APP.n(b)};nU.prototype.T=function(a,b){return b instanceof nU&&$APP.x.h(this.f,b.f)&&$APP.x.h(this.Aa,b.Aa)};nU.prototype.Y=function(){return $APP.yd(new $APP.H(null,2,5,$APP.I,[this.f,this.Aa],null))};
nU.prototype.V=function(a,b,c){return jU(b,c,"Track",new $APP.h(null,2,[$APP.hu,this.Ja(null),$APP.yL,this.f],null))};var MU=function MU(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return MU.l(arguments[0],1<c.length?new $APP.Ed(c.slice(1),0,null):null)};MU.l=function(a,b){return jTa(a,b)};MU.B=1;MU.G=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};$APP.g=kTa.prototype;
$APP.g._peek=function(){var a=hU;hU=null;try{return this.Ja(null)}finally{hU=a}};$APP.g._set_state=function(a,b){if(a===b)return null;this.state=b;return null!=this.lb?iU(this,a,b):null};$APP.g.V=function(a,b,c){return jU(b,c,"RCursor",new $APP.h(null,2,[$APP.hu,this.Ja(null),$APP.Nr,this.path],null))};$APP.g.Y=function(){return $APP.yd(new $APP.H(null,2,5,$APP.I,[this.jc,this.path],null))};$APP.g.T=function(a,b){return b instanceof kTa&&$APP.x.h(this.path,b.path)&&$APP.x.h(this.jc,b.jc)};
$APP.g.fd=function(a,b){this._set_state(this.state,b);(null!=this.jc?this.jc.J&32768||$APP.xd===this.jc.Zf||(this.jc.J?0:$APP.Ib($APP.rc,this.jc)):$APP.Ib($APP.rc,this.jc))?$APP.x.h(this.path,$APP.Sg)?$APP.vg(this.jc,b):$APP.Bj.F(this.jc,$APP.Jq,this.path,b):this.jc.h?this.jc.h(this.path,b):this.jc.call(null,this.path,b);return b};$APP.g.Zg=function(a,b){a=this.fd;var c=this._peek();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};
$APP.g.$g=function(a,b,c){a=this.fd;var d=this._peek();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.g.ah=function(a,b,c,d){a=this.fd;var e=this._peek();b=b.j?b.j(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};$APP.g.bh=function(a,b,c,d,e){return this.fd(null,$APP.qg.P(b,this._peek(),c,d,e))};$APP.g.Dg=function(a,b){iU(this,a,b)};$APP.g.bg=function(a,b,c){return gTa(this,b,c)};$APP.g.cg=function(a,b){return hTa(this,b)};
$APP.g.Ja=function(){var a=this,b=this,c=a.state,d=function(){var e=a.zh;return null==e?iTa((null!=a.jc?a.jc.J&32768||$APP.xd===a.jc.Zf||(a.jc.J?0:$APP.Ib($APP.rc,a.jc)):$APP.Ib($APP.rc,a.jc))?function(){return $APP.rp.h($APP.n(a.jc),a.path)}:function(){return a.jc.g?a.jc.g(a.path):a.jc.call(null,a.path)},a.jc,a.path,b,null):$APP.n(e)}();b._set_state(c,d);return d};$APP.g=oTa.prototype;$APP.g._peek_at=function(){var a=hU;hU=null;try{return this.Ja(null)}finally{hU=a}};
$APP.g._handle_change=function(a,b,c){return b===c||this.Mf?null:null==this.ef?(this.Mf=!0,null==rU&&(rU=[],!1===dU.ri&&dU.schedule()),rU.push(this)):!0===this.ef?this._run(!1):this.ef.g?this.ef.g(this):this.ef.call(null,this)};
$APP.g._update_watching=function(a){var b=$APP.Di(a),c=$APP.Di(this.vg);this.vg=a;a=$APP.r($APP.bx.h(b,c));for(var d=null,e=0,f=0;;)if(f<e){var l=d.ea(null,f);$APP.Qc(l,this,nTa);f+=1}else if(a=$APP.r(a))d=a,$APP.Ee(d)?(a=$APP.cd(d),f=$APP.dd(d),d=a,e=$APP.be(a),a=f):(a=$APP.v(d),$APP.Qc(a,this,nTa),a=$APP.w(d),d=null,e=0),f=0;else break;b=$APP.r($APP.bx.h(c,b));c=null;for(e=d=0;;)if(e<d)a=c.ea(null,e),$APP.Rc(a,this),e+=1;else if(b=$APP.r(b))c=b,$APP.Ee(c)?(b=$APP.cd(c),d=$APP.dd(c),c=b,a=$APP.be(b),
b=d,d=a):(a=$APP.v(c),$APP.Rc(a,this),b=$APP.w(c),c=null,d=0),e=0;else return null};$APP.g._queued_run=function(){return this.Mf&&null!=this.vg?this._run(!0):null};$APP.g._try_capture=function(a){try{return this.Ci=null,eTa(a,this)}catch(b){return this.Ci=this.state=a=b,this.Mf=!1}};$APP.g._run=function(a){var b=this.state;a=$APP.k(a)?this._try_capture(this.f):eTa(this.f,this);this.sk||(this.state=a,null==this.lb||$APP.x.h(b,a)||iU(this,b,a));return a};
$APP.g._set_opts=function(a){var b=$APP.Yf(a);a=$APP.C.h(b,pU);var c=$APP.C.h(b,aVa),d=$APP.C.h(b,mU);b=$APP.C.h(b,GVa);null!=a&&(this.ef=a);null!=c&&(this.Qm=c);null!=d&&(this.uk=d);return null!=b?this.sk=b:null};$APP.g.V=function(a,b,c){return jU(b,c,"Reaction",new $APP.h(null,1,[$APP.hu,this.Ja(null)],null))};$APP.g.Y=function(){return $APP.la(this)};$APP.g.T=function(a,b){return this===b};
$APP.g.vj=function(){var a=this.state,b=this.vg;this.ef=this.state=this.vg=null;this.Mf=!0;b=$APP.r($APP.Di(b));for(var c=null,d=0,e=0;;)if(e<d){var f=c.ea(null,e);$APP.Rc(f,this);e+=1}else if(b=$APP.r(b))c=b,$APP.Ee(c)?(b=$APP.cd(c),e=$APP.dd(c),c=b,d=$APP.be(b),b=e):(b=$APP.v(c),$APP.Rc(b,this),b=$APP.w(c),c=null,d=0),e=0;else break;null!=this.uk&&this.uk(a);a=this.no;if(null==a)return null;b=a.length;for(c=0;;)if(c<b)d=a[c],d.g?d.g(this):d.call(null,this),c+=1;else return null};
$APP.g.fd=function(a,b){a=this.state;this.state=b;this.Qm(a,b);iU(this,a,b);return b};$APP.g.Zg=function(a,b){a=this.fd;var c=this._peek_at();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};$APP.g.$g=function(a,b,c){a=this.fd;var d=this._peek_at();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.g.ah=function(a,b,c,d){a=this.fd;var e=this._peek_at();b=b.j?b.j(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};
$APP.g.bh=function(a,b,c,d,e){return this.fd(null,$APP.qg.P(b,this._peek_at(),c,d,e))};$APP.g.Dg=function(a,b){iU(this,a,b)};$APP.g.bg=function(a,b,c){return gTa(this,b,c)};$APP.g.cg=function(a,b){a=$APP.ve(this.lb);hTa(this,b);return!a&&$APP.ve(this.lb)&&null==this.ef?this.vj(null):null};
$APP.g.Ja=function(){var a=this.Ci;if(null!=a)throw a;(a=null==hU)&&($APP.sU.D?$APP.sU.D():$APP.sU.call(null));a&&null==this.ef?this.Mf&&(a=this.state,this.state=this.f.D?this.f.D():this.f.call(null),null==this.lb||$APP.x.h(a,this.state)||iU(this,a,this.state)):(fTa(this),this.Mf&&this._run(!1));return this.state};YSa=$APP.sU;var lU=function lU(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return lU.l(arguments[0],1<c.length?new $APP.Ed(c.slice(1),0,null):null)};
lU.l=function(a,b){var c=$APP.Yf(b);b=$APP.C.h(c,pU);var d=$APP.C.h(c,aVa);c=$APP.C.h(c,mU);a=new oTa(a);a._set_opts(new $APP.h(null,3,[pU,b,aVa,d,mU,c],null));return a};lU.B=1;lU.G=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};var qTa=lU(null);var uU,pTa=new $APP.h(null,1,[GVa,!0],null),CTa=new $APP.h(null,2,[tVa,null,JUa,null],null),xTa=function(a){var b=$APP.Aj.g($APP.Xf);return function(c){var d=$APP.C.h($APP.n(b),c);if(null!=d)return d;d=a.g?a.g(c):a.call(null,c);$APP.Bj.F(b,$APP.ui,c,d);return d}}(function(a){if("string"===typeof a)return a;a=$APP.Fi(a);a=$APP.$k(a,/(unsafe|UNSAFE)[-_]/,"UNSAFE_");a=$APP.fl.h(a,/-/);var b=$APP.r(a);a=$APP.v(b);b=$APP.w(b);return $APP.qg.j($APP.m,a,$APP.ej.h(RSa,b))}),GTa=new $APP.H(null,5,5,$APP.I,
[OUa,XUa,iVa,qVa,ZVa],null);var QTa=new $APP.zi(null,new $APP.h(null,6,["url",null,"tel",null,"text",null,"textarea",null,"password",null,"search",null],null),null),jUa=new $APP.h(null,4,[nVa,"ReagentInput",kVa,BU,RVa,function(a){return a.Ti=null},ITa,function(a,b,c,d,e){TTa(c);return gU(e,a,b,c,d)}],null);var gUa=/([^\s\.#]+)(?:#([^\s\.#]+))?(?:\.([^\s#]+))?/,WTa={"class":"className","for":"htmlFor",charset:"charSet"},YTa={},fUa={};$APP.g=nUa.prototype;$APP.g.W=function(a,b){return new nUa(this.Ed,this.id,this.hk,this.ki,b)};$APP.g.U=function(){return this.Im};$APP.g.Ym=function(){return this.id};$APP.g.Zk=function(a,b,c){return this.ki.j?this.ki.j(this,b,c):this.ki.call(null,this,b,c)};
$APP.g.Xk=function(a,b){return"object"!==$APP.fa(b)?b:$APP.De(b)?mUa(b,this,this.hk):$APP.Je(b)?lUa(b,this):bU(b)?$APP.Fi(b):(null!=b?b.J&2147483648||$APP.xd===b.Ka||(b.J?0:$APP.Ib($APP.Mc,b)):$APP.Ib($APP.Mc,b))?$APP.yj.l($APP.z([b])):b};$APP.g.Yk=function(a,b,c,d,e){return aUa(this,b,c,d,e)};$APP.NU=qUa($APP.Xf);var OU=function OU(a){switch(arguments.length){case 1:return OU.g(arguments[0]);case 2:return OU.h(arguments[0],arguments[1]);case 3:return OU.j(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return OU.l(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.Ed(c.slice(3),0,null):null)}};OU.g=function(a){return OU.h(a,null)};OU.h=function(a,b){return $APP.Iu.nbb$internal$react.createElement(a,b)};
OU.j=function(a,b,c){return $APP.Iu.nbb$internal$react.createElement(a,b,c)};OU.l=function(a,b,c,d){return $APP.qg.P($APP.Iu.nbb$internal$react.createElement,a,b,c,d)};OU.G=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);var d=$APP.w(c);c=$APP.v(d);d=$APP.w(d);return this.l(b,a,c,d)};OU.B=3;var PU=function PU(a){switch(arguments.length){case 1:return PU.g(arguments[0]);case 2:return PU.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};
PU.g=function(a){return $APP.fU($APP.NU,a)};PU.h=function(a,b){return $APP.fU(b,a)};PU.B=2;var QU=function QU(a){switch(arguments.length){case 1:return QU.g(arguments[0]);case 2:return QU.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};QU.g=function(a){return QU.h(a,$APP.NU)};QU.h=function(a,b){return tTa(a)?a:JTa(a,b)};QU.B=2;
var RU=function RU(a){switch(arguments.length){case 1:return RU.g(arguments[0]);case 2:return RU.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};RU.g=function(a){return AU(a,$APP.NU)};RU.h=function(a,b){return AU(a,b)};RU.B=2;
var SU=function SU(a){switch(arguments.length){case 0:return SU.D();case 1:return SU.g(arguments[0]);case 2:return SU.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return SU.l(arguments[0],arguments[1],2<c.length?new $APP.Ed(c.slice(2),0,null):null)}};SU.D=function(){return null};SU.g=function(a){return DU.g(a)};SU.h=function(a,b){return DU.h(a,b)};SU.l=function(a,b,c){return $APP.qg.F(DU,a,b,c)};
SU.G=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.l(b,a,c)};SU.B=2;var TU=function TU(a){switch(arguments.length){case 1:return TU.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return TU.l(arguments[0],1<c.length?new $APP.Ed(c.slice(1),0,null):null)}};TU.g=function(a){return vU.g(a)};TU.l=function(a,b){return $APP.qg.j(vU,a,b)};TU.G=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};TU.B=1;
var UU=function UU(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return UU.l(arguments[0],1<c.length?new $APP.Ed(c.slice(1),0,null):null)};UU.l=function(a,b){return oU(a,b)};UU.B=1;UU.G=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};var VU=function VU(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return VU.l(arguments[0],1<c.length?new $APP.Ed(c.slice(1),0,null):null)};VU.l=function(a,b){return jTa(a,b)};
VU.B=1;VU.G=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};var WU=function WU(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return WU.l(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.Ed(c.slice(3),0,null):null)};
WU.l=function(a,b,c,d){var e=$APP.$n.g("with-let");a=$APP.fj.g(e);var f=$APP.$n.g("init");c=$APP.Eh.h(new $APP.H(null,2,5,$APP.I,[f,$APP.R.g($APP.r($APP.K.h(new $APP.D(null,HVa,null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.h(new $APP.D(null,$APP.sxa,null,1,null),new $APP.D(null,e,null,1,null)))),null,1,null))))],null),$APP.xu.h(function(u,t){if($APP.pg(u))return t;u=$APP.kf(u,2);return $APP.R.g($APP.r($APP.K.l(new $APP.D(null,$APP.rk,null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.l(new $APP.D(null,
$APP.QI,null,1,null),new $APP.D(null,f,null,1,null),$APP.z([new $APP.D(null,$APP.R.g($APP.r($APP.K.h(new $APP.D(null,$APP.WK,null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.l(new $APP.D(null,AVa,null,1,null),new $APP.D(null,e,null,1,null),$APP.z([new $APP.D(null,u,null,1,null)])))),null,1,null)))),null,1,null)])))),null,1,null),$APP.z([new $APP.D(null,$APP.R.g($APP.r($APP.K.l(new $APP.D(null,$APP.Qwa,null,1,null),new $APP.D(null,e,null,1,null),$APP.z([new $APP.D(null,u,null,1,null),new $APP.D(null,
t,null,1,null)])))),null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.l(new $APP.D(null,$APP.dna,null,1,null),new $APP.D(null,e,null,1,null),$APP.z([new $APP.D(null,u,null,1,null)])))),null,1,null)]))))},c));var l=function(){var u=$APP.me(d);return $APP.Je(u)&&$APP.x.h($APP.ok,$APP.v(u))?new $APP.H(null,2,5,$APP.I,[$APP.Ei(d),$APP.R.g($APP.r($APP.K.l(new $APP.D(null,$APP.dv,null,1,null),new $APP.D(null,$APP.cf($APP.R.g($APP.r($APP.K.D()))),null,1,null),$APP.z([$APP.Id(u)]))))],null):new $APP.H(null,
2,5,$APP.I,[d,null],null)}();b=$APP.y.j(l,0,null);l=$APP.y.j(l,1,null);l=$APP.k(l)?new $APP.D(null,$APP.R.g($APP.r($APP.K.l(new $APP.D(null,$APP.Pq,null,1,null),new $APP.D(null,$APP.cf($APP.R.g($APP.r($APP.K.h(new $APP.D(null,ZUa,null,1,null),new $APP.D(null,l,null,1,null))))),null,1,null),$APP.z([new $APP.D(null,$APP.R.g($APP.r($APP.K.l(new $APP.D(null,$APP.rk,null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.g(new $APP.D(null,KVa,null,1,null)))),null,1,null),$APP.z([new $APP.D(null,$APP.R.g($APP.r($APP.K.l(new $APP.D(null,
$APP.Xz,null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.h(new $APP.D(null,$APP.IH,null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.h(new $APP.D(null,HUa,null,1,null),new $APP.D(null,e,null,1,null)))),null,1,null)))),null,1,null),$APP.z([new $APP.D(null,$APP.R.g($APP.r($APP.K.l(new $APP.D(null,cVa,null,1,null),new $APP.D(null,e,null,1,null),$APP.z([new $APP.D(null,ZUa,null,1,null)])))),null,1,null)])))),null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.g(new $APP.D(null,ZUa,null,1,null)))),
null,1,null)])))),null,1,null)])))),null,1,null):null;var p=$APP.$n.g("res");return $APP.R.g($APP.r($APP.K.l(new $APP.D(null,$APP.Pq,null,1,null),new $APP.D(null,$APP.cf($APP.R.g($APP.r($APP.K.h(new $APP.D(null,e,null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.h(new $APP.D(null,SVa,null,1,null),new $APP.D(null,a,null,1,null)))),null,1,null))))),null,1,null),$APP.z([new $APP.D(null,null,null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.l(new $APP.D(null,$APP.Pq,null,1,null),new $APP.D(null,$APP.Eh.h(c,
new $APP.H(null,2,5,$APP.I,[p,$APP.R.g($APP.r($APP.K.h(new $APP.D(null,$APP.qk,null,1,null),b)))],null)),null,1,null),$APP.z([l,new $APP.D(null,p,null,1,null)])))),null,1,null)]))))};WU.B=3;WU.G=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);var d=$APP.w(c);c=$APP.v(d);d=$APP.w(d);return this.l(b,a,c,d)};var XU=function XU(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return XU.l(0<c.length?new $APP.Ed(c.slice(0),0,null):null)};
XU.l=function(a){return $APP.R.g($APP.r($APP.K.h(new $APP.D(null,FUa,null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.l(new $APP.D(null,$APP.dv,null,1,null),new $APP.D(null,$APP.cf($APP.R.g($APP.r($APP.K.D()))),null,1,null),$APP.z([a])))),null,1,null))))};XU.B=0;XU.G=function(a){return this.l($APP.r(a))};
var YU=$APP.EO.h($APP.pI,null),eWa=$APP.gi([NUa,zVa,LUa,$APP.Pz,XVa,$Ua,LVa,DVa,$Va,GUa,gVa,LU,YUa,JU],[function(){var a=new $APP.Cd(function(){return RU},xVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.pI,NUa,"reagent/core.cljs",19,new $APP.h(null,6,[$APP.BA,!1,$APP.Os,2,$APP.cL,2,$APP.LK,new $APP.H(null,2,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.kz],null),new $APP.H(null,2,5,$APP.I,[$APP.kz,$APP.IU],null)],null),$APP.V,$APP.J(new $APP.H(null,
1,5,$APP.I,[$APP.kz],null),new $APP.H(null,2,5,$APP.I,[$APP.kz,$APP.IU],null)),$APP.gG,$APP.J(null,null)],null),1,68,68,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.kz],null),new $APP.H(null,2,5,$APP.I,[$APP.kz,$APP.IU],null)),"Creates JS class based on provided Clojure map, for example:\n\n  ```cljs\n  {;; Constructor\n   :constructor (fn [this props])\n   :get-initial-state (fn [this])\n   ;; Static methods\n   :get-derived-state-from-props (fn [props state] partial-state)\n   :get-derived-state-from-error (fn [error] partial-state)\n   ;; Methods\n   :get-snapshot-before-update (fn [this old-argv new-argv] snapshot)\n   :should-component-update (fn [this old-argv new-argv])\n   :component-did-mount (fn [this])\n   :component-did-update (fn [this old-argv old-state snapshot])\n   :component-will-unmount (fn [this])\n   :component-did-catch (fn [this error info])\n   :reagent-render (fn [args....])\n   ;; Or alternatively:\n   :render (fn [this])\n   ;; Deprecated methods:\n   :UNSAFE_component-will-receive-props (fn [this new-argv])\n   :UNSAFE_component-will-update (fn [this new-argv new-state])\n   :UNSAFE_component-will-mount (fn [this])}\n  ```\n\n  Everything is optional, except either :reagent-render or :render.\n\n  Map keys should use `React.Component` method names (https://reactjs.org/docs/react-component.html),\n  and can be provided in snake-case or camelCase.\n\n  State can be initialized using constructor, which matches React.Component class,\n  or using getInitialState which matches old React createClass function and is\n  now implemented by Reagent for compatibility.\n\n  State can usually be anything, e.g. Cljs object. But if using getDerivedState\n  methods, the state has to be plain JS object as React implementation uses\n  Object.assign to merge partial state into the current state.\n\n  React built-in static methods or properties are automatically defined as statics.",
$APP.k(RU)?RU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return UU},YVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.pI,zVa,"reagent/core.cljs",
12,new $APP.h(null,6,[$APP.BA,!0,$APP.Os,1,$APP.cL,1,$APP.LK,new $APP.H(null,1,5,$APP.I,[$APP.J($APP.hJ,$APP.JD)],null),$APP.V,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.hJ,$APP.lk,$APP.JD],null)),$APP.gG,$APP.J(null)],null),1,218,218,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.hJ,$APP.lk,$APP.JD],null)),"Takes a function and optional arguments, and returns a derefable\n  containing the output of that function. If the function derefs\n  Reagent atoms (or track, etc), the value will be updated whenever\n  the atom changes.\n\n  In other words, `@(track foo bar)` will produce the same result\n  as `(foo bar)`, but foo will only be called again when the atoms it\n  depends on changes, and will only trigger updates of components when\n  its result changes.\n\n  track is lazy, i.e the function is only evaluated on deref.",
$APP.k(UU)?UU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return WU},VVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.mq,$APP.YL,$APP.V,$APP.M,$APP.oG],[KU,LUa,"sci/configs/reagent/reagent.cljs",
23,new $APP.h(null,6,[$APP.BA,!0,$APP.Os,1,$APP.cL,1,$APP.LK,$APP.J($APP.J($APP.Dz,$APP.WB)),$APP.V,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.Dz,$APP.lk,$APP.WB],null)),$APP.gG,$APP.J(null)],null),1,10,!0,10,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.Dz,$APP.lk,$APP.WB],null)),null,$APP.k(WU)?WU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=
$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return TU},PUa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.pI,$APP.Pz,"reagent/core.cljs",11,new $APP.h(null,6,[$APP.BA,!0,$APP.Os,1,$APP.cL,1,$APP.LK,new $APP.H(null,1,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.AJ],null)],null),$APP.V,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.AJ],null),new $APP.H(null,3,5,$APP.I,[$APP.AJ,
$APP.lk,$APP.aB],null)),$APP.gG,$APP.J(null,null)],null),1,211,211,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.AJ],null),new $APP.H(null,3,5,$APP.I,[$APP.AJ,$APP.lk,$APP.aB],null)),"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.k(TU)?TU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?
$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return SU},WVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.pI,XVa,"reagent/core.cljs",18,new $APP.h(null,6,[$APP.BA,!0,$APP.Os,2,$APP.cL,2,$APP.LK,new $APP.H(null,3,5,$APP.I,[$APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.zE],null),new $APP.H(null,2,5,$APP.I,[GU,FU],null)],null),$APP.V,
$APP.J($APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.zE],null),new $APP.H(null,2,5,$APP.I,[GU,FU],null),new $APP.H(null,4,5,$APP.I,[GU,FU,$APP.lk,pVa],null)),$APP.gG,$APP.J(null,null,null,null)],null),1,179,179,$APP.J($APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.zE],null),new $APP.H(null,2,5,$APP.I,[GU,FU],null),new $APP.H(null,4,5,$APP.I,[GU,FU,$APP.lk,pVa],null)),"Function which normalizes and combines class values to a string\n\n  Reagent allows classes to be defined as:\n  - Strings\n  - Named objects (Symbols or Keywords)\n  - Collections of previous types",
$APP.k(SU)?SU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return XU},oVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.mq,$APP.YL,$APP.V,$APP.M,$APP.oG],[KU,$Ua,"sci/configs/reagent/reagent.cljs",
23,new $APP.h(null,6,[$APP.BA,!0,$APP.Os,-2,$APP.cL,-2,$APP.LK,$APP.J($APP.Hd),$APP.V,$APP.J($APP.Sg),$APP.gG,$APP.J(null)],null),1,62,!0,62,$APP.J($APP.Sg),null,$APP.k(XU)?XU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=
new $APP.Cd(function(){return PU},vVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.pI,LVa,"reagent/core.cljs",17,new $APP.h(null,6,[$APP.BA,!1,$APP.Os,2,$APP.cL,2,$APP.LK,new $APP.H(null,2,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.OI],null),new $APP.H(null,2,5,$APP.I,[$APP.OI,$APP.IU],null)],null),$APP.V,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.OI],null),new $APP.H(null,2,5,$APP.I,[$APP.OI,$APP.IU],null)),$APP.gG,$APP.J(null,null)],null),1,46,
46,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.OI],null),new $APP.H(null,2,5,$APP.I,[$APP.OI,$APP.IU],null)),"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.k(PU)?PU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,
b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return QU},fVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.pI,DVa,"reagent/core.cljs",25,new $APP.h(null,6,[$APP.BA,!1,$APP.Os,2,$APP.cL,2,$APP.LK,new $APP.H(null,2,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.gJ],null),new $APP.H(null,2,5,$APP.I,[$APP.gJ,$APP.IU],null)],null),$APP.V,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.gJ],null),new $APP.H(null,2,5,$APP.I,[$APP.gJ,$APP.IU],null)),
$APP.gG,$APP.J(null,null)],null),1,59,59,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.gJ],null),new $APP.H(null,2,5,$APP.I,[$APP.gJ,$APP.IU],null)),"Returns an adapter for a Reagent component, that may be used from\n  React, for example in JSX. A single argument, props, is passed to\n  the component, converted to a map.",$APP.k(QU)?QU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?
$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return OU},PVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.pI,$Va,"reagent/core.cljs",21,new $APP.h(null,6,[$APP.BA,!0,$APP.Os,3,$APP.cL,3,$APP.LK,new $APP.H(null,3,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.kF],null),new $APP.H(null,2,5,$APP.I,[$APP.kF,HU],null),new $APP.H(null,
3,5,$APP.I,[$APP.kF,HU,$APP.YI],null)],null),$APP.V,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.kF],null),new $APP.H(null,2,5,$APP.I,[$APP.kF,HU],null),new $APP.H(null,3,5,$APP.I,[$APP.kF,HU,$APP.YI],null),new $APP.H(null,5,5,$APP.I,[$APP.kF,HU,$APP.YI,$APP.lk,$APP.BH],null)),$APP.gG,$APP.J(null,null,null,null)],null),1,17,17,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.kF],null),new $APP.H(null,2,5,$APP.I,[$APP.kF,HU],null),new $APP.H(null,3,5,$APP.I,[$APP.kF,HU,$APP.YI],null),new $APP.H(null,5,5,$APP.I,
[$APP.kF,HU,$APP.YI,$APP.lk,$APP.BH],null)),'Create a native React element, by calling React.createElement directly.\n\n  That means the second argument must be a javascript object (or nil), and\n  that any Reagent hiccup forms must be processed with as-element. For example\n  like this:\n\n  ```cljs\n  (r/create-element "div" #js{:className "foo"}\n    "Hi " (r/as-element [:strong "world!"])\n  ```\n\n  which is equivalent to\n\n  ```cljs\n  [:div.foo "Hi" [:strong "world!"]]\n  ```',$APP.k(OU)?
OU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return rUa},jVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.pI,GUa,"reagent/core.cljs",15,1,242,242,
$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.AJ],null)),"Stop the result of track! from updating.",$APP.k(rUa)?rUa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return sUa},QUa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,
$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.pI,gVa,"reagent/core.cljs",13,1,272,272,$APP.J(new $APP.H(null,2,5,$APP.I,[lVa,$APP.FBa],null)),"Provide a cursor into a Reagent atom.\n\n  Behaves like a Reagent atom but focuses updates and derefs to\n  the specified path within the wrapped Reagent atom. e.g.,\n\n  ```cljs\n  (let [c (cursor ra [:nested :content])]\n    ... @c ;; equivalent to (get-in @ra [:nested :content])\n    ... (reset! c 42) ;; equivalent to (swap! ra assoc-in [:nested :content] 42)\n    ... (swap! c inc) ;; equivalence to (swap! ra update-in [:nested :content] inc)\n    )\n  ```\n\n  The first parameter can also be a function, that should look\n  something like this:\n\n  ```cljs\n  (defn set-get\n    ([k] (get-in @state k))\n    ([k v] (swap! state assoc-in k v)))\n  ```\n\n  The function will be called with one argument – the path passed to\n  cursor – when the cursor is deref'ed, and two arguments (path and\n  new value) when the cursor is modified.\n\n  Given that set-get function, (and that state is a Reagent atom, or\n  another cursor) these cursors are equivalent:\n  `(cursor state [:foo])` and `(cursor set-get [:foo])`.\n\n  Note that a cursor is lazy: its value will not change until it is\n  used. This may be noticed with add-watch.",
$APP.k(sUa)?sUa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return VU},uVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.pI,LU,"reagent/core.cljs",
13,new $APP.h(null,6,[$APP.BA,!0,$APP.Os,1,$APP.cL,1,$APP.LK,new $APP.H(null,1,5,$APP.I,[$APP.J($APP.hJ,$APP.JD)],null),$APP.V,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.hJ,$APP.lk,$APP.JD],null)),$APP.gG,$APP.J(null)],null),1,234,234,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.hJ,$APP.lk,$APP.JD],null)),"An eager version of track. The function passed is called\n  immediately, and continues to be called when needed, until stopped\n  with dispose!.",$APP.k(VU)?VU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?
null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return tUa},IUa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.pI,YUa,"reagent/core.cljs",22,1,353,353,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.DH],null)),"Creates Compiler object with given `opts`,\n  this can be passed to `render`, `as-element` and other functions to control\n  how they turn the Reagent-style Hiccup into React components and elements.",
$APP.k(tUa)?tUa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return EU},EUa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.pI,JU,"reagent/core.cljs",24,
1,52,52,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.gJ],null)),"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.k(EU)?EU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,
b,d)}()]),ZU=$APP.EO.h($APP.XK,null),fWa=$APP.gi([MUa,$APP.Pz,MVa,VUa,SUa,bVa,dVa,hVa,TVa,BUa,LU,wVa],[function(){var a=new $APP.Cd(function(){return mTa},SVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.XK,MUa,"reagent/ratom.cljs",22,1,329,329,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.$H],null)),null,$APP.k(mTa)?mTa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,ZU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,
$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return vU},NVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.XK,$APP.Pz,"reagent/ratom.cljs",11,new $APP.h(null,6,[$APP.BA,!0,$APP.Os,1,$APP.cL,1,$APP.LK,new $APP.H(null,1,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.AJ],null)],null),$APP.V,
$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.AJ],null),new $APP.H(null,3,5,$APP.I,[$APP.AJ,$APP.lk,new $APP.h(null,1,[$APP.UB,new $APP.H(null,2,5,$APP.I,[$APP.uA,$APP.bya],null)],null)],null)),$APP.gG,$APP.J(null,null)],null),1,172,172,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.AJ],null),new $APP.H(null,3,5,$APP.I,[$APP.AJ,$APP.lk,new $APP.h(null,1,[$APP.UB,new $APP.H(null,2,5,$APP.I,[$APP.uA,$APP.bya],null)],null)],null)),"Like clojure.core/atom, except that it keeps track of derefs.",$APP.k(vU)?vU.H:null])),
b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return oU},yVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.XK,MVa,"reagent/ratom.cljs",17,1,228,228,$APP.J(new $APP.H(null,
2,5,$APP.I,[$APP.hJ,$APP.JD],null)),null,$APP.k(oU)?oU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return zUa},UUa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],
[KU,VUa,"sci/configs/reagent/reagent.cljs",15,1,106,106,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.re($APP.yJ,new $APP.h(null,1,[$APP.Em,$APP.XC],null))],null)),null,$APP.k(zUa)?zUa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,ZU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=
new $APP.Cd(function(){return xUa},UVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[KU,SUa,"sci/configs/reagent/reagent.cljs",29,1,98,98,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.re($APP.yJ,new $APP.h(null,1,[$APP.Em,$APP.XC],null)),$APP.re($APP.gJ,new $APP.h(null,1,[$APP.Em,$APP.XC],null))],null)),null,$APP.k(xUa)?xUa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,ZU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],
null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return dTa},KVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.Em,$APP.V,$APP.M,$APP.oG],[$APP.XK,bVa,"reagent/ratom.cljs",25,1,17,17,$APP.qI,$APP.J($APP.Sg),null,dTa?dTa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,ZU,$APP.N,
a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return yUa},FVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[KU,dVa,"sci/configs/reagent/reagent.cljs",16,1,102,102,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.re($APP.yJ,new $APP.h(null,1,[$APP.Em,$APP.XC],null)),sVa],null)),
null,$APP.k(yUa)?yUa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,ZU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return lU},FUa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.XK,hVa,"reagent/ratom.cljs",
20,new $APP.h(null,6,[$APP.BA,!0,$APP.Os,1,$APP.cL,1,$APP.LK,new $APP.H(null,1,5,$APP.I,[$APP.J($APP.hJ,new $APP.h(null,1,[$APP.UB,new $APP.H(null,3,5,$APP.I,[RUa,DUa,QVa],null)],null))],null),$APP.V,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.hJ,$APP.lk,new $APP.h(null,1,[$APP.UB,new $APP.H(null,3,5,$APP.I,[RUa,DUa,QVa],null)],null)],null)),$APP.gG,$APP.J(null)],null),1,517,517,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.hJ,$APP.lk,new $APP.h(null,1,[$APP.UB,new $APP.H(null,3,5,$APP.I,[RUa,DUa,QVa],null)],
null)],null)),null,$APP.k(lU)?lU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return uUa},TUa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[KU,TVa,"sci/configs/reagent/reagent.cljs",
21,1,85,85,$APP.J($APP.Sg),"Read-only access to the ratom context.",$APP.k(uUa)?uUa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,ZU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return vUa},mVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,
$APP.YL,$APP.V,$APP.M,$APP.oG],[KU,BUa,"sci/configs/reagent/reagent.cljs",18,1,90,90,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.re($APP.AJ,new $APP.h(null,1,[$APP.Em,$APP.XC],null))],null)),null,$APP.k(vUa)?vUa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,ZU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,
b,d)}(),function(){var a=new $APP.Cd(function(){return MU},CUa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.XK,LU,"reagent/ratom.cljs",13,new $APP.h(null,6,[$APP.BA,!0,$APP.Os,1,$APP.cL,1,$APP.LK,new $APP.H(null,1,5,$APP.I,[$APP.J($APP.hJ,$APP.JD)],null),$APP.V,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.hJ,$APP.lk,$APP.JD],null)),$APP.gG,$APP.J(null)],null),1,242,242,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.hJ,$APP.lk,$APP.JD],null)),null,$APP.k(MU)?
MU.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,YU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return wUa},rVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[KU,wVa,"sci/configs/reagent/reagent.cljs",24,
1,94,94,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.re($APP.AJ,new $APP.h(null,1,[$APP.Em,$APP.XC],null))],null)),null,$APP.k(wUa)?wUa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,ZU,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}()]),gWa=$APP.EO.h(CVa,null),$U=function $U(a){for(var c=[],d=
arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return $U.l(arguments[0],arguments[1],2<c.length?new $APP.Ed(c.slice(2),0,null):null)};
$U.l=function(a,b,c){return $APP.k(!0)?$APP.R.g($APP.r($APP.K.l(new $APP.D(null,$APP.Xz,null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.h(new $APP.D(null,$APP.FF,null,1,null),new $APP.D(null,EVa,null,1,null)))),null,1,null),$APP.z([new $APP.D(null,$APP.R.g($APP.r($APP.K.l(new $APP.D(null,IVa,null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.l(new $APP.D(null,$APP.rk,null,1,null),new $APP.D(null,$APP.R.g($APP.r($APP.K.g(new $APP.D(null,JVa,null,1,null)))),null,1,null),$APP.z([new $APP.D(null,
OVa,null,1,null),new $APP.D(null,EVa,null,1,null)])))),null,1,null),$APP.z([new $APP.D(null,$APP.R.g($APP.r($APP.K.h(new $APP.D(null,$APP.Zu,null,1,null),c))),null,1,null)])))),null,1,null)])))):null};$U.B=2;$U.G=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.l(b,a,c)};
var hWa=new $APP.h(null,3,[$APP.OH,function(){var a=new $APP.Cd(function(){return $U},eVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.mq,$APP.YL,$APP.V,$APP.M,$APP.oG],[KU,$APP.OH,"sci/configs/reagent/reagent.cljs",20,new $APP.h(null,6,[$APP.BA,!0,$APP.Os,0,$APP.cL,0,$APP.LK,$APP.J($APP.J($APP.jH)),$APP.V,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.lk,$APP.jH],null)),$APP.gG,$APP.J(null)],null),1,132,!0,132,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.lk,$APP.jH],null)),"Print with console.error.",
$APP.k($U)?$U.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,gWa,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),KUa,function(){var a=new $APP.Cd(function(){return AUa},BVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[KU,KUa,"sci/configs/reagent/reagent.cljs",
17,1,129,129,$APP.J($APP.Sg),null,$APP.k(AUa)?AUa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,gWa,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),WUa,function(){var a=new $APP.Cd(function(){return bWa},OVa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],
[CVa,WUa,"reagent/debug.cljs",23,1,10,10,$APP.Hd,null,$APP.k(bWa)?bWa.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,gWa,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}()],null);$APP.Wu(new $APP.h(null,1,[$APP.Iq,new $APP.h(null,3,[$APP.pI,$APP.ui.j(eWa,JU,function(){var a=$APP.EO.g($APP.pI),b=new $APP.Cd(function(){return EU},EUa,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.pI,JU,"reagent/core.cljs",24,1,52,52,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.gJ],null)),"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.k(EU)?EU.H:null])),c=$APP.n(b),
d=$APP.se(b);b=$APP.k(null)?null:$APP.N.g(d);a=new $APP.h(null,4,[$APP.Q,a,$APP.N,b,$APP.V,$APP.V.g(d),$APP.M,$APP.M.g(d)],null);return $APP.k($APP.Sq.g(d))?$APP.yO.j(b,c,a):$APP.k(function(){var e=$APP.mq.g(d);return $APP.k(e)?e:$APP.zq.g(d)}())?$APP.zO.j(b,c,a):$APP.gu.j(b,c,a)}()),$APP.XK,fWa,CVa,hWa],null)],null));