import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var gOa,iOa,jOa,SX,TX,kOa,lOa,mOa,nOa,oOa,pOa,qOa,rOa,VX,sOa,XX,tOa,uOa,vOa,wOa,xOa,ZX,$X,aY,yOa,dY,eY,zOa,AOa,BOa,COa,gY,DOa,EOa,HOa,jY,IOa,JOa,KOa,LOa,MOa,OOa,QOa,ROa,TOa,qY,XOa,ZOa,$Oa,aPa,bPa,cPa,dPa,gPa,rY,hPa,iPa,jPa,kPa,mPa,sY,oPa,pPa,qPa,rPa,sPa,tPa,uPa,xPa,APa,BPa,CPa,DPa,GPa,uY,HPa,IPa,JPa,KPa,LPa,MPa,NPa,OPa,PPa,QPa,RPa,SPa,nY,TPa,UPa,VPa,WPa,XPa,YPa,ZPa,yPa,$Pa,aQa,bQa,cQa,dQa,eQa,vY,wY,fQa,gQa,hQa,iQa,jQa,kQa,lQa,fY,mQa,YOa,nQa,oQa,xY,pQa,qQa,ePa,rQa,cY,sQa,tQa,uQa,mY,vQa,wQa,xQa,yQa,
zQa,AQa,BQa,oY,CQa,DQa,EQa,FQa,GQa,FPa,HQa,IQa,JQa,KQa,LQa,MQa,NQa,zY,OQa,PQa,QQa,RQa,SQa,TQa,UQa,AY,VQa,WQa,XQa,BY,YQa,ZQa,EPa,$Qa,aRa,bRa,cRa,dRa,eRa,fRa,gRa,hRa,iRa,POa,jRa,kRa,lRa,mRa,VOa,nRa,oRa,pRa;gOa=function(a){return 2>$APP.ce(a)?$APP.dl(a):[$APP.dl($APP.Zi.j(a,0,1)),$APP.Zi.h(a,1)].join("")};
iOa=function(a){if("string"===typeof a)return a;a=$APP.Hi(a);var b=$APP.hl.h(a,/-/),c=$APP.u(b);b=$APP.v(c);c=$APP.w(c);return $APP.l(hOa.g?hOa.g(b):hOa.call(null,b))?a:$APP.sg.j($APP.m,b,$APP.fj.h(gOa,c))};
jOa=function(a){var b=function(){var c=function(){var d=$APP.qe(a);if(d){d=a.displayName;if($APP.l(d))return d;d=a.name;return"string"===typeof d&&$APP.u(d)?d:null}return d}();if($APP.l(c))return c;c=function(){var d=null!=a?a.K&4096||$APP.xd===a.Ag?!0:!1:!1;return d?$APP.Hi(a):d}();if($APP.l(c))return c;c=$APP.te(a);return $APP.Ce(c)?$APP.O.g(c):null}();return $APP.l(b)?$APP.bl($APP.m.g(b),"$","."):null};SX=function(a){return a instanceof $APP.G||a instanceof $APP.r};
TX=function(a){if($APP.Ce(a))try{var b=$APP.C.h(a,$APP.RE)}catch(c){b=null}else b=null;return b};kOa=function(a){var b=$APP.RE.g($APP.te(a));if($APP.l(b))return b;b=TX($APP.A.j(a,1,null));if($APP.l(b))return b;b=$APP.A.j(a,0,null);switch(b instanceof $APP.G?b.S:null){case "\x3e":case "f\x3e":return TX($APP.A.j(a,2,null));case "r\x3e":return a=$APP.A.j(a,2,null),null==a?null:a.key;default:return null}};lOa=function(a){return setTimeout(a,16)};mOa=function(a,b){return a.xi-b.xi};nOa=function(){return null};
oOa=function(a){for(var b=a.length,c=0;;)if(c<b){var d=a[c];d.C?d.C():d.call(null);c+=1}else return null};pOa=function(a,b,c){b.push(c);return a.schedule()};qOa=function(){this.Vh=!1};rOa=function(a){if($APP.l(a.cljsIsDirty))return null;a.cljsIsDirty=!0;return UX.queue_render(a)};VX=function(a){if(null!=a&&null!=a.zm)a=a.id;else{var b=VX[$APP.fa(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=VX._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.Lb("Compiler.get-id",a);}return a};
sOa=function(a,b,c){if(null!=a&&null!=a.Ak)a=a.Ak(a,b,c);else{var d=sOa[$APP.fa(null==a?null:a)];if(null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else if(d=sOa._,null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else throw $APP.Lb("Compiler.parse-tag",a);}return a};
$APP.WX=function(a,b){if(null!=a&&null!=a.yk)a=a.yk(a,b);else{var c=$APP.WX[$APP.fa(null==a?null:a)];if(null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else if(c=$APP.WX._,null!=c)a=c.h?c.h(a,b):c.call(null,a,b);else throw $APP.Lb("Compiler.as-element",a);}return a};
XX=function(a,b,c,d,e){if(null!=a&&null!=a.zk)a=a.zk(a,b,c,d,e);else{var f=XX[$APP.fa(null==a?null:a)];if(null!=f)a=f.N?f.N(a,b,c,d,e):f.call(null,a,b,c,d,e);else if(f=XX._,null!=f)a=f.N?f.N(a,b,c,d,e):f.call(null,a,b,c,d,e);else throw $APP.Lb("Compiler.make-element",a);}return a};tOa=function(){return null!=YX};
uOa=function(a,b){b.ei=null;a:{var c=YX;YX=b;try{var d=a.C?a.C():a.call(null);break a}finally{YX=c}d=void 0}a=b.ei;b.mf=!1;a:{c=b.Zf;var e=null==a?0:a.length,f=e===(null==c?0:c.length);if(f)for(f=0;;){var h=f===e;if(h){c=h;break a}if(a[f]===c[f])f+=1;else{c=!1;break a}}else c=f}c||b._update_watching(a);return d};vOa=function(a){var b=YX;if(null!=b){var c=b.ei;null==c?b.ei=[a]:c.push(a)}};wOa=function(a,b,c){a.jb=$APP.vi.j(a.jb,b,c);return a.dj=null};
xOa=function(a,b){a.jb=$APP.Nl.h(a.jb,b);return a.dj=null};ZX=function(a,b,c){var d=a.dj;d=null==d?a.dj=$APP.ef(function(t,q,x){t.push(q);t.push(x);return t},[],a.jb):d;for(var e=d.length,f=0;;)if(f<e){var h=d[f],n=d[f+1];n.D?n.D(h,a,b,c):n.call(null,h,a,b,c);f=2+f}else return null};$X=function(a,b,c,d){$APP.Mc(a,["#object[reagent.ratom.",$APP.m.g(c)," "].join(""));a:{c=YX;YX=null;try{var e=d;break a}finally{YX=c}e=void 0}$APP.ej(e,a,b);return $APP.Mc(a,"]")};
aY=function(a,b,c,d){this.state=a;this.M=b;this.Xf=c;this.jb=d;this.J=2154201088;this.K=114690};yOa=function(a,b,c,d,e){var f=b.Yi;f=null==f?$APP.Xf:f;var h=f.h?f.h(c,null):f.call(null,c,null);if(null!=h)return $APP.p(h);if(null==YX)return a.C?a.C():a.call(null);h=function(){function t(q){var x=$APP.Nl.h(b.Yi,c);b.Yi=x;null!=d&&(d.bh=null);return null!=e?e.g?e.g(q):e.call(null,q):null}return bY.j?bY.j(a,cY,t):bY.call(null,a,cY,t)}();var n=$APP.p(h);b.Yi=$APP.vi.j(f,c,h);null!=d&&(d.bh=h);return n};
dY=function(a,b){this.f=a;this.ya=b;this.bh=null;this.J=2153807872;this.K=0};eY=function(a,b){return new dY(a,b)};zOa=function(a,b){var c=eY(a,b);a=function(){function d(){return c.Ja(null)}return bY.j?bY.j(d,fY,!0):bY.call(null,d,fY,!0)}();$APP.p(a);return a};AOa=function(a,b){this.cc=a;this.path=b;this.jb=this.state=this.bh=null;this.J=2153807872;this.K=114690};BOa=function(a){a=a.destroy;return null==a?null:a.C?a.C():a.call(null)};
COa=function(a){var b=YX;return null==b?[]:yOa($APP.Pb,b,a,null,BOa)};gY=function(a){if(null!=a&&null!=a.Zi)a=a.Zi(a);else{var b=gY[$APP.fa(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=gY._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw $APP.Lb("IDisposable.dispose!",a);}return a};DOa=function(a,b,c,d){return a._handle_change(b,c,d)};EOa=function(a){this.f=a;this.state=null;this.mf=!0;this.Tj=!1;this.fi=this.Je=this.jb=this.Zf=null;this.J=2153807872;this.K=114690};
$APP.iY=function(){for(;;){var a=hY;if(null==a)return null;hY=null;for(var b=a.length,c=0;;)if(c<b)a[c]._queued_run(),c+=1;else break}};HOa=function(a,b){var c=FOa,d=GOa,e=uOa(a,d);null!=d.Zf&&(GOa=bY(null),d._set_opts(c),d.f=a,d.Je=function(){return rOa.g?rOa.g(b):rOa.call(null,b)},b.cljsRatom=d);return e};
jY=function(a,b){var c=b.argv;if(null==c){c=$APP.I;a=a.constructor;a:for(var d=$APP.Ka(b),e=d.length,f=$APP.Xf,h=0;;)if(h<e){var n=d[h];f=$APP.vi.j(f,$APP.gj.g(n),$APP.Ma(b,n));h+=1}else break a;b=new $APP.H(null,2,5,c,[a,f],null)}else b=c;return b};IOa=function(a){var b;if(b=$APP.qe(a))a=null==a?null:a.prototype,b=null!=(null==a?null:a.rf);return b};JOa=function(a){var b;if(b=$APP.qe(a))a=null==a?null:a.prototype,b=null!=(null==a?null:a.render);return b};
KOa=function(a,b){for(;;){var c=a.rf,d=!0===a.ql?c.call(a,a):function(){var e=jY(a,a.props);switch($APP.ce(e)){case 1:return c.call(a);case 2:return c.call(a,$APP.A.h(e,1));case 3:return c.call(a,$APP.A.h(e,1),$APP.A.h(e,2));case 4:return c.call(a,$APP.A.h(e,1),$APP.A.h(e,2),$APP.A.h(e,3));case 5:return c.call(a,$APP.A.h(e,1),$APP.A.h(e,2),$APP.A.h(e,3),$APP.A.h(e,4));default:return c.apply(a,$APP.qs.g(e).slice(1))}}();if($APP.Fe(d))return $APP.WX(b,d);if($APP.Ne(d))a.rf=IOa(d)?function(e,f,h,n,t){return function(){function q(z){var E=
null;if(0<arguments.length){E=0;for(var F=Array(arguments.length-0);E<F.length;)F[E]=arguments[E+0],++E;E=new $APP.Fd(F,0,null)}return x.call(this,E)}function x(z){return $APP.WX(f,$APP.sg.j($APP.Bw,t,z))}q.A=0;q.F=function(z){z=$APP.u(z);return x(z)};q.l=x;return q}()}(a,b,c,null,d):d;else return d}};LOa=function(a,b){var c=kY;kY=a;try{return KOa(a,b)}finally{kY=c}};
MOa=function(a,b){switch(a instanceof $APP.G?a.S:null){case "getDefaultProps":throw Error("getDefaultProps not supported");case "getDerivedStateFromProps":return function(c,d){var e=b.call,f=c.argv;null!=f&&(c=$APP.A.j(f,1,null),c=$APP.Ce(c)?c:null);return e.call(b,null,c,d)};case "getInitialState":return function(c){var d=c.sl;d=null!=d?d:c.sl=lY.g(null);return $APP.Bg(d,b.call(c,c))};case "getSnapshotBeforeUpdate":return function(c,d){return b.call(this,this,jY(this,c),d)};case "componentWillReceiveProps":return function(c){return b.call(this,
this,jY(this,c))};case "UNSAFE_componentWillReceiveProps":return function(c){return b.call(this,this,jY(this,c))};case "shouldComponentUpdate":return function(c){if($APP.l(!1))return!1;var d=this.props.argv,e=c.argv,f=null==d||null==e;if(null==b){if(f)return f;try{return $APP.ui.h(d,e)}catch(h){return!1}}else return f?b.call(this,this,jY(this,this.props),jY(this,c)):b.call(this,this,d,e)};case "componentWillUpdate":return function(c,d){return b.call(this,this,jY(this,c),d)};case "UNSAFE_componentWillUpdate":return function(c,
d){return b.call(this,this,jY(this,c),d)};case "componentDidUpdate":return function(c,d,e){return b.call(this,this,jY(this,c),d,e)};case "componentWillMount":return function(){return b.call(this,this)};case "UNSAFE_componentWillMount":return function(){return b.call(this,this)};case "componentDidMount":return function(){return b.call(this,this)};case "componentWillUnmount":return function(){var c=$APP.Ma(this,"cljsRatom");null!=c&&gY(c);this.cljsIsDirty=!1;return null==b?null:b.call(this,this)};case "componentDidCatch":return function(c,
d){return b.call(this,this,c,d)};default:return null}};OOa=function(a){return $APP.ef(function(b,c,d){return $APP.vi.j(b,$APP.gj.g(NOa(c)),d)},$APP.Xf,a)};
QOa=function(a,b){var c=function(){var h=mY.g(a);return $APP.l(h)?h:nY.g(a)}(),d=null==mY.g(a),e=function(){var h=oY.g(a);if($APP.l(h))return h;h=jOa(c);return $APP.l(h)?h:$APP.m.g($APP.Xn.g("reagent"))}(),f=$APP.ef(function(h,n,t){var q=$APP.vi.j,x=MOa(n,t);return q.call($APP.vi,h,n,$APP.l(x)?x:t)},$APP.Xf,a);return $APP.vi.l(f,oY,e,$APP.B([POa,d,mY,c,nY,function(){var h=this;if($APP.pY)return LOa(h,b);var n=$APP.Ma(h,"cljsRatom");h.cljsIsDirty=!1;return null==n?HOa(function(){return LOa(h,b)},h):
n._run(!1)}]))};ROa=function(a){return $APP.ef(function(b,c,d){c=$APP.Hi(c);b[c]=d;return b},{},a)};TOa=function(a,b){return QOa($APP.Ml.l($APP.B([SOa,OOa(a)])),b)};
qY=function(a,b){function c(n,t,q){$APP.Cu.nbb$internal$react.ej.call(this,n,t,q);$APP.l(h)&&(h.h?h.h(this,n):h.call(null,this,n));$APP.l(f)&&(this.state=f.g?f.g(this):f.call(null,this));this.xi=UOa+=1;return this}a=TOa(a,b);b=ROa($APP.sg.l($APP.Nl,a,oY,VOa,$APP.Us,$APP.B([nY,mY,WOa])));var d=ROa($APP.wi(a,WOa)),e=oY.g(a),f=VOa.g(a),h=$APP.Us.g(a);$APP.Oa(c.prototype,$APP.Cu.nbb$internal$react.ej.prototype,b);$APP.l(nY.g(a))&&(c.prototype.render=nY.g(a));$APP.l(mY.g(a))&&(c.prototype.rf=mY.g(a));
$APP.l(POa.g(a))&&(c.prototype.ql=POa.g(a));$APP.Oa(c,$APP.Cu.nbb$internal$react.ej,d);$APP.l(e)&&(c.displayName=e,c.th=e,c.pl=function(n){return $APP.Mc(n,e)},Object.defineProperty(c,"name",{value:e,writable:!1}));c.zj=!0;return c.prototype.constructor=c};XOa=function(a,b,c){a=VX(a);return b[a]=c};ZOa=function(a,b){var c=$APP.Ma(a,VX(b));null==c?IOa(a)?a=XOa(b,a,a):(c=$APP.te(a),c=$APP.vi.j(c,YOa,a),c=qY(c,b),a=XOa(b,a,c)):a=c;return a};
$Oa=function(a,b){for(;;){var c=b.rf,d=b.argv,e=$APP.sg.h(c,d);if($APP.Fe(e))return $APP.WX(a,e);if($APP.Ne(e))b.rf=IOa(e)?function(f,h,n,t,q,x){return function(){function z(F){var N=null;if(0<arguments.length){N=0;for(var S=Array(arguments.length-0);N<S.length;)S[N]=arguments[N+0],++N;N=new $APP.Fd(S,0,null)}return E.call(this,N)}function E(F){return $APP.WX(f,$APP.sg.j($APP.Bw,x,F))}z.A=0;z.F=function(F){F=$APP.u(F);return E(F)};z.l=E;return z}()}(a,b,c,null,d,e):e;else return e}};
aPa=function(a,b){var c=kY;kY=b;try{return $Oa(a,b)}finally{kY=c}};
bPa=function(a,b){if($APP.pY)return aPa(a,b);var c=b.argv,d=b.rf;b=$APP.Cu.nbb$internal$react.Tn(0);$APP.A.j(b,0,null);var e=$APP.A.j(b,1,null),f=$APP.Cu.nbb$internal$react.Sn();$APP.l(f.current)||function(){var n={forceUpdate:function(){return e.g?e.g($APP.Rd):e.call(null,$APP.Rd)}};n.xi=UOa+=1;n.constructor=d;n.rf=d;return f.current=n}();var h=f.current;b=$APP.Ma(h,"cljsRatom");$APP.Cu.nbb$internal$react.Rn(function(){return function(){var n=$APP.Ma(h,"cljsRatom");return null==n?null:gY(n)}},[]);
h.argv=c;h.cljsIsDirty=!1;return null==b?HOa(function(){return aPa(a,h)},h):b._run(!1)};cPa=function(a,b){a=a.argv;b=b.argv;try{return $APP.y.h(a,b)}catch(c){return!1}};dPa=function(a,b){function c(e){return bPa(a,e)}var d=$APP.Ma(b,VX(a));if($APP.l(d))return d;d=jOa(b);c.displayName=d;Object.defineProperty(c,"name",{value:d,writable:!1});d=$APP.Cu.nbb$internal$react.Mn(c,cPa);XOa(a,b,d);return d};
gPa=function(a,b,c,d){var e=$APP.Yf($APP.Xf);e=$APP.C.h(e,ePa);if(a===document.activeElement&&$APP.Te(fPa,a.type)&&"string"===typeof b&&"string"===typeof c){var f=a.value;if($APP.ui.h(f,c))return UX.add_after_render(function(){return rY.g?rY.g(d):rY.call(null,d)});c=$APP.ce(f)-a.selectionStart;c=$APP.ce(b)-c;d.uh=b;a.value=b;$APP.qe(e)&&(e.g?e.g(b):e.call(null,b));a.selectionStart=c;return a.selectionEnd=c}d.uh=b;a.value=b;return $APP.qe(e)?e.g?e.g(b):e.call(null,b):null};
rY=function(a){if($APP.l(a.wi)){a.Cj=!1;var b=a.rl,c=a.uh,d=a.Ki;return $APP.ui.h(b,c)?gPa(d,b,c,a):null}return null};hPa=function(a,b,c){a.uh=c.target.value;$APP.l(a.Cj)||(a.Cj=!0,UX.add_after_render(function(){return rY(a)}));return b.g?b.g(c):b.call(null,c)};
iPa=function(a){var b=kY;if($APP.l(function(){var f=null!=a;return f?(f=a.hasOwnProperty("onChange"),$APP.l(f)?a.hasOwnProperty("value"):f):f}())){var c=a.value;c=null==c?"":c;var d=a.onChange,e=a.ref;$APP.l(b.wi)||(b.wi=!0,b.uh=c);$APP.l(b.Bk)||(b.Bk=$APP.qe(e)?function(f){b.Ki=f;return e.g?e.g(f):e.call(null,f)}:$APP.l($APP.l(e)?e.hasOwnProperty("current"):e)?function(f){b.Ki=f;return e.current=f}:function(f){return b.Ki=f});b.rl=c;delete a.value;a.defaultValue=c;a.onChange=function(f){return hPa(b,
d,f)};a.ref=b.Bk}};jPa=function(a){this.tag=a;this.className=this.id=null};kPa=function(a,b){return a.hasOwnProperty(b)?$APP.Ma(a,b):null};mPa=function(a,b,c){if(SX(b)){var d=kPa(lPa,$APP.Hi(b));null==d?(d=iOa(b),b=$APP.Hi(b),b=lPa[b]=d):b=d}c=sY.g?sY.g(c):sY.call(null,c);a[b]=c;return a};
sY=function(a){return"object"!==$APP.fa(a)?a:SX(a)?$APP.Hi(a):$APP.Ce(a)?$APP.ef(mPa,{},a):$APP.xe(a)?$APP.Fy(a):$APP.Ne(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Fd(f,0,null)}return c.call(this,e)}function c(d){return $APP.sg.h(a,d)}b.A=0;b.F=function(d){d=$APP.u(d);return c(d)};b.l=c;return b}():$APP.Fy(a)};
oPa=function(a,b,c){if(SX(b)){var d=kPa(nPa,$APP.Hi(b));null==d?(d=iOa(b),b=$APP.Hi(b),b=nPa[b]=d):b=d}c=sY(c);a[b]=c;return a};
pPa=function(a){return"object"!==$APP.fa(a)?a:SX(a)?$APP.Hi(a):$APP.Ce(a)?$APP.ef(oPa,{},a):$APP.xe(a)?$APP.Fy(a):$APP.Ne(a)?function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Fd(f,0,null)}return c.call(this,e)}function c(d){return $APP.sg.h(a,d)}b.A=0;b.F=function(d){d=$APP.u(d);return c(d)};b.l=c;return b}():$APP.Fy(a)};
qPa=function(a,b,c,d,e){switch($APP.ce(b)-e){case 0:return $APP.Cu.nbb$internal$react.createElement(c,d);case 1:return $APP.Cu.nbb$internal$react.createElement(c,d,$APP.WX(a,$APP.A.j(b,e,null)));default:return $APP.Cu.nbb$internal$react.createElement.apply(null,$APP.ef(function(f,h,n){h>=e&&f.push($APP.WX(a,n));return f},[c,d],b))}};rPa=function(a,b,c,d){this.tag=a;this.id=b;this.className=c;this.vl=d};
sPa=function(a,b,c){a=ZOa(a,c);c={};c.argv=b;b=kOa(b);null!=b&&(c.key=b);return $APP.Cu.nbb$internal$react.createElement(a,c)};tPa=function(a,b,c,d){var e={};e.rf=a;e.argv=$APP.gl.h(b,c);b=kOa(b);null!=b&&(e.key=b);return $APP.Cu.nbb$internal$react.createElement(dPa(d,a),e)};uPa=function(a,b,c){return JOa(a)?sPa(a,b,c):tPa(a,b,1,c)};
xPa=function(a,b){a=kPa(vPa,b);if(null==a){var c=$APP.w($APP.Ti(wPa,$APP.Hi(b)));a=$APP.A.j(c,0,null);var d=$APP.A.j(c,1,null);c=$APP.A.j(c,2,null);c=null==c?null:$APP.bl(c,/\./," ");var e=$APP.ui.h(-1,a.indexOf("-"));a=new rPa(a,d,c,e);return vPa[b]=a}return a};
APa=function(a,b,c,d){var e=a.tag,f=$APP.A.j(b,c,null),h=null==f||$APP.Ce(f),n=function(){var x=h?f:null;var z=$APP.Ar.g(x);z=$APP.l(z)?$APP.vi.j(x,$APP.Ar,tY.g(z)):x;var E=a.id;x=a.className;E=null!=E&&null==$APP.yq.g(z)?$APP.vi.j(z,$APP.yq,E):z;if($APP.l(x)){var F=$APP.vi.j,N=tY.h,S=$APP.Ar.g(z);z=$APP.l(S)?S:yPa.g(z);x=F.call($APP.vi,E,$APP.Ar,N.call(tY,x,z))}else x=E;x=$APP.l(a.vl)?pPa(x):sY(x);return $APP.l(x)?x:{}}();c+=h?1:0;a:switch(e){case "input":case "textarea":var t=!0;break a;default:t=
!1}if(t){t=TX(f);var q=function(){var x=d.Am;if($APP.l(x))return x;x=qY(zPa,d);return d.Am=x}();return $APP.WX(d,$APP.se(new $APP.H(null,6,5,$APP.I,[q,b,e,n,c,d],null),$APP.Ml.l($APP.B([$APP.l(t)?new $APP.k(null,1,[$APP.RE,t],null):null,$APP.te(b)]))))}t=TX($APP.te(b));null!=t&&(n.key=t);return XX(d,b,e,n,c)};BPa=function(a,b){return $APP.qs.g($APP.fj.h(function(c){return $APP.WX(b,c)},a))};
CPa=function(a,b,c){null==b&&console.error("vec-to-elem",$APP.zj.l($APP.B([a])));var d=$APP.A.j(a,0,null);switch(d instanceof $APP.G?d.S:null){case "\x3e":return c=$APP.A.j(a,1,null),APa(new rPa(c,null,null,null),a,2,b);case "r\x3e":c=$APP.A.j(a,1,null);d=$APP.A.j(a,2,null);d=$APP.l(d)?d:{};var e=TX($APP.te(a));null!=e&&(d.key=e);return XX(b,a,c,d,3);case "f\x3e":return tPa($APP.A.j(a,1,null),a,2,b);case "\x3c\x3e":return d=$APP.A.j(a,1,null),c=null==d||$APP.Ce(d),d=sY(c?d:null),d=$APP.l(d)?d:{},
c=1+(c?1:0),e=kOa(a),null!=e&&(d.key=e),XX(b,a,$APP.Cu.nbb$internal$react.fn,d,c);default:if(SX(d)||"string"===typeof d)a:for(;;)switch(c=$APP.A.j(a,0,null),d=$APP.Hi(c),e=d.indexOf("\x3e"),e){case -1:b=APa(sOa(b,d,c),a,1,b);break a;case 0:b=null;break a;default:a=$APP.se(new $APP.H(null,2,5,$APP.I,[$APP.Zi.j(d,0,e),$APP.vi.j($APP.se(a,null),0,$APP.Zi.h(d,e+1))],null),$APP.te(a))}else b=d instanceof jPa?APa(d,a,1,b):c.j?c.j(d,a,b):c.call(null,d,a,b);return b}};
DPa=function(a,b,c,d,e){this.pd=a;this.id=b;this.Jj=c;this.Ph=d;this.jm=e;this.J=393216;this.K=0};GPa=function(a){var b=$APP.Xn.g("reagent-compiler"),c=$APP.l(EPa.g(a))?uPa:sPa,d=$APP.C.j(a,FPa,xPa);return new DPa(a,b,c,d,$APP.Xf)};uY=function(a){return new jPa(a)};HPa=function(a){return gY(a)};IPa=function(a,b){return new AOa(a,b)};JPa=function(a){return GPa(a)};KPa=function(){return YX};LPa=function(a){return a.generation};MPa=function(a){return a.ratomGeneration};
NPa=function(a,b){return a.generation=b.ratomGeneration};OPa=function(a,b){return a.destroy=b};PPa=function(a){return a.destroy};QPa=function(){return!1};RPa=new $APP.r(null,"-generation","-generation",627658965,null);SPa=new $APP.r("reagent.ratom","track!","reagent.ratom/track!",1183599982,null);nY=new $APP.G(null,"render","render",-1408033454);TPa=new $APP.r(null,"on-set","on-set",1499578057,null);UPa=new $APP.r("reagent.core","adapt-react-class","reagent.core/adapt-react-class",1789410154,null);
VPa=new $APP.r("reagent.ratom","make-reaction","reagent.ratom/make-reaction",272608527,null);WPa=new $APP.r(null,"dispose!","dispose!",-395693497,null);XPa=new $APP.r("reagent.ratom","-destroy","reagent.ratom/-destroy",-1284026419,null);YPa=new $APP.r("reagent.core","create-compiler","reagent.core/create-compiler",491047088,null);ZPa=new $APP.G(null,"componentWillUnmount","componentWillUnmount",1573788814);yPa=new $APP.G(null,"className","className",-1983287057);
$Pa=new $APP.r(null,"-tracking?","-tracking?",-1106885352,null);aQa=new $APP.r(null,"with-let","with-let",-1310113408,null);bQa=new $APP.r(null,"with-let-values","with-let-values",1929572375,null);cQa=new $APP.r(null,"create-class","create-class",-665911586,null);dQa=new $APP.G(null,"childContextTypes","childContextTypes",578717991);eQa=new $APP.r("reagent.core","atom","reagent.core/atom",1748890217,null);vY=new $APP.r(null,"class2","class2",-1266396392,null);
wY=new $APP.r(null,"class1","class1",-1905977651,null);fQa=new $APP.r("reagent.core","cursor","reagent.core/cursor",-1137097804,null);gQa=new $APP.r(null,"auto-run","auto-run",-696035332,null);hQa=new $APP.r(null,"-set-ratom-generation!","-set-ratom-generation!",-1545989828,null);iQa=new $APP.r("sci.configs.reagent.reagent","-ratom-context","sci.configs.reagent.reagent/-ratom-context",270989566,null);jQa=new $APP.r(null,"destroy__37442__auto__","destroy__37442__auto__",-1899493150,null);
kQa=new $APP.r("sci.configs.reagent.reagent","-destroy","sci.configs.reagent.reagent/-destroy",-1999711192,null);lQa=new $APP.r(null,"-destroy","-destroy",-557272508,null);fY=new $APP.G(null,"auto-run","auto-run",1958400437);mQa=new $APP.r(null,"track-console","track-console",17070495,null);YOa=new $APP.G(null,"reagent-render","reagent-render",-985383853);nQa=new $APP.G(null,"contextTypes","contextTypes",-2023853910);oQa=new $APP.r(null,"create-compiler","create-compiler",1059333141,null);
xY=new $APP.r(null,"props","props",2093813254,null);pQa=new $APP.r(null,"reaction","reaction",2131401315,null);qQa=new $APP.G(null,"on-set","on-set",-140953470);ePa=new $APP.G(null,"on-write","on-write",31519475);rQa=new $APP.r(null,"reactive?","reactive?",1213887990,null);cY=new $APP.G(null,"on-dispose","on-dispose",2105306360);$APP.yY=new $APP.r(null,"compiler","compiler",1372604796,null);sQa=new $APP.r("reagent.ratom","-destroy!","reagent.ratom/-destroy!",-337873850,null);
tQa=new $APP.r(null,"-destroy!","-destroy!",143253949,null);uQa=new $APP.r("sci.configs.reagent.reagent","error","sci.configs.reagent.reagent/error",1433174531,null);mY=new $APP.G(null,"reagentRender","reagentRender",-358306383);vQa=new $APP.r("reagent.core","reactify-component","reagent.core/reactify-component",-385504376,null);wQa=new $APP.r(null,"cursor","cursor",-1642498285,null);xQa=new $APP.r(null,"make-reaction","make-reaction",1935680112,null);
yQa=new $APP.G(null,"contextType","contextType",1033066077);zQa=new $APP.r("reagent.core","dispose!","reagent.core/dispose!",239740642,null);AQa=new $APP.G(null,"component-did-update","component-did-update",-1468549173);BQa=new $APP.r(null,"src","src",-10544524,null);oY=new $APP.G(null,"displayName","displayName",-809144601);CQa=new $APP.r("sci.configs.reagent.reagent","-generation","sci.configs.reagent.reagent/-generation",-1754580423,null);DQa=new $APP.G(null,"display-name","display-name",694513143);
EQa=new $APP.r("sci.configs.reagent.reagent","reaction","sci.configs.reagent.reagent/reaction",-1324858361,null);FQa=new $APP.r(null,"others","others",-569561186,null);GQa=new $APP.G(null,"getDerivedStateFromProps","getDerivedStateFromProps",-991834739);FPa=new $APP.G(null,"parse-tag","parse-tag",1427313738);HQa=new $APP.r("sci.configs.reagent.reagent","-ratom-generation","sci.configs.reagent.reagent/-ratom-generation",662254794,null);IQa=new $APP.r(null,"destroy","destroy",796871122,null);
JQa=new $APP.G(null,"shouldComponentUpdate","shouldComponentUpdate",1795750960);KQa=new $APP.r("reagent.core","track!","reagent.core/track!",-954652078,null);LQa=new $APP.r("reagent.core","as-element","reagent.core/as-element",-1369748434,null);MQa=new $APP.r(null,"-ratom-generation","-ratom-generation",-176468250,null);NQa=new $APP.r("reagent.core","create-class","reagent.core/create-class",-1100017147,null);zY=new $APP.r(null,"adapt-react-class","adapt-react-class",1221068673,null);
OQa=new $APP.r("reagent.ratom","make-track","reagent.ratom/make-track",267038680,null);PQa=new $APP.r(null,"track","track",1836319014,null);QQa=new $APP.r(null,".hasOwnProperty",".hasOwnProperty",-1264659034,null);RQa=new $APP.r("sci.configs.reagent.reagent","-tracking?","sci.configs.reagent.reagent/-tracking?",201600244,null);SQa=new $APP.r(null,"reagent.debug","reagent.debug",1010511129,null);TQa=new $APP.r(null,"reactify-component","reactify-component",-882526483,null);
UQa=new $APP.r("js","console","js/console",-1426368245,null);AY=new $APP.r(null,"sci.configs.reagent.reagent","sci.configs.reagent.reagent",94604865,null);VQa=new $APP.r("sci.configs.reagent.reagent","-destroy!","sci.configs.reagent.reagent/-destroy!",-561262631,null);WQa=new $APP.G(null,"no-cache","no-cache",1588056370);XQa=new $APP.r("cljs.core","zero?","cljs.core/zero?",-341242858,null);BY=new $APP.r(null,"track!","track!",-516308489,null);YQa=new $APP.r(null,".error",".error",1756007195,null);
ZQa=new $APP.r("reagent.debug","-tracking?","reagent.debug/-tracking?",409956583,null);EPa=new $APP.G(null,"function-components","function-components",1492814963);$Qa=new $APP.r("reagent.ratom","reactive?","reagent.ratom/reactive?",-358553475,null);aRa=new $APP.r(null,"as-element","as-element",-2139409597,null);bRa=new $APP.r(null,"make-track","make-track",-1388299455,null);cRa=new $APP.r("reagent.ratom","atom","reagent.ratom/atom",-391081187,null);
dRa=new $APP.r("reagent.debug","track-console","reagent.debug/track-console",-1553126476,null);eRa=new $APP.r("reagent.core","create-element","reagent.core/create-element",-1888667366,null);fRa=new $APP.r(null,"on-dispose","on-dispose",-549129409,null);gRa=new $APP.G(null,"component-will-unmount","component-will-unmount",-2058314698);hRa=new $APP.r("reagent.ratom","with-let-values","reagent.ratom/with-let-values",-575838306,null);iRa=new $APP.r(null,"-ratom-context","-ratom-context",1646839514,null);
POa=new $APP.G(null,"cljsLegacyRender","cljsLegacyRender",-1527295613);jRa=new $APP.r("sci.configs.reagent.reagent","-set-ratom-generation!","sci.configs.reagent.reagent/-set-ratom-generation!",-35374248,null);kRa=new $APP.r("sci.configs.reagent.reagent","with-let","sci.configs.reagent.reagent/with-let",65759084,null);lRa=new $APP.r("reagent.core","class-names","reagent.core/class-names",-1902681251,null);mRa=new $APP.r(null,"class-names","class-names",-1397320704,null);
VOa=new $APP.G(null,"getInitialState","getInitialState",1541760916);nRa=new $APP.r("reagent.core","track","reagent.core/track",1263921785,null);oRa=new $APP.G(null,"getDerivedStateFromError","getDerivedStateFromError",166658477);pRa=new $APP.r(null,"create-element","create-element",1833774591,null);var qRa=$APP.Bj.g(null),rRa=function(){var a={};a.warn=function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Fd(f,0,null)}return c.call(this,e)}function c(d){return $APP.Cj.l(qRa,$APP.Kl,new $APP.H(null,1,5,$APP.I,[$APP.Twa],null),$APP.wf,$APP.B([$APP.sg.h($APP.m,d)]))}b.A=0;b.F=function(d){d=$APP.u(d);return c(d)};b.l=c;return b}();a.error=function(){function b(d){var e=null;if(0<arguments.length){e=0;for(var f=
Array(arguments.length-0);e<f.length;)f[e]=arguments[e+0],++e;e=new $APP.Fd(f,0,null)}return c.call(this,e)}function c(d){return $APP.Cj.l(qRa,$APP.Kl,new $APP.H(null,1,5,$APP.I,[$APP.Hn],null),$APP.wf,$APP.B([$APP.sg.h($APP.m,d)]))}b.A=0;b.F=function(d){d=$APP.u(d);return c(d)};b.l=c;return b}();return a}();var sRa,hOa,tY;sRa="undefined"!==typeof window&&null!=window.document;$APP.pY=!1;hOa=new $APP.Bi(null,new $APP.k(null,2,["aria",null,"data",null],null),null);tY=function tY(a){switch(arguments.length){case 0:return tY.C();case 1:return tY.g(arguments[0]);case 2:return tY.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return tY.l(arguments[0],arguments[1],2<c.length?new $APP.Fd(c.slice(2),0,null):null)}};tY.C=function(){return null};
tY.g=function(a){return $APP.xe(a)?(a=$APP.qn.h(function(b){return $APP.l(b)?SX(b)?$APP.Hi(b):b:null},a),$APP.u(a)?$APP.kn.h(" ",a):null):SX(a)?$APP.Hi(a):a};tY.h=function(a,b){return $APP.l(a)?$APP.l(b)?[$APP.m.g(tY.g(a))," ",$APP.m.g(tY.g(b))].join(""):tY.g(a):tY.g(b)};tY.l=function(a,b,c){return $APP.bf.j(tY,tY.h(a,b),c)};tY.F=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.l(b,a,c)};tY.A=2;var UOa=0,tRa=sRa?function(){var a=window;return function(){var b=a.requestAnimationFrame;if($APP.l(b))return b;b=a.webkitRequestAnimationFrame;if($APP.l(b))return b;b=a.mozRequestAnimationFrame;if($APP.l(b))return b;b=a.msRequestAnimationFrame;return $APP.l(b)?b:lOa}().bind(a)}():lOa;$APP.g=qOa.prototype;$APP.g.flush_after_render=function(){var a=this.lh;if(null==a)return null;this.lh=null;return oOa(a)};$APP.g.queue_render=function(a){null==this.Bh&&(this.Bh=[]);return pOa(this,this.Bh,a)};
$APP.g.schedule=function(){function a(){return b.run_queues()}var b=this;if(this.Vh)return null;this.Vh=!0;return tRa.g?tRa.g(a):tRa.call(null,a)};$APP.g.flush_before_flush=function(){var a=this.oh;if(null==a)return null;this.oh=null;return oOa(a)};$APP.g.flush_queues=function(){this.flush_before_flush();nOa();this.flush_render();return this.flush_after_render()};$APP.g.run_queues=function(){this.Vh=!1;return this.flush_queues()};
$APP.g.add_before_flush=function(a){null==this.oh&&(this.oh=[]);return pOa(this,this.oh,a)};$APP.g.add_after_render=function(a){null==this.lh&&(this.lh=[]);return pOa(this,this.lh,a)};$APP.g.flush_render=function(){var a=this.Bh;if(null==a)return null;this.Bh=null;a:{a.sort(mOa);for(var b=a.length,c=0;;)if(c<b){var d=a[c];!0===d.cljsIsDirty&&d.forceUpdate();c+=1}else break a}return null};var UX=new qOa;var YX;$APP.Bj.g(0);var hY=null;$APP.g=aY.prototype;$APP.g.W=function(a,b,c){return $X(b,c,"RAtom",new $APP.k(null,1,[$APP.du,this.Ja(null)],null))};$APP.g.V=function(){return this.M};$APP.g.Y=function(){return $APP.oa(this)};$APP.g.R=function(a,b){return this===b};$APP.g.Tc=function(a,b){a=this.state;this.state=b;null!=this.jb&&ZX(this,a,b);return b};$APP.g.Cg=function(a,b){return this.Tc(null,b.g?b.g(this.state):b.call(null,this.state))};
$APP.g.Dg=function(a,b,c){return this.Tc(null,b.h?b.h(this.state,c):b.call(null,this.state,c))};$APP.g.Eg=function(a,b,c,d){return this.Tc(null,b.j?b.j(this.state,c,d):b.call(null,this.state,c,d))};$APP.g.Fg=function(a,b,c,d,e){return this.Tc(null,$APP.sg.N(b,this.state,c,d,e))};$APP.g.gg=function(a,b){ZX(this,a,b)};$APP.g.Df=function(a,b,c){return wOa(this,b,c)};$APP.g.Ef=function(a,b){return xOa(this,b)};$APP.g.X=function(a,b){return new aY(this.state,b,this.Xf,this.jb)};
$APP.g.Ja=function(){vOa(this);return this.state};var lY=function lY(a){switch(arguments.length){case 1:return lY.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return lY.l(arguments[0],1<c.length?new $APP.Fd(c.slice(1),0,null):null)}};lY.g=function(a){return new aY(a,null,null,null)};lY.l=function(a,b){var c=$APP.Yf(b);b=$APP.C.h(c,$APP.nb);c=$APP.C.h(c,$APP.Px);return new aY(a,b,c,null)};
lY.F=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};lY.A=1;dY.prototype.Ja=function(){var a=this,b=a.bh;return null==b?yOa(function(){return $APP.sg.h(a.f,a.ya)},a.f,a.ya,this,null):$APP.p(b)};dY.prototype.R=function(a,b){return b instanceof dY&&$APP.y.h(this.f,b.f)&&$APP.y.h(this.ya,b.ya)};dY.prototype.Y=function(){return $APP.yd(new $APP.H(null,2,5,$APP.I,[this.f,this.ya],null))};
dY.prototype.W=function(a,b,c){return $X(b,c,"Track",new $APP.k(null,2,[$APP.du,this.Ja(null),$APP.RO,this.f],null))};var CY=function CY(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return CY.l(arguments[0],1<c.length?new $APP.Fd(c.slice(1),0,null):null)};CY.l=function(a,b){return zOa(a,b)};CY.A=1;CY.F=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};$APP.g=AOa.prototype;
$APP.g._peek=function(){var a=YX;YX=null;try{return this.Ja(null)}finally{YX=a}};$APP.g._set_state=function(a,b){if(a===b)return null;this.state=b;return null!=this.jb?ZX(this,a,b):null};$APP.g.W=function(a,b,c){return $X(b,c,"RCursor",new $APP.k(null,2,[$APP.du,this.Ja(null),$APP.Hr,this.path],null))};$APP.g.Y=function(){return $APP.yd(new $APP.H(null,2,5,$APP.I,[this.cc,this.path],null))};$APP.g.R=function(a,b){return b instanceof AOa&&$APP.y.h(this.path,b.path)&&$APP.y.h(this.cc,b.cc)};
$APP.g.Tc=function(a,b){this._set_state(this.state,b);(null!=this.cc?this.cc.J&32768||$APP.xd===this.cc.Af||(this.cc.J?0:$APP.Jb($APP.sc,this.cc)):$APP.Jb($APP.sc,this.cc))?$APP.y.h(this.path,$APP.Sg)?$APP.Bg(this.cc,b):$APP.Cj.D(this.cc,$APP.Dq,this.path,b):this.cc.h?this.cc.h(this.path,b):this.cc.call(null,this.path,b);return b};$APP.g.Cg=function(a,b){a=this.Tc;var c=this._peek();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};
$APP.g.Dg=function(a,b,c){a=this.Tc;var d=this._peek();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.g.Eg=function(a,b,c,d){a=this.Tc;var e=this._peek();b=b.j?b.j(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};$APP.g.Fg=function(a,b,c,d,e){return this.Tc(null,$APP.sg.N(b,this._peek(),c,d,e))};$APP.g.gg=function(a,b){ZX(this,a,b)};$APP.g.Df=function(a,b,c){return wOa(this,b,c)};$APP.g.Ef=function(a,b){return xOa(this,b)};
$APP.g.Ja=function(){var a=this,b=this,c=a.state,d=function(){var e=a.bh;return null==e?yOa((null!=a.cc?a.cc.J&32768||$APP.xd===a.cc.Af||(a.cc.J?0:$APP.Jb($APP.sc,a.cc)):$APP.Jb($APP.sc,a.cc))?function(){return $APP.rp.h($APP.p(a.cc),a.path)}:function(){return a.cc.g?a.cc.g(a.path):a.cc.call(null,a.path)},a.cc,a.path,b,null):$APP.p(e)}();b._set_state(c,d);return d};$APP.g=EOa.prototype;$APP.g._peek_at=function(){var a=YX;YX=null;try{return this.Ja(null)}finally{YX=a}};
$APP.g._handle_change=function(a,b,c){return b===c||this.mf?null:null==this.Je?(this.mf=!0,null==hY&&(hY=[],!1===UX.Vh&&UX.schedule()),hY.push(this)):!0===this.Je?this._run(!1):this.Je.g?this.Je.g(this):this.Je.call(null,this)};
$APP.g._update_watching=function(a){var b=$APP.Fi(a),c=$APP.Fi(this.Zf);this.Zf=a;a=$APP.u($APP.Ww.h(b,c));for(var d=null,e=0,f=0;;)if(f<e){var h=d.ca(null,f);$APP.Qc(h,this,DOa);f+=1}else if(a=$APP.u(a))d=a,$APP.Ge(d)?(a=$APP.cd(d),f=$APP.dd(d),d=a,e=$APP.ce(a),a=f):(a=$APP.v(d),$APP.Qc(a,this,DOa),a=$APP.w(d),d=null,e=0),f=0;else break;b=$APP.u($APP.Ww.h(c,b));c=null;for(e=d=0;;)if(e<d)a=c.ca(null,e),$APP.Rc(a,this),e+=1;else if(b=$APP.u(b))c=b,$APP.Ge(c)?(b=$APP.cd(c),d=$APP.dd(c),c=b,a=$APP.ce(b),
b=d,d=a):(a=$APP.v(c),$APP.Rc(a,this),b=$APP.w(c),c=null,d=0),e=0;else return null};$APP.g._queued_run=function(){return this.mf&&null!=this.Zf?this._run(!0):null};$APP.g._try_capture=function(a){try{return this.fi=null,uOa(a,this)}catch(b){return this.fi=this.state=a=b,this.mf=!1}};$APP.g._run=function(a){var b=this.state;a=$APP.l(a)?this._try_capture(this.f):uOa(this.f,this);this.Tj||(this.state=a,null==this.jb||$APP.y.h(b,a)||ZX(this,b,a));return a};
$APP.g._set_opts=function(a){var b=$APP.Yf(a);a=$APP.C.h(b,fY);var c=$APP.C.h(b,qQa),d=$APP.C.h(b,cY);b=$APP.C.h(b,WQa);null!=a&&(this.Je=a);null!=c&&(this.rm=c);null!=d&&(this.Vj=d);return null!=b?this.Tj=b:null};$APP.g.W=function(a,b,c){return $X(b,c,"Reaction",new $APP.k(null,1,[$APP.du,this.Ja(null)],null))};$APP.g.Y=function(){return $APP.oa(this)};$APP.g.R=function(a,b){return this===b};
$APP.g.Zi=function(){var a=this.state,b=this.Zf;this.Je=this.state=this.Zf=null;this.mf=!0;b=$APP.u($APP.Fi(b));for(var c=null,d=0,e=0;;)if(e<d){var f=c.ca(null,e);$APP.Rc(f,this);e+=1}else if(b=$APP.u(b))c=b,$APP.Ge(c)?(b=$APP.cd(c),e=$APP.dd(c),c=b,d=$APP.ce(b),b=e):(b=$APP.v(c),$APP.Rc(b,this),b=$APP.w(c),c=null,d=0),e=0;else break;null!=this.Vj&&this.Vj(a);a=this.Nn;if(null==a)return null;b=a.length;for(c=0;;)if(c<b)d=a[c],d.g?d.g(this):d.call(null,this),c+=1;else return null};
$APP.g.Tc=function(a,b){a=this.state;this.state=b;this.rm(a,b);ZX(this,a,b);return b};$APP.g.Cg=function(a,b){a=this.Tc;var c=this._peek_at();b=b.g?b.g(c):b.call(null,c);return a.call(this,null,b)};$APP.g.Dg=function(a,b,c){a=this.Tc;var d=this._peek_at();b=b.h?b.h(d,c):b.call(null,d,c);return a.call(this,null,b)};$APP.g.Eg=function(a,b,c,d){a=this.Tc;var e=this._peek_at();b=b.j?b.j(e,c,d):b.call(null,e,c,d);return a.call(this,null,b)};
$APP.g.Fg=function(a,b,c,d,e){return this.Tc(null,$APP.sg.N(b,this._peek_at(),c,d,e))};$APP.g.gg=function(a,b){ZX(this,a,b)};$APP.g.Df=function(a,b,c){return wOa(this,b,c)};$APP.g.Ef=function(a,b){a=$APP.we(this.jb);xOa(this,b);return!a&&$APP.we(this.jb)&&null==this.Je?this.Zi(null):null};
$APP.g.Ja=function(){var a=this.fi;if(null!=a)throw a;(a=null==YX)&&($APP.iY.C?$APP.iY.C():$APP.iY.call(null));a&&null==this.Je?this.mf&&(a=this.state,this.state=this.f.C?this.f.C():this.f.call(null),null==this.jb||$APP.y.h(a,this.state)||ZX(this,a,this.state)):(vOa(this),this.mf&&this._run(!1));return this.state};nOa=$APP.iY;var bY=function bY(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return bY.l(arguments[0],1<c.length?new $APP.Fd(c.slice(1),0,null):null)};
bY.l=function(a,b){var c=$APP.Yf(b);b=$APP.C.h(c,fY);var d=$APP.C.h(c,qQa);c=$APP.C.h(c,cY);a=new EOa(a);a._set_opts(new $APP.k(null,3,[fY,b,qQa,d,cY,c],null));return a};bY.A=1;bY.F=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};var GOa=bY(null);var kY,FOa=new $APP.k(null,1,[WQa,!0],null),SOa=new $APP.k(null,2,[JQa,null,ZPa,null],null),NOa=function(a){var b=$APP.Bj.g($APP.Xf);return function(c){var d=$APP.C.h($APP.p(b),c);if(null!=d)return d;d=a.g?a.g(c):a.call(null,c);$APP.Cj.D(b,$APP.vi,c,d);return d}}(function(a){if("string"===typeof a)return a;a=$APP.Hi(a);a=$APP.bl(a,/(unsafe|UNSAFE)[-_]/,"UNSAFE_");a=$APP.hl.h(a,/-/);var b=$APP.u(a);a=$APP.v(b);b=$APP.w(b);return $APP.sg.j($APP.m,a,$APP.fj.h(gOa,b))}),WOa=new $APP.H(null,5,5,$APP.I,
[dQa,nQa,yQa,GQa,oRa],null);var fPa=new $APP.Bi(null,new $APP.k(null,6,["url",null,"tel",null,"text",null,"textarea",null,"password",null,"search",null],null),null),zPa=new $APP.k(null,4,[DQa,"ReagentInput",AQa,rY,gRa,function(a){return a.wi=null},YOa,function(a,b,c,d,e){iPa(c);return XX(e,a,b,c,d)}],null);var wPa=/([^\s\.#]+)(?:#([^\s\.#]+))?(?:\.([^\s#]+))?/,lPa={"class":"className","for":"htmlFor",charset:"charSet"},nPa={},vPa={};$APP.g=DPa.prototype;$APP.g.X=function(a,b){return new DPa(this.pd,this.id,this.Jj,this.Ph,b)};$APP.g.V=function(){return this.jm};$APP.g.zm=function(){return this.id};$APP.g.Ak=function(a,b,c){return this.Ph.j?this.Ph.j(this,b,c):this.Ph.call(null,this,b,c)};
$APP.g.yk=function(a,b){return"object"!==$APP.fa(b)?b:$APP.Fe(b)?CPa(b,this,this.Jj):$APP.Le(b)?BPa(b,this):SX(b)?$APP.Hi(b):(null!=b?b.J&2147483648||$APP.xd===b.Ma||(b.J?0:$APP.Jb($APP.Nc,b)):$APP.Jb($APP.Nc,b))?$APP.zj.l($APP.B([b])):b};$APP.g.zk=function(a,b,c,d,e){return qPa(this,b,c,d,e)};$APP.DY=GPa($APP.Xf);var EY=function EY(a){switch(arguments.length){case 1:return EY.g(arguments[0]);case 2:return EY.h(arguments[0],arguments[1]);case 3:return EY.j(arguments[0],arguments[1],arguments[2]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return EY.l(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.Fd(c.slice(3),0,null):null)}};EY.g=function(a){return EY.h(a,null)};EY.h=function(a,b){return $APP.Cu.nbb$internal$react.createElement(a,b)};
EY.j=function(a,b,c){return $APP.Cu.nbb$internal$react.createElement(a,b,c)};EY.l=function(a,b,c,d){return $APP.sg.N($APP.Cu.nbb$internal$react.createElement,a,b,c,d)};EY.F=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);var d=$APP.w(c);c=$APP.v(d);d=$APP.w(d);return this.l(b,a,c,d)};EY.A=3;var FY=function FY(a){switch(arguments.length){case 1:return FY.g(arguments[0]);case 2:return FY.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};
FY.g=function(a){return $APP.WX($APP.DY,a)};FY.h=function(a,b){return $APP.WX(b,a)};FY.A=2;var GY=function GY(a){switch(arguments.length){case 1:return GY.g(arguments[0]);case 2:return GY.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};GY.g=function(a){return GY.h(a,$APP.DY)};GY.h=function(a,b){return JOa(a)?a:ZOa(a,b)};GY.A=2;
var HY=function HY(a){switch(arguments.length){case 1:return HY.g(arguments[0]);case 2:return HY.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};HY.g=function(a){return qY(a,$APP.DY)};HY.h=function(a,b){return qY(a,b)};HY.A=2;
var IY=function IY(a){switch(arguments.length){case 0:return IY.C();case 1:return IY.g(arguments[0]);case 2:return IY.h(arguments[0],arguments[1]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return IY.l(arguments[0],arguments[1],2<c.length?new $APP.Fd(c.slice(2),0,null):null)}};IY.C=function(){return null};IY.g=function(a){return tY.g(a)};IY.h=function(a,b){return tY.h(a,b)};IY.l=function(a,b,c){return $APP.sg.D(tY,a,b,c)};
IY.F=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.l(b,a,c)};IY.A=2;var JY=function JY(a){switch(arguments.length){case 1:return JY.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return JY.l(arguments[0],1<c.length?new $APP.Fd(c.slice(1),0,null):null)}};JY.g=function(a){return lY.g(a)};JY.l=function(a,b){return $APP.sg.j(lY,a,b)};JY.F=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};JY.A=1;
var KY=function KY(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return KY.l(arguments[0],1<c.length?new $APP.Fd(c.slice(1),0,null):null)};KY.l=function(a,b){return eY(a,b)};KY.A=1;KY.F=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};var LY=function LY(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return LY.l(arguments[0],1<c.length?new $APP.Fd(c.slice(1),0,null):null)};LY.l=function(a,b){return zOa(a,b)};
LY.A=1;LY.F=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};var MY=function MY(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return MY.l(arguments[0],arguments[1],arguments[2],3<c.length?new $APP.Fd(c.slice(3),0,null):null)};
MY.l=function(a,b,c,d){var e=$APP.Xn.g("with-let");a=$APP.gj.g(e);var f=$APP.Xn.g("init");c=$APP.Fh.h(new $APP.H(null,2,5,$APP.I,[f,$APP.T.g($APP.u($APP.K.h(new $APP.D(null,XQa,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.h(new $APP.D(null,$APP.XK,null,1,null),new $APP.D(null,e,null,1,null)))),null,1,null))))],null),$APP.ru.h(function(t,q){if($APP.rg(t))return q;t=$APP.lf(t,2);return $APP.T.g($APP.u($APP.K.l(new $APP.D(null,$APP.qk,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.l(new $APP.D(null,
$APP.JJ,null,1,null),new $APP.D(null,f,null,1,null),$APP.B([new $APP.D(null,$APP.T.g($APP.u($APP.K.h(new $APP.D(null,$APP.LN,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.l(new $APP.D(null,QQa,null,1,null),new $APP.D(null,e,null,1,null),$APP.B([new $APP.D(null,t,null,1,null)])))),null,1,null)))),null,1,null)])))),null,1,null),$APP.B([new $APP.D(null,$APP.T.g($APP.u($APP.K.l(new $APP.D(null,$APP.Nua,null,1,null),new $APP.D(null,e,null,1,null),$APP.B([new $APP.D(null,t,null,1,null),new $APP.D(null,
q,null,1,null)])))),null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.l(new $APP.D(null,$APP.Boa,null,1,null),new $APP.D(null,e,null,1,null),$APP.B([new $APP.D(null,t,null,1,null)])))),null,1,null)]))))},c));var h=function(){var t=$APP.ne(d);return $APP.Le(t)&&$APP.y.h($APP.nk,$APP.v(t))?new $APP.H(null,2,5,$APP.I,[$APP.Gi(d),$APP.T.g($APP.u($APP.K.l(new $APP.D(null,$APP.Yu,null,1,null),new $APP.D(null,$APP.df($APP.T.g($APP.u($APP.K.C()))),null,1,null),$APP.B([$APP.Ld(t)]))))],null):new $APP.H(null,
2,5,$APP.I,[d,null],null)}();b=$APP.A.j(h,0,null);h=$APP.A.j(h,1,null);h=$APP.l(h)?new $APP.D(null,$APP.T.g($APP.u($APP.K.l(new $APP.D(null,$APP.Jq,null,1,null),new $APP.D(null,$APP.df($APP.T.g($APP.u($APP.K.h(new $APP.D(null,jQa,null,1,null),new $APP.D(null,h,null,1,null))))),null,1,null),$APP.B([new $APP.D(null,$APP.T.g($APP.u($APP.K.l(new $APP.D(null,$APP.qk,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.g(new $APP.D(null,$Qa,null,1,null)))),null,1,null),$APP.B([new $APP.D(null,$APP.T.g($APP.u($APP.K.l(new $APP.D(null,
$APP.Bz,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.h(new $APP.D(null,$APP.CH,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.h(new $APP.D(null,XPa,null,1,null),new $APP.D(null,e,null,1,null)))),null,1,null)))),null,1,null),$APP.B([new $APP.D(null,$APP.T.g($APP.u($APP.K.l(new $APP.D(null,sQa,null,1,null),new $APP.D(null,e,null,1,null),$APP.B([new $APP.D(null,jQa,null,1,null)])))),null,1,null)])))),null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.g(new $APP.D(null,jQa,null,1,null)))),
null,1,null)])))),null,1,null)])))),null,1,null):null;var n=$APP.Xn.g("res");return $APP.T.g($APP.u($APP.K.l(new $APP.D(null,$APP.Jq,null,1,null),new $APP.D(null,$APP.df($APP.T.g($APP.u($APP.K.h(new $APP.D(null,e,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.h(new $APP.D(null,hRa,null,1,null),new $APP.D(null,a,null,1,null)))),null,1,null))))),null,1,null),$APP.B([new $APP.D(null,null,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.l(new $APP.D(null,$APP.Jq,null,1,null),new $APP.D(null,$APP.Fh.h(c,
new $APP.H(null,2,5,$APP.I,[n,$APP.T.g($APP.u($APP.K.h(new $APP.D(null,$APP.pk,null,1,null),b)))],null)),null,1,null),$APP.B([h,new $APP.D(null,n,null,1,null)])))),null,1,null)]))))};MY.A=3;MY.F=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);var d=$APP.w(c);c=$APP.v(d);d=$APP.w(d);return this.l(b,a,c,d)};var NY=function NY(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return NY.l(0<c.length?new $APP.Fd(c.slice(0),0,null):null)};
NY.l=function(a){return $APP.T.g($APP.u($APP.K.h(new $APP.D(null,VPa,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.l(new $APP.D(null,$APP.Yu,null,1,null),new $APP.D(null,$APP.df($APP.T.g($APP.u($APP.K.C()))),null,1,null),$APP.B([a])))),null,1,null))))};NY.A=0;NY.F=function(a){return this.l($APP.u(a))};
var OY=$APP.uS.h($APP.KI,null),uRa=$APP.gi([cQa,PQa,aQa,$APP.tz,mRa,pQa,aRa,TQa,pRa,WPa,wQa,BY,oQa,zY],[function(){var a=new $APP.Cd(function(){return HY},NQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.KI,cQa,"reagent/core.cljs",19,new $APP.k(null,6,[$APP.cA,!1,$APP.Is,2,$APP.$N,2,$APP.pN,new $APP.H(null,2,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.Qy],null),new $APP.H(null,2,5,$APP.I,[$APP.Qy,$APP.yY],null)],null),$APP.Z,$APP.J(new $APP.H(null,
1,5,$APP.I,[$APP.Qy],null),new $APP.H(null,2,5,$APP.I,[$APP.Qy,$APP.yY],null)),$APP.AF,$APP.J(null,null)],null),1,68,68,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.Qy],null),new $APP.H(null,2,5,$APP.I,[$APP.Qy,$APP.yY],null)),"Creates JS class based on provided Clojure map, for example:\n\n  ```cljs\n  {;; Constructor\n   :constructor (fn [this props])\n   :get-initial-state (fn [this])\n   ;; Static methods\n   :get-derived-state-from-props (fn [props state] partial-state)\n   :get-derived-state-from-error (fn [error] partial-state)\n   ;; Methods\n   :get-snapshot-before-update (fn [this old-argv new-argv] snapshot)\n   :should-component-update (fn [this old-argv new-argv])\n   :component-did-mount (fn [this])\n   :component-did-update (fn [this old-argv old-state snapshot])\n   :component-will-unmount (fn [this])\n   :component-did-catch (fn [this error info])\n   :reagent-render (fn [args....])\n   ;; Or alternatively:\n   :render (fn [this])\n   ;; Deprecated methods:\n   :UNSAFE_component-will-receive-props (fn [this new-argv])\n   :UNSAFE_component-will-update (fn [this new-argv new-state])\n   :UNSAFE_component-will-mount (fn [this])}\n  ```\n\n  Everything is optional, except either :reagent-render or :render.\n\n  Map keys should use `React.Component` method names (https://reactjs.org/docs/react-component.html),\n  and can be provided in snake-case or camelCase.\n\n  State can be initialized using constructor, which matches React.Component class,\n  or using getInitialState which matches old React createClass function and is\n  now implemented by Reagent for compatibility.\n\n  State can usually be anything, e.g. Cljs object. But if using getDerivedState\n  methods, the state has to be plain JS object as React implementation uses\n  Object.assign to merge partial state into the current state.\n\n  React built-in static methods or properties are automatically defined as statics.",
$APP.l(HY)?HY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return KY},nRa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.KI,PQa,"reagent/core.cljs",
12,new $APP.k(null,6,[$APP.cA,!0,$APP.Is,1,$APP.$N,1,$APP.pN,new $APP.H(null,1,5,$APP.I,[$APP.J($APP.wK,$APP.gD)],null),$APP.Z,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.wK,$APP.kk,$APP.gD],null)),$APP.AF,$APP.J(null)],null),1,218,218,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.wK,$APP.kk,$APP.gD],null)),"Takes a function and optional arguments, and returns a derefable\n  containing the output of that function. If the function derefs\n  Reagent atoms (or track, etc), the value will be updated whenever\n  the atom changes.\n\n  In other words, `@(track foo bar)` will produce the same result\n  as `(foo bar)`, but foo will only be called again when the atoms it\n  depends on changes, and will only trigger updates of components when\n  its result changes.\n\n  track is lazy, i.e the function is only evaluated on deref.",
$APP.l(KY)?KY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return MY},kRa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.gq,$APP.EP,$APP.Z,$APP.M,$APP.JF],[AY,aQa,"sci/configs/reagent/reagent.cljs",
23,new $APP.k(null,6,[$APP.cA,!0,$APP.Is,1,$APP.$N,1,$APP.pN,$APP.J($APP.J($APP.gz,$APP.xB)),$APP.Z,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.gz,$APP.kk,$APP.xB],null)),$APP.AF,$APP.J(null)],null),1,10,!0,10,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.gz,$APP.kk,$APP.xB],null)),null,$APP.l(MY)?MY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=
$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return JY},eQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.KI,$APP.tz,"reagent/core.cljs",11,new $APP.k(null,6,[$APP.cA,!0,$APP.Is,1,$APP.$N,1,$APP.pN,new $APP.H(null,1,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.PK],null)],null),$APP.Z,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.PK],null),new $APP.H(null,3,5,$APP.I,[$APP.PK,
$APP.kk,$APP.BA],null)),$APP.AF,$APP.J(null,null)],null),1,211,211,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.PK],null),new $APP.H(null,3,5,$APP.I,[$APP.PK,$APP.kk,$APP.BA],null)),"Like clojure.core/atom, except that it keeps track of derefs.\n  Reagent components that derefs one of these are automatically\n  re-rendered.",$APP.l(JY)?JY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?
$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return IY},lRa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.KI,mRa,"reagent/core.cljs",18,new $APP.k(null,6,[$APP.cA,!0,$APP.Is,2,$APP.$N,2,$APP.pN,new $APP.H(null,3,5,$APP.I,[$APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.YD],null),new $APP.H(null,2,5,$APP.I,[wY,vY],null)],null),$APP.Z,
$APP.J($APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.YD],null),new $APP.H(null,2,5,$APP.I,[wY,vY],null),new $APP.H(null,4,5,$APP.I,[wY,vY,$APP.kk,FQa],null)),$APP.AF,$APP.J(null,null,null,null)],null),1,179,179,$APP.J($APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.YD],null),new $APP.H(null,2,5,$APP.I,[wY,vY],null),new $APP.H(null,4,5,$APP.I,[wY,vY,$APP.kk,FQa],null)),"Function which normalizes and combines class values to a string\n\n  Reagent allows classes to be defined as:\n  - Strings\n  - Named objects (Symbols or Keywords)\n  - Collections of previous types",
$APP.l(IY)?IY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return NY},EQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.gq,$APP.EP,$APP.Z,$APP.M,$APP.JF],[AY,pQa,"sci/configs/reagent/reagent.cljs",
23,new $APP.k(null,6,[$APP.cA,!0,$APP.Is,-2,$APP.$N,-2,$APP.pN,$APP.J($APP.Kd),$APP.Z,$APP.J($APP.Sg),$APP.AF,$APP.J(null)],null),1,62,!0,62,$APP.J($APP.Sg),null,$APP.l(NY)?NY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=
new $APP.Cd(function(){return FY},LQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.KI,aRa,"reagent/core.cljs",17,new $APP.k(null,6,[$APP.cA,!1,$APP.Is,2,$APP.$N,2,$APP.pN,new $APP.H(null,2,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.EJ],null),new $APP.H(null,2,5,$APP.I,[$APP.EJ,$APP.yY],null)],null),$APP.Z,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.EJ],null),new $APP.H(null,2,5,$APP.I,[$APP.EJ,$APP.yY],null)),$APP.AF,$APP.J(null,null)],null),1,46,
46,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.EJ],null),new $APP.H(null,2,5,$APP.I,[$APP.EJ,$APP.yY],null)),"Turns a vector of Hiccup syntax into a React element. Returns form\n  unchanged if it is not a vector.",$APP.l(FY)?FY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,
b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return GY},vQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.KI,TQa,"reagent/core.cljs",25,new $APP.k(null,6,[$APP.cA,!1,$APP.Is,2,$APP.$N,2,$APP.pN,new $APP.H(null,2,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.vK],null),new $APP.H(null,2,5,$APP.I,[$APP.vK,$APP.yY],null)],null),$APP.Z,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.vK],null),new $APP.H(null,2,5,$APP.I,[$APP.vK,$APP.yY],null)),
$APP.AF,$APP.J(null,null)],null),1,59,59,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.vK],null),new $APP.H(null,2,5,$APP.I,[$APP.vK,$APP.yY],null)),"Returns an adapter for a Reagent component, that may be used from\n  React, for example in JSX. A single argument, props, is passed to\n  the component, converted to a map.",$APP.l(GY)?GY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?
$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return EY},eRa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.KI,pRa,"reagent/core.cljs",21,new $APP.k(null,6,[$APP.cA,!0,$APP.Is,3,$APP.$N,3,$APP.pN,new $APP.H(null,3,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.GE],null),new $APP.H(null,2,5,$APP.I,[$APP.GE,xY],null),new $APP.H(null,
3,5,$APP.I,[$APP.GE,xY,$APP.iK],null)],null),$APP.Z,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.GE],null),new $APP.H(null,2,5,$APP.I,[$APP.GE,xY],null),new $APP.H(null,3,5,$APP.I,[$APP.GE,xY,$APP.iK],null),new $APP.H(null,5,5,$APP.I,[$APP.GE,xY,$APP.iK,$APP.kk,$APP.mH],null)),$APP.AF,$APP.J(null,null,null,null)],null),1,17,17,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.GE],null),new $APP.H(null,2,5,$APP.I,[$APP.GE,xY],null),new $APP.H(null,3,5,$APP.I,[$APP.GE,xY,$APP.iK],null),new $APP.H(null,5,5,$APP.I,
[$APP.GE,xY,$APP.iK,$APP.kk,$APP.mH],null)),'Create a native React element, by calling React.createElement directly.\n\n  That means the second argument must be a javascript object (or nil), and\n  that any Reagent hiccup forms must be processed with as-element. For example\n  like this:\n\n  ```cljs\n  (r/create-element "div" #js{:className "foo"}\n    "Hi " (r/as-element [:strong "world!"])\n  ```\n\n  which is equivalent to\n\n  ```cljs\n  [:div.foo "Hi" [:strong "world!"]]\n  ```',$APP.l(EY)?
EY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return HPa},zQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.KI,WPa,"reagent/core.cljs",15,1,242,242,
$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.PK],null)),"Stop the result of track! from updating.",$APP.l(HPa)?HPa.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return IPa},fQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,
$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.KI,wQa,"reagent/core.cljs",13,1,272,272,$APP.J(new $APP.H(null,2,5,$APP.I,[BQa,$APP.Jxa],null)),"Provide a cursor into a Reagent atom.\n\n  Behaves like a Reagent atom but focuses updates and derefs to\n  the specified path within the wrapped Reagent atom. e.g.,\n\n  ```cljs\n  (let [c (cursor ra [:nested :content])]\n    ... @c ;; equivalent to (get-in @ra [:nested :content])\n    ... (reset! c 42) ;; equivalent to (swap! ra assoc-in [:nested :content] 42)\n    ... (swap! c inc) ;; equivalence to (swap! ra update-in [:nested :content] inc)\n    )\n  ```\n\n  The first parameter can also be a function, that should look\n  something like this:\n\n  ```cljs\n  (defn set-get\n    ([k] (get-in @state k))\n    ([k v] (swap! state assoc-in k v)))\n  ```\n\n  The function will be called with one argument – the path passed to\n  cursor – when the cursor is deref'ed, and two arguments (path and\n  new value) when the cursor is modified.\n\n  Given that set-get function, (and that state is a Reagent atom, or\n  another cursor) these cursors are equivalent:\n  `(cursor state [:foo])` and `(cursor set-get [:foo])`.\n\n  Note that a cursor is lazy: its value will not change until it is\n  used. This may be noticed with add-watch.",
$APP.l(IPa)?IPa.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return LY},KQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.KI,BY,"reagent/core.cljs",
13,new $APP.k(null,6,[$APP.cA,!0,$APP.Is,1,$APP.$N,1,$APP.pN,new $APP.H(null,1,5,$APP.I,[$APP.J($APP.wK,$APP.gD)],null),$APP.Z,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.wK,$APP.kk,$APP.gD],null)),$APP.AF,$APP.J(null)],null),1,234,234,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.wK,$APP.kk,$APP.gD],null)),"An eager version of track. The function passed is called\n  immediately, and continues to be called when needed, until stopped\n  with dispose!.",$APP.l(LY)?LY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?
null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return JPa},YPa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.KI,oQa,"reagent/core.cljs",22,1,353,353,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.sH],null)),"Creates Compiler object with given `opts`,\n  this can be passed to `render`, `as-element` and other functions to control\n  how they turn the Reagent-style Hiccup into React components and elements.",
$APP.l(JPa)?JPa.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return uY},UPa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.KI,zY,"reagent/core.cljs",24,
1,52,52,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.vK],null)),"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.l(uY)?uY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,
b,d)}()]),PY=$APP.uS.h($APP.MN,null),vRa=$APP.gi([bQa,$APP.tz,bRa,lQa,hQa,rQa,tQa,xQa,iRa,RPa,BY,MQa],[function(){var a=new $APP.Cd(function(){return COa},hRa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.MN,bQa,"reagent/ratom.cljs",22,1,329,329,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.cI],null)),null,$APP.l(COa)?COa.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,PY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,
$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return lY},cRa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.MN,$APP.tz,"reagent/ratom.cljs",11,new $APP.k(null,6,[$APP.cA,!0,$APP.Is,1,$APP.$N,1,$APP.pN,new $APP.H(null,1,5,$APP.I,[new $APP.H(null,1,5,$APP.I,[$APP.PK],null)],null),$APP.Z,
$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.PK],null),new $APP.H(null,3,5,$APP.I,[$APP.PK,$APP.kk,new $APP.k(null,1,[$APP.uB,new $APP.H(null,2,5,$APP.I,[$APP.Xz,$APP.DL],null)],null)],null)),$APP.AF,$APP.J(null,null)],null),1,172,172,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.PK],null),new $APP.H(null,3,5,$APP.I,[$APP.PK,$APP.kk,new $APP.k(null,1,[$APP.uB,new $APP.H(null,2,5,$APP.I,[$APP.Xz,$APP.DL],null)],null)],null)),"Like clojure.core/atom, except that it keeps track of derefs.",$APP.l(lY)?lY.H:null])),
b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return eY},OQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.MN,bRa,"reagent/ratom.cljs",17,1,228,228,$APP.J(new $APP.H(null,
2,5,$APP.I,[$APP.wK,$APP.gD],null)),null,$APP.l(eY)?eY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return PPa},kQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],
[AY,lQa,"sci/configs/reagent/reagent.cljs",15,1,106,106,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.se($APP.NK,new $APP.k(null,1,[$APP.Dm,$APP.wC],null))],null)),null,$APP.l(PPa)?PPa.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,PY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=
new $APP.Cd(function(){return NPa},jRa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[AY,hQa,"sci/configs/reagent/reagent.cljs",29,1,98,98,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.se($APP.NK,new $APP.k(null,1,[$APP.Dm,$APP.wC],null)),$APP.se($APP.vK,new $APP.k(null,1,[$APP.Dm,$APP.wC],null))],null)),null,$APP.l(NPa)?NPa.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,PY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],
null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return tOa},$Qa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Dm,$APP.Z,$APP.M,$APP.JF],[$APP.MN,rQa,"reagent/ratom.cljs",25,1,17,17,$APP.LI,$APP.J($APP.Sg),null,tOa?tOa.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,PY,$APP.O,
a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return OPa},VQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[AY,tQa,"sci/configs/reagent/reagent.cljs",16,1,102,102,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.se($APP.NK,new $APP.k(null,1,[$APP.Dm,$APP.wC],null)),IQa],null)),
null,$APP.l(OPa)?OPa.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,PY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return bY},VPa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.MN,xQa,"reagent/ratom.cljs",
20,new $APP.k(null,6,[$APP.cA,!0,$APP.Is,1,$APP.$N,1,$APP.pN,new $APP.H(null,1,5,$APP.I,[$APP.J($APP.wK,new $APP.k(null,1,[$APP.uB,new $APP.H(null,3,5,$APP.I,[gQa,TPa,fRa],null)],null))],null),$APP.Z,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.wK,$APP.kk,new $APP.k(null,1,[$APP.uB,new $APP.H(null,3,5,$APP.I,[gQa,TPa,fRa],null)],null)],null)),$APP.AF,$APP.J(null)],null),1,517,517,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.wK,$APP.kk,new $APP.k(null,1,[$APP.uB,new $APP.H(null,3,5,$APP.I,[gQa,TPa,fRa],null)],
null)],null)),null,$APP.l(bY)?bY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return KPa},iQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[AY,iRa,"sci/configs/reagent/reagent.cljs",
21,1,85,85,$APP.J($APP.Sg),"Read-only access to the ratom context.",$APP.l(KPa)?KPa.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,PY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return LPa},CQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,
$APP.EP,$APP.Z,$APP.M,$APP.JF],[AY,RPa,"sci/configs/reagent/reagent.cljs",18,1,90,90,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.se($APP.PK,new $APP.k(null,1,[$APP.Dm,$APP.wC],null))],null)),null,$APP.l(LPa)?LPa.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,PY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,
b,d)}(),function(){var a=new $APP.Cd(function(){return CY},SPa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.MN,BY,"reagent/ratom.cljs",13,new $APP.k(null,6,[$APP.cA,!0,$APP.Is,1,$APP.$N,1,$APP.pN,new $APP.H(null,1,5,$APP.I,[$APP.J($APP.wK,$APP.gD)],null),$APP.Z,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.wK,$APP.kk,$APP.gD],null)),$APP.AF,$APP.J(null)],null),1,242,242,$APP.J(new $APP.H(null,3,5,$APP.I,[$APP.wK,$APP.kk,$APP.gD],null)),null,$APP.l(CY)?
CY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,OY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),function(){var a=new $APP.Cd(function(){return MPa},HQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[AY,MQa,"sci/configs/reagent/reagent.cljs",24,
1,94,94,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.se($APP.PK,new $APP.k(null,1,[$APP.Dm,$APP.wC],null))],null)),null,$APP.l(MPa)?MPa.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,PY,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}()]),wRa=$APP.uS.h(SQa,null),QY=function QY(a){for(var c=[],d=
arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return QY.l(arguments[0],arguments[1],2<c.length?new $APP.Fd(c.slice(2),0,null):null)};
QY.l=function(a,b,c){return $APP.l(!0)?$APP.T.g($APP.u($APP.K.l(new $APP.D(null,$APP.Bz,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.h(new $APP.D(null,$APP.ZE,null,1,null),new $APP.D(null,UQa,null,1,null)))),null,1,null),$APP.B([new $APP.D(null,$APP.T.g($APP.u($APP.K.l(new $APP.D(null,YQa,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.l(new $APP.D(null,$APP.qk,null,1,null),new $APP.D(null,$APP.T.g($APP.u($APP.K.g(new $APP.D(null,ZQa,null,1,null)))),null,1,null),$APP.B([new $APP.D(null,
dRa,null,1,null),new $APP.D(null,UQa,null,1,null)])))),null,1,null),$APP.B([new $APP.D(null,$APP.T.g($APP.u($APP.K.h(new $APP.D(null,$APP.Tu,null,1,null),c))),null,1,null)])))),null,1,null)])))):null};QY.A=2;QY.F=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.l(b,a,c)};
var xRa=new $APP.k(null,3,[$APP.KH,function(){var a=new $APP.Cd(function(){return QY},uQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.gq,$APP.EP,$APP.Z,$APP.M,$APP.JF],[AY,$APP.KH,"sci/configs/reagent/reagent.cljs",20,new $APP.k(null,6,[$APP.cA,!0,$APP.Is,0,$APP.$N,0,$APP.pN,$APP.J($APP.J($APP.EG)),$APP.Z,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.kk,$APP.EG],null)),$APP.AF,$APP.J(null)],null),1,132,!0,132,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.kk,$APP.EG],null)),"Print with console.error.",
$APP.l(QY)?QY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,wRa,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),$Pa,function(){var a=new $APP.Cd(function(){return QPa},RQa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[AY,$Pa,"sci/configs/reagent/reagent.cljs",
17,1,129,129,$APP.J($APP.Sg),null,$APP.l(QPa)?QPa.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,wRa,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),mQa,function(){var a=new $APP.Cd(function(){return rRa},dRa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],
[SQa,mQa,"reagent/debug.cljs",23,1,10,10,$APP.Kd,null,$APP.l(rRa)?rRa.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,wRa,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}()],null);$APP.Qu(new $APP.k(null,1,[$APP.Cq,new $APP.k(null,3,[$APP.KI,$APP.vi.j(uRa,zY,function(){var a=$APP.uS.g($APP.KI),b=new $APP.Cd(function(){return uY},UPa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[$APP.KI,zY,"reagent/core.cljs",24,1,52,52,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.vK],null)),"Returns an adapter for a native React class, that may be used\n  just like a Reagent component function or class in Hiccup forms.",$APP.l(uY)?uY.H:null])),c=$APP.p(b),
d=$APP.te(b);b=$APP.l(null)?null:$APP.O.g(d);a=new $APP.k(null,4,[$APP.Q,a,$APP.O,b,$APP.Z,$APP.Z.g(d),$APP.M,$APP.M.g(d)],null);return $APP.l($APP.Mq.g(d))?$APP.gS.j(b,c,a):$APP.l(function(){var e=$APP.gq.g(d);return $APP.l(e)?e:$APP.tq.g(d)}())?$APP.hS.j(b,c,a):$APP.cu.j(b,c,a)}()),$APP.MN,vRa,SQa,xRa],null)],null));