import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_goog_string.js";
import "./nbb_pprint.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_net from"node:net";import*as esm_import$node_fs from"node:fs";import*as esm_import$node_path from"node:path";
var aab=function(a,b){a=a.indexOf(b);if(0>a)throw Error("out of input");return a},R_=function(a,b){if(a.length<b)throw Error("out of input");return a.slice(b)},S_=function(a,b){if(b>a.length)throw Error("out of input");return a.slice(0,b)},bab=function(a){return(new TextEncoder).encode(a).length},T_=function(a){return $APP.k($APP.zu.g($APP.n($APP.KO)))?console.debug($APP.mn.h(" ",a)):null},dab=function(a){return function(b,c){b=$APP.Yf(b);var d=$APP.C.h(b,$APP.Eq),e=$APP.C.h(b,cab);c=$APP.ui.j(c,
"id",d);c=$APP.k(e)?$APP.ui.j(c,"session",e):c;return a.h?a.h(b,c):a.call(null,b,c)}},fab=function(){var a=eab;return function(b,c){b=$APP.an.j(b,$APP.KI,$APP.fj);return a.h?a.h(b,c):a.call(null,b,c)}},hab=function(){var a=gab();return function(b,c){T_($APP.z(["request",b]));return a.h?a.h(b,c):a.call(null,b,c)}},iab=function(a){return function(b,c){T_($APP.z(["response",c]));return a.h?a.h(b,c):a.call(null,b,c)}},gab=function(){var a=fab();return function(b,c){return a.h?a.h(b,c):a.call(null,b,c)}},
jab=function(a){return $APP.ui.j($APP.Gi(new $APP.H(null,3,5,$APP.I,["major","minor","incremental"],null),$APP.bz.g(a.split("."))),"version-string",a)},lab=function(a,b,c){if($APP.k(a))if(a=kab.g?kab.g(a):kab.call(null,a),$APP.k(a)){b=$APP.Yf(b);var d=$APP.C.h(b,$APP.xNa),e=$APP.C.h(b,$APP.bNa),f=$APP.C.h(b,$APP.mNa);b=$APP.rb;var l=$APP.$i,p=$APP.hR;$APP.rb=e;$APP.$i=f;$APP.hR=d;try{var u=new $APP.gb;d=$APP.tb;e=$APP.ub;$APP.tb=!0;$APP.ub=function(t){return u.append(t)};try{a.g?a.g(c):a.call(null,
c)}finally{$APP.ub=e,$APP.tb=d}return $APP.m.g(u)}finally{$APP.hR=p,$APP.$i=l,$APP.rb=b}}else return T_($APP.z(["Pretty-Printing is only supported for clojure.core/prn and clojure.pprint/pprint."])),$APP.yj.l($APP.z([c]));else return $APP.yj.l($APP.z([c]))},mab=function(a,b,c){$APP.AO.h($APP.kO,$APP.sg(c));var d=$APP.Hq.g($APP.fk(c));d=$APP.k(d)?d:c.message;$APP.k(d)&&(d=new $APP.h(null,1,["err",[$APP.m.g(d),"\n"].join("")],null),a.h?a.h(b,d):a.call(null,b,d));c=new $APP.h(null,2,["ex",$APP.m.g(c),
"ns",$APP.m.g($APP.n($APP.Lq))],null);return a.h?a.h(b,c):a.call(null,b,c)},rab=function(a,b){var c=$APP.Yf(a),d=$APP.C.h(c,$APP.Q);a=$APP.C.h(c,U_);var e=$APP.C.h(c,$APP.Vl);$APP.C.h(c,nab);$APP.C.h(c,oab);var f=$APP.wp(a),l=function t(u){try{var A=function(){var E=$APP.Q.g($APP.ge(u));if($APP.k(E))return E;E=$APP.n(V_);return $APP.k(E)?E:d}(),B=$APP.aja(f,new $APP.h(null,3,[$APP.Q,A,$APP.Vl,e,$APP.dK,$APP.Fw],null));return $APP.x.h($APP.WH,B)?Promise.resolve(u):$APP.LKa(B,new $APP.h(null,3,[$APP.Q,
A,$APP.Vl,e,$APP.dK,$APP.Fw],null)).then(function(E){var G=$APP.y.j(E,0,null),O=$APP.y.j(E,1,null);O=$APP.Q.g(O);$APP.vg(V_,O);$APP.AO.h($APP.jO,$APP.sg($APP.n($APP.iO)));$APP.AO.h($APP.iO,$APP.sg($APP.n($APP.hO)));$APP.AO.h($APP.hO,$APP.sg(G));G=lab(pab.g(c),qab.g(c),G);G=new $APP.h(null,2,["value",G,"ns",$APP.m.g(O)],null);b.h?b.h(c,G):b.call(null,c,G);return t(E)})}catch(E){return mab(b,c,E),t(null)}};$APP.Xp($APP.Wf([$APP.Lq,d,$APP.xq,e,$APP.YM,$APP.n($APP.YM),$APP.cN,!0]));return function(){$APP.AO.h($APP.WM,
$APP.sg(function(u){u=new $APP.h(null,1,["out",u],null);return b.h?b.h(c,u):b.call(null,c,u)}));return l(null).catch($APP.Pl.j(mab,b,c)).finally(function(){var u=new $APP.h(null,2,["ns",$APP.m.g($APP.n(V_)),"status",new $APP.H(null,1,5,$APP.I,["done"],null)],null);return b.h?b.h(c,u):b.call(null,c,u)})}().finally(function(){return $APP.Zp()})},sab=function(a,b){a=$APP.Yf(a);var c=$APP.C.h(a,$APP.Q),d=$APP.ui.j;c=$APP.k(c)?$APP.QKa($APP.Cu(),$APP.kj.g(c)):null;$APP.k(c)||(c=$APP.n(V_),c=$APP.k(c)?
c:$APP.n($APP.Lq));return rab(d.call($APP.ui,a,$APP.Q,c),b)},uab=function(a,b){var c=$APP.Yf(a),d=$APP.C.h(c,$APP.Q),e=$APP.KI.g(c);try{var f=$APP.Q.g(c),l=function(){var O=$APP.bF.g(c);return $APP.k(O)?O:$APP.zm.g(c)}(),p=function(){var O=$APP.k(d)?$APP.QKa($APP.Cu(),$APP.kj.g(d)):null;if($APP.k(O))return O;O=$APP.n(V_);return $APP.k(O)?O:$APP.n($APP.Lq)}(),u=$APP.Wf([$APP.Lq,p]);$APP.Xp(u);try{var t=$APP.du($APP.Cu(),$APP.rV("\n(let [ns '%s\n      full-sym '%s]\n  (when-let [v (ns-resolve ns full-sym)]\n    (let [m (meta v)]\n      (assoc m :arglists (:arglists m)\n       :doc (:doc m)\n       :name (:name m)\n       :ns (some-\x3e m :ns ns-name)\n       :val @v))))",
f,l)),A=$APP.M.g(t),B=$APP.Vl.g(t),E=$APP.Wl.g(t),G=function(){var O=e instanceof $APP.F?e.N:null;switch(O){case "eldoc":return O=new $APP.h(null,5,["ns",$APP.Q.g(t),"name",$APP.N.g(t),"eldoc",$APP.on.h(function(T){return $APP.on.h($APP.m,T)},$APP.V.g(t)),"type",$APP.Le($APP.hu.g(t))?"function":"variable","status",new $APP.H(null,1,5,$APP.I,["done"],null)],null),$APP.k(A)?$APP.ui.j(O,"docstring",A):O;case "info":case "lookup":return O=new $APP.h(null,4,["ns",$APP.Q.g(t),"name",$APP.N.g(t),"arglists-str",
$APP.mn.h("\n",$APP.ej.h($APP.yj,$APP.V.g(t))),"status",new $APP.H(null,1,5,$APP.I,["done"],null)],null),O=$APP.k(A)?$APP.ui.j(O,"doc",A):O,O=$APP.k(B)?$APP.ui.j(O,"file",B):O,$APP.k(E)?$APP.ui.j(O,"line",E):O;default:throw Error(["No matching clause: ",$APP.m.g(O)].join(""));}}();return b.h?b.h(c,G):b.call(null,c,G)}finally{$APP.Zp()}}catch(O){if(O instanceof Error)return a=O,f=function(){var T=new $APP.zi(null,new $APP.h(null,1,["done",null],null),null);return $APP.x.h(e,tab)?$APP.vf.h(T,"no-eldoc"):
T}(),a=new $APP.h(null,2,["status",f,"ex",$APP.m.g(a)],null),b.h?b.h(c,a):b.call(null,c,a);throw O;}},eab=function(a,b){a=$APP.Yf(a);var c=$APP.C.h(a,$APP.KI),d=$APP.C.h(vab,c);if($APP.k(d))return d.h?d.h(a,b):d.call(null,a,b);console.warn($APP.mn.h(" ",$APP.z(["Unhandled operation",c])));c=new $APP.h(null,1,["status",new $APP.H(null,3,5,$APP.I,["error","unknown-op","done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},wab=function(a){return function(b,c){return a.write(W_(c))}},xab=function(a,
b){T_($APP.z(["Connection accepted"]));b.setNoDelay(!0);var c=hab(),d=dab(iab(wab(b))),e=$APP.Aj.g(null);b.on("data",function(f){var l=$APP.n(e);if($APP.k(l)){f=[$APP.m.g(l),$APP.m.g(f)].join("");$APP.vg(e,null);var p=f}else p=f;a:for(f=$APP.z([$APP.cz,!0]),l=$APP.Sg;;){var u=$APP.qg.j(X_,p,f);p=$APP.y.j(u,0,null);u=$APP.y.j(u,1,null);if(null==p){l=new $APP.H(null,2,5,$APP.I,[l,u],null);break a}l=$APP.vf.h(l,p);p=u}f=$APP.y.j(l,0,null);l=$APP.y.j(l,1,null);$APP.hl(l)||$APP.vg(e,l);f=$APP.r(f);l=null;
for(var t=u=0;;)if(t<u)p=l.ea(null,t),c(p,d),t+=1;else if(f=$APP.r(f))l=f,$APP.Ee(l)?(f=$APP.cd(l),u=$APP.dd(l),l=f,p=$APP.be(f),f=u,u=p):(p=$APP.v(l),c(p,d),f=$APP.w(l),l=null,u=0),t=0;else return null});return b.on("close",function(f){return $APP.k(f)?T_($APP.z(["Connection lost"])):T_($APP.z(["Connection closed"]))})},Aab=function(a){return Promise.resolve($APP.tQ(esm_import$node_path.resolve("script.cljs"),null)).then(function(){function b(e){return $APP.IKa(new $APP.D(null,$APP.Ak,new $APP.D(null,
new $APP.D(null,$APP.Ak,new $APP.D(null,e,null,1,null),2,null),null,1,null),2,null))}var c=$APP.y.j($APP.LO,0,null),d=$APP.y.j($APP.LO,1,null);return b(c).then(function(){return b(d)})}).then(function(){var b=$APP.Nl.l($APP.z([$APP.n($APP.KO),a])),c=function(){var f=$APP.yH.g(b);return $APP.k(f)?f:0}(),d=function(){var f=$APP.CL.g(b);return $APP.k(f)?f:"127.0.0.1"}();(function(){var f=$APP.Eb(b)?b.lo:yab.g(b);return $APP.k(f)?f:"info"})();var e=esm_import$node_net.createServer($APP.Pl.h(xab,$APP.Xf));
e.listen(c,d,function(){var f=e.address(),l=f.port;f=f.address;$APP.Ry.l($APP.z([["nREPL server started on port ",$APP.m.g(l)," on host ",$APP.m.g(f)," - nrepl://",$APP.m.g(f),":",$APP.m.g(l)].join("")]));$APP.AO.h($APP.cN,$APP.sg(!0));try{return esm_import$node_fs.writeFileSync(".nrepl-port",$APP.m.g(l))}catch(p){return console.warn($APP.mn.h(" ",$APP.z(["Could not write .nrepl-port",p])))}});return $APP.vg(zab,e)})},Bab=new $APP.q("nbb.impl.nrepl-server","stop-server!","nbb.impl.nrepl-server/stop-server!",
1628751782,null),qab=new $APP.F("nrepl.middleware.print","options","nrepl.middleware.print/options",868480159),Cab=new $APP.q(null,"nbb.impl.nrepl-server","nbb.impl.nrepl-server",-1821079079,null),cab=new $APP.F(null,"session","session",1008279103),Dab=new $APP.q("nbb.impl.nrepl-server","start-server!","nbb.impl.nrepl-server/start-server!",-2119141227,null),Eab=new $APP.F(null,"load-file","load-file",-424586670),U_=new $APP.F(null,"code","code",1586293142),yab=new $APP.F(null,"log_level","log_level",
-1756736313),pab=new $APP.F("nrepl.middleware.print","print","nrepl.middleware.print/print",-1616742548),Fab=new $APP.F(null,"clone","clone",711747572),Gab=new $APP.F(null,"close","close",1835149582),Hab=new $APP.F(null,"info","info",-317069002),Iab=new $APP.F(null,"macroexpand","macroexpand",-130598183),Jab=new $APP.F(null,"complete","complete",-500388775),oab=new $APP.F(null,"_line","_line",232847719),Kab=new $APP.q(null,"server","server",-1155245649,null),Lab=new $APP.F(null,"lookup","lookup",
1225356838),Mab=new $APP.F(null,"expander","expander",379138924),nab=new $APP.F(null,"_load-file?","_load-file?",-1198848711),Nab=new $APP.F(null,"describe","describe",1369790582),tab=new $APP.F(null,"eldoc","eldoc",-1321421900),Oab=new $APP.q(null,"stop-server!","stop-server!",-410772185,null),Pab=new $APP.F(null,"load-file?","load-file?",1892536169);var Y_=function Y_(a,b){switch($APP.m.g(S_(a,1))){case "i":return a=R_(a,1),b=aab(a,"e"),new $APP.H(null,2,5,$APP.I,[parseInt(S_(a,b)),R_(a,b+1)],null);case "l":var d=a=R_(a,1);for(a=$APP.Tc($APP.Sg);;){if($APP.x.h($APP.m.g(S_(d,1)),"e"))return new $APP.H(null,2,5,$APP.I,[$APP.Vc(a),R_(d,1)],null);var e=Y_.h?Y_.h(d,b):Y_.call(null,d,b),f=$APP.y.j(e,0,null),l=$APP.y.j(e,1,null);e=l;a=$APP.Rg.h(a,f);d=e}case "d":for(a=R_(a,1),f=$APP.Yf(b),f=$APP.C.h(f,$APP.cz),d=a,e=$APP.Tc($APP.Xf);;){if($APP.x.h($APP.m.g(S_(d,
1)),"e"))return new $APP.H(null,2,5,$APP.I,[$APP.Vc(e),R_(d,1)],null);a=Y_.h?Y_.h(d,b):Y_.call(null,d,b);d=$APP.y.j(a,0,null);l=$APP.y.j(a,1,null);l=Y_.h?Y_.h(l,b):Y_.call(null,l,b);a=$APP.y.j(l,0,null);l=$APP.y.j(l,1,null);d=$APP.k(f)?$APP.fj.g(d):d;a=$APP.Ih.j(e,d,a);d=l;e=a}default:return b=aab(a,":"),f=parseInt(S_(a,b)),a=R_(a,b+1),new $APP.H(null,2,5,$APP.I,[$APP.m.g(S_(a,f)),R_(a,f)],null)}},X_=function X_(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;
return X_.l(arguments[0],1<c.length?new $APP.Ed(c.slice(1),0,null):null)};X_.l=function(a,b){try{return Y_(a,b)}catch(c){if(c instanceof Error)return new $APP.H(null,2,5,$APP.I,[null,a],null);throw c;}};X_.B=1;X_.G=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};
var W_=function W_(a){for(;;){if("string"===typeof a)return[$APP.m.g(bab(a)),":",a].join("");if(a instanceof $APP.F||a instanceof $APP.q)a=[function(){var c=$APP.Bf(a);return $APP.k(c)?[c,"/"].join(""):null}(),$APP.Fi(a)].join("");else return"number"===typeof a?["i",$APP.m.g(a),"e"].join(""):$APP.ye(a)||$APP.De(a)||null==a?["l",$APP.m.g($APP.qg.h($APP.m,$APP.ej.h(W_,a))),"e"].join(""):$APP.Be(a)?["d",$APP.m.g($APP.qg.h($APP.m,$APP.ej.h(function(){return function(c){var d=$APP.y.j(c,0,null);c=$APP.y.j(c,
1,null);return[$APP.m.g(W_.g?W_.g(d):W_.call(null,d)),$APP.m.g(W_.g?W_.g(c):W_.call(null,c))].join("")}}(a),$APP.Jx.h($APP.v,a)))),"e"].join(""):null}};var V_=$APP.Aj.g(null),kab=new $APP.h(null,1,["cider.nrepl.pprint/pprint",$APP.KS],null),vab=$APP.gi([$APP.uQ,Lab,Gab,Eab,tab,Fab,Nab,Hab,Jab,Iab,$APP.rza],[function(a,b){var c=new $APP.h(null,2,["status",new $APP.H(null,1,5,$APP.I,["done"],null),"classpath",$APP.fl.h($APP.yp(),$APP.Zi(esm_import$node_path.delimiter))],null);return b.h?b.h(a,c):b.call(null,a,c)},uab,function(a,b){var c=new $APP.h(null,1,["status",new $APP.H(null,1,5,$APP.I,["done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},
function(a,b){a=$APP.Yf(a);var c=$APP.C.h(a,$APP.Vl);return rab($APP.ui.l(a,U_,c,$APP.z([Pab,!0,$APP.Q,$APP.n($APP.Lq)])),b)},uab,function(a,b){var c=new $APP.h(null,2,["new-session",$APP.m.g($APP.dk()),"status",new $APP.H(null,1,5,$APP.I,["done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},function(a,b){var c=new $APP.h(null,4,["versions",new $APP.h(null,2,["nbb-nrepl",jab("TODO"),"node",jab(esm_import$node_process.version)],null),"aux",$APP.Xf,"ops",$APP.Gi($APP.ej.h($APP.Fi,$APP.qi(vab)),
$APP.jn.g($APP.Xf)),"status",new $APP.H(null,1,5,$APP.I,["done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},uab,function(a,b){var c=$APP.WKa(a);return b.h?b.h(a,c):b.call(null,a,c)},function(a,b){a=$APP.Yf(a);var c=$APP.C.h(a,U_),d=$APP.C.h(a,Mab);try{return sab($APP.ui.j(a,U_,["( ",$APP.m.g(d),"(quote ",$APP.m.g(c),"))"].join("")),function(e,f){var l=f.g?f.g("value"):f.call(null,"value");f=$APP.k(l)?$APP.ui.j(f,"expansion",l):f;return b.h?b.h(e,f):b.call(null,e,f)})}catch(e){if(e instanceof
Error)return c=new $APP.h(null,3,["ex",$APP.m.g(e),"ns",$APP.m.g($APP.n($APP.Lq)),"status",new $APP.H(null,1,5,$APP.I,["done"],null)],null),b.h?b.h(a,c):b.call(null,a,c);throw e;}},sab]),zab=$APP.Aj.g(null),Z_=function Z_(a){switch(arguments.length){case 0:return Z_.D();case 1:return Z_.g(arguments[0]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};Z_.D=function(){return Z_.g($APP.n(zab))};
Z_.g=function(a){return a.close(function(){$APP.AO.h($APP.WM,$APP.sg($APP.ub));$APP.AO.h($APP.cN,$APP.sg($APP.tb));return $APP.k(esm_import$node_fs.existsSync(".nrepl-port"))?esm_import$node_fs.unlinkSync(".nrepl-port"):null})};Z_.B=1;
var Qab=$APP.EO.h($APP.gA,null),Rab=new $APP.h(null,2,[$APP.ZKa,function(){var a=new $APP.Cd(function(){return Aab},Dab,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.re(Cab,new $APP.h(null,1,[$APP.M,"Original implementation taken from https://github.com/viesti/nrepl-cljs-sci."],null)),$APP.ZKa,"nbb/impl/nrepl_server.cljs",20,1,327,327,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.DH],null)),"Start nRepl server. Accepts options either as JS object or Clojure map.",
$APP.k(Aab)?Aab.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,Qab,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}(),Oab,function(){var a=new $APP.Cd(function(){return Z_},Bab,$APP.gi([$APP.Q,$APP.N,$APP.Vl,$APP.Vz,$APP.SJ,$APP.Om,$APP.Wl,$APP.YL,$APP.V,$APP.M,$APP.oG],[$APP.re(Cab,new $APP.h(null,
1,[$APP.M,"Original implementation taken from https://github.com/viesti/nrepl-cljs-sci."],null)),Oab,"nbb/impl/nrepl_server.cljs",19,new $APP.h(null,6,[$APP.BA,!1,$APP.Os,1,$APP.cL,1,$APP.LK,new $APP.H(null,2,5,$APP.I,[$APP.Sg,new $APP.H(null,1,5,$APP.I,[Kab],null)],null),$APP.V,$APP.J($APP.Sg,new $APP.H(null,1,5,$APP.I,[Kab],null)),$APP.gG,$APP.J(null,null)],null),1,398,398,$APP.J($APP.Sg,new $APP.H(null,1,5,$APP.I,[Kab],null)),null,$APP.k(Z_)?Z_.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?
null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.Q,Qab,$APP.N,a,$APP.V,$APP.V.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Sq.g(c))?$APP.yO.j(a,b,d):$APP.k(function(){var e=$APP.mq.g(c);return $APP.k(e)?e:$APP.zq.g(c)}())?$APP.zO.j(a,b,d):$APP.gu.j(a,b,d)}()],null);$APP.Wu(new $APP.h(null,1,[$APP.Iq,new $APP.h(null,1,[$APP.gA,Rab],null)],null));