import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_module from"node:module";import*as esm_import$node_fs from"node:fs";import*as esm_import$import_meta_resolve from"import-meta-resolve";import*as esm_import$node_path from"node:path";import*as esm_import$node_url from"node:url";var yMa,AMa,rMa,qMa,vMa,BMa,wMa,CMa,zMa;
$APP.pMa=function(a){a=$APP.Ld(a);a=$APP.js.h($APP.Bf,a);a=$APP.qn.h(function(d){return $APP.mu($APP.Fp(),d)},a);var b=$APP.n($APP.Nq),c=$APP.n($APP.wq);return $APP.Ku(a,new $APP.h(null,2,[$APP.R,b,$APP.Sl,c],null))};$APP.sMa=function(a,b){return qMa(rMa,a,b)};
$APP.VO=function(a,b){return Promise.resolve($APP.k($APP.n(tMa))?null:function(){var c=esm_import$node_path.resolve($APP.k(a)?a:"script.cljs"),d=$APP.k($APP.HB.g(b))?$APP.xi.j(b,$APP.HB,$APP.QK.g(esm_import$node_fs.readFileSync($APP.HB.g(b),"utf8"))):function(){var m;a:for(m=c;;){var p=esm_import$node_fs.existsSync(m);p=$APP.k(p)?esm_import$node_fs.lstatSync(m).isDirectory():p;if($APP.k(p)){p=esm_import$node_path.resolve(m,"nbb.edn");if($APP.k(esm_import$node_fs.existsSync(p))){m=p;break a}p=esm_import$node_path.dirname(m)}else p=
esm_import$node_path.dirname(m);if($APP.x.h(p,m)){m=null;break a}m=p}return $APP.k(m)?(p=$APP.QK.g(esm_import$node_fs.readFileSync(m,"utf8")),$APP.xi.l(b,$APP.HB,p,$APP.z([$APP.pJ,esm_import$node_path.dirname(m)]))):b}(),e=uMa.g?uMa.g(c):uMa.call(null,c),f=$APP.l.g(esm_import$node_url.pathToFileURL(c));$APP.Mu.require=e;$APP.Aj.F($APP.Ou,$APP.xi,$APP.yn,e);$APP.Aj.F($APP.Ou,$APP.xi,$APP.Pu,function(m){return esm_import$import_meta_resolve.resolve(m,f)});$APP.vg($APP.qN,d);return Promise.resolve(function(){var m=
function(){var E=$APP.Cb(vMa.g(d));return E?$APP.HB.g(d):E}();if($APP.k(m)){m=wMa.g(m);if($APP.k(m)){m=$APP.r(m);for(var p=null,u=0,t=0;;)if(t<u){var B=p.ha(null,t);$APP.Cb(esm_import$node_path.isAbsolute(B))?$APP.Cp(function(){var E=$APP.pJ.g(d);return $APP.k(E)?esm_import$node_path.resolve(E,B):B}()):$APP.Cp(B);t+=1}else if(m=$APP.r(m)){p=m;if($APP.Fe(p))m=$APP.ed(p),t=$APP.fd(p),p=m,u=$APP.de(m),m=t;else{var C=$APP.v(p);$APP.Cb(esm_import$node_path.isAbsolute(C))?$APP.Cp(function(){var E=$APP.pJ.g(d);
return $APP.k(E)?esm_import$node_path.resolve(E,C):C}()):$APP.Cp(C);m=$APP.w(p);p=null;u=0}t=0}else break}else $APP.Cp(esm_import$node_process.cwd());return shadow_esm_import("./nbb_deps.js")}return $APP.Cp(esm_import$node_process.cwd())}()).then(function(){return $APP.vg(tMa,!0)})}())};$APP.xMa=function(a,b){return $APP.Ot(a,b)};
yMa=function(a,b){b=$APP.lu(a,$APP.$k("(keys (ns-map '%s))","%s",b));b=$APP.fj.h(function(c){return["`",$APP.l.g(c)].join("")},b);b=["[",$APP.on.h(" ",b),"]"].join("");a=$APP.lu(a,b);return $APP.js.h(function(c){return $APP.il($APP.l.g(c),"nbb.internal")},a)};
AMa=function(a,b){var c=$APP.Fp();b=$APP.fl.h(b,/\//);$APP.y.j(b,0,null);var d=$APP.y.j(b,1,null),e=$APP.lu(c,$APP.xj.l($APP.z([$APP.T.g($APP.r($APP.M.l(new $APP.D(null,$APP.Rq,null,1,null),new $APP.D(null,$APP.ef($APP.T.g($APP.r($APP.M.h(new $APP.D(null,zMa,null,1,null),new $APP.D(null,$APP.T.g($APP.r($APP.M.h(new $APP.D(null,$APP.fpa,null,1,null),new $APP.D(null,$APP.T.g($APP.r($APP.M.h(new $APP.D(null,$APP.Ak,null,1,null),new $APP.D(null,a,null,1,null)))),null,1,null)))),null,1,null))))),null,
1,null),$APP.z([new $APP.D(null,$APP.T.g($APP.r($APP.M.l(new $APP.D(null,$APP.gJ,null,1,null),new $APP.D(null,$APP.T.g($APP.r($APP.M.h(new $APP.D(null,$APP.kua,null,1,null),new $APP.D(null,zMa,null,1,null)))),null,1,null),$APP.z([new $APP.D(null,zMa,null,1,null)])))),null,1,null)]))))])));if($APP.k(e)&&(c=$APP.k(d)?function(){var p=$APP.Fa(d,"."),u=$APP.fl.h(d,/\./);p=p?u:$APP.Fi(u);return new $APP.H(null,2,5,$APP.J,[[$APP.l.g(a),"/",$APP.r(p)?[$APP.on.h(".",p),"."].join(""):null].join(""),$APP.qg.j($APP.La,
e,p)],null)}():new $APP.H(null,2,5,$APP.J,[[$APP.l.g(a),"/"].join(""),e],null),$APP.k(c))){var f=$APP.y.j(c,0,null),m=$APP.y.j(c,1,null);c=function(){for(var p=m,u=$APP.Sg;;)if($APP.k(p)){var t=Object.getPrototypeOf(p);u=$APP.Eh.h(u,Object.getOwnPropertyNames(p));p=t}else return u}();return $APP.fj.h(function(p){return new $APP.H(null,2,5,$APP.J,[null,[$APP.l.g(f),$APP.l.g(p)].join("")],null)},c)}return null};
$APP.DMa=function(a){var b=$APP.Xf(a);a=$APP.A.h(b,$APP.R);try{var c=$APP.Fp(),d=$APP.k(a)?$APP.xMa(c,$APP.lj.g(a)):null,e=$APP.Vf([$APP.Nq,$APP.k(d)?d:$APP.n($APP.Nq)]);$APP.bq(e);try{var f=function(){var ma=$APP.Am.g(b);return $APP.k(ma)?ma:$APP.VG.g(b)}();if($APP.k(f)){var m=$APP.Ia(f,"/"),p=m?function(){var ma=$APP.fl.h(f,/\//);ma=null==ma?null:$APP.v(ma);return null==ma?null:$APP.lj.g(ma)}():null,u=yMa(c,$APP.lu(c,"(ns-name *ns*)")),t=$APP.fj.h(function(ma){return new $APP.H(null,3,5,$APP.J,
[$APP.Cf(ma),$APP.Gi(ma),BMa],null)},u),B=$APP.lu(c,"(let [m (ns-aliases *ns*)] (zipmap (keys m) (map ns-name (vals m))))"),C=$APP.Ii($APP.vi(B),$APP.ti(B)),E=$APP.Rn.g($APP.Og.l(function(ma){var ua=$APP.A.h(B,ma);ma=$APP.lu(c,$APP.$k("(keys (ns-publics '%s))","%s",ua));return $APP.fj.h(function(Ea){return new $APP.H(null,3,5,$APP.J,[$APP.l.g(ua),$APP.l.g(Ea),CMa],null)},ma)},$APP.z([$APP.ti(B)]))),I=$APP.fj.h(function(ma){return new $APP.H(null,3,5,$APP.J,[$APP.l.g(ma),null,CMa],null)},$APP.lu(c,
"(all-ns)")),P=m?AMa(p,f):null,S=$APP.k(P)?null:m?function(){var ma=$APP.A.j(B,p,p),ua=$APP.lu(c,$APP.$k("(and (find-ns '%s)\n                                                                                         (keys (ns-publics '%s)))","%s",ma));return $APP.fj.h(function(Ea){return new $APP.H(null,3,5,$APP.J,[$APP.l.g(ma),$APP.l.g(Ea),CMa],null)},ua)}():null,V=$APP.M.l(t,E,$APP.z([I,S])),aa=$APP.un.h(function(ma){var ua=$APP.y.j(ma,0,null);var Ea=$APP.y.j(ma,1,null);ma=$APP.y.j(ma,2,null);ma=
$APP.x.h(BMa,ma)&&$APP.Ia(Ea,f)?new $APP.H(null,2,5,$APP.J,[ua,Ea],null):null;$APP.k(ma)?ua=ma:$APP.k(ua)?(ma=[$APP.l.g($APP.A.h(C,$APP.lj.g(ua))),"/",$APP.l.g(Ea)].join(""),ma=$APP.Ia(ma,f)?new $APP.H(null,2,5,$APP.J,[ua,ma],null):null,$APP.k(ma)?ua=ma:(Ea=[$APP.l.g(ua),"/",$APP.l.g(Ea)].join(""),ua=$APP.Ia(Ea,f)?new $APP.H(null,2,5,$APP.J,[ua,Ea],null):null)):ua=null;return ua},V),ca=$APP.M.h(aa,P),ka=$APP.ef($APP.Ky.g($APP.fj.h(function(ma){var ua=$APP.y.j(ma,0,null);ma=$APP.y.j(ma,1,null);ma=
new $APP.h(null,1,["candidate",$APP.l.g(ma)],null);return $APP.k(ua)?$APP.xi.j(ma,"ns",$APP.l.g(ua)):ma},ca)));return new $APP.h(null,2,["completions",ka,"status",new $APP.H(null,1,5,$APP.J,["done"],null)],null)}return new $APP.h(null,1,["status",new $APP.H(null,1,5,$APP.J,["done"],null)],null)}finally{$APP.dq()}}catch(ma){return console.warn(ma),new $APP.h(null,2,["completions",$APP.Sg,"status",new $APP.H(null,1,5,$APP.J,["done"],null)],null)}};rMa={};
qMa=function qMa(a,b,c){for(;;){if(b instanceof Promise)return b;if(rMa===a){if($APP.Le(b))return $APP.uN(b,b,c,qMa);a=$APP.Uu(b,c)}else{b=Promise;var e=b.resolve;var f=$APP.xI.g(c);f=$APP.k(f)?f:$APP.gf;c=new $APP.h(null,1,[$APP.R,$APP.R.g(c)],null);c=f.h?f.h(a,c):f.call(null,a,c);return e.call(b,c)}}};$APP.EMa=new $APP.q(null,"socket-repl","socket-repl",-1615225633,null);$APP.FMa=new $APP.q(null,"repl","repl",1605132860,null);vMa=new $APP.F(null,"disableConfig","disableConfig",844586790);
BMa=new $APP.F(null,"unqualified","unqualified",-98904653);wMa=new $APP.F(null,"paths","paths",-1807389588);CMa=new $APP.F(null,"qualified","qualified",-2065109343);$APP.GMa=new $APP.q(null,"start-server!","start-server!",203437330,null);zMa=new $APP.q(null,"resolved__34368__auto__","resolved__34368__auto__",-1509245552,null);$APP.WO=new $APP.F(null,"classpath","classpath",299521985);var uMa,tMa;uMa=function(){var a=esm_import$node_module.createRequire;return $APP.k(a)?a:function(){return function(){throw Error("createRequire is not defined, this is a no-op");}}}();tMa=$APP.zj.g(!1);$APP.XO=function XO(a){switch(arguments.length){case 1:return XO.g(arguments[0]);case 2:return XO.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.l.g(arguments.length)].join(""));}};$APP.XO.g=function(a){return $APP.XO.h(a,null)};
$APP.XO.h=function(a,b){b=$APP.gz.l(b,$APP.z([$APP.hz,!0]));var c=esm_import$node_path.resolve(a);$APP.vg($APP.JJa,c);return $APP.VO(c,b).then(function(){return $APP.Zu(c)})};$APP.XO.B=2;$APP.YO=function YO(a){switch(arguments.length){case 1:return YO.g(arguments[0]);case 2:return YO.h(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",$APP.l.g(arguments.length)].join(""));}};$APP.YO.g=function(a){return $APP.YO.h(a,null)};
$APP.YO.h=function(a,b){b=$APP.gz.l(b,$APP.z([$APP.hz,!0]));return $APP.VO(null,b).then(function(){return $APP.Xu(a)})};$APP.YO.B=2;export const loadFile=$APP.XO;export const loadString=$APP.YO;export const getClassPath=function(){return $APP.Bp()};export const addClassPath=function(a){return $APP.Cp(a)};export const version=function(){return $APP.lv()};export const registerModule=function(a,b){b=$APP.Sia($APP.Jk(b));return $APP.Aj.F($APP.Nu,$APP.xi,b,a)};export const printErrorReport=$APP.vN;