import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var utb=function(a,b,c,d){return $APP.Zi(a,function(e,f){$APP.Ic(f,"[");$APP.Ic(f,$APP.xj.l($APP.x([e],0)));$APP.Ic(f," ");$APP.Ic(f,$APP.xj.l($APP.x([$APP.z.g(b,e)],0)));return $APP.Ic(f,"]")},"("," ",")",d,c)},Y$=function(a,b){this.Ya=a;this.cd=b;this.I=2297825039;this.K=8192},Z$=function(a,b){return $APP.r.g(a,b instanceof Y$?b.Ya:b)},vtb=new $APP.C(null,"skip-protocol-flag","skip-protocol-flag",-1426798630),wtb=new $APP.l("cljs.core","IKVReduce","cljs.core/IKVReduce",878013381,null),xtb=new $APP.l("cljs.core",
"IFind","cljs.core/IFind",-1727519574,null),ytb=new $APP.l("cljs.core","IMeta","cljs.core/IMeta",-1459057517,null),ztb=new $APP.l("cljs.core","ISeqable","cljs.core/ISeqable",137437203,null),Atb=new $APP.l("cljs.core","ICounted","cljs.core/ICounted",-1299011378,null),Btb=new $APP.l("cljs.core","ILookup","cljs.core/ILookup",-150575073,null),Ctb=new $APP.l(null,"ordered-map","ordered-map",-706459974,null),Dtb=new $APP.l("cljs.core","IWithMeta","cljs.core/IWithMeta",-1981666051,null),Etb=new $APP.l("cljs.core",
"IAssociative","cljs.core/IAssociative",-1700920611,null),Ftb=new $APP.l("cljs.core","IFn","cljs.core/IFn",-920223129,null),Gtb=new $APP.l("cljs.core","ICloneable","cljs.core/ICloneable",-1712216461,null),Htb=new $APP.l(null,"print-ordered-map","print-ordered-map",1388177372,null),Itb=new $APP.l(null,"that","that",828965210,null),Jtb=new $APP.l("flatland.ordered.map","-\x3eOrderedMap","flatland.ordered.map/-\x3eOrderedMap",-2112744986,null),Ktb=new $APP.l("flatland.ordered.map","print-ordered-map",
"flatland.ordered.map/print-ordered-map",-867774065,null),Ltb=new $APP.l("flatland.ordered.map","ordered-map","flatland.ordered.map/ordered-map",1887268971,null),Mtb=new $APP.l(null,"equiv-impl","equiv-impl",417944565,null),Ntb=new $APP.l("cljs.core","IReversible","cljs.core/IReversible",-1422278012,null),Otb=new $APP.l("cljs.core","IHash","cljs.core/IHash",-32453786,null),Ptb=new $APP.l("flatland.ordered.map","equiv-impl","flatland.ordered.map/equiv-impl",-229597862,null),Qtb=new $APP.l("cljs.core",
"IEmptyableCollection","cljs.core/IEmptyableCollection",5045035,null),Rtb=new $APP.l(null,"-\x3eOrderedMap","-\x3eOrderedMap",613100471,null),Stb=new $APP.l("cljs.core","IEquiv","cljs.core/IEquiv",-1245752602,null),Ttb=new $APP.l("cljs.core","ICollection","cljs.core/ICollection",802638471,null),Utb=new $APP.C(null,"protocols","protocols",-5615896),Vtb=new $APP.l("cljs.core","Object","cljs.core/Object",-345545431,null),Wtb=new $APP.l("cljs.core","IPrintWithWriter","cljs.core/IPrintWithWriter",1349251417,
null);$APP.g=Y$.prototype;$APP.g.Qe=$APP.rd;$APP.g.te=function(a,b){return $APP.dc(this.Ya,b)};$APP.g.entry_set=function(){return $APP.Ze($APP.Pj.g($APP.Ze,this.Ya))};
$APP.g.forEach=function(){function a(d,e){for(var f=$APP.m(this.cd),k=null,n=0,t=0;;)if(t<n){var w=k.ga(null,t);d.call(e,w,$APP.z.g(this.Ya,w),this);t+=1}else if(f=$APP.m(f))k=f,$APP.Ae(k)?(f=$APP.Zc(k),n=$APP.$c(k),k=f,w=$APP.Yd(f),f=n,n=w):(w=$APP.p(k),d.call(e,w,$APP.z.g(this.Ya,w),this),f=$APP.q(k),k=null,n=0),t=0;else return null}function b(d){for(var e=$APP.m(this.cd),f=null,k=0,n=0;;)if(n<k){var t=f.ga(null,n),w=t;t=$APP.z.g(this.Ya,t);d.j?d.j(w,t,this):d.call(null,w,t,this);n+=1}else if(e=
$APP.m(e))$APP.Ae(e)?(t=$APP.Zc(e),e=$APP.$c(e),f=t,k=t=$APP.Yd(t)):(f=t=$APP.p(e),t=$APP.z.g(this.Ya,t),d.j?d.j(f,t,this):d.call(null,f,t,this),e=$APP.q(e),f=null,k=0),n=0;else return null}var c=null;c=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};c.h=b;c.g=a;return c}();$APP.g.get=function(a){return this.Ya.get(a)};$APP.g.key_set=function(){return $APP.Ze($APP.qi(this.Ya))};$APP.g.entries=function(){return $APP.wh($APP.m(this.Ya))};
$APP.g.value_set=function(){return $APP.Ze($APP.Pj.g($APP.eh,this.Ya))};$APP.g.toString=function(){return $APP.kd(this)};$APP.g.keys=function(){return $APP.Gd(this.cd)};$APP.g.values=function(){return $APP.Gd($APP.si(this.Ya))};$APP.g.equiv=function(a){return Z$.g?Z$.g(this.Ya,a):Z$.call(null,this.Ya,a)};$APP.g.has=function(a){return this.Ya.get(a)!=null};$APP.g.aa=function(a,b){return $APP.sy(this.Ya,b)};$APP.g.J=function(a,b,c){return $APP.sy(this.Ya,b,c)};
$APP.g.ja=function(a,b,c){var d=this;return $APP.Ye.j(function(e,f){var k=$APP.z.g(d.Ya,f);return b.j?b.j(e,f,k):b.call(null,e,f,k)},c,d.cd)};$APP.g.V=function(a,b,c){$APP.Ic(b,"#ordered/map ");return utb(b,this.Ya,this.cd,c)};$APP.g.T=function(){return $APP.pe(this.Ya)};$APP.g.ba=function(){return new Y$(this.Ya,this.cd)};$APP.g.Y=function(){return $APP.Yd(this.Ya)};$APP.g.Fd=function(){var a=this;return $APP.m(a.cd)?$APP.Pj.g(function(b){return $APP.dc(a.Ya,b)},$APP.Cc(a.cd)):null};$APP.g.X=function(){return $APP.sd(this.Ya)};
$APP.g.R=function(a,b){return Z$.g?Z$.g(this.Ya,b):Z$.call(null,this.Ya,b)};$APP.g.$a=function(){return $APP.m(this.cd)?new Y$($APP.Rb(this.Ya),$APP.Rg):this};$APP.g.ma=function(a,b){return $APP.Ne(this.Ya,b)?new Y$($APP.Il.g(this.Ya,b),$APP.Ch.j($APP.Rg,$APP.Ns.h($APP.zi([b])),this.cd)):this};$APP.g.N=function(a,b,c){return new Y$($APP.ui.j(this.Ya,b,c),$APP.Ne(this.Ya,b)?this.cd:$APP.vf.g(this.cd,b))};$APP.g.fa=function(a,b){return $APP.Ne(this.Ya,b)};
$APP.g.Z=function(){var a=this;return $APP.m(a.cd)?$APP.Pj.g(function(b){return $APP.dc(a.Ya,b)},a.cd):null};$APP.g.U=function(a,b){return $APP.pe(this.Ya)===b?this:new Y$($APP.ne(this.Ya,b),this.cd)};$APP.g.ca=function(a,b){var c=this;return $APP.ze(b)?new Y$($APP.vf.g(c.Ya,b),$APP.Ne(c.Ya,$APP.ke(b,0))?c.cd:$APP.vf.g(c.cd,$APP.ke(b,0))):new Y$($APP.vf.g(c.Ya,b),$APP.Ch.j(c.cd,$APP.yq.g($APP.Pj.h(function(d){return $APP.ke(d,0)}),$APP.Ns.h(function(d){return $APP.Ne(c.Ya,d)})),b))};
$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.h(arguments[1]);case 2:return this.g(arguments[1],arguments[2]);default:throw Error("Invalid arity: "+$APP.G.h(arguments.length-1));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Lb(b)))};$APP.g.h=function(a){return this.Ya.h?this.Ya.h(a):this.Ya.call(null,a)};$APP.g.g=function(a,b){return this.Ya.g?this.Ya.g(a,b):this.Ya.call(null,a,b)};
var Xtb=new Y$($APP.Xf,$APP.Rg),$$=function $$(a){switch(arguments.length){case 0:return $$.D();case 1:return $$.h(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return $$.l(arguments[0],arguments[1],2<c.length?new $APP.Ad(c.slice(2),0,null):null)}};$$.D=function(){return Xtb};$$.h=function(a){return $APP.Ch.g(Xtb,a)};$$.l=function(a,b,c){return $APP.sg.P($APP.ui,Xtb,a,b,c)};
$$.G=function(a){var b=$APP.p(a),c=$APP.q(a);a=$APP.p(c);c=$APP.q(c);return this.l(b,a,c)};$$.B=2;var Ytb=$APP.FM.g($APP.eya,null),Ztb=$APP.lv(new $APP.F(null,4,[$APP.ne(Mtb,new $APP.F(null,1,[$APP.SD,!0],null)),new $APP.F(null,3,[$APP.R,Ptb,$APP.fv,Z$,$APP.cj,new $APP.F(null,4,[$APP.V,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.kF,Itb],null)),$APP.J,"flatland/ordered/map.cljs",$APP.K,131,$APP.M,7],null)],null),$APP.ne(Htb,new $APP.F(null,1,[$APP.V,$APP.I($APP.Dk,$APP.I(new $APP.D(null,4,5,$APP.E,[$APP.GA,$APP.kF,$APP.YC,$APP.zF],null)))],null)),new $APP.F(null,3,[$APP.R,Ktb,$APP.fv,utb,$APP.cj,new $APP.F(null,
4,[$APP.V,$APP.I(new $APP.D(null,4,5,$APP.E,[$APP.GA,$APP.kF,$APP.YC,$APP.zF],null)),$APP.J,"flatland/ordered/map.cljs",$APP.K,5,$APP.M,7],null)],null),$APP.ne(Rtb,new $APP.F(null,5,[Utb,new $APP.xi(null,new $APP.F(null,18,[Ntb,"null",wtb,"null",Stb,"null",Otb,"null",Ftb,"null",Ttb,"null",Vtb,"null",xtb,"null",Qtb,"null",Atb,"null",ztb,"null",ytb,"null",Gtb,"null",Wtb,"null",Dtb,"null",Etb,"null",$APP.JE,"null",Btb,"null"],null),null),$APP.BI,$APP.Ota,$APP.V,$APP.I($APP.Dk,$APP.I(new $APP.D(null,
2,5,$APP.E,[$APP.kF,$APP.YC],null))),vtb,new $APP.xi(null,new $APP.F(null,16,[Ntb,"null",wtb,"null",Stb,"null",Otb,"null",Ftb,"null",Ttb,"null",Qtb,"null",Atb,"null",ztb,"null",ytb,"null",Gtb,"null",Wtb,"null",Dtb,"null",Etb,"null",$APP.JE,"null",Btb,"null"],null),null),$APP.O,"Positional factory function for flatland.ordered.map/OrderedMap."],null)),new $APP.F(null,3,[$APP.R,Jtb,$APP.fv,function(a,b){return new Y$(a,b)},$APP.cj,new $APP.F(null,5,[$APP.V,$APP.I(new $APP.D(null,2,5,$APP.E,[$APP.kF,
$APP.YC],null)),$APP.O,"Positional factory function for flatland.ordered.map/OrderedMap.",$APP.J,"flatland/ordered/map.cljs",$APP.K,18,$APP.M,10],null)],null),$APP.ne(Ctb,new $APP.F(null,2,[$APP.V,$APP.I($APP.Dk,$APP.I($APP.Rg,new $APP.D(null,1,5,$APP.E,[$APP.hE],null),new $APP.D(null,4,5,$APP.E,[$APP.eH,$APP.mH,$APP.kk,$APP.kF],null))),$APP.GH,new $APP.F(null,6,[$APP.mB,!0,$APP.bt,2,$APP.NI,2,$APP.xI,new $APP.D(null,2,5,$APP.E,[$APP.Rg,new $APP.D(null,1,5,$APP.E,[$APP.hE],null)],null),$APP.V,$APP.I($APP.Rg,
new $APP.D(null,1,5,$APP.E,[$APP.hE],null),new $APP.D(null,4,5,$APP.E,[$APP.eH,$APP.mH,$APP.kk,$APP.kF],null)),$APP.yE,$APP.I(null,null,null)],null)],null)),new $APP.F(null,3,[$APP.R,Ltb,$APP.fv,$$,$APP.cj,new $APP.F(null,4,[$APP.V,$APP.I($APP.Rg,new $APP.D(null,1,5,$APP.E,[$APP.hE],null),new $APP.D(null,4,5,$APP.E,[$APP.eH,$APP.mH,$APP.kk,$APP.kF],null)),$APP.J,"flatland/ordered/map.cljs",$APP.K,138,$APP.M,7],null)],null)],null),Ytb);$APP.Tv(new $APP.F(null,1,[$APP.Oq,new $APP.F(null,1,[$APP.eya,Ztb],null)],null));