import { $APP, shadow$provide } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_impl_main.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_path from"node:path";
var D7a=function(a){var b=$APP.kj.h(a),c=$APP.Bf(b);return $APP.Sk("\n(require '[babashka.cli])\n(require '$1)\n(let [the-var (resolve '$2)\n      the-var-meta (meta the-var)\n      ns (:ns (meta the-var))\n      ns-meta (meta ns)\n      cli-opts (babashka.cli/merge-opts (:org.babashka/cli ns-meta)\n                                        (:org.babashka/cli the-var-meta))\n      opts (babashka.cli/parse-opts *command-line-args* cli-opts)]\n  (the-var opts))\n",/\$(\d)/,function(d){d=$APP.de(d);switch(d){case "1":return c;
case "2":return b;default:throw Error("No matching clause: "+$APP.G.h(d));}})},E7a=function(a){a=$APP.kj.h(a);var b=$APP.Df(a)?$APP.kj.g(""+$APP.G.h(a),"-main"):a,c=$APP.Bf(b);return $APP.Sk("(require '$1) (apply $2 *command-line-args*)",/\$(\d)/,function(d){d=$APP.de(d);switch(d){case "1":return c;case "2":return b;default:throw Error("No matching clause: "+$APP.G.h(d));}})},F7a=function(a){for(var b=$APP.Xf,c=a;;){if($APP.h(c)){var d=$APP.p(c);a=$APP.q(c);switch(d){case "--help":case "-h":return $APP.ui.j(b,
$APP.NC,!0);case "--version":case "-v":return $APP.ui.j(b,$APP.dWa,!0);case "-e":b=$APP.ui.j(b,$APP.Ro,$APP.p(a));c=a=$APP.q(a);continue;case "-m":case "--main":return $APP.ui.l(b,$APP.Ro,E7a($APP.p(a)),$APP.x([$APP.$m,$APP.q(a)],0));case "-x":case "--exec":return $APP.ui.l(b,$APP.Ro,D7a($APP.p(a)),$APP.x([$APP.$m,$APP.q(a)],0));case "-cp":case "--classpath":b=$APP.ui.j(b,$APP.qO,$APP.p(a));c=a=$APP.q(a);continue;case "--config":b=$APP.ui.j(b,$APP.kC,$APP.p(a));c=a=$APP.q(a);continue;case "--debug":b=
$APP.ui.j(b,$APP.Av,!0);c=a;continue;case "nrepl-server":b=$APP.ui.j(b,$APP.$Va,!0);c=a;continue;case "socket-repl":b=$APP.ui.j(b,$APP.aWa,!0);c=a;continue;case ":port":case "--port":b=$APP.ui.j(b,$APP.tF,$APP.p(a));c=a=$APP.q(a);continue;case ":host":case "--host":b=$APP.ui.j(b,$APP.oJ,$APP.p(a));c=a=$APP.q(a);continue;case "repl":b=$APP.ui.j(b,$APP.cWa,!0);c=a;continue;case "bundle":return $APP.ui.j(b,$APP.CH,$APP.zn.g(a,new $APP.F(null,1,[$APP.Rn,new $APP.F(null,2,[$APP.eWa,$APP.wDa,$APP.fWa,$APP.NC],
null)],null)));default:if($APP.yb($APP.Ro.h(c)))return $APP.ui.l(b,$APP.bWa,d,$APP.x([$APP.$m,$APP.q(c)],0));throw $APP.Wl.g("Unrecognized options:"+$APP.G.h(c),$APP.Xf);}}else return b;break}};if($APP.h(esm_import$node_process.on))esm_import$node_process.on("unhandledRejection",function(a){console.error($APP.ik(a));return process.exitCode=1});(function(){var a=$APP.m(function(){var k=globalThis.nbb_args;return $APP.h(k)?k:esm_import$node_process.argv}());$APP.p(a);a=$APP.q(a);$APP.p(a);a=$APP.q(a);var b=F7a(a);$APP.yg($APP.gWa,b);var c=$APP.bWa.h(b),d=$APP.Ro.h(b);a=$APP.qO.h(b);$APP.h(a)&&$APP.Ep(a);a=$APP.$Va.h(b);var e=function(){var k=$APP.cWa.h(b);if($APP.h(k))return k;k=$APP.aWa.h(b);return $APP.h(k)?k:$APP.se($APP.Il.l(b,$APP.qO,$APP.x([$APP.Av,$APP.kC],0)))}(),f=$APP.CH.h(b);$APP.h($APP.NC.h(b))&&($APP.xz.l($APP.x([$APP.maa("nbb-logseq"),
"version:",$APP.$v()],0)),$APP.xz.l($APP.x(["\nHelp:\n\n -h / --help: print this help text and exit.\n -v / --version: print the current version of nbb.\n\nGlobal options:\n\n --debug: print additional debug info.\n -cp / --classpath: set the classpath.\n\nEvaluation:\n\n -e: execute expression\n -m / --main: execute main function\n -x / --exec: execute function using babashka.cli\n\nREPL:\n\n repl: start console REPL.\n nrepl-server: start nrepl server. [1,2]\n socket-repl: start socket repl server. [1]\n\n 1: Provide :port \x3cport\x3e to specify port\n 2: Provide :host \x3chost\x3e to specify host\n\nTooling:\n\n  bundle: produce single JS file for usage with bundlers.\n"],
0)),esm_import$node_process.exit(0));$APP.h($APP.dWa.h(b))&&($APP.xz.l($APP.x([""+$APP.G.h("nbb-logseq")+" v"+$APP.G.h($APP.$v())],0)),esm_import$node_process.exit(0));return $APP.h($APP.h(c)?c:$APP.h(d)?d:$APP.h(a)?a:$APP.h(e)?e:f)?($APP.BM.g($APP.uJa,$APP.wg($APP.$m.h(b))),Promise.resolve($APP.mO($APP.h(e)?esm_import$node_path.resolve("script.cljs"):c,b)).then(function(){return($APP.h(c)?$APP.rO.h(c):$APP.h(d)?$APP.sO.h(d):$APP.h($APP.$Va.h(b))?shadow_esm_import("./nbb_nrepl_server.js").then(function(){var k=
$APP.z.g($APP.z.g($APP.Oq.h($APP.Qd($APP.Jq.h($APP.Hp()))),$APP.VA),$APP.pO);return k.h?k.h(b):k.call(null,b)}):$APP.h($APP.h(e)?$APP.aWa.h(b):e)?shadow_esm_import("./nbb_repl.js").then(function(){var k=new $APP.F(null,1,[$APP.tF,$APP.tF.h(b)],null),n=$APP.z.g($APP.z.g($APP.Oq.h($APP.Qd($APP.Jq.h($APP.Hp()))),$APP.Xz),$APP.nO);return n.h?n.h(k):n.call(null,k)}):$APP.h($APP.CH.h(b))?shadow_esm_import("./nbb_bundler.js"):$APP.h(e)?shadow_esm_import("./nbb_repl.js").then(function(){var k=$APP.z.g($APP.z.g($APP.Oq.h($APP.Qd($APP.Jq.h($APP.Hp()))),
$APP.Xz),$APP.oO);return k.D?k.D():k.call(null)}):null).then(function(k){$APP.h($APP.h(d)?k!=null:d)&&$APP.zv.l($APP.x([k],0));return k}).catch(function(k){$APP.Hja(k,b);$APP.h($APP.Av.h(b))&&console.error(k);throw Error($APP.ik(k));})})):console.error("Usage: "+$APP.G.h("nbb-logseq")+" \x3cscript\x3e or nbb -e \x3cexpr\x3e.")})();