import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_impl_main.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$path from"path";
var yGa=function(a){var b=$APP.fl.g(a),c=$APP.Jg(b);return $APP.jn("\n(require '[babashka.cli])\n(require '$1)\n(let [the-var (resolve '$2)\n      the-var-meta (meta the-var)\n      ns (:ns (meta the-var))\n      ns-meta (meta ns)\n      cli-opts (babashka.cli/merge-opts (:org.babashka/cli ns-meta)\n                                        (:org.babashka/cli the-var-meta))\n      opts (babashka.cli/parse-opts *command-line-args* cli-opts)]\n  (the-var opts))\n",/\$(\d)/,function(d){d=$APP.ne(d);switch(d){case "1":return c;
case "2":return b;default:throw Error(["No matching clause: ",$APP.n.g(d)].join(""));}})},Gia=function(a){a=$APP.fl.g(a);var b=$APP.Ng(a)?$APP.fl.h($APP.n.g(a),"-main"):a,c=$APP.Jg(b);return $APP.jn("(require '$1) (apply $2 *command-line-args*)",/\$(\d)/,function(d){d=$APP.ne(d);switch(d){case "1":return c;case "2":return b;default:throw Error(["No matching clause: ",$APP.n.g(d)].join(""));}})},Hia=function(a){for(var b=$APP.uh,c=a;;)if($APP.m(c)){var d=$APP.x(c);a=$APP.z(c);switch(d){case "--help":case "-h":return $APP.K.j(b,
$APP.LD,!0);case "--version":case "-v":return $APP.K.j(b,$APP.yKa,!0);case "-e":b=$APP.K.j(b,$APP.Sq,$APP.x(a));c=a=$APP.z(a);continue;case "-m":case "--main":return $APP.K.l(b,$APP.Sq,Gia($APP.x(a)),$APP.F([$APP.Vo,$APP.z(a)]));case "-x":case "--exec":return $APP.K.l(b,$APP.Sq,yGa($APP.x(a)),$APP.F([$APP.Vo,$APP.z(a)]));case "-cp":case "--classpath":b=$APP.K.j(b,$APP.GJ,$APP.x(a));c=a=$APP.z(a);continue;case "--config":b=$APP.K.j(b,$APP.zD,$APP.x(a));c=a=$APP.z(a);continue;case "--debug":b=$APP.K.j(b,
$APP.Ny,!0);c=a;continue;case "nrepl-server":b=$APP.K.j(b,$APP.uKa,!0);c=a;continue;case "socket-repl":b=$APP.K.j(b,$APP.vKa,!0);c=a;continue;case ":port":case "--port":b=$APP.K.j(b,$APP.FJ,$APP.x(a));c=a=$APP.z(a);continue;case ":host":case "--host":b=$APP.K.j(b,$APP.IIa,$APP.x(a));c=a=$APP.z(a);continue;case "repl":b=$APP.K.j(b,$APP.xKa,!0);c=a;continue;case "bundle":return $APP.K.j(b,$APP.JH,$APP.RQ.h(a,new $APP.g(null,1,[$APP.pq,new $APP.g(null,2,[$APP.zKa,$APP.FCa,$APP.AKa,$APP.LD],null)],null)));
default:if($APP.qb($APP.Sq.g(c)))return $APP.K.l(b,$APP.wKa,d,$APP.F([$APP.Vo,$APP.z(c)]));throw $APP.Fp.h(["Unrecognized options:",$APP.n.g(c)].join(""),$APP.uh);}}else return b};process.on("unhandledRejection",function(a){console.error($APP.vm(a));return process.exitCode=1});(function(){var a=$APP.u(process.argv);$APP.x(a);a=$APP.z(a);$APP.x(a);a=$APP.z(a);var b=Hia(a);$APP.Th($APP.qia,b);var c=$APP.wKa.g(b),d=$APP.Sq.g(b);a=$APP.GJ.g(b);$APP.m(a)&&$APP.Jn(a);a=$APP.uKa.g(b);var e=function(){var l=$APP.xKa.g(b);if($APP.m(l))return l;l=$APP.vKa.g(b);return $APP.m(l)?l:$APP.Ee($APP.cp.l(b,$APP.GJ,$APP.F([$APP.Ny,$APP.zD])))}(),h=$APP.JH.g(b);$APP.m($APP.LD.g(b))&&($APP.VA.l($APP.F([$APP.Ra("nbb-logseq"),"version:",$APP.jz()])),$APP.VA.l($APP.F(["\nHelp:\n\n -h / --help: print this help text and exit.\n -v / --version: print the current version of nbb.\n\nGlobal options:\n\n --debug: print additional debug info.\n -cp / --classpath: set the classpath.\n\nEvaluation:\n\n -e: execute expression\n -m / --main: execute main function\n -x / --exec: execute function using babashka.cli\n\nREPL:\n\n repl: start console REPL.\n nrepl-server: start nrepl server. [1,2]\n socket-repl: start socket repl server. [1]\n\n 1: Provide :port \x3cport\x3e to specify port\n 2: Provide :host \x3chost\x3e to specify host\n\nTooling:\n\n  bundle: produce single JS file for usage with bundlers.\n"])),
process.exit(0));$APP.m($APP.yKa.g(b))&&($APP.VA.l($APP.F([["nbb-logseq v",$APP.jz()].join("")])),process.exit(0));return $APP.m($APP.m(c)?c:$APP.m(d)?d:$APP.m(a)?a:$APP.m(e)?e:h)?($APP.fN.h($APP.jN,$APP.Rh($APP.Vo.g(b))),Promise.resolve($APP.wR($APP.m(e)?esm_import$path.resolve("script.cljs"):c,b)).then(function(){return($APP.m(c)?$APP.vP(c):$APP.m(d)?$APP.wP(d):$APP.m($APP.uKa.g(b))?shadow_esm_import("./nbb_nrepl_server.js").then(function(){var l=$APP.gf.h($APP.gf.h($APP.Ft.g($APP.q($APP.jt.g($APP.ho()))),
$APP.eC),$APP.HIa);return l.g?l.g(b):l.call(null,b)}):$APP.m($APP.m(e)?$APP.vKa.g(b):e)?shadow_esm_import("./nbb_repl.js").then(function(){var l=new $APP.g(null,1,[$APP.FJ,$APP.FJ.g(b)],null),p=$APP.gf.h($APP.gf.h($APP.Ft.g($APP.q($APP.jt.g($APP.ho()))),$APP.lB),$APP.FIa);return p.g?p.g(l):p.call(null,l)}):$APP.m($APP.JH.g(b))?shadow_esm_import("./nbb_bundler.js"):$APP.m(e)?shadow_esm_import("./nbb_repl.js").then(function(){var l=$APP.gf.h($APP.gf.h($APP.Ft.g($APP.q($APP.jt.g($APP.ho()))),$APP.lB),
$APP.GIa);return l.F?l.F():l.call(null)}):null).then(function(l){$APP.m($APP.m(d)?null!=l:d)&&$APP.WA.l($APP.F([l]));return l}).catch(function(l){$APP.zca(l,b);$APP.m($APP.Ny.g(b))&&console.error(l);throw Error($APP.vm(l));})})):console.error("Usage: nbb-logseq \x3cscript\x3e or nbb -e \x3cexpr\x3e.")})();