import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_api.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$net from"net";import*as esm_import$readline from"readline";import*as esm_import$vm from"vm";
var BR=function(a){var b=function(){var e=$APP.Yp.h(a,"(");return $APP.m(e)?new $APP.H(null,2,5,$APP.I,[$APP.Ik.j(a,0,e+1),$APP.Ik.h(a,e+1)],null):new $APP.H(null,2,5,$APP.I,[null,a],null)}(),c=$APP.C.j(b,0,null),d=$APP.C.j(b,1,null);b=$APP.gf.h(function(){try{return $APP.yP(new $APP.g(null,2,[$APP.O,$APP.n.g($APP.q(AR)),$APP.vG,d],null))}catch(h){var e=h;console.warn($APP.n.g($APP.rCa),$APP.vm(e));return null}}(),"completions");return $APP.Wk.h(function(e){return[$APP.n.g(c),$APP.n.g(e)].join("")},
$APP.ri(function(e){return $APP.tb(e,d)},$APP.Wk.h(function(e){return $APP.gf.h(e,"candidate")},b)))},CR=function(a){return[$APP.pp.g(BR(a)),a]},GR=function(a,b){$APP.Th(DR,!1);a.setPrompt([$APP.n.g($APP.q(AR)),"\x3d\x3e "].join(""));a.prompt();return $APP.zn($APP.q(ER))?null:FR.h?FR.h(b,a):FR.call(null,b,a)},HR=function(a){var b=$APP.No(a);a=$APP.Oo(a);var c=$APP.sn($APP.q(ER));b=$APP.Yh.h(b-1,c);c=$APP.u(b);b=$APP.x(c);c=$APP.z(c);a=$APP.m(b)?$APP.Ik.h(b,a):null;$APP.Th(ER,$APP.En.h("\n",$APP.Fg(a,
c)))},tia=function(a,b){b={f:b};esm_import$vm.createContext(b);try{return $APP.m($APP.m(JR)?$APP.qb(a):JR)&&process.stdin.setRawMode(!1),esm_import$vm.runInContext("f()",b,{displayErrors:!0,breakOnSigint:!0,microtaskMode:"afterEvaluate"}).then(function(c){var d={f:$APP.m(a)?function(){return c}:function(){var e=$APP.x(c);$APP.WA.l($APP.F([e]));return c}};esm_import$vm.createContext(d);return esm_import$vm.runInContext("f()",d,{displayErrors:!0,breakOnSigint:!0,microtaskMode:"afterEvaluate"})}).finally(function(){return $APP.m($APP.m(JR)?
$APP.qb(a):JR)?process.stdin.setRawMode(!0):null})}catch(c){return b=c,$APP.m($APP.m(JR)?$APP.qb(a):JR)&&process.stdin.setRawMode(!0),Promise.reject(b)}},FR=function(a,b){if($APP.m(function(){var e=$APP.q(DR);return $APP.m(e)?e:$APP.zn($APP.q(ER))}()))return null;$APP.Th(DR,!0);var c=$APP.as($APP.q(ER)),d=function(){try{var e=$APP.hj([$APP.ef,$APP.q(AR)]);$APP.jo(e);try{return $APP.Jy(c)}finally{$APP.lo()}}catch(h){e=h;if(-1!=$APP.vm(e).indexOf("EOF while reading"))return gKa;HR(c);$APP.WA.l($APP.F([$APP.n.g(e)]));
return hKa}}();if($APP.B.h(hKa,d))return GR(b,a);if($APP.B.h(gKa,d))return $APP.Th(DR,!1);HR(c);if($APP.B.h($APP.gG,d))return $APP.Th(DR,!1);$APP.jo($APP.hj([$APP.ef,$APP.q(AR)]));return tia(a,function(){return $APP.NCa(d,new $APP.g(null,3,[$APP.O,$APP.q(AR),$APP.Km,$APP.q($APP.bf),$APP.NH,$APP.Tt],null))}).then(function(e){var h=$APP.C.j(e,0,null);e=$APP.C.j(e,1,null);e=$APP.ph(e);e=$APP.gf.h(e,$APP.O);$APP.Th(AR,e);$APP.fN.h($APP.Yda,$APP.Rh($APP.q($APP.Xda)));$APP.fN.h($APP.Xda,$APP.Rh($APP.q($APP.Wda)));
$APP.fN.h($APP.Wda,$APP.Rh(h));$APP.m(a)&&a.write($APP.RA.l($APP.F([h])));return GR(b,a)}).catch(function(e){$APP.WA.l($APP.F([$APP.n.g(e)]));$APP.fN.h($APP.Zda,$APP.Rh(e));return GR(b,a)}).finally(function(){return $APP.lo()})},LR=function(a,b){a.on("line",function(c){$APP.Dl.I(ER,$APP.n,c,"\n");return FR(b,a)})},NR=function(a){return esm_import$readline.createInterface({input:a,output:a,completer:CR})},uia=function(a){var b=NR(a);LR(b,a);a.setNoDelay(!0);return a.on("close",function(){return $APP.VA.l($APP.F(["Client closed connection."]))})},
iKa=new $APP.r(null,"nbb.impl.repl","nbb.impl.repl",-339140484,null),gKa=new $APP.k("nbb.impl.repl","eof-while-reading","nbb.impl.repl/eof-while-reading",1743626215),jKa=new $APP.r("nbb.impl.repl","completer*","nbb.impl.repl/completer*",455172317,null),kKa=new $APP.r("nbb.impl.repl","repl","nbb.impl.repl/repl",-1645296655,null),nKa=new $APP.r(null,"completer*","completer*",-648150376,null),oKa=new $APP.r("nbb.impl.repl","socket-repl","nbb.impl.repl/socket-repl",1509490200,null),pKa=new $APP.k(null,
"init","init",-1875481434),qKa=new $APP.r(null,"get-completions","get-completions",1933789168,null),hKa=new $APP.k("nbb.impl.repl","continue","nbb.impl.repl/continue",-1326808644);var AR=$APP.Cl.g($APP.q($APP.ef)),ER=$APP.Cl.g(""),DR=$APP.Cl.g(!1),JR,rKa=process.stdout.isTTY;JR=$APP.m(rKa)?process.stdin.setRawMode:rKa;var QR=$APP.zJ.h($APP.XA,null),RR=function RR(a){switch(arguments.length){case 0:return RR.F();case 1:return RR.g(arguments[0]);default:throw Error(["Invalid arity: ",$APP.n.g(arguments.length)].join(""));}};RR.F=function(){return RR.g(null)};
RR.g=function(a){var b=function(){var d=$APP.KJ.g(a);return $APP.m(d)?d:0}(),c=esm_import$net.createServer(uia);return c.listen(b,"127.0.0.1",function(){var d=c.address(),e=d.address;return $APP.VA.l($APP.F([["Socket REPL listening on port ",$APP.n.g(d.port)," on host ",$APP.n.g(e)].join("")]))})};RR.C=1;var SR=function SR(a){switch(arguments.length){case 0:return SR.F();case 1:return SR.g(arguments[0]);default:throw Error(["Invalid arity: ",$APP.n.g(arguments.length)].join(""));}};SR.F=function(){return SR.g(null)};
SR.g=function(a){function b(e){return $APP.rP(new $APP.G(null,$APP.Bm,new $APP.G(null,new $APP.G(null,$APP.Bm,new $APP.G(null,e,null,1,null),2,null),null,1,null),2,null))}$APP.m(JR)&&process.stdin.setRawMode(!0);var c=$APP.C.j($APP.iN,0,null),d=$APP.C.j($APP.iN,1,null);$APP.VA.l($APP.F([["Welcome to nbb-logseq v",$APP.jz(),"!"].join("")]));return b(c).then(function(){return b(d)}).then(pKa.h(a,$APP.zf)).then(function(){return new Promise(function(e){var h=$APP.m(null)?NR(null):esm_import$readline.createInterface({input:process.stdin,
output:process.stdout,completer:CR});LR(h,null);h.setPrompt([$APP.n.g($APP.q(AR)),"\x3d\x3e "].join(""));h.on("close",e);return h.prompt()})})};SR.C=1;
var yia=new $APP.g(null,3,[$APP.pIa,function(){var a=new $APP.Dd(function(){return SR},kKa,$APP.Oj([$APP.O,$APP.U,$APP.Km,$APP.vB,$APP.FH,$APP.io,$APP.Lm,$APP.BP,$APP.V,$APP.N,$APP.oF],[iKa,$APP.pIa,"nbb/impl/repl.cljs",11,new $APP.g(null,6,[$APP.nC,!1,$APP.sw,1,$APP.GI,1,$APP.qI,new $APP.H(null,2,5,$APP.I,[$APP.qi,new $APP.H(null,1,5,$APP.I,[$APP.TF],null)],null),$APP.V,$APP.R($APP.qi,new $APP.H(null,1,5,$APP.I,[$APP.TF],null)),$APP.lF,$APP.R(null,null)],null),1,186,186,$APP.R($APP.qi,new $APP.H(null,
1,5,$APP.I,[$APP.TF],null)),null,$APP.m(SR)?SR.A:null])),b=$APP.q(a),c=$APP.Be(a);a=$APP.m(null)?null:$APP.U.g(c);var d=new $APP.g(null,4,[$APP.O,QR,$APP.U,a,$APP.V,$APP.V.g(c),$APP.N,$APP.N.g(c)],null);return $APP.m($APP.Qt.g(c))?$APP.uJ.j(a,b,d):$APP.m(function(){var e=$APP.Qs.g(c);return $APP.m(e)?e:$APP.Ys.g(c)}())?$APP.vJ.j(a,b,d):$APP.xy.j(a,b,d)}(),qKa,function(){var a=new $APP.Dd(function(){return BR},jKa,$APP.Oj([$APP.O,$APP.U,$APP.Km,$APP.vB,$APP.io,$APP.Lm,$APP.BP,$APP.V,$APP.N,$APP.oF],
[iKa,nKa,"nbb/impl/repl.cljs",17,1,15,15,$APP.R(new $APP.H(null,1,5,$APP.I,[$APP.hka],null)),"Given a line, returns a flat vector of completions",$APP.m(BR)?BR.A:null])),b=$APP.q(a),c=$APP.Be(a);a=$APP.m(null)?null:$APP.U.g(c);var d=new $APP.g(null,4,[$APP.O,QR,$APP.U,a,$APP.V,$APP.V.g(c),$APP.N,$APP.N.g(c)],null);return $APP.m($APP.Qt.g(c))?$APP.uJ.j(a,b,d):$APP.m(function(){var e=$APP.Qs.g(c);return $APP.m(e)?e:$APP.Ys.g(c)}())?$APP.vJ.j(a,b,d):$APP.xy.j(a,b,d)}(),$APP.oIa,function(){var a=new $APP.Dd(function(){return RR},
oKa,$APP.Oj([$APP.O,$APP.U,$APP.Km,$APP.vB,$APP.FH,$APP.io,$APP.Lm,$APP.BP,$APP.V,$APP.N,$APP.oF],[iKa,$APP.oIa,"nbb/impl/repl.cljs",18,new $APP.g(null,6,[$APP.nC,!1,$APP.sw,1,$APP.GI,1,$APP.qI,new $APP.H(null,2,5,$APP.I,[$APP.qi,new $APP.H(null,1,5,$APP.I,[$APP.TF],null)],null),$APP.V,$APP.R($APP.qi,new $APP.H(null,1,5,$APP.I,[$APP.TF],null)),$APP.lF,$APP.R(null,null)],null),1,171,171,$APP.R($APP.qi,new $APP.H(null,1,5,$APP.I,[$APP.TF],null)),null,$APP.m(RR)?RR.A:null])),b=$APP.q(a),c=$APP.Be(a);
a=$APP.m(null)?null:$APP.U.g(c);var d=new $APP.g(null,4,[$APP.O,QR,$APP.U,a,$APP.V,$APP.V.g(c),$APP.N,$APP.N.g(c)],null);return $APP.m($APP.Qt.g(c))?$APP.uJ.j(a,b,d):$APP.m(function(){var e=$APP.Qs.g(c);return $APP.m(e)?e:$APP.Ys.g(c)}())?$APP.vJ.j(a,b,d):$APP.xy.j(a,b,d)}()],null);$APP.Wy(new $APP.g(null,1,[$APP.Ft,new $APP.g(null,1,[$APP.XA,yia],null)],null));