import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_transit.js";
import "./nbb_datascript.js";
const shadow_esm_import = function(x) { return import(x) };
var apb=function(a){return $APP.BO($APP.QO.h($ob,new $APP.h(null,1,[$APP.MO,f7],null)),a)},bpb=function(a){return $APP.KO($APP.RO.h($ob,new $APP.h(null,1,[$APP.MO,g7],null)),a)},$ob=new $APP.F(null,"json","json",1279968570),cpb=new $APP.q("datascript.transit","read-transit-str","datascript.transit/read-transit-str",526272408,null),dpb=new $APP.q(null,"write-handlers","write-handlers",-456757384,null),epb=new $APP.q("datascript.transit","write-handlers","datascript.transit/write-handlers",-1659157370,
null),fpb=new $APP.q(null,"read-transit-str","read-transit-str",-953853518,null),gpb=new $APP.q("datascript.transit","read-handlers","datascript.transit/read-handlers",400129984,null),hpb=new $APP.q("datascript.transit","write-transit-str","datascript.transit/write-transit-str",-396975951,null),ipb=new $APP.q(null,"read-handlers","read-handlers",-544976454,null),jpb=new $APP.q(null,"write-transit-str","write-transit-str",546948831,null);var f7=new $APP.h(null,3,["u",$APP.dk,"datascript/DB",$APP.c2,"datascript/Datom",$APP.h1],null),g7=$APP.Uf([$APP.z1,$APP.SO.h($APP.tg("datascript/DB"),function(a){return new $APP.h(null,2,[$APP.A1,$APP.A1.g(a),$APP.b2,$APP.B1.g(a)],null)}),$APP.f1,$APP.SO.h($APP.tg("datascript/Datom"),function(a){return $APP.k($APP.e1(a))?new $APP.G(null,4,5,$APP.H,[a.e,a.a,a.v,$APP.d1(a)],null):new $APP.G(null,5,5,$APP.H,[a.e,a.a,a.v,$APP.d1(a),!1],null)}),$APP.G0,new $APP.EO]);var h7=$APP.kN.h($APP.WI,null),kpb=new $APP.h(null,4,[ipb,function(){var a=new $APP.Dd(function(){return f7},gpb,$APP.hi([$APP.P,$APP.N,$APP.Wl,$APP.Xz,$APP.Pm,$APP.Xl,$APP.EK,$APP.U,$APP.M,$APP.kF],[$APP.WI,ipb,"datascript/transit.cljs",19,1,9,9,$APP.Id,null,$APP.k(f7)?f7.H:null])),b=$APP.n(a),c=$APP.te(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,h7,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Vq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.lq.g(c);
return $APP.k(e)?e:$APP.yq.g(c)}())?$APP.fN.j(a,b,d):$APP.ju.j(a,b,d)}(),dpb,function(){var a=new $APP.Dd(function(){return g7},epb,$APP.hi([$APP.P,$APP.N,$APP.Wl,$APP.Xz,$APP.Pm,$APP.Xl,$APP.EK,$APP.U,$APP.M,$APP.kF],[$APP.WI,dpb,"datascript/transit.cljs",20,1,16,16,$APP.Id,null,$APP.k(g7)?g7.H:null])),b=$APP.n(a),c=$APP.te(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,h7,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Vq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=
$APP.lq.g(c);return $APP.k(e)?e:$APP.yq.g(c)}())?$APP.fN.j(a,b,d):$APP.ju.j(a,b,d)}(),fpb,function(){var a=new $APP.Dd(function(){return apb},cpb,$APP.hi([$APP.P,$APP.N,$APP.Wl,$APP.Xz,$APP.Pm,$APP.Xl,$APP.EK,$APP.U,$APP.M,$APP.kF],[$APP.WI,fpb,"datascript/transit.cljs",23,1,29,29,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.WH],null)),null,$APP.k(apb)?apb.H:null])),b=$APP.n(a),c=$APP.te(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,h7,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],
null);return $APP.k($APP.Vq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.lq.g(c);return $APP.k(e)?e:$APP.yq.g(c)}())?$APP.fN.j(a,b,d):$APP.ju.j(a,b,d)}(),jpb,function(){var a=new $APP.Dd(function(){return bpb},hpb,$APP.hi([$APP.P,$APP.N,$APP.Wl,$APP.Xz,$APP.Pm,$APP.Xl,$APP.EK,$APP.U,$APP.M,$APP.kF],[$APP.WI,jpb,"datascript/transit.cljs",24,1,33,33,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.SH],null)),null,$APP.k(bpb)?bpb.H:null])),b=$APP.n(a),c=$APP.te(a);a=$APP.k(null)?null:$APP.N.g(c);var d=
new $APP.h(null,4,[$APP.P,h7,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Vq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.lq.g(c);return $APP.k(e)?e:$APP.yq.g(c)}())?$APP.fN.j(a,b,d):$APP.ju.j(a,b,d)}()],null);$APP.Zu(new $APP.h(null,1,[$APP.Lq,new $APP.h(null,1,[$APP.WI,kpb],null)],null));