import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var B8a,dY,eY,C8a,D8a,E8a,F8a,hY,iY,H8a,kY,lY,I8a,mY,J8a,K8a,L8a,M8a,pY,N8a,O8a,P8a,Q8a,R8a,S8a,T8a,U8a,V8a,W8a,X8a,Y8a,Z8a,$8a,a9a;B8a=function(a,b,c){if(null!=a&&null!=a.ph)a=a.ph(a,b,c);else{var d=B8a[$APP.ea(null==a?null:a)];if(null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else if(d=B8a._,null!=d)a=d.j?d.j(a,b,c):d.call(null,a,b,c);else throw $APP.Kb("ITransientVector.-assoc-n!",a);}return a};
dY=function(a,b,c){var d=$APP.be(a);if(c>=d)return-1;!(0<c)&&0>c&&(c+=d,c=0>c?0:c);for(;;)if(c<d){if($APP.x.h($APP.y.h(a,c),b))return c;c+=1}else return-1};eY=function(a,b,c){var d=$APP.be(a);if(0===d)return-1;0<c?(--d,c=d<c?d:c):c=0>c?d+c:c;for(;;)if(0<=c){if($APP.x.h($APP.y.h(a,c),b))return c;--c}else return-1};
C8a=function(a,b){if($APP.ze(b))if($APP.$d(a)&&$APP.$d(b)&&$APP.be(a)!==$APP.be(b))a=!1;else a:for(a=$APP.r(a),b=$APP.r(b);;){if(null==a){a=null==b;break a}if(null!=b&&$APP.x.h($APP.v(a),$APP.v(b)))a=$APP.w(a),b=$APP.w(b);else{a=!1;break a}}else a=null;return $APP.hb(a)};D8a=function(a,b){var c=a.aa(null);if(0===c)return b.D?b.D():b.call(null);for(var d=a.ha(null,0),e=1;;)if(e<c){var f=a.ha(null,e);d=b.h?b.h(d,f):b.call(null,d,f);if($APP.Td(d))return $APP.n(d);e+=1}else return d};
E8a=function(a,b,c){var d=a.aa(null),e=c;for(c=0;;)if(c<d){var f=a.ha(null,c);e=b.h?b.h(e,f):b.call(null,e,f);if($APP.Td(e))return $APP.n(e);c+=1}else return e};F8a=function(a){return"number"===typeof a||"string"===typeof a||$APP.Ie(a)||null==a};hY=function(a,b,c,d){var e=null!=d?d.g?d.g(a):d.call(null,a):null;return null==e?F8a(a)?a:$APP.Db(a)?new $APP.fY(null,a,b,c,d,!0,null,null,null):$APP.zb(a)?new $APP.gY(null,b,c,d,a,null):a:e};
iY=function(a){return F8a(a)?a:a instanceof $APP.fY?a.Ja:a instanceof $APP.gY?a.I:a};H8a=function(a,b,c,d,e){var f=$APP.yg($APP.Tc(G8a));$APP.Ia(a,function(m,p){return f.uc(null,$APP.Gh.j(f.Ka(null),b.g?b.g(p):b.call(null,p),$APP.k(e)?hY(m,b,c,d):m))});return $APP.Vc($APP.n(f))};kY=function(a){a:for(var b=a.length,c=$APP.Ob(a),d=0;;)if(d<b){var e=d;var f=a[d];f=jY.g?jY.g(f):jY.call(null,f);c[e]=f;d+=1}else break a;return $APP.cf(c)};
lY=function(a,b,c,d,e,f,m){m=f[m];f=b.g?b.g(m):b.call(null,m);a=a[m];b=e?hY(a,b,c,d):a;return new $APP.Se(f,b,null)};I8a=function(a,b){return a instanceof $APP.F&&b===$APP.fj||"string"===typeof a&&b===$APP.ef};mY=function(a,b){return F8a(a)||!($APP.Ae(a)&&!(a instanceof $APP.fY)||$APP.De(a)&&!(a instanceof $APP.gY))&&$APP.Bb($APP.k(b)?$APP.Db(a)||$APP.zb(a):b)};J8a=function(a,b,c,d,e,f){this.lc=!0;this.Ja=a;this.ya=b;this.ia=c;this.transform=d;this.Da=e;this.ae=f;this.J=259;this.M=56};
K8a=function(a,b,c,d,e,f,m){this.Ja=a;this.ya=b;this.ia=c;this.transform=d;this.Da=e;this.I=f;this.X=0;this.T=m};$APP.nY=function(a,b,c,d,e,f,m,p){this.Ja=a;this.ya=b;this.ia=c;this.transform=d;this.Da=e;this.I=f;this.X=m;this.P=p;this.J=2179858686;this.M=8192};$APP.fY=function(a,b,c,d,e,f,m,p,u){this.P=a;this.Ja=b;this.ya=c;this.ia=d;this.transform=e;this.Da=f;this.ne=m;this.ae=p;this.C=u;this.J=2164131599;this.M=139268};
L8a=function(a,b,c,d){this.lc=!0;this.I=a;this.ya=b;this.ia=c;this.transform=d;this.M=88;this.J=275};M8a=function(a,b,c,d,e){this.ya=a;this.ia=b;this.transform=c;this.I=d;this.X=0;this.T=e};$APP.oY=function(a,b,c,d,e,f){this.ya=a;this.ia=b;this.transform=c;this.I=d;this.X=e;this.P=f;this.J=2179858686;this.M=8192};$APP.gY=function(a,b,c,d,e,f){this.P=a;this.ya=b;this.ia=c;this.transform=d;this.I=e;this.C=f;this.J=2315150111;this.M=141316};pY=function(a){return a instanceof $APP.F?a.N:null};
N8a=function(a){return a instanceof $APP.fY};O8a=function(a){return a.Ja};P8a=new $APP.q("cljs-bean.core","-\x3ejs","cljs-bean.core/-\x3ejs",272545438,null);Q8a=new $APP.F(null,"key-\x3eprop","key-\x3eprop",-1028452531);R8a=new $APP.q(null,"bean?","bean?",2057456095,null);S8a=new $APP.F(null,"recursive","recursive",718885872);T8a=new $APP.F(null,"prop-\x3ekey","prop-\x3ekey",-1297715246);U8a=new $APP.q("cljs-bean.core","bean?","cljs-bean.core/bean?",-413971875,null);
V8a=new $APP.q("cljs-bean.core","bean","cljs-bean.core/bean",444589162,null);W8a=new $APP.q(null,"bean","bean",-1620239896,null);X8a=new $APP.F(null,"transform","transform",1381301764);Y8a=new $APP.q(null,"-\x3eclj","-\x3eclj",-1549422014,null);Z8a=new $APP.q("cljs-bean.core","object","cljs-bean.core/object",1153194626,null);$8a=new $APP.q("cljs-bean.core","-\x3eclj","cljs-bean.core/-\x3eclj",649375936,null);a9a=new $APP.q(null,"-\x3ejs","-\x3ejs",-1825590244,null);var qY={},G8a=$APP.Uf;$APP.g=J8a.prototype;$APP.g.ba=function(a,b){if(this.lc)return a=this.Ja[this.ia.g?this.ia.g(b):this.ia.call(null,b)],this.Da?hY(a,this.ya,this.ia,this.transform):a;throw Error("lookup after persistent!");};$APP.g.K=function(a,b,c){if(this.lc)return a=$APP.La(this.Ja,this.ia.g?this.ia.g(b):this.ia.call(null,b),c),this.Da&&a!==c?hY(a,this.ya,this.ia,this.transform):a;throw Error("lookup after persistent!");};
$APP.g.aa=function(){return null==this.ae?this.ae=$APP.be($APP.Ja(this.Ja)):this.ae};$APP.g.Oe=function(a,b){a:if($APP.k(this.lc))if($APP.eh(b))a=this.qf(null,$APP.jc(b),$APP.kc(b));else if($APP.De(b))a=this.qf(null,b.g?b.g(0):b.call(null,0),b.g?b.g(1):b.call(null,1));else for(a=$APP.r(b),b=this;;){var c=$APP.v(a);if($APP.k(c))a=$APP.w(a),b=$APP.Wc(b,$APP.jc(c),$APP.kc(c));else{a=b;break a}}else throw Error("conj! after persistent!");return a};
$APP.g.Df=function(){if(this.lc)return this.lc=!1,new $APP.fY(null,this.Ja,this.ya,this.ia,this.transform,this.Da,null,this.ae,null);throw Error("persistent! called twice");};$APP.g.qf=function(a,b,c){if(this.lc){if(!I8a(b,this.ya)||!mY(c,this.Da))return $APP.Wc($APP.Tc(H8a(this.Ja,this.ya,this.ia,this.transform,this.Da)),b,c);this.Ja[this.ia.g?this.ia.g(b):this.ia.call(null,b)]=this.Da?iY(c):c;this.ae=null;return this}throw Error("assoc! after persistent!");};
$APP.g.ci=function(a,b){if(this.lc)return delete this.Ja[this.ia.g?this.ia.g(b):this.ia.call(null,b)],this.ae=null,this;throw Error("dissoc! after persistent!");};$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.l.g(arguments.length-1)].join(""));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Ob(b)))};
$APP.g.g=function(a){if(this.lc)return a=this.Ja[this.ia.g?this.ia.g(a):this.ia.call(null,a)],this.Da?hY(a,this.ya,this.ia,this.transform):a;throw Error("lookup after persistent!");};$APP.g.h=function(a,b){if(this.lc)return a=$APP.La(this.Ja,this.ia.g?this.ia.g(a):this.ia.call(null,a),b),this.Da&&a!==b?hY(a,this.ya,this.ia,this.transform):a;throw Error("lookup after persistent!");};K8a.prototype.hasNext=function(){return this.X<this.T};
K8a.prototype.next=function(){var a=lY(this.Ja,this.ya,this.ia,this.transform,this.Da,this.I,this.X);this.X+=1;return a};$APP.g=$APP.nY.prototype;$APP.g.toString=function(){return $APP.od(this)};$APP.g.equiv=function(a){return this.S(null,a)};
$APP.g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return dY(this,b,0);case 2:return dY(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return dY(this,b,0)};a.h=function(b,c){return dY(this,b,c)};return a}();
$APP.g.lastIndexOf=function(){function a(c){return eY(this,c,$APP.be(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return eY(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return eY(this,c,d)};return b}();$APP.g.ha=function(a,b){a=b+this.X;if(0<=a&&a<this.I.length)return lY(this.Ja,this.ya,this.ia,this.transform,this.Da,this.I,a);throw Error("Index out of bounds");};
$APP.g.kb=function(a,b,c){a=b+this.X;return 0<=a&&a<this.I.length?lY(this.Ja,this.ya,this.ia,this.transform,this.Da,this.I,a):c};$APP.g.W=function(a,b,c){return $APP.aj(b,$APP.dj,"("," ",")",c,this)};$APP.g.U=function(){return this.P};$APP.g.ca=function(){return new $APP.nY(this.Ja,this.ya,this.ia,this.transform,this.Da,this.I,this.X,this.P)};$APP.g.bb=function(){return this.X+1<this.I.length?new $APP.nY(this.Ja,this.ya,this.ia,this.transform,this.Da,this.I,this.X+1,null):null};
$APP.g.aa=function(){var a=this.I.length-this.X;return 0>a?0:a};$APP.g.Y=function(){return $APP.Ld(this)};$APP.g.S=function(a,b){return C8a(this,b)};$APP.g.Oa=function(){return $APP.Hd};$APP.g.lb=function(a,b){return D8a(this,b)};$APP.g.gb=function(a,b,c){return E8a(this,b,c)};$APP.g.hb=function(){return lY(this.Ja,this.ya,this.ia,this.transform,this.Da,this.I,this.X)};
$APP.g.xb=function(){return this.X+1<this.I.length?new $APP.nY(this.Ja,this.ya,this.ia,this.transform,this.Da,this.I,this.X+1,null):$APP.Hd};$APP.g.Z=function(){return this};$APP.g.V=function(a,b){return b===this.P?this:new $APP.nY(this.Ja,this.ya,this.ia,this.transform,this.Da,this.I,this.X,b)};$APP.g.da=function(a,b){return $APP.yf(b,this)};$APP.g=$APP.fY.prototype;$APP.g.Ne=$APP.vd;
$APP.g.qe=function(a,b){a=$APP.La(this.Ja,this.ia.g?this.ia.g(b):this.ia.call(null,b),qY);return a===qY?null:new $APP.Se(b,this.Da?hY(a,this.ya,this.ia,this.transform):a,null)};$APP.g.toString=function(){return $APP.od(this)};$APP.g.equiv=function(a){return this.S(null,a)};$APP.g.keys=function(){return $APP.Jd($APP.qi(this))};$APP.g.entries=function(){return $APP.wh($APP.r(this))};$APP.g.values=function(){return $APP.Jd($APP.si(this))};$APP.g.has=function(a){return $APP.Re(this,a)};
$APP.g.get=function(a,b){return this.K(null,a,b)};$APP.g.forEach=function(a){for(var b=$APP.r(this),c=null,d=0,e=0;;)if(e<d){var f=c.ha(null,e),m=$APP.y.j(f,0,null);f=$APP.y.j(f,1,null);a.h?a.h(f,m):a.call(null,f,m);e+=1}else if(b=$APP.r(b))$APP.Ee(b)?(c=$APP.cd(b),b=$APP.dd(b),m=c,d=$APP.be(c),c=m):(c=$APP.v(b),m=$APP.y.j(c,0,null),f=$APP.y.j(c,1,null),a.h?a.h(f,m):a.call(null,f,m),b=$APP.w(b),c=null,d=0),e=0;else return null};
$APP.g.ba=function(a,b){a=this.Ja[this.ia.g?this.ia.g(b):this.ia.call(null,b)];return this.Da?hY(a,this.ya,this.ia,this.transform):a};$APP.g.K=function(a,b,c){a=$APP.La(this.Ja,this.ia.g?this.ia.g(b):this.ia.call(null,b),c);return this.Da&&a!==c?hY(a,this.ya,this.ia,this.transform):a};
$APP.g.ja=function(a,b,c){var d=this;try{var e=$APP.yg(c);$APP.Ia(d.Ja,function(f,m){var p=e.uc;var u=e.Ka(null);m=d.ya.g?d.ya.g(m):d.ya.call(null,m);f=d.Da?hY(f,d.ya,d.ia,d.transform):f;u=b.j?b.j(u,m,f):b.call(null,u,m,f);p=p.call(e,null,u);if($APP.Td(p))throw p;return null});return $APP.n(e)}catch(f){a=f;if($APP.Td(a))return $APP.n(a);throw a;}};$APP.g.W=function(a,b,c){return $APP.gj(this,$APP.dj,b,c)};
$APP.g.fa=function(){null==this.ne&&(this.ne=$APP.Ja(this.Ja));return new K8a(this.Ja,this.ya,this.ia,this.transform,this.Da,this.ne,this.aa(null))};$APP.g.U=function(){return this.P};$APP.g.ca=function(){return new $APP.fY(this.P,this.Ja,this.ya,this.ia,this.transform,this.Da,this.ne,this.ae,this.C)};$APP.g.aa=function(){return null==this.ae?(null==this.ne&&(this.ne=$APP.Ja(this.Ja)),this.ae=this.ne.length):this.ae};$APP.g.Y=function(){var a=this.C;return null!=a?a:this.C=a=$APP.Md(this)};
$APP.g.S=function(a,b){return $APP.uh(this,b)};$APP.g.mf=function(){return new J8a($APP.Ma(this.Ja),this.ya,this.ia,this.transform,this.Da,this.ae)};$APP.g.Oa=function(){return new $APP.fY(this.P,{},this.ya,this.ia,this.transform,this.Da,[],0,null)};$APP.g.lb=function(a,b){return $APP.Hx(this.Z(null),b)};$APP.g.gb=function(a,b,c){return this.ja(null,function(d,e,f){e=new $APP.Se(e,f,null);return b.h?b.h(d,e):b.call(null,d,e)},c)};
$APP.g.la=function(a,b){a=this.P;var c=$APP.Ma(this.Ja);delete c[this.ia.g?this.ia.g(b):this.ia.call(null,b)];return new $APP.fY(a,c,this.ya,this.ia,this.transform,this.Da,null,null,null)};
$APP.g.O=function(a,b,c){if(I8a(b,this.ya)&&mY(c,this.Da)){a=this.P;var d=$APP.Ma(this.Ja);d[this.ia.g?this.ia.g(b):this.ia.call(null,b)]=this.Da?iY(c):c;b=new $APP.fY(a,d,this.ya,this.ia,this.transform,this.Da,null,null,null)}else b=$APP.fc($APP.re(H8a(this.Ja,this.ya,this.ia,this.transform,this.Da),this.P),b,c);return b};$APP.g.ga=function(a,b){return this.K(null,b,qY)!==qY};
$APP.g.Z=function(){null==this.ne&&(this.ne=$APP.Ja(this.Ja));return 0<this.ne.length?new $APP.nY(this.Ja,this.ya,this.ia,this.transform,this.Da,this.ne,0,null):null};$APP.g.V=function(a,b){return b===this.P?this:new $APP.fY(b,this.Ja,this.ya,this.ia,this.transform,this.Da,this.ne,this.ae,this.C)};
$APP.g.da=function(a,b){a:if($APP.De(b))a=this.O(null,$APP.oe(b,0),$APP.oe(b,1));else for(a=this,b=$APP.r(b);;){if(null==b)break a;var c=$APP.v(b);if($APP.De(c))a=$APP.fc(a,$APP.oe(c,0),$APP.oe(c,1)),b=$APP.w(b);else throw Error("conj on a map takes map entries or seqables of map entries");}return a};
$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.l.g(arguments.length-1)].join(""));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Ob(b)))};$APP.g.g=function(a){a=this.Ja[this.ia.g?this.ia.g(a):this.ia.call(null,a)];return this.Da?hY(a,this.ya,this.ia,this.transform):a};
$APP.g.h=function(a,b){a=$APP.La(this.Ja,this.ia.g?this.ia.g(a):this.ia.call(null,a),b);return this.Da&&a!==b?hY(a,this.ya,this.ia,this.transform):a};$APP.g=L8a.prototype;$APP.g.Oe=function(a,b){if(this.lc)return mY(b,!0)?(this.I.push(iY(b)),this):$APP.Uc($APP.Tc(kY(this.I)),b);throw Error("conj! after persistent!");};$APP.g.Df=function(){if(this.lc)return this.lc=!1,new $APP.gY(null,this.ya,this.ia,this.transform,this.I,null);throw Error("persistent! called twice");};
$APP.g.qf=function(a,b,c){if("number"===typeof b)a=this.ph(null,b,c);else throw Error([$APP.l.g("TransientArrayVector"),"'s key for assoc! must be a number."].join(""));return a};
$APP.g.ph=function(a,b,c){if(this.lc){if(mY(c,!0)){if(0<=b&&b<this.I.length)return this.I[b]=iY(c),this;if(b===this.I.length)return this.Oe(null,c);throw Error(["Index ",$APP.l.g(b)," out of bounds for TransientArrayVector of length",$APP.l.g(this.I.length)].join(""));}return B8a($APP.Tc(kY(this.I)),b,c)}throw Error("assoc! after persistent!");};
$APP.g.fj=function(){if(this.lc){if(0===this.I.length)throw Error("Can't pop empty vector");this.I=this.I.slice(0,this.I.length-1);return this}throw Error("pop! after persistent!");};$APP.g.aa=function(){if(this.lc)return this.I.length;throw Error("count after persistent!");};$APP.g.ha=function(a,b){if(this.lc)return hY(this.I[b],this.ya,this.ia,this.transform);throw Error("nth after persistent!");};$APP.g.kb=function(a,b,c){return 0<=b&&b<this.I.length?this.ha(null,b):c};
$APP.g.ba=function(a,b){return this.K(null,b,null)};$APP.g.K=function(a,b,c){return"number"===typeof b?this.kb(null,b,c):c};$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.l.g(arguments.length-1)].join(""));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Ob(b)))};$APP.g.g=function(a){return this.ba(null,a)};
$APP.g.h=function(a,b){return this.K(null,a,b)};M8a.prototype.hasNext=function(){return this.X<this.T};M8a.prototype.next=function(){var a=hY(this.I[this.X],this.ya,this.ia,this.transform);this.X+=1;return a};$APP.g=$APP.oY.prototype;$APP.g.toString=function(){return $APP.od(this)};$APP.g.equiv=function(a){return this.S(null,a)};
$APP.g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return dY(this,b,0);case 2:return dY(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return dY(this,b,0)};a.h=function(b,c){return dY(this,b,c)};return a}();
$APP.g.lastIndexOf=function(){function a(c){return eY(this,c,$APP.be(this))}var b=null;b=function(c,d){switch(arguments.length){case 1:return a.call(this,c);case 2:return eY(this,c,d)}throw Error("Invalid arity: "+arguments.length);};b.g=a;b.h=function(c,d){return eY(this,c,d)};return b}();$APP.g.ha=function(a,b){a=b+this.X;if(0<=a&&a<this.I.length)return hY(this.I[a],this.ya,this.ia,this.transform);throw Error("Index out of bounds");};
$APP.g.kb=function(a,b,c){a=b+this.X;return 0<=a&&a<this.I.length?hY(this.I[a],this.ya,this.ia,this.transform):c};$APP.g.W=function(a,b,c){return $APP.aj(b,$APP.dj,"("," ",")",c,this)};$APP.g.U=function(){return this.P};$APP.g.ca=function(){return new $APP.oY(this.ya,this.ia,this.transform,this.I,this.X,this.P)};$APP.g.bb=function(){return this.X+1<this.I.length?new $APP.oY(this.ya,this.ia,this.transform,this.I,this.X+1,null):null};$APP.g.aa=function(){var a=this.I.length-this.X;return 0>a?0:a};
$APP.g.Y=function(){return $APP.Ld(this)};$APP.g.S=function(a,b){return C8a(this,b)};$APP.g.Oa=function(){return $APP.Hd};$APP.g.lb=function(a,b){return D8a(this,b)};$APP.g.gb=function(a,b,c){return E8a(this,b,c)};$APP.g.hb=function(){return hY(this.I[this.X],this.ya,this.ia,this.transform)};$APP.g.xb=function(){return this.X+1<this.I.length?new $APP.oY(this.ya,this.ia,this.transform,this.I,this.X+1,null):$APP.Hd};$APP.g.Z=function(){return this};
$APP.g.V=function(a,b){return b===this.P?this:new $APP.oY(this.ya,this.ia,this.transform,this.I,this.X,b)};$APP.g.da=function(a,b){return $APP.yf(b,this)};$APP.g=$APP.gY.prototype;$APP.g.Ne=$APP.vd;$APP.g.qe=function(a,b){return 0<=b&&b<this.I.length?new $APP.Se(b,hY(this.I[b],this.ya,this.ia,this.transform),null):null};$APP.g.toString=function(){return $APP.od(this)};$APP.g.equiv=function(a){return this.S(null,a)};
$APP.g.indexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return dY(this,b,0);case 2:return dY(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return dY(this,b,0)};a.h=function(b,c){return dY(this,b,c)};return a}();
$APP.g.lastIndexOf=function(){var a=null;a=function(b,c){switch(arguments.length){case 1:return eY(this,b,$APP.be(this));case 2:return eY(this,b,c)}throw Error("Invalid arity: "+arguments.length);};a.g=function(b){return eY(this,b,$APP.be(this))};a.h=function(b,c){return eY(this,b,c)};return a}();$APP.g.ba=function(a,b){return this.K(null,b,null)};$APP.g.K=function(a,b,c){return"number"===typeof b?this.kb(null,b,c):c};
$APP.g.ja=function(a,b,c){a=0;for(var d=c;;)if(a<this.I.length){c=this.I.length;var e;a:for(e=0;;)if(e<c){var f=e+a,m=hY(this.I[e],this.ya,this.ia,this.transform);d=b.j?b.j(d,f,m):b.call(null,d,f,m);if($APP.Td(d)){e=d;break a}e+=1}else{e=d;break a}if($APP.Td(e))return $APP.n(e);a+=c;d=e}else return d};$APP.g.ha=function(a,b){if(0<=b&&b<this.I.length)return hY(this.I[b],this.ya,this.ia,this.transform);throw Error(["No item ",$APP.l.g(b)," in vector of length ",$APP.l.g(this.I.length)].join(""));};
$APP.g.kb=function(a,b,c){return 0<=b&&b<this.I.length?hY(this.I[b],this.ya,this.ia,this.transform):c};$APP.g.W=function(a,b,c){return $APP.aj(b,$APP.dj,"["," ","]",c,this)};$APP.g.de=function(a,b,c){if(0<=b&&b<this.I.length)return mY(c,!0)?(a=$APP.Ob(this.I),a[b]=iY(c),new $APP.gY(this.P,this.ya,this.ia,this.transform,a,null)):$APP.qc(kY(this.I),b,c);if(b===this.I.length)return this.da(null,c);throw Error(["Index ",$APP.l.g(b)," out of bounds  [0,",$APP.l.g(this.I.length),"]"].join(""));};
$APP.g.fa=function(){return new M8a(this.ya,this.ia,this.transform,this.I,this.I.length)};$APP.g.U=function(){return this.P};$APP.g.ca=function(){return new $APP.gY(this.P,this.ya,this.ia,this.transform,this.I,this.C)};$APP.g.aa=function(){return this.I.length};$APP.g.nf=function(){return 0<this.I.length?this.ha(null,this.I.length-1):null};
$APP.g.pf=function(){if(0===this.I.length)throw Error("Can't pop empty vector");if(1===this.I.length)return this.Oa(null);var a=$APP.Ob(this.I);return new $APP.gY(this.P,this.ya,this.ia,this.transform,a.slice(0,a.length-1),null)};$APP.g.Bd=function(){return 0<this.I.length?new $APP.fe(this,this.I.length-1,null):null};$APP.g.Y=function(){var a=this.C;return null!=a?a:this.C=a=$APP.Ld(this)};
$APP.g.S=function(a,b){a:if(b instanceof $APP.gY)if(this.I.length===$APP.be(b))for(a=this.fa(null),b=$APP.ld(b);;)if(a.hasNext()){var c=a.next(),d=b.next();if(!$APP.x.h(c,d)){a=!1;break a}}else{a=!0;break a}else a=!1;else a=C8a(this,b);return a};$APP.g.mf=function(){return new L8a($APP.Ob(this.I),this.ya,this.ia,this.transform)};$APP.g.Oa=function(){return new $APP.gY(this.P,this.ya,this.ia,this.transform,[],null)};$APP.g.lb=function(a,b){return D8a(this,b)};
$APP.g.gb=function(a,b,c){return E8a(this,b,c)};$APP.g.O=function(a,b,c){if("number"===typeof b)a=this.de(null,b,c);else throw Error("Vector's key for assoc must be a number.");return a};$APP.g.ga=function(a,b){return $APP.Me(b)?0<=b&&b<this.I.length:!1};$APP.g.Z=function(){return 0<this.I.length?new $APP.oY(this.ya,this.ia,this.transform,this.I,0,null):null};$APP.g.V=function(a,b){return b===this.P?this:new $APP.gY(b,this.ya,this.ia,this.transform,this.I,this.C)};
$APP.g.da=function(a,b){return mY(b,!0)?(a=$APP.Ob(this.I),a[a.length]=iY(b),new $APP.gY(this.P,this.ya,this.ia,this.transform,a,null)):$APP.Vb(kY(this.I),b)};$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.l.g(arguments.length-1)].join(""));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Ob(b)))};$APP.g.g=function(a){return this.ha(null,a)};
$APP.g.h=function(a,b){return this.kb(null,a,b)};$APP.g.be=function(a,b){if($APP.De(b)){a=$APP.be(this);var c=$APP.be(b);if(a<c)b=-1;else if(a>c)b=1;else if(0===a)b=0;else a:for(c=0;;){var d=$APP.Ve($APP.y.h(this,c),$APP.y.h(b,c));if(0===d&&c+1<a)c+=1;else{b=d;break a}}return b}throw Error(["Cannot compare ",$APP.l.g(this)," to ",$APP.l.g(b)].join(""));};
var rY=function rY(a){switch(arguments.length){case 0:return rY.D();case 1:return rY.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return rY.l(arguments[0],1<c.length?new $APP.Ed(c.slice(1),0,null):null)}};rY.D=function(){return new $APP.fY(null,{},$APP.fj,pY,null,!1,[],0,null)};rY.g=function(a){return new $APP.fY(null,a,$APP.fj,pY,null,!1,null,null,null)};
rY.l=function(a,b){var c=$APP.Vf(b);b=$APP.B.h(c,$APP.fz);var d=$APP.B.h(c,T8a),e=$APP.B.h(c,Q8a),f=$APP.B.h(c,X8a);c=$APP.B.h(c,S8a);return!1===b?new $APP.fY(null,a,$APP.ef,$APP.ef,f,$APP.hb(c),null,null,null):null!=d&&null!=e?new $APP.fY(null,a,d,e,f,$APP.hb(c),null,null,null):new $APP.fY(null,a,$APP.fj,pY,f,$APP.hb(c),null,null,null)};rY.G=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};rY.B=1;
var jY=function jY(a){switch(arguments.length){case 1:return jY.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return jY.l(arguments[0],1<c.length?new $APP.Ed(c.slice(1),0,null):null)}};jY.g=function(a){return hY(a,$APP.fj,pY,null)};jY.l=function(a,b){var c=$APP.Vf(b);b=$APP.B.h(c,$APP.fz);var d=$APP.B.h(c,T8a),e=$APP.B.h(c,Q8a);c=$APP.B.h(c,X8a);return!1===b?hY(a,$APP.ef,$APP.ef,c):null!=d&&null!=e?hY(a,d,e,c):hY(a,$APP.fj,pY,c)};
jY.G=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};jY.B=1;var sY=function sY(a){switch(arguments.length){case 1:return sY.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return sY.l(arguments[0],1<c.length?new $APP.Ed(c.slice(1),0,null):null)}};sY.g=function(a){return a instanceof $APP.fY?a.Ja:a instanceof $APP.gY?a.I:$APP.cz.l(a,$APP.z([$APP.dz,pY]))};
sY.l=function(a,b){if(a instanceof $APP.fY)return a.Ja;if(a instanceof $APP.gY)return a.I;b=$APP.Vf(b);b=$APP.B.j(b,Q8a,pY);return $APP.cz.l(a,$APP.z([$APP.dz,b]))};sY.G=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};sY.B=1;var tY=$APP.kN.h($APP.QE,null),b9a=new $APP.h(null,5,[W8a,function(){var a=new $APP.Cd(function(){return rY},V8a,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.oI,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.QE,W8a,"cljs_bean/core.cljs",11,new $APP.h(null,6,[$APP.DA,!0,$APP.Qs,1,$APP.DJ,1,$APP.lJ,new $APP.G(null,2,5,$APP.H,[$APP.Sg,new $APP.G(null,1,5,$APP.H,[$APP.WH],null)],null),$APP.U,$APP.J($APP.Sg,new $APP.G(null,1,5,$APP.H,[$APP.WH],null),new $APP.G(null,3,5,$APP.H,[$APP.WH,$APP.ik,$APP.bG],
null)),$APP.fF,$APP.J(null,null,null)],null),1,702,702,$APP.J($APP.Sg,new $APP.G(null,1,5,$APP.H,[$APP.WH],null),new $APP.G(null,3,5,$APP.H,[$APP.WH,$APP.ik,$APP.bG],null)),"Takes a JavaScript object and returns a read-only implementation of the map\n  abstraction backed by the object.\n\n  By default, bean produces beans that keywordize the keys. Supply\n  :keywordize-keys false to suppress this behavior. You can alternatively\n  supply :prop-\x3ekey and :key-\x3eprop with functions that control the mapping\n  between properties and keys.\n\n  Supply :recursive true to create a bean which recursively converts\n  JavaScript object values to beans and JavaScript arrays into vectors.\n\n  Supply :transform and a function of one argument to transform values being\n  converted from JavaScript to ClojureScript. This function should return nil\n  if no conversion is to be performed, thus allowing default logic to be applied.\n\n  Calling (bean) produces an empty bean.",
$APP.k(rY)?rY.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,tY,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),R8a,function(){var a=new $APP.Cd(function(){return N8a},U8a,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.QE,R8a,"cljs_bean/core.cljs",
12,1,735,735,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.WH],null)),"Returns true if x is a bean.",$APP.k(N8a)?N8a.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,tY,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),$APP.Qxa,function(){var a=new $APP.Cd(function(){return O8a},Z8a,$APP.gi([$APP.P,
$APP.N,$APP.Vl,$APP.Zz,$APP.Om,$APP.Wl,$APP.EK,$APP.Cm,$APP.U,$APP.M,$APP.lF],[$APP.QE,$APP.Qxa,"cljs_bean/core.cljs",17,1,740,740,$APP.aD,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.zH],null)),"Takes a bean and returns a JavaScript object.",$APP.k(O8a)?O8a.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,tY,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?
e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),a9a,function(){var a=new $APP.Cd(function(){return sY},P8a,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.oI,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.QE,a9a,"cljs_bean/core.cljs",11,new $APP.h(null,6,[$APP.DA,!0,$APP.Qs,1,$APP.DJ,1,$APP.lJ,new $APP.G(null,1,5,$APP.H,[new $APP.G(null,1,5,$APP.H,[$APP.WH],null)],null),$APP.U,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.WH],null),new $APP.G(null,3,5,$APP.H,[$APP.WH,$APP.ik,$APP.bG],null)),$APP.fF,
$APP.J(null,null)],null),1,775,775,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.WH],null),new $APP.G(null,3,5,$APP.H,[$APP.WH,$APP.ik,$APP.bG],null)),"Recursively converts ClojureScript values to JavaScript.\n\n  Where possible, directly returns the backing objects and arrays for values\n  produced using -\x3eclj and bean.\n\n  Otherwise delegates to clj-\x3ejs to perform the conversion, converting keyword\n  keys using their qualified names. You can alternatively supply :key-\x3eprop with\n  a function that controls the mapping from keys to properties.",
$APP.k(sY)?sY.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,tY,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),Y8a,function(){var a=new $APP.Cd(function(){return jY},$8a,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.oI,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.QE,Y8a,"cljs_bean/core.cljs",
12,new $APP.h(null,6,[$APP.DA,!0,$APP.Qs,1,$APP.DJ,1,$APP.lJ,new $APP.G(null,1,5,$APP.H,[new $APP.G(null,1,5,$APP.H,[$APP.WH],null)],null),$APP.U,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.WH],null),new $APP.G(null,3,5,$APP.H,[$APP.WH,$APP.ik,$APP.bG],null)),$APP.fF,$APP.J(null,null)],null),1,745,745,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.WH],null),new $APP.G(null,3,5,$APP.H,[$APP.WH,$APP.ik,$APP.bG],null)),"Recursively converts JavaScript values to ClojureScript.\n\n  JavaScript objects are converted to beans with keywords for keys.\n\n  JavaScript arrays are converted to read-only implementations of the vector\n  abstraction, backed by the supplied array.\n\n  By default, -\x3eclj produces values that keywordize the keys. Supply\n  :keywordize-keys false to suppress this behavior. You can alternatively\n  supply :prop-\x3ekey and :key-\x3eprop with functions that control the mapping\n  between properties and keys.\n\n  Supply :transform and a function of one argument to transform values being\n  converted from JavaScript to ClojureScript. This function should return nil\n  if no conversion is to be performed, thus allowing default logic to be applied.",
$APP.k(jY)?jY.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,tY,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}()],null);$APP.Yu(new $APP.h(null,1,[$APP.Kq,new $APP.h(null,1,[$APP.QE,b9a],null)],null));