import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var Z5a=function(a,b,c,d){return $APP.Ci(a,function(e,f){$APP.nc(f,"[");$APP.nc(f,$APP.aj.l($APP.C([e])));$APP.nc(f," ");$APP.nc(f,$APP.aj.l($APP.C([$APP.D.h(b,e)])));return $APP.nc(f,"]")},"("," ",")",d,c)},Y$=function(a,b){this.Ha=a;this.Jc=b;this.J=2297825039;this.M=8192},Z$=function(a,b){return $APP.z.h(a,b instanceof Y$?b.Ha:b)},$5a=new $APP.G(null,"skip-protocol-flag","skip-protocol-flag",-1426798630),a6a=new $APP.t("cljs.core","IKVReduce","cljs.core/IKVReduce",878013381,null),b6a=new $APP.t("cljs.core",
"IFind","cljs.core/IFind",-1727519574,null),c6a=new $APP.t("cljs.core","IMeta","cljs.core/IMeta",-1459057517,null),d6a=new $APP.t("cljs.core","ISeqable","cljs.core/ISeqable",137437203,null),e6a=new $APP.t("cljs.core","ICounted","cljs.core/ICounted",-1299011378,null),f6a=new $APP.t("cljs.core","ILookup","cljs.core/ILookup",-150575073,null),g6a=new $APP.t(null,"ordered-map","ordered-map",-706459974,null),h6a=new $APP.t("cljs.core","IWithMeta","cljs.core/IWithMeta",-1981666051,null),i6a=new $APP.t("cljs.core",
"IAssociative","cljs.core/IAssociative",-1700920611,null),j6a=new $APP.t("cljs.core","ICloneable","cljs.core/ICloneable",-1712216461,null),k6a=new $APP.t(null,"print-ordered-map","print-ordered-map",1388177372,null),l6a=new $APP.t(null,"that","that",828965210,null),m6a=new $APP.t("flatland.ordered.map","-\x3eOrderedMap","flatland.ordered.map/-\x3eOrderedMap",-2112744986,null),n6a=new $APP.t("flatland.ordered.map","print-ordered-map","flatland.ordered.map/print-ordered-map",-867774065,null),o6a=new $APP.t("flatland.ordered.map",
"ordered-map","flatland.ordered.map/ordered-map",1887268971,null),p6a=new $APP.t(null,"equiv-impl","equiv-impl",417944565,null),q6a=new $APP.t("cljs.core","IMap","cljs.core/IMap",1407777598,null),r6a=new $APP.t("cljs.core","IReversible","cljs.core/IReversible",-1422278012,null),s6a=new $APP.t("cljs.core","IHash","cljs.core/IHash",-32453786,null),t6a=new $APP.t("flatland.ordered.map","equiv-impl","flatland.ordered.map/equiv-impl",-229597862,null),u6a=new $APP.t("cljs.core","IEmptyableCollection","cljs.core/IEmptyableCollection",
5045035,null),v6a=new $APP.t(null,"-\x3eOrderedMap","-\x3eOrderedMap",613100471,null),w6a=new $APP.t("cljs.core","IEquiv","cljs.core/IEquiv",-1245752602,null),x6a=new $APP.t("cljs.core","ICollection","cljs.core/ICollection",802638471,null),y6a=new $APP.G(null,"protocols","protocols",-5615896),z6a=new $APP.t("cljs.core","Object","cljs.core/Object",-345545431,null),A6a=new $APP.t("cljs.core","IPrintWithWriter","cljs.core/IPrintWithWriter",1349251417,null);$APP.g=Y$.prototype;$APP.g.Yd=$APP.cd;$APP.g.Id=function(a,b){return $APP.Lb(this.Ha,b)};$APP.g.entry_set=function(){return $APP.Ee($APP.Ii.h($APP.Ee,this.Ha))};
$APP.g.forEach=function(){function a(d,e){for(var f=$APP.u(this.Jc),h=null,m=0,r=0;;)if(r<m){var n=h.da(null,r);d.call(e,n,$APP.D.h(this.Ha,n),this);r+=1}else if(f=$APP.u(f))h=f,$APP.je(h)?(f=$APP.Kc(h),m=$APP.Lc(h),h=f,n=$APP.Gd(f),f=m,m=n):(n=$APP.v(h),d.call(e,n,$APP.D.h(this.Ha,n),this),f=$APP.y(h),h=null,m=0),r=0;else return null}function b(d){for(var e=$APP.u(this.Jc),f=null,h=0,m=0;;)if(m<h){var r=f.da(null,m),n=r;r=$APP.D.h(this.Ha,r);d.j?d.j(n,r,this):d.call(null,n,r,this);m+=1}else if(e=
$APP.u(e))$APP.je(e)?(r=$APP.Kc(e),e=$APP.Lc(e),f=r,h=r=$APP.Gd(r)):(f=r=$APP.v(e),r=$APP.D.h(this.Ha,r),d.j?d.j(f,r,this):d.call(null,f,r,this),e=$APP.y(e),f=null,h=0),m=0;else return null}var c=null;c=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};c.g=b;c.h=a;return c}();$APP.g.get=function(a){return this.Ha.get(a)};$APP.g.key_set=function(){return $APP.Ee($APP.Wh(this.Ha))};$APP.g.entries=function(){return $APP.Zg($APP.u(this.Ha))};
$APP.g.value_set=function(){return $APP.Ee($APP.Ii.h($APP.Hg,this.Ha))};$APP.g.toString=function(){return $APP.Uc(this)};$APP.g.keys=function(){return $APP.od(this.Jc)};$APP.g.values=function(){return $APP.od($APP.Yh(this.Ha))};$APP.g.equiv=function(a){return Z$.h?Z$.h(this.Ha,a):Z$.call(null,this.Ha,a)};$APP.g.has=function(a){return null!=this.Ha.get(a)};$APP.g.fa=function(a,b){return $APP.Au(this.Ha,b)};$APP.g.N=function(a,b,c){return $APP.Au(this.Ha,b,c)};
$APP.g.la=function(a,b,c){var d=this;return $APP.De.j(function(e,f){var h=$APP.D.h(d.Ha,f);return b.j?b.j(e,f,h):b.call(null,e,f,h)},c,d.Jc)};$APP.g.V=function(a,b,c){$APP.nc(b,"#ordered/map ");return Z5a(b,this.Ha,this.Jc,c)};$APP.g.W=function(){return $APP.Xd(this.Ha)};$APP.g.ba=function(){return new Y$(this.Ha,this.Jc)};$APP.g.aa=function(){return $APP.Gd(this.Ha)};$APP.g.bd=function(){var a=this;return $APP.u(a.Jc)?$APP.Ii.h(function(b){return $APP.Lb(a.Ha,b)},$APP.ic(a.Jc)):null};$APP.g.Y=function(){return $APP.dd(this.Ha)};
$APP.g.R=function(a,b){return Z$.h?Z$.h(this.Ha,b):Z$.call(null,this.Ha,b)};$APP.g.Ja=function(){return $APP.u(this.Jc)?new Y$($APP.Bb(this.Ha),$APP.qg):this};$APP.g.sa=function(a,b){return $APP.ue(this.Ha,b)?new Y$($APP.ql.h(this.Ha,b),$APP.fh.j($APP.qg,$APP.kr.g($APP.ei([b])),this.Jc)):this};$APP.g.U=function(a,b,c){return new Y$($APP.$h.j(this.Ha,b,c),$APP.ue(this.Ha,b)?this.Jc:$APP.We.h(this.Jc,b))};$APP.g.ka=function(a,b){return $APP.ue(this.Ha,b)};
$APP.g.Z=function(){var a=this;return $APP.u(a.Jc)?$APP.Ii.h(function(b){return $APP.Lb(a.Ha,b)},a.Jc):null};$APP.g.X=function(a,b){return $APP.Xd(this.Ha)===b?this:new Y$($APP.Wd(this.Ha,b),this.Jc)};$APP.g.ca=function(a,b){var c=this;return $APP.ie(b)?new Y$($APP.We.h(c.Ha,b),$APP.ue(c.Ha,$APP.Td(b,0))?c.Jc:$APP.We.h(c.Jc,$APP.Td(b,0))):new Y$($APP.We.h(c.Ha,b),$APP.fh.j(c.Jc,$APP.tp.h($APP.Ii.g(function(d){return $APP.Td(d,0)}),$APP.kr.g(function(d){return $APP.ue(c.Ha,d)})),b))};
$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.p.g(arguments.length-1)].join(""));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.vb(b)))};$APP.g.g=function(a){return this.Ha.g?this.Ha.g(a):this.Ha.call(null,a)};$APP.g.h=function(a,b){return this.Ha.h?this.Ha.h(a,b):this.Ha.call(null,a,b)};
var B6a=new Y$($APP.wf,$APP.qg),$$=function $$(a){switch(arguments.length){case 0:return $$.C();case 1:return $$.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return $$.l(arguments[0],arguments[1],new $APP.jd(c.slice(2),0,null))}};$$.C=function(){return B6a};$$.g=function(a){return $APP.fh.h(B6a,a)};$$.l=function(a,b,c){return $APP.Xf.P($APP.$h,B6a,a,b,c)};
$$.G=function(a){var b=$APP.v(a),c=$APP.y(a);a=$APP.v(c);c=$APP.y(c);return this.l(b,a,c)};$$.A=2;var C6a=$APP.GO.h($APP.tF,null),D6a=$APP.nt(new $APP.k(null,4,[$APP.Wd(p6a,new $APP.k(null,1,[$APP.oB,!0],null)),new $APP.k(null,3,[$APP.O,t6a,$APP.mt,Z$,$APP.Ta,new $APP.k(null,1,[$APP.Z,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.RD,l6a],null))],null)],null),$APP.Wd(k6a,new $APP.k(null,1,[$APP.Z,$APP.J($APP.Zj,$APP.J(new $APP.H(null,4,5,$APP.I,[$APP.Sw,$APP.RD,$APP.Mz,$APP.pE],null)))],null)),new $APP.k(null,3,[$APP.O,n6a,$APP.mt,Z5a,$APP.Ta,new $APP.k(null,1,[$APP.Z,$APP.J(new $APP.H(null,4,5,$APP.I,
[$APP.Sw,$APP.RD,$APP.Mz,$APP.pE],null))],null)],null),$APP.Wd(v6a,new $APP.k(null,5,[y6a,new $APP.ci(null,new $APP.k(null,18,[r6a,"null",a6a,"null",w6a,"null",s6a,"null",$APP.SA,"null",x6a,"null",z6a,"null",b6a,"null",u6a,"null",e6a,"null",d6a,"null",c6a,"null",j6a,"null",A6a,"null",h6a,"null",i6a,"null",q6a,"null",f6a,"null"],null),null),$APP.$J,$APP.Vpa,$APP.Z,$APP.J($APP.Zj,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.RD,$APP.Mz],null))),$5a,new $APP.ci(null,new $APP.k(null,16,[r6a,"null",a6a,"null",
w6a,"null",s6a,"null",$APP.SA,"null",x6a,"null",u6a,"null",e6a,"null",d6a,"null",c6a,"null",j6a,"null",A6a,"null",h6a,"null",i6a,"null",q6a,"null",f6a,"null"],null),null),$APP.N,"Positional factory function for flatland.ordered.map/OrderedMap."],null)),new $APP.k(null,3,[$APP.O,m6a,$APP.mt,function(a,b){return new Y$(a,b)},$APP.Ta,new $APP.k(null,2,[$APP.Z,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.RD,$APP.Mz],null)),$APP.N,"Positional factory function for flatland.ordered.map/OrderedMap."],null)],null),
$APP.Wd(g6a,new $APP.k(null,2,[$APP.Z,$APP.J($APP.Zj,$APP.J($APP.qg,new $APP.H(null,1,5,$APP.I,[$APP.$B],null),new $APP.H(null,4,5,$APP.I,[$APP.qH,$APP.zH,$APP.Kj,$APP.RD],null))),$APP.gI,new $APP.k(null,6,[$APP.ux,!0,$APP.Ur,2,$APP.CK,2,$APP.UJ,new $APP.H(null,2,5,$APP.I,[$APP.qg,new $APP.H(null,1,5,$APP.I,[$APP.$B],null)],null),$APP.Z,$APP.J($APP.qg,new $APP.H(null,1,5,$APP.I,[$APP.$B],null),new $APP.H(null,4,5,$APP.I,[$APP.qH,$APP.zH,$APP.Kj,$APP.RD],null)),$APP.BC,$APP.J(null,null,null)],null)],
null)),new $APP.k(null,3,[$APP.O,o6a,$APP.mt,$$,$APP.Ta,new $APP.k(null,1,[$APP.Z,$APP.J($APP.qg,new $APP.H(null,1,5,$APP.I,[$APP.$B],null),new $APP.H(null,4,5,$APP.I,[$APP.qH,$APP.zH,$APP.Kj,$APP.RD],null))],null)],null)],null),C6a);$APP.$t(new $APP.k(null,1,[$APP.Mp,new $APP.k(null,1,[$APP.tF,D6a],null)],null));