import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_impl_main.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_path from"node:path";
var x9a=function(a){var b=$APP.lj.g(a),c=$APP.Cf(b);return $APP.al("\n(require '[babashka.cli])\n(require '$1)\n(let [the-var (resolve '$2)\n      the-var-meta (meta the-var)\n      ns (:ns (meta the-var))\n      ns-meta (meta ns)\n      cli-opts (babashka.cli/merge-opts (:org.babashka/cli ns-meta)\n                                        (:org.babashka/cli the-var-meta))\n      opts (babashka.cli/parse-opts *command-line-args* cli-opts)]\n  (the-var opts))\n",/\$(\d)/,function(d){d=$APP.he(d);switch(d){case "1":return c;
case "2":return b;default:throw Error(["No matching clause: ",$APP.l.g(d)].join(""));}})},y9a=function(a){a=$APP.lj.g(a);var b=$APP.Ef(a)?$APP.lj.h($APP.l.g(a),"-main"):a,c=$APP.Cf(b);return $APP.al("(require '$1) (apply $2 *command-line-args*)",/\$(\d)/,function(d){d=$APP.he(d);switch(d){case "1":return c;case "2":return b;default:throw Error(["No matching clause: ",$APP.l.g(d)].join(""));}})},z9a=function(a){for(var b=$APP.Vf,c=a;;)if($APP.k(c)){var d=$APP.v(c);a=$APP.w(c);switch(d){case "--help":case "-h":return $APP.vi.j(b,
$APP.SC,!0);case "--version":case "-v":return $APP.vi.j(b,$APP.QXa,!0);case "-e":b=$APP.vi.j(b,$APP.Po,$APP.v(a));c=a=$APP.w(a);continue;case "-m":case "--main":return $APP.vi.l(b,$APP.Po,y9a($APP.v(a)),$APP.z([$APP.dn,$APP.w(a)]));case "-x":case "--exec":return $APP.vi.l(b,$APP.Po,x9a($APP.v(a)),$APP.z([$APP.dn,$APP.w(a)]));case "-cp":case "--classpath":b=$APP.vi.j(b,$APP.WO,$APP.v(a));c=a=$APP.w(a);continue;case "--config":b=$APP.vi.j(b,$APP.FB,$APP.v(a));c=a=$APP.w(a);continue;case "--debug":b=
$APP.vi.j(b,$APP.Au,!0);c=a;continue;case "nrepl-server":b=$APP.vi.j(b,$APP.MXa,!0);c=a;continue;case "socket-repl":b=$APP.vi.j(b,$APP.NXa,!0);c=a;continue;case ":port":case "--port":b=$APP.vi.j(b,$APP.XF,$APP.v(a));c=a=$APP.w(a);continue;case ":host":case "--host":b=$APP.vi.j(b,$APP.hK,$APP.v(a));c=a=$APP.w(a);continue;case "repl":b=$APP.vi.j(b,$APP.PXa,!0);c=a;continue;case "bundle":return $APP.vi.j(b,$APP.nI,$APP.Dn.h(a,new $APP.h(null,1,[$APP.lo,new $APP.h(null,2,[$APP.RXa,$APP.WBa,$APP.SXa,$APP.SC],
null)],null)));default:if($APP.Bb($APP.Po.g(c)))return $APP.vi.l(b,$APP.OXa,d,$APP.z([$APP.dn,$APP.w(c)]));throw $APP.Zl.h(["Unrecognized options:",$APP.l.g(c)].join(""),$APP.Vf);}}else return b};if($APP.k(esm_import$node_process.on))esm_import$node_process.on("unhandledRejection",function(a){console.error($APP.hk(a));return process.exitCode=1});(function(){var a=$APP.r(function(){var m=globalThis.nbb_args;return $APP.k(m)?m:esm_import$node_process.argv}());$APP.v(a);a=$APP.w(a);$APP.v(a);a=$APP.w(a);var b=z9a(a);$APP.vg($APP.TXa,b);var c=$APP.OXa.g(b),d=$APP.Po.g(b);a=$APP.WO.g(b);$APP.k(a)&&$APP.Bp(a);a=$APP.MXa.g(b);var e=function(){var m=$APP.PXa.g(b);if($APP.k(m))return m;m=$APP.NXa.g(b);return $APP.k(m)?m:$APP.we($APP.Ml.l(b,$APP.WO,$APP.z([$APP.Au,$APP.FB])))}(),f=$APP.nI.g(b);$APP.k($APP.SC.g(b))&&($APP.Vy.l($APP.z([$APP.Sa("nbb-logseq"),
"version:",$APP.kv()])),$APP.Vy.l($APP.z(["\nHelp:\n\n -h / --help: print this help text and exit.\n -v / --version: print the current version of nbb.\n\nGlobal options:\n\n --debug: print additional debug info.\n -cp / --classpath: set the classpath.\n\nEvaluation:\n\n -e: execute expression\n -m / --main: execute main function\n -x / --exec: execute function using babashka.cli\n\nREPL:\n\n repl: start console REPL.\n nrepl-server: start nrepl server. [1,2]\n socket-repl: start socket repl server. [1]\n\n 1: Provide :port \x3cport\x3e to specify port\n 2: Provide :host \x3chost\x3e to specify host\n\nTooling:\n\n  bundle: produce single JS file for usage with bundlers.\n"])),
esm_import$node_process.exit(0));$APP.k($APP.QXa.g(b))&&($APP.Vy.l($APP.z([["nbb-logseq v",$APP.kv()].join("")])),esm_import$node_process.exit(0));return $APP.k($APP.k(c)?c:$APP.k(d)?d:$APP.k(a)?a:$APP.k(e)?e:f)?($APP.gN.h($APP.xJa,$APP.tg($APP.dn.g(b))),Promise.resolve($APP.VO($APP.k(e)?esm_import$node_path.resolve("script.cljs"):c,b)).then(function(){return($APP.k(c)?$APP.XO.g(c):$APP.k(d)?$APP.YO.g(d):$APP.k($APP.MXa.g(b))?shadow_esm_import("./nbb_nrepl_server.js").then(function(){var m=$APP.B.h($APP.B.h($APP.Lq.g($APP.n($APP.Gq.g($APP.Du()))),
$APP.jA),$APP.DMa);return m.g?m.g(b):m.call(null,b)}):$APP.k($APP.k(e)?$APP.NXa.g(b):e)?shadow_esm_import("./nbb_repl.js").then(function(){var m=new $APP.h(null,1,[$APP.XF,$APP.XF.g(b)],null),p=$APP.B.h($APP.B.h($APP.Lq.g($APP.n($APP.Gq.g($APP.Du()))),$APP.pz),$APP.BMa);return p.g?p.g(m):p.call(null,m)}):$APP.k($APP.nI.g(b))?shadow_esm_import("./nbb_bundler.js"):$APP.k(e)?shadow_esm_import("./nbb_repl.js").then(function(){var m=$APP.B.h($APP.B.h($APP.Lq.g($APP.n($APP.Gq.g($APP.Du()))),$APP.pz),$APP.CMa);
return m.D?m.D():m.call(null)}):null).then(function(m){$APP.k($APP.k(d)?null!=m:d)&&$APP.zu.l($APP.z([m]));return m}).catch(function(m){$APP.Mia(m,b);$APP.k($APP.Au.g(b))&&console.error(m);throw Error($APP.hk(m));})})):console.error("Usage: nbb-logseq \x3cscript\x3e or nbb -e \x3cexpr\x3e.")})();