import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_transit.js";
import "./nbb_datascript.js";
const shadow_esm_import = function(x) { return import(x) };
var Xob=function(a){return $APP.BO($APP.QO.h(Wob,new $APP.h(null,1,[$APP.MO,f7],null)),a)},Yob=function(a){return $APP.KO($APP.RO.h(Wob,new $APP.h(null,1,[$APP.MO,g7],null)),a)},Wob=new $APP.F(null,"json","json",1279968570),Zob=new $APP.q("datascript.transit","read-transit-str","datascript.transit/read-transit-str",526272408,null),$ob=new $APP.q(null,"write-handlers","write-handlers",-456757384,null),apb=new $APP.q("datascript.transit","write-handlers","datascript.transit/write-handlers",-1659157370,
null),bpb=new $APP.q(null,"read-transit-str","read-transit-str",-953853518,null),cpb=new $APP.q("datascript.transit","read-handlers","datascript.transit/read-handlers",400129984,null),dpb=new $APP.q("datascript.transit","write-transit-str","datascript.transit/write-transit-str",-396975951,null),epb=new $APP.q(null,"read-handlers","read-handlers",-544976454,null),fpb=new $APP.q(null,"write-transit-str","write-transit-str",546948831,null);var f7=new $APP.h(null,3,["u",$APP.ck,"datascript/DB",$APP.c2,"datascript/Datom",$APP.h1],null),g7=$APP.Tf([$APP.z1,$APP.SO.h($APP.sg("datascript/DB"),function(a){return new $APP.h(null,2,[$APP.A1,$APP.A1.g(a),$APP.b2,$APP.B1.g(a)],null)}),$APP.f1,$APP.SO.h($APP.sg("datascript/Datom"),function(a){return $APP.k($APP.e1(a))?new $APP.G(null,4,5,$APP.H,[a.e,a.a,a.v,$APP.d1(a)],null):new $APP.G(null,5,5,$APP.H,[a.e,a.a,a.v,$APP.d1(a),!1],null)}),$APP.G0,new $APP.EO]);var h7=$APP.kN.h($APP.UI,null),gpb=new $APP.h(null,4,[epb,function(){var a=new $APP.Cd(function(){return f7},cpb,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.UI,epb,"datascript/transit.cljs",19,1,9,9,$APP.Hd,null,$APP.k(f7)?f7.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,h7,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);
return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),$ob,function(){var a=new $APP.Cd(function(){return g7},apb,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.UI,$ob,"datascript/transit.cljs",20,1,16,16,$APP.Hd,null,$APP.k(g7)?g7.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,h7,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=
$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),bpb,function(){var a=new $APP.Cd(function(){return Xob},Zob,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.UI,bpb,"datascript/transit.cljs",23,1,29,29,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.TH],null)),null,$APP.k(Xob)?Xob.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,h7,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],
null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}(),fpb,function(){var a=new $APP.Cd(function(){return Yob},dpb,$APP.gi([$APP.P,$APP.N,$APP.Vl,$APP.Zz,$APP.Om,$APP.Wl,$APP.EK,$APP.U,$APP.M,$APP.lF],[$APP.UI,fpb,"datascript/transit.cljs",24,1,33,33,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.PH],null)),null,$APP.k(Yob)?Yob.H:null])),b=$APP.n(a),c=$APP.se(a);a=$APP.k(null)?null:$APP.N.g(c);var d=
new $APP.h(null,4,[$APP.P,h7,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Uq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.kq.g(c);return $APP.k(e)?e:$APP.xq.g(c)}())?$APP.fN.j(a,b,d):$APP.iu.j(a,b,d)}()],null);$APP.Yu(new $APP.h(null,1,[$APP.Kq,new $APP.h(null,1,[$APP.UI,gpb],null)],null));