import { $APP, shadow$provide } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_module from"node:module";import*as esm_import$node_fs from"node:fs";import*as esm_import$import_meta_resolve from"import-meta-resolve";import*as esm_import$node_path from"node:path";import*as esm_import$node_url from"node:url";var hMa,jMa,aMa,$La,eMa,kMa,fMa,lMa,iMa;
$APP.ZLa=function(a){a=$APP.Ed(a);a=$APP.Ns.g($APP.zf,a);a=$APP.mn.g(function(d){return $APP.jv($APP.Hp(),d)},a);var b=$APP.oc($APP.Rq),c=$APP.oc($APP.Cq);return $APP.Ev(a,new $APP.F(null,2,[$APP.S,b,$APP.J,c],null))};$APP.bMa=function(a,b){return $La(aMa,a,b)};
$APP.mO=function(a,b){return Promise.resolve($APP.h($APP.oc(cMa))?null:function(){var c=esm_import$node_path.resolve($APP.h(a)?a:"script.cljs"),d=$APP.h($APP.kC.h(b))?$APP.ui.j(b,$APP.kC,$APP.bK.h(esm_import$node_fs.readFileSync($APP.kC.h(b),"utf8"))):function(){var k;a:{for(k=c;;){var n=esm_import$node_fs.existsSync(k);n=$APP.h(n)?esm_import$node_fs.lstatSync(k).isDirectory():n;if($APP.h(n)){n=esm_import$node_path.resolve(k,"nbb.edn");if($APP.h(esm_import$node_fs.existsSync(n))){k=n;break a}n=esm_import$node_path.dirname(k)}else n=
esm_import$node_path.dirname(k);if($APP.r.g(n,k)){k=null;break a}k=n}k=void 0}return $APP.h(k)?(n=$APP.bK.h(esm_import$node_fs.readFileSync(k,"utf8")),$APP.ui.l(b,$APP.kC,n,$APP.x([$APP.EI,esm_import$node_path.dirname(k)],0))):b}(),e=dMa.h?dMa.h(c):dMa.call(null,c),f=""+$APP.G.h(esm_import$node_url.pathToFileURL(c));$APP.Gv.require=e;$APP.Aj.F($APP.Iv,$APP.ui,$APP.un,e);$APP.Aj.F($APP.Iv,$APP.ui,$APP.Jv,function(k){return esm_import$import_meta_resolve.resolve(k,f)});$APP.yg($APP.LM,d);return Promise.resolve(function(){var k=
function(){var B=$APP.yb(eMa.h(d));return B?$APP.kC.h(d):B}();if($APP.h(k)){k=fMa.h(k);if($APP.h(k)){k=$APP.m(k);for(var n=null,t=0,w=0;;)if(w<t){var y=n.ga(null,w);$APP.yb(esm_import$node_path.isAbsolute(y))?$APP.Ep(function(){var B=$APP.EI.h(d);return $APP.h(B)?esm_import$node_path.resolve(B,y):y}()):$APP.Ep(y);w+=1}else if(k=$APP.m(k)){n=k;if($APP.Ae(n))k=$APP.Zc(n),w=$APP.$c(n),n=k,t=$APP.Yd(k),k=w;else{var u=$APP.p(n);$APP.yb(esm_import$node_path.isAbsolute(u))?$APP.Ep(function(){var B=$APP.EI.h(d);
return $APP.h(B)?esm_import$node_path.resolve(B,u):u}()):$APP.Ep(u);k=$APP.q(n);n=null;t=0}w=0}else break}else $APP.Ep(esm_import$node_process.cwd());return shadow_esm_import("./nbb_deps.js")}return $APP.Ep(esm_import$node_process.cwd())}()).then(function(){return $APP.yg(cMa,!0)})}())};$APP.gMa=function(a,b){return $APP.xu(a,b)};
hMa=function(a,b){b=$APP.iv(a,$APP.Sk("(keys (ns-map '%s))","%s",b));b=$APP.Pj.g(function(c){return"`"+$APP.G.h(c)},b);b="["+$APP.G.h($APP.kn.g(" ",b))+"]";a=$APP.gv(a,b,null);return $APP.Ns.g(function(c){return $APP.el(""+$APP.G.h(c),"nbb.internal")},a)};
jMa=function(a,b){var c=$APP.Hp();b=$APP.Zk.g(b,/\//);$APP.v.j(b,0,null);var d=$APP.v.j(b,1,null),e=$APP.iv(c,$APP.xj.l($APP.x([$APP.U.h($APP.m($APP.N.l(new $APP.A(null,$APP.Vq,null,1,null),new $APP.A(null,$APP.$e($APP.U.h($APP.m($APP.N.g(new $APP.A(null,iMa,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.g(new $APP.A(null,$APP.OD,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.g(new $APP.A(null,$APP.Dk,null,1,null),new $APP.A(null,a,null,1,null)))),null,1,null)))),null,1,null))))),null,1,
null),$APP.x([new $APP.A(null,$APP.U.h($APP.m($APP.N.l(new $APP.A(null,$APP.wI,null,1,null),new $APP.A(null,$APP.U.h($APP.m($APP.N.g(new $APP.A(null,$APP.tua,null,1,null),new $APP.A(null,iMa,null,1,null)))),null,1,null),$APP.x([new $APP.A(null,iMa,null,1,null)],0)))),null,1,null)],0))))],0)));if($APP.h(e)&&(c=$APP.h(d)?function(){var n=$APP.Ga(d,"."),t=$APP.Zk.g(d,/\./);n=n?t:$APP.Ci(t);t=$APP.E;var w=""+$APP.G.h(a)+"/",y=$APP.G,u=y.h;if($APP.m(n)){var B=$APP.kn.g(".",n);B=""+$APP.G.h(B)+"."}else B=
null;return new $APP.D(null,2,5,t,[w+u.call(y,B),$APP.sg.j($APP.Pa,e,n)],null)}():new $APP.D(null,2,5,$APP.E,[""+$APP.G.h(a)+"/",e],null),$APP.h(c))){var f=$APP.v.j(c,0,null),k=$APP.v.j(c,1,null);c=function(){for(var n=k,t=$APP.Rg;;)if($APP.h(n)){var w=Object.getPrototypeOf(n);t=$APP.Ch.g(t,Object.getOwnPropertyNames(n));n=w}else return t}();return $APP.Pj.g(function(n){return new $APP.D(null,2,5,$APP.E,[null,""+$APP.G.h(f)+$APP.G.h(n)],null)},c)}return null};
$APP.mMa=function(a){var b=$APP.Yf(a);a=$APP.z.g(b,$APP.S);try{var c=$APP.Hp(),d=$APP.h(a)?$APP.gMa(c,$APP.kj.h(a)):null,e=$APP.Wf([$APP.Rq,$APP.h(d)?d:$APP.oc($APP.Rq)]);$APP.fq(e);try{var f=function(){var la=$APP.xm.h(b);return $APP.h(la)?la:$APP.rG.h(b)}();if($APP.h(f)){var k=$APP.Ja(f,"/"),n=k?function(){var la=$APP.Zk.g(f,/\//);la=la==null?null:$APP.p(la);return la==null?null:$APP.kj.h(la)}():null,t=hMa(c,$APP.gv(c,"(ns-name *ns*)",null)),w=$APP.Pj.g(function(la){return new $APP.D(null,3,5,$APP.E,
[$APP.Bf(la),$APP.Di(la),kMa],null)},t),y=$APP.gv(c,"(let [m (ns-aliases *ns*)] (zipmap (keys m) (map ns-name (vals m))))",null),u=$APP.Fi($APP.si(y),$APP.qi(y)),B=$APP.Xn.h($APP.Ng.l(function(la){var sa=$APP.z.g(y,la);la=$APP.iv(c,$APP.Sk("(keys (ns-publics '%s))","%s",sa));return $APP.Pj.g(function(ya){return new $APP.D(null,3,5,$APP.E,[""+$APP.G.h(sa),""+$APP.G.h(ya),lMa],null)},la)},$APP.x([$APP.qi(y)],0))),H=$APP.Pj.g(function(la){return new $APP.D(null,3,5,$APP.E,[""+$APP.G.h(la),null,lMa],
null)},$APP.gv(c,"(all-ns)",null)),P=k?jMa(n,f):null,T=$APP.h(P)?null:k?function(){var la=$APP.z.j(y,n,n),sa=$APP.iv(c,$APP.Sk("(and (find-ns '%s)\n                                                                                         (keys (ns-publics '%s)))","%s",la));return $APP.Pj.g(function(ya){return new $APP.D(null,3,5,$APP.E,[""+$APP.G.h(la),""+$APP.G.h(ya),lMa],null)},sa)}():null,Y=$APP.N.l(w,B,$APP.x([H,T],0)),ca=$APP.qn.g(function(la){var sa=$APP.v.j(la,0,null);var ya=$APP.v.j(la,1,null);
la=$APP.v.j(la,2,null);la=$APP.r.g(kMa,la)&&$APP.Ja(ya,f)?new $APP.D(null,2,5,$APP.E,[sa,ya],null):null;$APP.h(la)?sa=la:$APP.h(sa)?(la=""+$APP.G.h($APP.z.g(u,$APP.kj.h(sa)))+"/"+$APP.G.h(ya),la=$APP.Ja(la,f)?new $APP.D(null,2,5,$APP.E,[sa,la],null):null,$APP.h(la)?sa=la:(ya=""+$APP.G.h(sa)+"/"+$APP.G.h(ya),sa=$APP.Ja(ya,f)?new $APP.D(null,2,5,$APP.E,[sa,ya],null):null)):sa=null;return sa},Y),fa=$APP.N.g(ca,P),ka=$APP.$e($APP.lz.h($APP.Pj.g(function(la){var sa=$APP.v.j(la,0,null);la=$APP.v.j(la,1,
null);la=new $APP.F(null,1,["candidate",""+$APP.G.h(la)],null);return $APP.h(sa)?$APP.ui.j(la,"ns",""+$APP.G.h(sa)):la},fa)));return new $APP.F(null,2,["completions",ka,"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null)}return new $APP.F(null,1,["status",new $APP.D(null,1,5,$APP.E,["done"],null)],null)}finally{$APP.hq()}}catch(la){return console.warn(la),new $APP.F(null,2,["completions",$APP.Rg,"status",new $APP.D(null,1,5,$APP.E,["done"],null)],null)}};aMa={};
$La=function $La(a,b,c){for(;;){if(b instanceof Promise)return b;if(aMa===a){if($APP.Fe(b))return $APP.PM(b,b,c,$La);a=$APP.Ov(b,c)}else{b=Promise;var e=b.resolve;var f=$APP.TH.h(c);f=$APP.h(f)?f:$APP.bf;c=new $APP.F(null,1,[$APP.S,$APP.S.h(c)],null);c=f.g?f.g(a,c):f.call(null,a,c);return e.call(b,c)}}};$APP.nO=new $APP.l(null,"socket-repl","socket-repl",-1615225633,null);$APP.oO=new $APP.l(null,"repl","repl",1605132860,null);eMa=new $APP.C(null,"disableConfig","disableConfig",844586790);
kMa=new $APP.C(null,"unqualified","unqualified",-98904653);fMa=new $APP.C(null,"paths","paths",-1807389588);lMa=new $APP.C(null,"qualified","qualified",-2065109343);$APP.pO=new $APP.l(null,"start-server!","start-server!",203437330,null);$APP.qO=new $APP.C(null,"classpath","classpath",299521985);iMa=new $APP.l(null,"resolved__34662__auto__","resolved__34662__auto__",-729195568,null);var dMa,cMa;dMa=function(){var a=esm_import$node_module.createRequire;return $APP.h(a)?a:function(){return function(){throw Error("createRequire is not defined, this is a no-op");}}}();cMa=$APP.zj.h(!1);$APP.rO=function rO(a){switch(arguments.length){case 1:return rO.h(arguments[0]);case 2:return rO.g(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};$APP.rO.h=function(a){return $APP.rO.g(a,null)};
$APP.rO.g=function(a,b){b=$APP.Kz.l(b,$APP.x([$APP.Lz,!0],0));var c=esm_import$node_path.resolve(a);$APP.yg($APP.CJa,c);return $APP.mO(c,b).then(function(){return $APP.Sv(c)})};$APP.rO.B=2;$APP.sO=function sO(a){switch(arguments.length){case 1:return sO.h(arguments[0]);case 2:return sO.g(arguments[0],arguments[1]);default:throw Error(["Invalid arity: ",arguments.length].join(""));}};$APP.sO.h=function(a){return $APP.sO.g(a,null)};
$APP.sO.g=function(a,b){b=$APP.Kz.l(b,$APP.x([$APP.Lz,!0],0));return $APP.mO(null,b).then(function(){return $APP.Rv(a)})};$APP.sO.B=2;export const loadFile=$APP.rO;export const loadString=$APP.sO;export const getClassPath=function(){return $APP.Dp()};export const addClassPath=function(a){return $APP.Ep(a)};export const version=function(){return $APP.$v()};export const registerModule=function(a,b){b=$APP.Pja($APP.Mk(b));return $APP.Aj.F($APP.Hv,$APP.ui,b,a)};export const printErrorReport=$APP.RM;