import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_goog_string.js";
import "./nbb_pprint.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_process from"node:process";import*as esm_import$node_net from"node:net";import*as esm_import$node_fs from"node:fs";import*as esm_import$node_path from"node:path";
var Jeb=function(a,b){a=a.indexOf(b);if(0>a)throw Error("out of input");return a},S_=function(a,b){if(a.length<b)throw Error("out of input");return a.slice(b)},T_=function(a,b){if(b>a.length)throw Error("out of input");return a.slice(0,b)},Keb=function(a){return(new TextEncoder).encode(a).length},U_=function(a){return $APP.k($APP.Au.g($APP.n($APP.qN)))?console.debug($APP.on.h(" ",a)):null},Meb=function(a){return function(b,c){b=$APP.Wf(b);var d=$APP.B.h(b,$APP.Hq),e=$APP.B.h(b,Leb);c=$APP.vi.j(c,
"id",d);c=$APP.k(e)?$APP.vi.j(c,"session",e):c;return a.h?a.h(b,c):a.call(null,b,c)}},Oeb=function(){var a=Neb;return function(b,c){b=$APP.bn.j(b,$APP.jH,$APP.gj);return a.h?a.h(b,c):a.call(null,b,c)}},Qeb=function(){var a=Peb();return function(b,c){U_($APP.z(["request",b]));return a.h?a.h(b,c):a.call(null,b,c)}},Reb=function(a){return function(b,c){U_($APP.z(["response",c]));return a.h?a.h(b,c):a.call(null,b,c)}},Peb=function(){var a=Oeb();return function(b,c){return a.h?a.h(b,c):a.call(null,b,c)}},
Seb=function(a){return $APP.vi.j($APP.Gi(new $APP.G(null,3,5,$APP.H,["major","minor","incremental"],null),$APP.fz.g(a.split("."))),"version-string",a)},Ueb=function(a,b,c){if($APP.k(a))if(a=Teb.g?Teb.g(a):Teb.call(null,a),$APP.k(a)){b=$APP.Wf(b);var d=$APP.B.h(b,$APP.bPa),e=$APP.B.h(b,$APP.GOa),f=$APP.B.h(b,$APP.ROa);b=$APP.rb;var m=$APP.aj,p=$APP.JP;$APP.rb=e;$APP.aj=f;$APP.JP=d;try{var u=new $APP.fb;d=$APP.tb;e=$APP.ub;$APP.tb=!0;$APP.ub=function(t){return u.append(t)};try{a.g?a.g(c):a.call(null,
c)}finally{$APP.ub=e,$APP.tb=d}return $APP.l.g(u)}finally{$APP.JP=p,$APP.aj=m,$APP.rb=b}}else return U_($APP.z(["Pretty-Printing is only supported for clojure.core/prn and clojure.pprint/pprint."])),$APP.xj.l($APP.z([c]));else return $APP.xj.l($APP.z([c]))},Veb=function(a,b,c){$APP.gN.h($APP.RM,$APP.tg(c));var d=$APP.Kq.g($APP.gk(c));d=$APP.k(d)?d:c.message;$APP.k(d)&&(d=new $APP.h(null,1,["err",[$APP.l.g(d),"\n"].join("")],null),a.h?a.h(b,d):a.call(null,b,d));c=new $APP.h(null,2,["ex",$APP.l.g(c),
"ns",$APP.l.g($APP.n($APP.Oq))],null);return a.h?a.h(b,c):a.call(null,b,c)},$eb=function(a,b){var c=$APP.Wf(a),d=$APP.B.h(c,$APP.P);a=$APP.B.h(c,V_);var e=$APP.B.h(c,$APP.Wl);$APP.B.h(c,Web);$APP.B.h(c,Xeb);var f=$APP.yp(a),m=function t(u){try{var A=function(){var E=$APP.P.g($APP.he(u));if($APP.k(E))return E;E=$APP.n(W_);return $APP.k(E)?E:d}(),C=$APP.Yia(f,new $APP.h(null,3,[$APP.P,A,$APP.Wl,e,$APP.DI,$APP.Jw],null));return $APP.x.h($APP.tG,C)?Promise.resolve(u):$APP.pMa(C,new $APP.h(null,3,[$APP.P,
A,$APP.Wl,e,$APP.DI,$APP.Jw],null)).then(function(E){var I=$APP.y.j(E,0,null),Q=$APP.y.j(E,1,null);Q=$APP.P.g(Q);$APP.vg(W_,Q);$APP.gN.h($APP.QM,$APP.tg($APP.n($APP.PM)));$APP.gN.h($APP.PM,$APP.tg($APP.n($APP.OM)));$APP.gN.h($APP.OM,$APP.tg(I));I=Ueb(Yeb.g(c),Zeb.g(c),I);I=new $APP.h(null,2,["value",I,"ns",$APP.l.g(Q)],null);b.h?b.h(c,I):b.call(null,c,I);return t(E)})}catch(E){return Veb(b,c,E),t(null)}};$APP.Zp($APP.Uf([$APP.Oq,d,$APP.wq,e,$APP.EL,$APP.n($APP.EL),$APP.JL,!0]));return function(){$APP.gN.h($APP.CL,
$APP.tg(function(u){u=new $APP.h(null,1,["out",u],null);return b.h?b.h(c,u):b.call(null,c,u)}));return m(null).catch($APP.Nl.j(Veb,b,c)).finally(function(){var u=new $APP.h(null,2,["ns",$APP.l.g($APP.n(W_)),"status",new $APP.G(null,1,5,$APP.H,["done"],null)],null);return b.h?b.h(c,u):b.call(null,c,u)})}().finally(function(){return $APP.aq()})},afb=function(a,b){a=$APP.Wf(a);var c=$APP.B.h(a,$APP.P),d=$APP.vi.j;c=$APP.k(c)?$APP.uMa($APP.Du(),$APP.lj.g(c)):null;$APP.k(c)||(c=$APP.n(W_),c=$APP.k(c)?
c:$APP.n($APP.Oq));return $eb(d.call($APP.vi,a,$APP.P,c),b)},cfb=function(a,b){var c=$APP.Wf(a),d=$APP.B.h(c,$APP.P),e=$APP.jH.g(c);try{var f=$APP.P.g(c),m=function(){var Q=$APP.BE.g(c);return $APP.k(Q)?Q:$APP.Am.g(c)}(),p=function(){var Q=$APP.k(d)?$APP.uMa($APP.Du(),$APP.lj.g(d)):null;if($APP.k(Q))return Q;Q=$APP.n(W_);return $APP.k(Q)?Q:$APP.n($APP.Oq)}(),u=$APP.Uf([$APP.Oq,p]);$APP.Zp(u);try{var t=$APP.gu($APP.Du(),$APP.YT("\n(let [ns '%s\n      full-sym '%s]\n  (when-let [v (ns-resolve ns full-sym)]\n    (let [m (meta v)]\n      (assoc m :arglists (:arglists m)\n       :doc (:doc m)\n       :name (:name m)\n       :ns (some-\x3e m :ns ns-name)\n       :val @v))))",
f,m)),A=$APP.M.g(t),C=$APP.Wl.g(t),E=$APP.Xl.g(t),I=function(){var Q=e instanceof $APP.F?e.N:null;switch(Q){case "eldoc":return Q=new $APP.h(null,5,["ns",$APP.P.g(t),"name",$APP.N.g(t),"eldoc",$APP.qn.h(function(T){return $APP.qn.h($APP.l,T)},$APP.U.g(t)),"type",$APP.Me($APP.ku.g(t))?"function":"variable","status",new $APP.G(null,1,5,$APP.H,["done"],null)],null),$APP.k(A)?$APP.vi.j(Q,"docstring",A):Q;case "info":case "lookup":return Q=new $APP.h(null,4,["ns",$APP.P.g(t),"name",$APP.N.g(t),"arglists-str",
$APP.on.h("\n",$APP.fj.h($APP.xj,$APP.U.g(t))),"status",new $APP.G(null,1,5,$APP.H,["done"],null)],null),Q=$APP.k(A)?$APP.vi.j(Q,"doc",A):Q,Q=$APP.k(C)?$APP.vi.j(Q,"file",C):Q,$APP.k(E)?$APP.vi.j(Q,"line",E):Q;default:throw Error(["No matching clause: ",$APP.l.g(Q)].join(""));}}();return b.h?b.h(c,I):b.call(null,c,I)}finally{$APP.aq()}}catch(Q){if(Q instanceof Error)return a=Q,f=function(){var T=new $APP.yi(null,new $APP.h(null,1,["done",null],null),null);return $APP.x.h(e,bfb)?$APP.wf.h(T,"no-eldoc"):
T}(),a=new $APP.h(null,2,["status",f,"ex",$APP.l.g(a)],null),b.h?b.h(c,a):b.call(null,c,a);throw Q;}},Neb=function(a,b){a=$APP.Wf(a);var c=$APP.B.h(a,$APP.jH),d=$APP.B.h(dfb,c);if($APP.k(d))return d.h?d.h(a,b):d.call(null,a,b);console.warn($APP.on.h(" ",$APP.z(["Unhandled operation",c])));c=new $APP.h(null,1,["status",new $APP.G(null,3,5,$APP.H,["error","unknown-op","done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},efb=function(a){return function(b,c){return a.write(X_(c))}},ffb=function(a,
b){U_($APP.z(["Connection accepted"]));b.setNoDelay(!0);var c=Qeb(),d=Meb(Reb(efb(b))),e=$APP.Bj.g(null);b.on("data",function(f){var m=$APP.n(e);if($APP.k(m)){f=[$APP.l.g(m),$APP.l.g(f)].join("");$APP.vg(e,null);var p=f}else p=f;a:for(f=$APP.z([$APP.gz,!0]),m=$APP.Tg;;){var u=$APP.qg.j(Y_,p,f);p=$APP.y.j(u,0,null);u=$APP.y.j(u,1,null);if(null==p){m=new $APP.G(null,2,5,$APP.H,[m,u],null);break a}m=$APP.wf.h(m,p);p=u}f=$APP.y.j(m,0,null);m=$APP.y.j(m,1,null);$APP.il(m)||$APP.vg(e,m);f=$APP.r(f);m=null;
for(var t=u=0;;)if(t<u)p=m.ha(null,t),c(p,d),t+=1;else if(f=$APP.r(f))m=f,$APP.Fe(m)?(f=$APP.dd(m),u=$APP.ed(m),m=f,p=$APP.ce(f),f=u,u=p):(p=$APP.v(m),c(p,d),f=$APP.w(m),m=null,u=0),t=0;else return null});return b.on("close",function(f){return $APP.k(f)?U_($APP.z(["Connection lost"])):U_($APP.z(["Connection closed"]))})},ifb=function(a){return Promise.resolve($APP.VO(esm_import$node_path.resolve("script.cljs"),null)).then(function(){function b(e){return $APP.mMa(new $APP.D(null,$APP.Bk,new $APP.D(null,
new $APP.D(null,$APP.Bk,new $APP.D(null,e,null,1,null),2,null),null,1,null),2,null))}var c=$APP.y.j($APP.rN,0,null),d=$APP.y.j($APP.rN,1,null);return b(c).then(function(){return b(d)})}).then(function(){var b=$APP.Ll.l($APP.z([$APP.n($APP.qN),a])),c=function(){var f=$APP.XF.g(b);return $APP.k(f)?f:0}(),d=function(){var f=$APP.hK.g(b);return $APP.k(f)?f:"127.0.0.1"}();(function(){var f=$APP.Db(b)?b.Ho:gfb.g(b);return $APP.k(f)?f:"info"})();var e=esm_import$node_net.createServer($APP.Nl.h(ffb,$APP.Vf));
e.listen(c,d,function(){var f=e.address(),m=f.port;f=f.address;$APP.Vy.l($APP.z([["nREPL server started on port ",$APP.l.g(m)," on host ",$APP.l.g(f)," - nrepl://",$APP.l.g(f),":",$APP.l.g(m)].join("")]));$APP.gN.h($APP.JL,$APP.tg(!0));try{return esm_import$node_fs.writeFileSync(".nrepl-port",$APP.l.g(m))}catch(p){return console.warn($APP.on.h(" ",$APP.z(["Could not write .nrepl-port",p])))}});return $APP.vg(hfb,e)})},jfb=new $APP.q("nbb.impl.nrepl-server","stop-server!","nbb.impl.nrepl-server/stop-server!",
1628751782,null),Zeb=new $APP.F("nrepl.middleware.print","options","nrepl.middleware.print/options",868480159),kfb=new $APP.q(null,"nbb.impl.nrepl-server","nbb.impl.nrepl-server",-1821079079,null),Leb=new $APP.F(null,"session","session",1008279103),lfb=new $APP.q("nbb.impl.nrepl-server","start-server!","nbb.impl.nrepl-server/start-server!",-2119141227,null),mfb=new $APP.F(null,"load-file","load-file",-424586670),V_=new $APP.F(null,"code","code",1586293142),gfb=new $APP.F(null,"log_level","log_level",
-1756736313),Yeb=new $APP.F("nrepl.middleware.print","print","nrepl.middleware.print/print",-1616742548),nfb=new $APP.F(null,"clone","clone",711747572),ofb=new $APP.F(null,"close","close",1835149582),pfb=new $APP.F(null,"info","info",-317069002),qfb=new $APP.F(null,"macroexpand","macroexpand",-130598183),rfb=new $APP.F(null,"complete","complete",-500388775),Xeb=new $APP.F(null,"_line","_line",232847719),sfb=new $APP.q(null,"server","server",-1155245649,null),tfb=new $APP.F(null,"lookup","lookup",
1225356838),ufb=new $APP.F(null,"expander","expander",379138924),Web=new $APP.F(null,"_load-file?","_load-file?",-1198848711),vfb=new $APP.F(null,"describe","describe",1369790582),bfb=new $APP.F(null,"eldoc","eldoc",-1321421900),wfb=new $APP.q(null,"stop-server!","stop-server!",-410772185,null),xfb=new $APP.F(null,"load-file?","load-file?",1892536169);var Z_=function Z_(a,b){switch($APP.l.g(T_(a,1))){case "i":return a=S_(a,1),b=Jeb(a,"e"),new $APP.G(null,2,5,$APP.H,[parseInt(T_(a,b)),S_(a,b+1)],null);case "l":var d=a=S_(a,1);for(a=$APP.Uc($APP.Tg);;){if($APP.x.h($APP.l.g(T_(d,1)),"e"))return new $APP.G(null,2,5,$APP.H,[$APP.Wc(a),S_(d,1)],null);var e=Z_.h?Z_.h(d,b):Z_.call(null,d,b),f=$APP.y.j(e,0,null),m=$APP.y.j(e,1,null);e=m;a=$APP.Sg.h(a,f);d=e}case "d":for(a=S_(a,1),f=$APP.Wf(b),f=$APP.B.h(f,$APP.gz),d=a,e=$APP.Uc($APP.Vf);;){if($APP.x.h($APP.l.g(T_(d,
1)),"e"))return new $APP.G(null,2,5,$APP.H,[$APP.Wc(e),S_(d,1)],null);a=Z_.h?Z_.h(d,b):Z_.call(null,d,b);d=$APP.y.j(a,0,null);m=$APP.y.j(a,1,null);m=Z_.h?Z_.h(m,b):Z_.call(null,m,b);a=$APP.y.j(m,0,null);m=$APP.y.j(m,1,null);d=$APP.k(f)?$APP.gj.g(d):d;a=$APP.Hh.j(e,d,a);d=m;e=a}default:return b=Jeb(a,":"),f=parseInt(T_(a,b)),a=S_(a,b+1),new $APP.G(null,2,5,$APP.H,[$APP.l.g(T_(a,f)),S_(a,f)],null)}},Y_=function Y_(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;
return Y_.l(arguments[0],1<c.length?new $APP.Fd(c.slice(1),0,null):null)};Y_.l=function(a,b){try{return Z_(a,b)}catch(c){if(c instanceof Error)return new $APP.G(null,2,5,$APP.H,[null,a],null);throw c;}};Y_.B=1;Y_.G=function(a){var b=$APP.v(a);a=$APP.w(a);return this.l(b,a)};
var X_=function X_(a){for(;;){if("string"===typeof a)return[$APP.l.g(Keb(a)),":",a].join("");if(a instanceof $APP.F||a instanceof $APP.q)a=[function(){var c=$APP.Cf(a);return $APP.k(c)?[c,"/"].join(""):null}(),$APP.Fi(a)].join("");else return"number"===typeof a?["i",$APP.l.g(a),"e"].join(""):$APP.ye(a)||$APP.Ee(a)||null==a?["l",$APP.l.g($APP.qg.h($APP.l,$APP.fj.h(X_,a))),"e"].join(""):$APP.Be(a)?["d",$APP.l.g($APP.qg.h($APP.l,$APP.fj.h(function(){return function(c){var d=$APP.y.j(c,0,null);c=$APP.y.j(c,
1,null);return[$APP.l.g(X_.g?X_.g(d):X_.call(null,d)),$APP.l.g(X_.g?X_.g(c):X_.call(null,c))].join("")}}(a),$APP.Nx.h($APP.v,a)))),"e"].join(""):null}};var W_=$APP.Bj.g(null),Teb=new $APP.h(null,1,["cider.nrepl.pprint/pprint",$APP.pR],null),dfb=$APP.hi([$APP.WO,tfb,ofb,mfb,bfb,nfb,vfb,pfb,rfb,qfb,$APP.WAa],[function(a,b){var c=new $APP.h(null,2,["status",new $APP.G(null,1,5,$APP.H,["done"],null),"classpath",$APP.gl.h($APP.Ap(),$APP.Xi(esm_import$node_path.delimiter))],null);return b.h?b.h(a,c):b.call(null,a,c)},cfb,function(a,b){var c=new $APP.h(null,1,["status",new $APP.G(null,1,5,$APP.H,["done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},
function(a,b){a=$APP.Wf(a);var c=$APP.B.h(a,$APP.Wl);return $eb($APP.vi.l(a,V_,c,$APP.z([xfb,!0,$APP.P,$APP.n($APP.Oq)])),b)},cfb,function(a,b){var c=new $APP.h(null,2,["new-session",$APP.l.g($APP.ek()),"status",new $APP.G(null,1,5,$APP.H,["done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},function(a,b){var c=new $APP.h(null,4,["versions",new $APP.h(null,2,["nbb-nrepl",Seb("TODO"),"node",Seb(esm_import$node_process.version)],null),"aux",$APP.Vf,"ops",$APP.Gi($APP.fj.h($APP.Fi,$APP.ri(dfb)),
$APP.kn.g($APP.Vf)),"status",new $APP.G(null,1,5,$APP.H,["done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},cfb,function(a,b){var c=$APP.AMa(a);return b.h?b.h(a,c):b.call(null,a,c)},function(a,b){a=$APP.Wf(a);var c=$APP.B.h(a,V_),d=$APP.B.h(a,ufb);try{return afb($APP.vi.j(a,V_,["( ",$APP.l.g(d),"(quote ",$APP.l.g(c),"))"].join("")),function(e,f){var m=f.g?f.g("value"):f.call(null,"value");f=$APP.k(m)?$APP.vi.j(f,"expansion",m):f;return b.h?b.h(e,f):b.call(null,e,f)})}catch(e){if(e instanceof
Error)return c=new $APP.h(null,3,["ex",$APP.l.g(e),"ns",$APP.l.g($APP.n($APP.Oq)),"status",new $APP.G(null,1,5,$APP.H,["done"],null)],null),b.h?b.h(a,c):b.call(null,a,c);throw e;}},afb]),hfb=$APP.Bj.g(null),$_=function $_(a){switch(arguments.length){case 0:return $_.D();case 1:return $_.g(arguments[0]);default:throw Error(["Invalid arity: ",$APP.l.g(arguments.length)].join(""));}};$_.D=function(){return $_.g($APP.n(hfb))};
$_.g=function(a){return a.close(function(){$APP.gN.h($APP.CL,$APP.tg($APP.ub));$APP.gN.h($APP.JL,$APP.tg($APP.tb));return $APP.k(esm_import$node_fs.existsSync(".nrepl-port"))?esm_import$node_fs.unlinkSync(".nrepl-port"):null})};$_.B=1;
var yfb=$APP.kN.h($APP.jA,null),zfb=new $APP.h(null,2,[$APP.DMa,function(){var a=new $APP.Dd(function(){return ifb},lfb,$APP.hi([$APP.P,$APP.N,$APP.Wl,$APP.Xz,$APP.Pm,$APP.Xl,$APP.EK,$APP.U,$APP.M,$APP.kF],[$APP.se(kfb,new $APP.h(null,1,[$APP.M,"Original implementation taken from https://github.com/viesti/nrepl-cljs-sci."],null)),$APP.DMa,"nbb/impl/nrepl_server.cljs",20,1,327,327,$APP.J(new $APP.G(null,1,5,$APP.H,[$APP.bG],null)),"Start nRepl server. Accepts options either as JS object or Clojure map.",
$APP.k(ifb)?ifb.H:null])),b=$APP.n(a),c=$APP.te(a);a=$APP.k(null)?null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,yfb,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Vq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.lq.g(c);return $APP.k(e)?e:$APP.yq.g(c)}())?$APP.fN.j(a,b,d):$APP.ju.j(a,b,d)}(),wfb,function(){var a=new $APP.Dd(function(){return $_},jfb,$APP.hi([$APP.P,$APP.N,$APP.Wl,$APP.Xz,$APP.rI,$APP.Pm,$APP.Xl,$APP.EK,$APP.U,$APP.M,$APP.kF],[$APP.se(kfb,new $APP.h(null,
1,[$APP.M,"Original implementation taken from https://github.com/viesti/nrepl-cljs-sci."],null)),wfb,"nbb/impl/nrepl_server.cljs",19,new $APP.h(null,6,[$APP.DA,!1,$APP.Rs,1,$APP.DJ,1,$APP.lJ,new $APP.G(null,2,5,$APP.H,[$APP.Tg,new $APP.G(null,1,5,$APP.H,[sfb],null)],null),$APP.U,$APP.J($APP.Tg,new $APP.G(null,1,5,$APP.H,[sfb],null)),$APP.fF,$APP.J(null,null)],null),1,398,398,$APP.J($APP.Tg,new $APP.G(null,1,5,$APP.H,[sfb],null)),null,$APP.k($_)?$_.H:null])),b=$APP.n(a),c=$APP.te(a);a=$APP.k(null)?
null:$APP.N.g(c);var d=new $APP.h(null,4,[$APP.P,yfb,$APP.N,a,$APP.U,$APP.U.g(c),$APP.M,$APP.M.g(c)],null);return $APP.k($APP.Vq.g(c))?$APP.eN.j(a,b,d):$APP.k(function(){var e=$APP.lq.g(c);return $APP.k(e)?e:$APP.yq.g(c)}())?$APP.fN.j(a,b,d):$APP.ju.j(a,b,d)}()],null);$APP.Zu(new $APP.h(null,1,[$APP.Lq,new $APP.h(null,1,[$APP.jA,zfb],null)],null));