import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_api.js";
import "./nbb_goog_string.js";
import "./nbb_pprint.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$fs from"fs";import*as esm_import$net from"net";import*as esm_import$path from"path";
var vW=function(a,b){a=a.indexOf(b);if(0>a)throw Error("out of input");return a},wW=function(a,b){if(a.length<b)throw Error("out of input");return a.slice(b)},xW=function(a,b){if(b>a.length)throw Error("out of input");return a.slice(0,b)},yW=function(a){return $APP.m($APP.Ex.g($APP.q($APP.hN)))?console.debug($APP.En.h(" ",a)):null},Lja=function(a){return function(b,c){b=$APP.ph(b);var d=$APP.gf.h(b,$APP.As),e=$APP.gf.h(b,YLa);c=$APP.K.j(c,"id",d);c=$APP.m(e)?$APP.K.j(c,"session",e):c;return a.h?a.h(b,
c):a.call(null,b,c)}},Nja=function(){var a=Mja;return function(b,c){b=$APP.Eq.j(b,$APP.jI,$APP.Xk);return a.h?a.h(b,c):a.call(null,b,c)}},Oja=function(){var a=Qja();return function(b,c){yW($APP.F(["request",b]));return a.h?a.h(b,c):a.call(null,b,c)}},Pja=function(a){return function(b,c){yW($APP.F(["response",c]));return a.h?a.h(b,c):a.call(null,b,c)}},Qja=function(){var a=Nja();return function(b,c){return a.h?a.h(b,c):a.call(null,b,c)}},AW=function(a){return $APP.K.j($APP.tk(new $APP.H(null,3,5,$APP.I,
["major","minor","incremental"],null),$APP.fB.g(a.split("."))),"version-string",a)},Nsa=function(a,b,c){if($APP.m(a))if(a=Msa.g?Msa.g(a):Msa.call(null,a),$APP.m(a)){b=$APP.ph(b);var d=$APP.gf.h(b,$APP.qLa),e=$APP.gf.h(b,$APP.TKa),h=$APP.gf.h(b,$APP.hLa);b=$APP.eb;var l=$APP.Kk,p=$APP.l8;$APP.eb=e;$APP.Kk=h;$APP.l8=d;try{var t=new $APP.Sa;d=$APP.hb;e=$APP.ib;$APP.hb=!0;$APP.ib=function(A){return t.append(A)};try{a.g?a.g(c):a.call(null,c)}finally{$APP.ib=e,$APP.hb=d}return $APP.n.g(t)}finally{$APP.l8=
p,$APP.Kk=l,$APP.eb=b}}else return yW($APP.F(["Pretty-Printing is only supported for clojure.core/prn and clojure.pprint/pprint."])),$APP.yl.l($APP.F([c]));else return $APP.yl.l($APP.F([c]))},WLa=function(a,b,c){$APP.fN.h($APP.Zda,$APP.Rh(c));var d=$APP.Qs.g($APP.um(c));d=$APP.m(d)?d:c.message;$APP.m(d)&&(d=new $APP.g(null,1,["err",[$APP.n.g(d),"\n"].join("")],null),a.h?a.h(b,d):a.call(null,b,d));c=new $APP.g(null,2,["ex",$APP.n.g(c),"ns",$APP.n.g($APP.q($APP.ef))],null);return a.h?a.h(b,c):a.call(null,
b,c)},DW=function(a,b){var c=$APP.ph(a),d=$APP.gf.h(c,$APP.O);a=$APP.gf.h(c,FZ);var e=$APP.gf.h(c,$APP.Km);$APP.gf.h(c,ZLa);$APP.gf.h(c,$La);var h=$APP.as(a),l=function A(t){try{var y=function(){var v=$APP.O.g($APP.ne(t));if($APP.m(v))return v;v=$APP.q(CW);return $APP.m(v)?v:d}(),D=$APP.yca(h,new $APP.g(null,3,[$APP.O,y,$APP.Km,e,$APP.uJ,$APP.Tt],null));return $APP.B.h($APP.Cx,D)?Promise.resolve(t):$APP.NCa(D,new $APP.g(null,3,[$APP.O,y,$APP.Km,e,$APP.uJ,$APP.Tt],null)).then(function(v){var J=$APP.C.j(v,
0,null),P=$APP.C.j(v,1,null);P=$APP.O.g(P);$APP.Th(CW,P);$APP.fN.h($APP.Yda,$APP.Rh($APP.q($APP.Xda)));$APP.fN.h($APP.Xda,$APP.Rh($APP.q($APP.Wda)));$APP.fN.h($APP.Wda,$APP.Rh(J));J=Nsa(aMa.g(c),bMa.g(c),J);J=new $APP.g(null,2,["value",J,"ns",$APP.n.g(P)],null);b.h?b.h(c,J):b.call(null,c,J);return A(v)})}catch(v){return WLa(b,c,v),A(null)}};$APP.jo($APP.hj([$APP.ef,d,$APP.bf,e,$APP.FL,$APP.q($APP.FL),$APP.KL,!0]));return function(){$APP.fN.h($APP.ov,$APP.Rh(function(t){t=new $APP.g(null,1,["out",
t],null);return b.h?b.h(c,t):b.call(null,c,t)}));return l(null).catch($APP.rr.j(WLa,b,c)).finally(function(){var t=new $APP.g(null,2,["ns",$APP.n.g($APP.q(CW)),"status",new $APP.H(null,1,5,$APP.I,["done"],null)],null);return b.h?b.h(c,t):b.call(null,c,t)})}().finally(function(){return $APP.lo()})},pPa=function(a,b){a=$APP.ph(a);var c=$APP.gf.h(a,$APP.O),d=$APP.K.j;c=$APP.m(c)?$APP.xP($APP.ho(),$APP.fl.g(c)):null;$APP.m(c)||(c=$APP.q(CW),c=$APP.m(c)?c:$APP.q($APP.ef));return DW(d.call($APP.K,a,$APP.O,
c),b)},rPa=function(a,b){var c=$APP.ph(a),d=$APP.gf.h(c,$APP.O),e=$APP.jI.g(c);try{var h=$APP.O.g(c),l=function(){var P=$APP.Xla.g(c);return $APP.m(P)?P:$APP.wn.g(c)}(),p=function(){var P=$APP.m(d)?$APP.xP($APP.ho(),$APP.fl.g(d)):null;if($APP.m(P))return P;P=$APP.q(CW);return $APP.m(P)?P:$APP.q($APP.ef)}(),t=$APP.hj([$APP.ef,p]);$APP.jo(t);try{var A=$APP.qP($APP.ho(),$APP.R3("\n(let [ns '%s\n      full-sym '%s]\n  (when-let [v (ns-resolve ns full-sym)]\n    (let [m (meta v)]\n      (assoc m :arglists (:arglists m)\n       :doc (:doc m)\n       :name (:name m)\n       :ns (some-\x3e m :ns ns-name)\n       :val @v))))",
h,l)),y=$APP.V.g(A),D=$APP.Km.g(A),v=$APP.Lm.g(A),J=function(){var P=e instanceof $APP.k?e.T:null;switch(P){case "eldoc":return P=new $APP.g(null,5,["ns",$APP.O.g(A),"name",$APP.N.g(A),"eldoc",$APP.lq.h(function(W){return $APP.lq.h($APP.n,W)},$APP.U.g(A)),"type",$APP.Ye($APP.xx.g(A))?"function":"variable","status",new $APP.H(null,1,5,$APP.I,["done"],null)],null),$APP.m(y)?$APP.K.j(P,"docstring",y):P;case "info":case "lookup":return P=new $APP.g(null,4,["ns",$APP.O.g(A),"name",$APP.N.g(A),"arglists-str",
$APP.En.h("\n",$APP.Wk.h($APP.yl,$APP.U.g(A))),"status",new $APP.H(null,1,5,$APP.I,["done"],null)],null),P=$APP.m(y)?$APP.K.j(P,"doc",y):P,P=$APP.m(D)?$APP.K.j(P,"file",D):P,$APP.m(v)?$APP.K.j(P,"line",v):P;default:throw Error(["No matching clause: ",$APP.n.g(P)].join(""));}}();return b.h?b.h(c,J):b.call(null,c,J)}finally{$APP.lo()}}catch(P){if(P instanceof Error)return a=P,h=function(){var W=new $APP.lk(null,new $APP.g(null,1,["done",null],null),null);return $APP.B.h(e,cMa)?$APP.Cg.h(W,"no-eldoc"):
W}(),a=new $APP.g(null,2,["status",h,"ex",$APP.n.g(a)],null),b.h?b.h(c,a):b.call(null,c,a);throw P;}},Mja=function(a,b){a=$APP.ph(a);var c=$APP.gf.h(a,$APP.jI),d=$APP.gf.h(EW,c);if($APP.m(d))return d.h?d.h(a,b):d.call(null,a,b);console.warn($APP.En.h(" ",$APP.F(["Unhandled operation",c])));c=new $APP.g(null,1,["status",new $APP.H(null,3,5,$APP.I,["error","unknown-op","done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},Rja=function(a){return function(b,c){return a.write(FW(c))}},Sja=function(a,
b){yW($APP.F(["Connection accepted"]));b.setNoDelay(!0);var c=Oja(),d=Lja(Pja(Rja(b))),e=$APP.Cl.g(null);b.on("data",function(h){var l=$APP.q(e);if($APP.m(l)){h=[$APP.n.g(l),$APP.n.g(h)].join("");$APP.Th(e,null);var p=h}else p=h;a:for(h=$APP.F([$APP.ly,!0]),l=$APP.qi;;){var t=$APP.nh.j(GW,p,h);p=$APP.C.j(t,0,null);t=$APP.C.j(t,1,null);if(null==p){l=new $APP.H(null,2,5,$APP.I,[l,t],null);break a}l=$APP.Cg.h(l,p);p=t}h=$APP.C.j(l,0,null);l=$APP.C.j(l,1,null);$APP.zn(l)||$APP.Th(e,l);h=$APP.u(h);l=null;
for(var A=t=0;;)if(A<t)p=l.fa(null,A),c(p,d),A+=1;else if(h=$APP.u(h))l=h,$APP.Oe(l)?(h=$APP.dd(l),t=$APP.fd(l),l=h,p=$APP.ie(h),h=t,t=p):(p=$APP.x(l),c(p,d),h=$APP.z(l),l=null,t=0),A=0;else return null});return b.on("close",function(h){return $APP.m(h)?yW($APP.F(["Connection lost"])):yW($APP.F(["Connection closed"]))})},mKa=function(a){return Promise.resolve($APP.wR(esm_import$path.resolve("script.cljs"),null)).then(function(){function b(e){return $APP.rP(new $APP.G(null,$APP.Bm,new $APP.G(null,
new $APP.G(null,$APP.Bm,new $APP.G(null,e,null,1,null),2,null),null,1,null),2,null))}var c=$APP.C.j($APP.iN,0,null),d=$APP.C.j($APP.iN,1,null);return b(c).then(function(){return b(d)})}).then(function(){var b=$APP.bp.l($APP.F([$APP.q($APP.hN),a])),c=function(){var h=$APP.zP.g(b);return $APP.m(h)?h:0}(),d=function(){var h=$APP.BDa.g(b);return $APP.m(h)?h:"127.0.0.1"}();(function(){var h=$APP.sb(b)?b.Tj:fMa.g(b);return $APP.m(h)?h:"info"})();var e=esm_import$net.createServer($APP.rr.h(Sja,$APP.uh));
e.listen(c,d,function(){var h=e.address(),l=h.port;h=h.address;$APP.VA.l($APP.F([["nREPL server started on port ",$APP.n.g(l)," on host ",$APP.n.g(h)," - nrepl://",$APP.n.g(h),":",$APP.n.g(l)].join("")]));try{return esm_import$fs.writeFileSync(".nrepl-port",$APP.n.g(l))}catch(p){return console.warn($APP.En.h(" ",$APP.F(["Could not write .nrepl-port",p])))}});return $APP.Th(lKa,e)})},gMa=new $APP.r("nbb.impl.nrepl-server","stop-server!","nbb.impl.nrepl-server/stop-server!",1628751782,null),bMa=new $APP.k("nrepl.middleware.print",
"options","nrepl.middleware.print/options",868480159),hMa=new $APP.r(null,"nbb.impl.nrepl-server","nbb.impl.nrepl-server",-1821079079,null),YLa=new $APP.k(null,"session","session",1008279103),iMa=new $APP.r("nbb.impl.nrepl-server","start-server!","nbb.impl.nrepl-server/start-server!",-2119141227,null),jMa=new $APP.k(null,"load-file","load-file",-424586670),FZ=new $APP.k(null,"code","code",1586293142),fMa=new $APP.k(null,"log_level","log_level",-1756736313),aMa=new $APP.k("nrepl.middleware.print",
"print","nrepl.middleware.print/print",-1616742548),kMa=new $APP.k(null,"clone","clone",711747572),lMa=new $APP.k(null,"close","close",1835149582),mMa=new $APP.k(null,"info","info",-317069002),nMa=new $APP.k(null,"macroexpand","macroexpand",-130598183),oMa=new $APP.k(null,"complete","complete",-500388775),$La=new $APP.k(null,"_line","_line",232847719),pMa=new $APP.r(null,"server","server",-1155245649,null),qMa=new $APP.k(null,"lookup","lookup",1225356838),rMa=new $APP.k(null,"expander","expander",
379138924),ZLa=new $APP.k(null,"_load-file?","_load-file?",-1198848711),sMa=new $APP.k(null,"describe","describe",1369790582),cMa=new $APP.k(null,"eldoc","eldoc",-1321421900),uMa=new $APP.r(null,"stop-server!","stop-server!",-410772185,null),vMa=new $APP.k(null,"load-file?","load-file?",1892536169);var HW=function HW(a,b){switch($APP.n.g(xW(a,1))){case "i":return a=wW(a,1),b=vW(a,"e"),new $APP.H(null,2,5,$APP.I,[parseInt(xW(a,b)),wW(a,b+1)],null);case "l":var d=a=wW(a,1);for(a=$APP.Tc($APP.qi);;){if($APP.B.h($APP.n.g(xW(d,1)),"e"))return new $APP.H(null,2,5,$APP.I,[$APP.Vc(a),wW(d,1)],null);var e=HW.h?HW.h(d,b):HW.call(null,d,b),h=$APP.C.j(e,0,null),l=$APP.C.j(e,1,null);e=l;a=$APP.pi.h(a,h);d=e}case "d":for(a=wW(a,1),h=$APP.ph(b),h=$APP.gf.h(h,$APP.ly),d=a,e=$APP.Tc($APP.uh);;){if($APP.B.h($APP.n.g(xW(d,
1)),"e"))return new $APP.H(null,2,5,$APP.I,[$APP.Vc(e),wW(d,1)],null);a=HW.h?HW.h(d,b):HW.call(null,d,b);d=$APP.C.j(a,0,null);l=$APP.C.j(a,1,null);l=HW.h?HW.h(l,b):HW.call(null,l,b);a=$APP.C.j(l,0,null);l=$APP.C.j(l,1,null);d=$APP.m(h)?$APP.Xk.g(d):d;a=$APP.kj.j(e,d,a);d=l;e=a}default:return b=vW(a,":"),h=parseInt(xW(a,b)),a=wW(a,b+1),new $APP.H(null,2,5,$APP.I,[$APP.n.g(xW(a,h)),wW(a,h)],null)}},GW=function GW(a){for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return GW.l(arguments[0],
1<c.length?new $APP.Fd(c.slice(1),0,null):null)};GW.l=function(a,b){try{return HW(a,b)}catch(c){if(c instanceof Error)return new $APP.H(null,2,5,$APP.I,[null,a],null);throw c;}};GW.C=1;GW.G=function(a){var b=$APP.x(a);a=$APP.z(a);return this.l(b,a)};
var FW=function FW(a){for(;;){if("string"===typeof a)return[$APP.n.g(Buffer.from(a).length),":",a].join("");if(a instanceof $APP.k||a instanceof $APP.r)a=[function(){var c=$APP.Jg(a);return $APP.m(c)?[c,"/"].join(""):null}(),$APP.sk(a)].join("");else return"number"===typeof a?["i",$APP.n.g(a),"e"].join(""):$APP.Ge(a)||$APP.Ne(a)||null==a?["l",$APP.n.g($APP.nh.h($APP.n,$APP.Wk.h(FW,a))),"e"].join(""):$APP.Le(a)?["d",$APP.n.g($APP.nh.h($APP.n,$APP.Wk.h(function(){return function(c){var d=$APP.C.j(c,
0,null);c=$APP.C.j(c,1,null);return[$APP.n.g(FW.g?FW.g(d):FW.call(null,d)),$APP.n.g(FW.g?FW.g(c):FW.call(null,c))].join("")}}(a),$APP.Jz.h($APP.x,a)))),"e"].join(""):null}};var CW=$APP.Cl.g(null),Msa=new $APP.g(null,1,["cider.nrepl.pprint/pprint",$APP.n$],null),EW=$APP.Oj([$APP.AP,qMa,lMa,jMa,cMa,kMa,sMa,mMa,oMa,nMa,$APP.xxa],[function(a,b){var c=new $APP.g(null,2,["status",new $APP.H(null,1,5,$APP.I,["done"],null),"classpath",$APP.rn.h($APP.Hn(),$APP.Jk(esm_import$path.delimiter))],null);return b.h?b.h(a,c):b.call(null,a,c)},rPa,function(a,b){var c=new $APP.g(null,1,["status",new $APP.H(null,1,5,$APP.I,["done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},function(a,
b){a=$APP.ph(a);var c=$APP.gf.h(a,$APP.Km);return DW($APP.K.l(a,FZ,c,$APP.F([vMa,!0,$APP.O,$APP.q($APP.ef)])),b)},rPa,function(a,b){var c=new $APP.g(null,2,["new-session",$APP.n.g($APP.rm()),"status",new $APP.H(null,1,5,$APP.I,["done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},function(a,b){var c=new $APP.g(null,4,["versions",new $APP.g(null,2,["nbb-nrepl",AW("TODO"),"node",AW(process.version)],null),"aux",$APP.uh,"ops",$APP.tk($APP.Wk.h($APP.sk,$APP.fk(EW)),$APP.Qq.g($APP.uh)),"status",
new $APP.H(null,1,5,$APP.I,["done"],null)],null);return b.h?b.h(a,c):b.call(null,a,c)},rPa,function(a,b){var c=$APP.yP(a);return b.h?b.h(a,c):b.call(null,a,c)},function(a,b){a=$APP.ph(a);var c=$APP.gf.h(a,FZ),d=$APP.gf.h(a,rMa);try{return pPa($APP.K.j(a,FZ,["( ",$APP.n.g(d),"(quote ",$APP.n.g(c),"))"].join("")),function(e,h){var l=h.g?h.g("value"):h.call(null,"value");h=$APP.m(l)?$APP.K.j(h,"expansion",l):h;return b.h?b.h(e,h):b.call(null,e,h)})}catch(e){if(e instanceof Error)return c=new $APP.g(null,
3,["ex",$APP.n.g(e),"ns",$APP.n.g($APP.q($APP.ef)),"status",new $APP.H(null,1,5,$APP.I,["done"],null)],null),b.h?b.h(a,c):b.call(null,a,c);throw e;}},pPa]),lKa=$APP.Cl.g(null),i_=function i_(a){switch(arguments.length){case 0:return i_.F();case 1:return i_.g(arguments[0]);default:throw Error(["Invalid arity: ",$APP.n.g(arguments.length)].join(""));}};i_.F=function(){return i_.g($APP.q(lKa))};
i_.g=function(a){return a.close(function(){return $APP.m(esm_import$fs.existsSync(".nrepl-port"))?esm_import$fs.unlinkSync(".nrepl-port"):null})};i_.C=1;
var EKa=$APP.py($APP.NB),FKa=new $APP.g(null,2,[$APP.ADa,function(){var a=new $APP.Dd(function(){return mKa},iMa,$APP.Oj([$APP.O,$APP.N,$APP.Km,$APP.vB,$APP.io,$APP.Lm,$APP.BP,$APP.U,$APP.V,$APP.mH],[$APP.Ae(hMa,new $APP.g(null,1,[$APP.V,"Original implementation taken from https://github.com/viesti/nrepl-cljs-sci."],null)),$APP.ADa,"nbb/impl/nrepl_server.cljs",20,1,326,326,$APP.R(new $APP.H(null,1,5,$APP.I,[$APP.KH],null)),"Start nRepl server. Accepts options either as JS object or Clojure map.",
$APP.m(mKa)?mKa.A:null])),b=$APP.q(a);a=$APP.Be(a);var c=$APP.m(null)?null:$APP.N.g(a),d=new $APP.g(null,4,[$APP.O,EKa,$APP.N,c,$APP.U,$APP.U.g(a),$APP.V,$APP.V.g(a)],null);return $APP.m($APP.Ys.g(a))?$APP.jy(c,b,d):$APP.m($APP.is.g(a))?$APP.ky(c,b,d):$APP.iy(c,b,d)}(),uMa,function(){var a=new $APP.Dd(function(){return i_},gMa,$APP.Oj([$APP.O,$APP.N,$APP.Km,$APP.vB,$APP.mJ,$APP.io,$APP.Lm,$APP.BP,$APP.U,$APP.V,$APP.mH],[$APP.Ae(hMa,new $APP.g(null,1,[$APP.V,"Original implementation taken from https://github.com/viesti/nrepl-cljs-sci."],
null)),uMa,"nbb/impl/nrepl_server.cljs",19,new $APP.g(null,6,[$APP.bC,!1,$APP.Jv,1,$APP.kK,1,$APP.VJ,new $APP.H(null,2,5,$APP.I,[$APP.qi,new $APP.H(null,1,5,$APP.I,[pMa],null)],null),$APP.U,$APP.R($APP.qi,new $APP.H(null,1,5,$APP.I,[pMa],null)),$APP.XG,$APP.R(null,null)],null),1,375,375,$APP.R($APP.qi,new $APP.H(null,1,5,$APP.I,[pMa],null)),null,$APP.m(i_)?i_.A:null])),b=$APP.q(a);a=$APP.Be(a);var c=$APP.m(null)?null:$APP.N.g(a),d=new $APP.g(null,4,[$APP.O,EKa,$APP.N,c,$APP.U,$APP.U.g(a),$APP.V,$APP.V.g(a)],
null);return $APP.m($APP.Ys.g(a))?$APP.jy(c,b,d):$APP.m($APP.is.g(a))?$APP.ky(c,b,d):$APP.iy(c,b,d)}()],null);$APP.Wy(new $APP.g(null,1,[$APP.Ts,new $APP.g(null,1,[$APP.NB,FKa],null)],null));