import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
const shadow_esm_import = function(x) { return import(x) };
var qtb=function(a,b,c,d){return $APP.aj(a,function(e,f){$APP.Lc(f,"[");$APP.Lc(f,$APP.yj.l($APP.z([e])));$APP.Lc(f," ");$APP.Lc(f,$APP.yj.l($APP.z([$APP.C.h(b,e)])));return $APP.Lc(f,"]")},"("," ",")",d,c)},Y$=function(a,b){this.La=a;this.Zc=b;this.J=2297825039;this.M=8192},Z$=function(a,b){return $APP.x.h(a,b instanceof Y$?b.La:b)},rtb=new $APP.F(null,"skip-protocol-flag","skip-protocol-flag",-1426798630),stb=new $APP.q("cljs.core","IKVReduce","cljs.core/IKVReduce",878013381,null),ttb=new $APP.q("cljs.core",
"IFind","cljs.core/IFind",-1727519574,null),utb=new $APP.q("cljs.core","ISeqable","cljs.core/ISeqable",137437203,null),vtb=new $APP.q("cljs.core","ICounted","cljs.core/ICounted",-1299011378,null),wtb=new $APP.q("cljs.core","ILookup","cljs.core/ILookup",-150575073,null),xtb=new $APP.q(null,"ordered-map","ordered-map",-706459974,null),ytb=new $APP.q("cljs.core","IAssociative","cljs.core/IAssociative",-1700920611,null),ztb=new $APP.q("cljs.core","ICloneable","cljs.core/ICloneable",-1712216461,null),
Atb=new $APP.q(null,"print-ordered-map","print-ordered-map",1388177372,null),Btb=new $APP.q(null,"that","that",828965210,null),Ctb=new $APP.q("flatland.ordered.map","-\x3eOrderedMap","flatland.ordered.map/-\x3eOrderedMap",-2112744986,null),Dtb=new $APP.q("flatland.ordered.map","print-ordered-map","flatland.ordered.map/print-ordered-map",-867774065,null),Etb=new $APP.q("flatland.ordered.map","ordered-map","flatland.ordered.map/ordered-map",1887268971,null),Ftb=new $APP.q(null,"equiv-impl","equiv-impl",
417944565,null),Gtb=new $APP.q("cljs.core","IMap","cljs.core/IMap",1407777598,null),Htb=new $APP.q("cljs.core","IReversible","cljs.core/IReversible",-1422278012,null),Itb=new $APP.q("cljs.core","IHash","cljs.core/IHash",-32453786,null),Jtb=new $APP.q("flatland.ordered.map","equiv-impl","flatland.ordered.map/equiv-impl",-229597862,null),Ktb=new $APP.q("cljs.core","IEmptyableCollection","cljs.core/IEmptyableCollection",5045035,null),Ltb=new $APP.q(null,"-\x3eOrderedMap","-\x3eOrderedMap",613100471,
null),Mtb=new $APP.q("cljs.core","IEquiv","cljs.core/IEquiv",-1245752602,null),Ntb=new $APP.q("cljs.core","ICollection","cljs.core/ICollection",802638471,null),Otb=new $APP.F(null,"protocols","protocols",-5615896),Ptb=new $APP.q("cljs.core","Object","cljs.core/Object",-345545431,null),Qtb=new $APP.q("cljs.core","IPrintWithWriter","cljs.core/IPrintWithWriter",1349251417,null);$APP.g=Y$.prototype;$APP.g.Ie=$APP.xd;$APP.g.me=function(a,b){return $APP.gc(this.La,b)};$APP.g.entry_set=function(){return $APP.bf($APP.ej.h($APP.bf,this.La))};
$APP.g.forEach=function(){function a(d,e){for(var f=$APP.r(this.Zc),l=null,p=0,u=0;;)if(u<p){var t=l.ea(null,u);d.call(e,t,$APP.C.h(this.La,t),this);u+=1}else if(f=$APP.r(f))l=f,$APP.Ee(l)?(f=$APP.cd(l),p=$APP.dd(l),l=f,t=$APP.be(f),f=p,p=t):(t=$APP.v(l),d.call(e,t,$APP.C.h(this.La,t),this),f=$APP.w(l),l=null,p=0),u=0;else return null}function b(d){for(var e=$APP.r(this.Zc),f=null,l=0,p=0;;)if(p<l){var u=f.ea(null,p),t=u;u=$APP.C.h(this.La,u);d.j?d.j(t,u,this):d.call(null,t,u,this);p+=1}else if(e=
$APP.r(e))$APP.Ee(e)?(u=$APP.cd(e),e=$APP.dd(e),f=u,l=u=$APP.be(u)):(f=u=$APP.v(e),u=$APP.C.h(this.La,u),d.j?d.j(f,u,this):d.call(null,f,u,this),e=$APP.w(e),f=null,l=0),p=0;else return null}var c=null;c=function(d,e){switch(arguments.length){case 1:return b.call(this,d);case 2:return a.call(this,d,e)}throw Error("Invalid arity: "+arguments.length);};c.g=b;c.h=a;return c}();$APP.g.get=function(a){return this.La.get(a)};$APP.g.key_set=function(){return $APP.bf($APP.qi(this.La))};$APP.g.entries=function(){return $APP.xh($APP.r(this.La))};
$APP.g.value_set=function(){return $APP.bf($APP.ej.h($APP.gh,this.La))};$APP.g.toString=function(){return $APP.od(this)};$APP.g.keys=function(){return $APP.Jd(this.Zc)};$APP.g.values=function(){return $APP.Jd($APP.si(this.La))};$APP.g.equiv=function(a){return Z$.h?Z$.h(this.La,a):Z$.call(null,this.La,a)};$APP.g.has=function(a){return null!=this.La.get(a)};$APP.g.da=function(a,b){return $APP.Dx(this.La,b)};$APP.g.K=function(a,b,c){return $APP.Dx(this.La,b,c)};
$APP.g.ka=function(a,b,c){var d=this;return $APP.af.j(function(e,f){var l=$APP.C.h(d.La,f);return b.j?b.j(e,f,l):b.call(null,e,f,l)},c,d.Zc)};$APP.g.V=function(a,b,c){$APP.Lc(b,"#ordered/map ");return qtb(b,this.La,this.Zc,c)};$APP.g.U=function(){return $APP.se(this.La)};$APP.g.ba=function(){return new Y$(this.La,this.Zc)};$APP.g.aa=function(){return $APP.be(this.La)};$APP.g.xd=function(){var a=this;return $APP.r(a.Zc)?$APP.ej.h(function(b){return $APP.gc(a.La,b)},$APP.Fc(a.Zc)):null};$APP.g.Y=function(){return $APP.yd(this.La)};
$APP.g.T=function(a,b){return Z$.h?Z$.h(this.La,b):Z$.call(null,this.La,b)};$APP.g.Na=function(){return $APP.r(this.Zc)?new Y$($APP.Ub(this.La),$APP.Sg):this};$APP.g.la=function(a,b){return $APP.Se(this.La,b)?new Y$($APP.Ol.h(this.La,b),$APP.Eh.j($APP.Sg,$APP.gs.g($APP.Bi([b])),this.Zc)):this};$APP.g.R=function(a,b,c){return new Y$($APP.ui.j(this.La,b,c),$APP.Se(this.La,b)?this.Zc:$APP.vf.h(this.Zc,b))};$APP.g.ha=function(a,b){return $APP.Se(this.La,b)};
$APP.g.Z=function(){var a=this;return $APP.r(a.Zc)?$APP.ej.h(function(b){return $APP.gc(a.La,b)},a.Zc):null};$APP.g.W=function(a,b){return $APP.se(this.La)===b?this:new Y$($APP.re(this.La,b),this.Zc)};$APP.g.ca=function(a,b){var c=this;return $APP.De(b)?new Y$($APP.vf.h(c.La,b),$APP.Se(c.La,$APP.oe(b,0))?c.Zc:$APP.vf.h(c.Zc,$APP.oe(b,0))):new Y$($APP.vf.h(c.La,b),$APP.Eh.j(c.Zc,$APP.qq.h($APP.ej.g(function(d){return $APP.oe(d,0)}),$APP.gs.g(function(d){return $APP.Se(c.La,d)})),b))};
$APP.g.call=function(a){switch(arguments.length-1){case 1:return this.g(arguments[1]);case 2:return this.h(arguments[1],arguments[2]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length-1)].join(""));}};$APP.g.apply=function(a,b){return this.call.apply(this,[this].concat($APP.Ob(b)))};$APP.g.g=function(a){return this.La.g?this.La.g(a):this.La.call(null,a)};$APP.g.h=function(a,b){return this.La.h?this.La.h(a,b):this.La.call(null,a,b)};
var Rtb=new Y$($APP.Xf,$APP.Sg),$$=function $$(a){switch(arguments.length){case 0:return $$.D();case 1:return $$.g(arguments[0]);default:for(var c=[],d=arguments.length,e=0;;)if(e<d)c.push(arguments[e]),e+=1;else break;return $$.l(arguments[0],arguments[1],2<c.length?new $APP.Ed(c.slice(2),0,null):null)}};$$.D=function(){return Rtb};$$.g=function(a){return $APP.Eh.h(Rtb,a)};$$.l=function(a,b,c){return $APP.qg.P($APP.ui,Rtb,a,b,c)};
$$.G=function(a){var b=$APP.v(a),c=$APP.w(a);a=$APP.v(c);c=$APP.w(c);return this.l(b,a,c)};$$.B=2;var Stb=$APP.DO.h($APP.Dua,null),Ttb=$APP.iu(new $APP.h(null,4,[$APP.re(Ftb,new $APP.h(null,1,[$APP.KE,!0],null)),new $APP.h(null,3,[$APP.N,Jtb,$APP.hu,Z$,$APP.nb,new $APP.h(null,1,[$APP.V,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.qH,Btb],null))],null)],null),$APP.re(Atb,new $APP.h(null,1,[$APP.V,$APP.J($APP.Ak,$APP.J(new $APP.H(null,4,5,$APP.I,[$APP.Tz,$APP.qH,$APP.bD,$APP.DH],null)))],null)),new $APP.h(null,3,[$APP.N,Dtb,$APP.hu,qtb,$APP.nb,new $APP.h(null,1,[$APP.V,$APP.J(new $APP.H(null,4,5,$APP.I,
[$APP.Tz,$APP.qH,$APP.bD,$APP.DH],null))],null)],null),$APP.re(Ltb,new $APP.h(null,5,[Otb,new $APP.zi(null,new $APP.h(null,18,[Htb,"null",stb,"null",Mtb,"null",Itb,"null",$APP.lE,"null",Ntb,"null",Ptb,"null",ttb,"null",Ktb,"null",vtb,"null",utb,"null",$APP.IA,"null",ztb,"null",Qtb,"null",$APP.bE,"null",ytb,"null",Gtb,"null",wtb,"null"],null),null),$APP.PK,$APP.esa,$APP.V,$APP.J($APP.Ak,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.qH,$APP.bD],null))),rtb,new $APP.zi(null,new $APP.h(null,16,[Htb,"null",
stb,"null",Mtb,"null",Itb,"null",$APP.lE,"null",Ntb,"null",Ktb,"null",vtb,"null",utb,"null",$APP.IA,"null",ztb,"null",Qtb,"null",$APP.bE,"null",ytb,"null",Gtb,"null",wtb,"null"],null),null),$APP.M,"Positional factory function for flatland.ordered.map/OrderedMap."],null)),new $APP.h(null,3,[$APP.N,Ctb,$APP.hu,function(a,b){return new Y$(a,b)},$APP.nb,new $APP.h(null,2,[$APP.V,$APP.J(new $APP.H(null,2,5,$APP.I,[$APP.qH,$APP.bD],null)),$APP.M,"Positional factory function for flatland.ordered.map/OrderedMap."],
null)],null),$APP.re(xtb,new $APP.h(null,2,[$APP.V,$APP.J($APP.Ak,$APP.J($APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.wF],null),new $APP.H(null,4,5,$APP.I,[$APP.nJ,$APP.wJ,$APP.lk,$APP.qH],null))),$APP.QJ,new $APP.h(null,6,[$APP.zA,!0,$APP.Os,2,$APP.cL,2,$APP.KK,new $APP.H(null,2,5,$APP.I,[$APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.wF],null)],null),$APP.V,$APP.J($APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.wF],null),new $APP.H(null,4,5,$APP.I,[$APP.nJ,$APP.wJ,$APP.lk,$APP.qH],null)),$APP.aG,$APP.J(null,null,
null)],null)],null)),new $APP.h(null,3,[$APP.N,Etb,$APP.hu,$$,$APP.nb,new $APP.h(null,1,[$APP.V,$APP.J($APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.wF],null),new $APP.H(null,4,5,$APP.I,[$APP.nJ,$APP.wJ,$APP.lk,$APP.qH],null))],null)],null)],null),Stb);$APP.Wu(new $APP.h(null,1,[$APP.Iq,new $APP.h(null,1,[$APP.Dua,Ttb],null)],null));