import { $APP, shadow$provide, $jscomp } from "./nbb_core.js";
import "./nbb_api.js";
const shadow_esm_import = function(x) { return import(x) };
import*as esm_import$node_net from"node:net";import*as esm_import$node_process from"node:process";import*as esm_import$node_readline from"node:readline";import*as esm_import$node_vm from"node:vm";
var SY=function(a){var b=function(){var e=$APP.xr.h(a,"(");return $APP.l(e)?new $APP.H(null,2,5,$APP.I,[$APP.Zi.j(a,0,e+1),$APP.Zi.h(a,e+1)],null):new $APP.H(null,2,5,$APP.I,[null,a],null)}(),c=$APP.A.j(b,0,null),d=$APP.A.j(b,1,null);b=$APP.C.h(function(){try{return $APP.kGa(new $APP.k(null,2,[$APP.Q,$APP.m.g($APP.p(RY)),$APP.bJ,d],null))}catch(f){var e=f;console.warn($APP.m.g($APP.Twa),$APP.ik(e));return null}}(),"completions");return $APP.fj.h(function(e){return[$APP.m.g(c),$APP.m.g(e)].join("")},
$APP.Tg(function(e){return $APP.Ea(e,d)},$APP.fj.h(function(e){return $APP.C.h(e,"candidate")},b)))},KRa=function(a){return[$APP.qs.g(SY(a)),a]},LRa=function(a,b){$APP.Bg(TY,!1);a.setPrompt([$APP.m.g($APP.p(RY)),"\x3d\x3e "].join(""));a.prompt();return $APP.jl($APP.p(UY))?null:VY.h?VY.h(b,a):VY.call(null,b,a)},MRa=function(a){var b=$APP.wl(a);a=$APP.xl(a);var c=$APP.il($APP.p(UY));b=$APP.Kg.h(b-1,c);c=$APP.u(b);b=$APP.v(c);c=$APP.w(c);a=$APP.l(b)?$APP.Zi.h(b,a):null;$APP.Bg(UY,$APP.kn.h("\n",$APP.zf(a,
c)))},NRa=function(a,b){b={f:b};esm_import$node_vm.createContext(b);try{return $APP.l($APP.l(WY)?$APP.Cb(a):WY)&&esm_import$node_process.stdin.setRawMode(!1),esm_import$node_vm.runInContext("f()",b,{displayErrors:!0,breakOnSigint:!0,microtaskMode:"afterEvaluate"}).then(function(c){var d={f:$APP.l(a)?function(){return c}:function(){var e=$APP.v(c);$APP.su.l($APP.B([e]));return c}};esm_import$node_vm.createContext(d);return esm_import$node_vm.runInContext("f()",d,{displayErrors:!0,breakOnSigint:!0,
microtaskMode:"afterEvaluate"})}).finally(function(){return $APP.l($APP.l(WY)?$APP.Cb(a):WY)?esm_import$node_process.stdin.setRawMode(!0):null})}catch(c){return b=c,$APP.l($APP.l(WY)?$APP.Cb(a):WY)&&esm_import$node_process.stdin.setRawMode(!0),Promise.reject(b)}},VY=function(a,b){if($APP.l(function(){var e=$APP.p(TY);return $APP.l(e)?e:$APP.jl($APP.p(UY))}()))return null;$APP.Bg(TY,!0);var c=$APP.up($APP.p(UY)),d=function(){try{var e=$APP.Wf([$APP.Fq,$APP.p(RY)]);$APP.Vp(e);try{return $APP.fja(c)}finally{$APP.Xp()}}catch(f){e=
f;if($APP.Ha($APP.ik(e),"EOF while reading"))return ORa;MRa(c);$APP.su.l($APP.B([$APP.m.g(e)]));return PRa}}();if($APP.y.h(PRa,d))return LRa(b,a);if($APP.y.h(ORa,d))return $APP.Bg(TY,!1);MRa(c);if($APP.y.h($APP.UH,d))return $APP.Bg(TY,!1);$APP.Vp($APP.Wf([$APP.Fq,$APP.p(RY)]));return NRa(a,function(){return $APP.$Fa(d,new $APP.k(null,3,[$APP.Q,$APP.p(RY),$APP.Wl,$APP.p($APP.rq),$APP.hM,$APP.Bw],null))}).then(function(e){var f=$APP.A.j(e,0,null);e=$APP.A.j(e,1,null);e=$APP.Yf(e);e=$APP.C.h(e,$APP.Q);
$APP.Bg(RY,e);$APP.qS.h($APP.RR,$APP.zg($APP.p($APP.QR)));$APP.qS.h($APP.QR,$APP.zg($APP.p($APP.PR)));$APP.qS.h($APP.PR,$APP.zg(f));$APP.l(a)&&a.write($APP.ty.l($APP.B([f])));return LRa(b,a)}).catch(function(e){$APP.su.l($APP.B([$APP.m.g(e)]));$APP.qS.h($APP.SR,$APP.zg(e));return LRa(b,a)}).finally(function(){return $APP.Xp()})},QRa=function(a,b){a.on("line",function(c){$APP.Cj.D(UY,$APP.m,c,"\n");return VY(b,a)})},RRa=function(a){return esm_import$node_readline.createInterface({input:a,output:a,
completer:KRa})},SRa=function(a){var b=RRa(a);QRa(b,a);a.setNoDelay(!0);return a.on("close",function(){return $APP.wy.l($APP.B(["Client closed connection."]))})},TRa=new $APP.r(null,"nbb.impl.repl","nbb.impl.repl",-339140484,null),ORa=new $APP.G("nbb.impl.repl","eof-while-reading","nbb.impl.repl/eof-while-reading",1743626215),URa=new $APP.r("nbb.impl.repl","completer*","nbb.impl.repl/completer*",455172317,null),VRa=new $APP.r("nbb.impl.repl","repl","nbb.impl.repl/repl",-1645296655,null),WRa=new $APP.r(null,
"completer*","completer*",-648150376,null),XRa=new $APP.r("nbb.impl.repl","socket-repl","nbb.impl.repl/socket-repl",1509490200,null),YRa=new $APP.G(null,"init","init",-1875481434),ZRa=new $APP.r(null,"get-completions","get-completions",1933789168,null),PRa=new $APP.G("nbb.impl.repl","continue","nbb.impl.repl/continue",-1326808644);var RY=$APP.Bj.g($APP.p($APP.Fq)),UY=$APP.Bj.g(""),TY=$APP.Bj.g(!1),WY,$Ra=esm_import$node_process.stdout.isTTY;WY=$APP.l($Ra)?esm_import$node_process.stdin.setRawMode:$Ra;var aSa=$APP.uS.h($APP.Ry,null),XY=function XY(a){switch(arguments.length){case 0:return XY.C();case 1:return XY.g(arguments[0]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};XY.C=function(){return XY.g(null)};
XY.g=function(a){var b=function(){var d=$APP.iH.g(a);return $APP.l(d)?d:0}(),c=esm_import$node_net.createServer(SRa);return c.listen(b,"127.0.0.1",function(){var d=c.address(),e=d.address;return $APP.wy.l($APP.B([["Socket REPL listening on port ",$APP.m.g(d.port)," on host ",$APP.m.g(e)].join("")]))})};XY.A=1;var YY=function YY(a){switch(arguments.length){case 0:return YY.C();case 1:return YY.g(arguments[0]);default:throw Error(["Invalid arity: ",$APP.m.g(arguments.length)].join(""));}};YY.C=function(){return YY.g(null)};
YY.g=function(a){function b(e){return $APP.XFa(new $APP.D(null,$APP.zk,new $APP.D(null,new $APP.D(null,$APP.zk,new $APP.D(null,e,null,1,null),2,null),null,1,null),2,null))}$APP.l(WY)&&esm_import$node_process.stdin.setRawMode(!0);var c=$APP.A.j($APP.BS,0,null),d=$APP.A.j($APP.BS,1,null);$APP.wy.l($APP.B([["Welcome to nbb-logseq v",$APP.av(),"!"].join("")]));return b(c).then(function(){return b(d)}).then(YRa.h(a,$APP.ff)).then(function(){return new Promise(function(e){var f=$APP.l(null)?RRa(null):esm_import$node_readline.createInterface({input:esm_import$node_process.stdin,
output:esm_import$node_process.stdout,completer:KRa});QRa(f,null);f.setPrompt([$APP.m.g($APP.p(RY)),"\x3d\x3e "].join(""));f.on("close",e);return f.prompt()})})};YY.A=1;
var bSa=new $APP.k(null,3,[$APP.mGa,function(){var a=new $APP.Cd(function(){return YY},VRa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[TRa,$APP.mGa,"nbb/impl/repl.cljs",11,new $APP.k(null,6,[$APP.cA,!1,$APP.Is,1,$APP.$N,1,$APP.pN,new $APP.H(null,2,5,$APP.I,[$APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.sH],null)],null),$APP.Z,$APP.J($APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.sH],null)),$APP.AF,$APP.J(null,null)],null),1,187,187,$APP.J($APP.Sg,new $APP.H(null,
1,5,$APP.I,[$APP.sH],null)),null,$APP.l(YY)?YY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,aSa,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),ZRa,function(){var a=new $APP.Cd(function(){return SY},URa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],
[TRa,WRa,"nbb/impl/repl.cljs",17,1,16,16,$APP.J(new $APP.H(null,1,5,$APP.I,[$APP.spa],null)),"Given a line, returns a flat vector of completions",$APP.l(SY)?SY.H:null])),b=$APP.p(a),c=$APP.te(a);a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,aSa,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}(),$APP.lGa,function(){var a=new $APP.Cd(function(){return XY},
XRa,$APP.gi([$APP.Q,$APP.O,$APP.Wl,$APP.zz,$APP.wL,$APP.Nm,$APP.Xl,$APP.EP,$APP.Z,$APP.M,$APP.JF],[TRa,$APP.lGa,"nbb/impl/repl.cljs",18,new $APP.k(null,6,[$APP.cA,!1,$APP.Is,1,$APP.$N,1,$APP.pN,new $APP.H(null,2,5,$APP.I,[$APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.sH],null)],null),$APP.Z,$APP.J($APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.sH],null)),$APP.AF,$APP.J(null,null)],null),1,172,172,$APP.J($APP.Sg,new $APP.H(null,1,5,$APP.I,[$APP.sH],null)),null,$APP.l(XY)?XY.H:null])),b=$APP.p(a),c=$APP.te(a);
a=$APP.l(null)?null:$APP.O.g(c);var d=new $APP.k(null,4,[$APP.Q,aSa,$APP.O,a,$APP.Z,$APP.Z.g(c),$APP.M,$APP.M.g(c)],null);return $APP.l($APP.Mq.g(c))?$APP.gS.j(a,b,d):$APP.l(function(){var e=$APP.gq.g(c);return $APP.l(e)?e:$APP.tq.g(c)}())?$APP.hS.j(a,b,d):$APP.cu.j(a,b,d)}()],null);$APP.Qu(new $APP.k(null,1,[$APP.Cq,new $APP.k(null,1,[$APP.Ry,bSa],null)],null));